### PR TITLE
ROMIO: combined two separated send/recv for offsets and lengths into one

### PR DESCRIPTION
**Pull request by wkliao**
This PR combines the separated malloc for `my_req[i].offsets` and `my_req[i].lens` into one malloc (same for `others_req[i].offsets` and `others_req[i].lens)` , so the separated Isend for offsets and lens can be combined into one Isend (same for Irecv). Hopefully, this can improve ROMIO performance when run in large scale.

### CODE REVIEW

**Comment by roblatham00** [comment]
Did you see a performance problem in the wild with this code or are you proactively reducing send/receive calls?   ROMIO exchanges a lot of data all over the place, and reducing that communication is definitely good in the burst buffer era.  Maybe my internal performance model is off but this change doesn't strike me as having a whole lot of impact.

**Comment by wkliao** [comment]
The ACME I/O pattern shows a long list of offset-length pairs from each MPI process. I am checking ROMIO to see if anything can be improved. This is the first place I envision can use some improvement, particularly for large scale runs that the cost of exchanging large numbers of offset-length may no longer stay small. This change does not help much, but I am making one step at a time.

**Comment by roblatham00** [comment]
test:jenkins/ch3/all

**Comment by roblatham00** [comment]
Squashed your new commit into the existing ones.  Pushed to master in f2e4c540 .  Thanks!

**Pull request closed without merging**
