### PR TITLE
mpi: Replaced strncpy with MPL_strncpy

### PR DESCRIPTION
**Pull request by jain-surabhi-23**
Fixes coverity defect #66322, #112457 in MPICH-CH4 project

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
@jain-surabhi-23 looks like this has fallen out of date. Could you update it? I'll take a look at it after.

**Comment by jain-surabhi-23** [comment]
@raffenet The conflict is resolved.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Pull request merged**
