### PR TITLE
test: strictify warnings

### PR DESCRIPTION
**Pull request by hzhou**
The testsuite configure has a glitch resulting tests never compiled against "strict" flags. This PR tries to fix it.

### CODE REVIEW

**Comment by hzhou** [comment]
cross-referencing issue #3741

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
Added a commit https://github.com/pmodels/mpich/pull/3747/commits/4952fc53cca5f05d5f6d28d2feadc022dff9d65e to minimize the effect of `FROM_MPICH` -- it revealed the reason there were so many special treatments -- when we configure `test/mpi` within mpich's configure, mpich is not available and the configure has to rely on shortcuts. 

So in order for this to work, we first need to modify our build scripts -- Jenkins -- to separately configure `test/mpi` after installing mpich.

**Comment by pavanbalaji** [comment]
This PR has been sitting for more than a year.  I assume this is not being pursued anymore.

**Pull request closed without merging**
