### PR TITLE
Tree algorithms for Reduce collective

### PR DESCRIPTION
**Pull request by akhillanger**
Implemented transport based kary and knomial tree algorithms for reduce collective, along the same lines as the current tree based broadcast.

### CODE REVIEW

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
@pavanbalaji This PR adds tree based algorithms for reduce. Please review it. Only the commits following the commit: `coll: Fix makefile indentation` need to be reviewed. Rest of the commits are cleanup/refactoring commits that are part of another PR (PR #3000) that @raffenet is reviewing.

**Comment by akhillanger** [comment]
On discussion with @wesbland - I will take out some of the commits in this PR into a prereq PR once PR #3000 gets merged.

**Comment by akhillanger** [comment]
@pavanbalaji I have taken out the cleanup commits and put them in PR #3035. I will keep that PR for any further cleanup also.

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
@akhillanger can you update the malloc commit here so I can review this branch independently?

**Comment by akhillanger** [comment]
@raffenet is this commit msg ok?

`coll: Add malloc function for schedules

This function is used to allocate any memory required
for execution of the schedule. Upon invocation of the function in the
algorithm, the memory is allocated by the transport and
the memory address is stored in the buffers
array in the schedule. Once the schedule completes
execution, the transport frees this memory.`

**Comment by akhillanger** [comment]
@raffenet how about this?

Add function for allocating memory for schedule execution

There are two components in a collective algorithm - schedule generation and schedule execution. MPIR_TSP_sched_malloc is used to allocate any memory that is required for execution of the schedule. The memory allocated using this function need not be freed by the programmer. The transport itself will free that memory once the schedule has completed execution. Note that the usage of this function is different from MPL_malloc. In an algorithm, MPL_malloc may be used for any memory required to generate the schedule and then also freed using MPL_free. But any memory required to execute the schedule should be allocated using the MPIR_TSP_sched_malloc function and that would be freed later by the transport upon completion of schedule execution.

**Pull request merged**
