### PR TITLE
ch4/ofi: Clean ssendack request alloc/free

### PR DESCRIPTION
**Pull request by hajimefu**
This PR is a cleanup around OFI ssend ack request allocation/free routines. It includes

* Removing unused macros
* Shortening the function names
* Removing unnecessary wrapper macro

### CODE REVIEW

**Comment by hajimefu** [comment]
test:jenkins/ch4/ofi

**Comment by hajimefu** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
I have to say that this stuff with `MPIDI_OFI_ssendack_request_t` and others is a total abuse of the MPICH object pools. I'd rather see it completely purged in favor of `malloc/free` implementation, unless there is good reason for the current method.

**Comment by raffenet** [comment]
Looks much better. Can you go ahead and remove the wrappers, too?

**Comment by hajimefu** [comment]
test:jenkins/ch4/ofi

**Comment by hajimefu** [comment]
Done.

**Comment by hajimefu** [comment]
test:jenkins/ch4/ofi

**Comment by hajimefu** [comment]
Did I lose a right to launch Jenkins tests?

**Comment by raffenet** [comment]
Looks like it triggered eventually. Github webhook delivery times can be inconsistent, I have found.

**Comment by hajimefu** [comment]
Updated the patches to follow the general guideline: first remove the usage of X, then remove X in the second patch.

**Comment by hajimefu** [comment]
test:jenkins/ch4/ofi

**Pull request merged**
