### PR TITLE
ABI: update mpi_abi.h with upstream

### PR DESCRIPTION
**Pull request by dalcinl**
## Pull Request Description

* Remove MPIX_REAL1
* Update values of predefined attribute keys
* Some MPI_T constants are now bitsets.

cf. mpiwg-abi/header_and_stub_library#35

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by dalcinl** [comment]
This PR and the stubs one has to be merged roughly at the same time, otherwise the automated CI tests for mpi4py+ABI would fail.
https://github.com/mpi4py/mpi4py-testing/actions/workflows/abi.yml

**Comment by hzhou** [comment]
test:mpich/custom
config:mpi-abi

**Review by hzhou — APPROVED** [review]
LGTM. Will merge if tests are good.

**Comment by dalcinl** [comment]
@hzhou Can you please click the merge button in mpiwg-abi/header_and_stub_library#35 once you do the merge here?

**Comment by hzhou** [comment]
[like]  Zhou, Hui reacted to your message:
________________________________

**Pull request merged**
