### PR TITLE
Improve OFI provider detection

### PR DESCRIPTION
**Pull request by marcgamell**
The current behavior of CH4/OFI provider detection is inconsistent in some cases. This PR tries to solve the problems that were detected.

### CODE REVIEW

**Comment by marcgamell** [comment]
A few of us agreed that auto progress was not needed. However, I just found out that we actually need it. Let me drop the `ch4/ofi: Remove auto_progress capability check` patch and re-test.

**Comment by marcgamell** [comment]
@raffenet I tested the new patches locally and everything seemed to work well.

**Comment by raffenet** [comment]
OK, will merge this when I get a chance. Thanks for fixing it.

**Comment by hajimefu** [comment]
@raffenet Can you merge this now? It would be easier for me to refactor the OFI netmod (#3220) after having these changes. CC: @yfguo

**Comment by raffenet** [comment]
OK, will do.

**Comment by hajimefu** [comment]
Thanks!

**Pull request merged**
