### PR TITLE
Delete the get_elem_d test

### PR DESCRIPTION
**Pull request by pavanbalaji**
## Pull Request Description

This test is incorrect.  It sends data in `MPI_BYTE` type and expects to receive it in a combination of `MPI_DOUBLE_PRECISION` and `MPI_INTEGER`.  This is disallowed by the MPI standard.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
Let's say we are sending `1, 2, ..., 20` bytes, and receiving `100` `MPI_INT` (assuming 4-byte integer). What should `MPI_Get_elements` return?

I think we agree that `0, 0, 0, 1, 1, 1, 1, 2, ...` is wrong. But I think the right answer should be:
```
MPI_UNDEFINED, MPI_UNDEFINED, MPI_UNDEFINED, 1,
MPI_UNDEFINED, MPI_UNDEFINED, MPI_UNDEFINED, 2
...
```

or, do we think the right answer should be:
```
any, any, any, 1,
any, any, any, 2,
...
```
?

**Comment by pavanbalaji** [comment]
> Let's say we are sending `1, 2, ..., 20` bytes, and receiving `100` `MPI_INT` (assuming 4-byte integer). What should `MPI_Get_elements` return?
> 
> I think we agree that `0, 0, 0, 1, 1, 1, 1, 2, ...` is wrong. But I think the right answer should be:
> 
> ```
> MPI_UNDEFINED, MPI_UNDEFINED, MPI_UNDEFINED, 1,
> MPI_UNDEFINED, MPI_UNDEFINED, MPI_UNDEFINED, 2
> ...
> ```
> 
> or, do we think the right answer should be:
> 
> ```
> any, any, any, 1,
> any, any, any, 2,
> ...
> ```
> 
> ?

It's an error in all cases.

**Comment by pavanbalaji** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Pull request merged**
