### PR TITLE
mtest: fix tag in multisend[2-4]

### PR DESCRIPTION
**Pull request by zhenggb72**
Tags used in multisend[2-4] can be as high as up to 660000,
which is beyond what PSM2 can support (max_ub is 128K).
Fix the tests by using the log2 of the count instead of count.

Fixes csr/mpich-ofi#944

### CODE REVIEW

**Comment by pavanbalaji** [comment]
@zhenggb72 Can you also add an assert in the test to make sure that the tag stays within `MPI_TAG_UB` or the 64K minimum that the MPI standard allows?

**Comment by wesbland** [comment]
I'd prefer `MPI_TAG_UB` because we provide more than 64K and we should test them all.

**Comment by pavanbalaji** [comment]
The test isn't testing them all.  It's only testing `log(MAX_CNT)` of them.  It was just incrementing the tag as `2^iteration` earlier, and it's incrementing as `iteration` now.

**Comment by pavanbalaji** [comment]
Hmm.  On second thought, if we are going till `2^MPI_TAG_UB` iterations, I don't think we need to do that additional assert to make sure we are within range anyway.  That's `2^64K` iterations at the very least, and that'll take an eternity to test out.  Maybe that assertion is an overkill.  I'll go ahead and approve this PR as-is.

**Comment by pavanbalaji** [comment]
Can someone rebase this on to `mpich/master` and test it?

**Comment by wesbland** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by wesbland** [comment]
This was rebased but the GitHub/Jenkins gods do not smile upon me. Can someone investigate this on the Argonne side?

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by zhenggb72** [comment]
ok, cool

**Pull request merged**
