### PR TITLE
test/dtpools: Remove MPIX_C_FLOAT16 from type list

### PR DESCRIPTION
**Pull request by raffenet**
Remove this type for now, since it is not always defined. We need a
way to test for support and guard usage appropriately.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
Does the test script randomly select datatypes from the list to test? It might be more proper to add an exclusion check in the selection code. That way at least we have a trace (and a logic) in the test suite rather than completely missing from tests. 

Alternatively, we may consider use configure detection -- `HAVE_FLOAT16` . It is in `configure.ac`; we can add to `test/mpi/configure.ac`.

**Comment by raffenet** [comment]
The problem is not strictly the test script. The `dtpools.h` header file explicitly references `MPIX_C_FLOAT16` without a guard. A configure time check would be the right thing to do, however it requires refactoring the typelist definition https://github.com/pmodels/mpich/pull/3559/commits/856d3acd48d899cebb4516ed66ad721a05851083#diff-1c3429cec3b2b449676a32653288918aL64. This PR is just a quick hack to enable a short-term use case. We can iterate on a better solution before merging.

**Comment by hzhou** [comment]
What triggers the PR? Is having that type in the list breaking some tests or build?

**Comment by hzhou** [comment]
Is this fix related to using test suites on other MPI implementation?

**Comment by raffenet** [comment]
Yes, we are testing another MPI with the MPICH testsuite.

**Comment by hzhou** [comment]
I see. I'll sign off, commit to master, and also add an issue to track for later refactoring.

**Pull request merged**
