### PR TITLE
Docs: Mediawiki Pages Conversion

### PR DESCRIPTION
**Pull request by travisk1154**
## Pull Request Description
The pages for the [wiki.mpich.org](https://wiki.mpich.org/mpich/index.php/Developer_Documentation) site were converted to match the format for github wiki pages, where the site will be migrated to due to end of life of the mediawiki at ANL.

## WIP
The conversion and overhaul has been preliminarily completed. The new starting point of the wiki can be located [here](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/Index.md) and all of the pages can be found [here](https://github.com/travisk1154/mpich/tree/wiki_conversion/doc/wiki). 

## TODO
Below is a list of remaining items to complete.

### Break Up Student Project Page
- [x] This page was removed and each sub topic was created as a discussion [here](https://github.com/pmodels/pmrs-todo/discussions)

### Incomplete Pages
- [ ] [PE_RTE.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/source_code/PE_RTE.md)
- [ ] [CH4_Process_Address_Translation.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/extra/CH4_Process_Address_Translation.md)
- [ ] [Channel_Feature_Support_Matrix.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/extra/Channel_Feature_Support_Matrix.md)
- [ ] [Environment_Variables.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/Environment_Variables.md)
- [ ] [MPICH_Namespacing.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/MPICH_Namespacing.md)
- [ ] [Nemesis_Network_Module_API.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/Nemesis_Network_Module_API.md)
- [ ] [Tool Interfaces](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/Tool_Interfaces.md)
- [ ] [Ch3 Channels](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/CH3_And_Channels.md)
- [ ] [Sharing Blocking Resources](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/Sharing_Blocking_Resources.md)
- [ ] [Checkpointing.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/how_to/Checkpointing.md)
- [ ] Fixing Bugs in Released Code
    - This page had a link in the original page but the page only had "TODO" so it was not included in the current index page
- [ ] [KVS_Caching.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/KVS_Caching.md)
- [ ] [Include_Files_in_MPICH.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/Include_Files_in_MPICH.md)
- [ ] [DAME.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/DAME.md)
- [ ] [CH3_Object_Model.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/CH3_Object_Model.md)
- [ ] [CH4_Process_Address_Translation.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/CH4_Process_Address_Translation.md)

### Pages Requiring Validation
- [ ] [design/MPICH_Architecture.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/MPICH_Architecture.md)
    - This page currently just displays an image of the MPICH architecture
      heirarchy. Is this current? Should have a written description on this page for each section?
- [ ] [design/MPI-3_RMA_Implementation_Timeline.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/MPI-3_RMA_Implementation_Timeline.md)
- [ ] [Communicators_and_Context_IDs.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/Communicators_and_Context_IDs.md)
- [ ] [Atomic_Operations.md](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/design/Atomic_Operations.md)

### Extra Pages
This is a list of pages that existed in the old wiki but had no links to them. We need to confirm if they should be included and where.
- [ ] [Running_Tests_On_Remote_Machines.md](https://wiki.mpich.org/mpich/index.php/Running_Tests_On_Remote_Machines)
       Hui: Find an archived page for http://www-unix.mcs.anl.gov/mpi/mpichold/developer/remotetests.htm and port
- [x] [Netmod_Packet_Types.md](https://wiki.mpich.org/mpich/index.php/Netmod_Packet_Types)
       Hui: add ch3 to title, add link to Design Docs
- [x] [Object_Model.md](https://wiki.mpich.org/mpich/index.php/Object_Model)
       Hui: add ch3 to title, add link to Design Docs
- [x] [CH4_Process_Address_Translation.md](https://wiki.mpich.org/mpich/index.php/CH4_Process_Address_Translation)
       Hui: add link to Design Docs
- [x] [MPI+Argobots.md](https://wiki.mpich.org/mpich/index.php/MPI%2BArgobots)
       Hui: add to index page, I am thinking under a new heading (e.g. Options) above "Miscellaneous"
- [x] [MPIDU_Sched_progress.md](https://wiki.mpich.org/mpich/index.php/MPIDU_Sched_progress)
       Hui: add link to Design Docs (Moved to outdated, covered by Progress Engine page)
- [x] [Channel_Feature_Support_Matrix.md](https://wiki.mpich.org/mpich/index.php/Channel_Feature_Support_Matrix)
       Hui: completely outdated, remove
- [x] [MPICH2_FTB.md](https://wiki.mpich.org/mpich/index.php/MPICH2_FTB)
       Hui: completely outdated, remove
- [x] [MPICH2_FTB_Events.md](https://wiki.mpich.org/mpich/index.php/MPICH2_FTB_events)
       Hui: completely outdated, remove
- [x] [MPICH2_Parallel_Build.md](https://wiki.mpich.org/mpich/index.php/MPICH2_Parallel_Build)
       Hui: completely outdated, remove
- [x] [Nemesis_Module_Status.md](https://wiki.mpich.org/mpich/index.php/Nemesis_Module_Status)
       Hui: completely outdated, remove
- [x] [Pretty_Make.md](https://wiki.mpich.org/mpich/index.php/Pretty_Make)
       Hui: completely outdated, remove
- [x] [Progress_of_scalable_RMA_implementation.md](https://wiki.mpich.org/mpich/index.php/Progress_of_scalable_RMA_implementation)
       Hui: completely outdated, remove
- [x] [RMA_Failures.md](https://wiki.mpich.org/mpich/index.php/RMA_Failures)
       Hui: completely outdated, remove
- [x] [Simplemake_vs_automake.md](https://wiki.mpich.org/mpich/index.php/Simplemake_vs_automake)
       Hui: interesting, but completely outdated, remove

### Broken Links (Unresolvable)
Most of these pages have archives somewhere or have been moved. Try find them and replace the links. For example, the sowing pages now live at http://wgropp.cs.illinois.edu/projects/software/sowing/
| Page | Location | Broken Link | Text |
| ---- | -------- | ----------- | ---- |
| BGQ | source_code | <http://www.alcf.anl.gov/user-guides/bgclang-compiler> | |
| BGQ | source_code | <https://trac.alcf.anl.gov/projects/llvm-bgq> | |
| BGQ | source_code | <http://git.mpich.org/mpich-ibm.git> | mpich-ibm.git |
| Version Control System 101 | source_code | <https://svn.mcs.anl.gov/repos/mpi/mpich2/branches/dev> | |
| Version Control System 101 | source_code | <https://sitaramc.github.com/gitolite/master-toc.html> | manual |
| Version Control System 101 | source_code | <https://sitaramc.github.com/gitolite/user.html#perms> | command |
| Coding Standards | source_code | <https://www.oracle.com/technetwork/systems/ccompare-141326.html> | |
| HPCToolkit By Exmaple | tools | <https://www.alcf.anl.gov/user-guides/hpctoolkit> | |
| HPCToolkit By Exmaple | tools | <https://computing.llnl.gov/tutorials/HPCToolkit.MellorCrummey.2012.08.07.pdf> | |
| Frequently Asked Questions | faq | <http://softwareforums.intel.com/ISN/Community/en-US/search/SearchResults.aspx?q=libimf.so> | |
| Frequently Asked Questions | faq | <http://www.mcs.anl.gov/research/projects/mpich2/documentation/index.php?s=docs> | 3 occurrences |
| Nightly Tests | testing | <http://www.mpich.org/static/cron/errors/testoptions.htm> | Configure Options Tests |
| Code Coverage Reports | testing | <https://www.mpich.org/static/cron/coverage/ch3:sock/index.htm> | ch3:sock |
| MPICH ABI Tests | testing | No Link Provided | Intel MPI-1 tests |
| MPICH ABI Tests | testing | No Link Provided | LLNL IO tests |
| Creating A Release | source_code | <http://web.engr.illinois.edu/~wgropp/projects/software/sowing/> | doctext |
| Managing Commits In Trunk.. | source_code | <https://trac.mpich.org/mpich/roadmap> | roadmap (2 occurrences) |
| Managing Commits In Trunk.. | source_code | <https://trac.mpich.org/mpich/timeline> | |
| Compiler Quirks | source_code | <http://docs.sun.com/source/817-5064/c99.app.html> | documentation |
| Compiler Quirks | source_code | <http://h21007.www2.hp.com/portal/site/dspp/menuitem.863c3e4cbcdc3f3515b49c108973a801/?ciid=4b080f1bace021100f1bace02110275d6e10RCRD> | docs in a link that may not stay accessible |
| RMA Design | design | <https://wiki.mpich.org/mpich/index.php/MPI-3_RMA_Implementation_Timeline> | Wiki page from old site |
| Reporting And Returning Error Codes | design | <https://trac.mcs.anl.gov/projects/mpich2/browser/mpich2/trunk/src/include/mpierrs.h> | src/include/mpierrs.h (2 occurrences) |

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
Each page need add a title line, e.g. `# [Title]`

**Comment by hzhou** [comment]
@travisk1154 Could provide a link to the index page?

**Comment by travisk1154** [comment]
> @travisk1154 Could you provide a link to the index page?

https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/Developer_Documentation.md

**Comment by hzhou** [comment]
I understand this is very tedious, but could you try to correct the spelling?

**Comment by travisk1154** [comment]
> I understand this is very tedious, but could you try to correct the spelling?

Yes

**Comment by hzhou** [comment]
> > @travisk1154 Could you provide a link to the index page?
> 
> https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/Developer_Documentation.md
> 
> I fixed the links, so let me know if you have issues with them.

Thanks! Maybe rename the file into `index.md`?

**Comment by hzhou** [comment]
The links in https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/index.md is still broken

**Comment by travisk1154** [comment]
I have completed all of the overhaul of the wiki. Please reference [here](https://github.com/travisk1154/mpich/blob/wiki_conversion/doc/wiki/Developer_Documentation_Index.md) as the new starting point for the wiki. The only thing missing should be pictures.

**Comment by hzhou** [comment]
I added some notes in the description on outdated pages. Don't remove them in this PR. Remove them in the next PR. That way we have a history to track.

**Review by hzhou — APPROVED** [review]
Looks good. Nice job!

Just rebase to the current main branch

**Pull request merged**
