### PR TITLE
config: only try -Werror if the compiler accepts it

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
For example, pgi compiler and suncc won't accept -Werror. Adding it only
result in test failures.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/custom
compiler=pgi

**Comment by raffenet** [comment]
We should tackle this instance too: https://github.com/pmodels/mpich/blob/master/configure.ac#L4518

**Comment by raffenet** [comment]
Maybe set a `WERROR_FLAG` shell variable in `aclocal_cc` and re-use it when needed?

**Comment by hzhou** [comment]
> Maybe set a `WERROR_FLAG` shell variable in `aclocal_cc` and re-use it when needed?

I think it is a good idea.

**Comment by hzhou** [comment]
> We should tackle this instance too: https://github.com/pmodels/mpich/blob/master/configure.ac#L4518

Added a commit to check this instance too. Since we only use `-Werror` rarely, managing a global `WERROR_FLAG` seems more trouble than its worth at this point.

**Pull request merged**
