### PR TITLE
Debug logging improvements

### PR DESCRIPTION
**Pull request by pavanbalaji**
## Pull Request Description

Improvements to the debug logging code.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
@pavanbalaji I already have a PR to automatically generate all debug logging - https://github.com/pmodels/mpich/pull/4276.  The idea is to remove all explicit macro from code base, and when needed, simply run a script (in `maint/`) to generate all the logging macros. Run the script again can remove those generated macros for clean commits.  Future enhancements can allow scripts to generate more targeted logging or variation of debugging/hook/profiling.

**Comment by pavanbalaji** [comment]
> @pavanbalaji I already have a PR to automatically generate all debug logging - #4276. The idea is to remove all explicit macro from code base, and when needed, simply run a script (in `maint/`) to generate all the logging macros. Run the script again can remove those generated macros for clean commits. Future enhancements can allow scripts to generate more targeted logging or variation of debugging/hook/profiling.

That PR has been sitting there since January, and I needed this to move ahead with the current critical work.

**Comment by hzhou** [comment]
> 
> 
> > @pavanbalaji I already have a PR to automatically generate all debug logging - #4276. The idea is to remove all explicit macro from code base, and when needed, simply run a script (in `maint/`) to generate all the logging macros. Run the script again can remove those generated macros for clean commits. Future enhancements can allow scripts to generate more targeted logging or variation of debugging/hook/profiling.
> 
> That PR has been sitting there since January, and I needed this to move ahead with the current critical work.

That PR is updated by a script, I can update it quickly anytime

**Comment by pavanbalaji** [comment]
> That PR is updated by a script, I can update it quickly anytime

Thanks.  I'll merge this PR into master to avoid depending on some PR that is not in master.

**Comment by pavanbalaji** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by pavanbalaji** [comment]
Some concurrent memory-hog job knocked out a bunch of tests causing everything to fail.  Rerunning the tests.

test:mpich/ch3/most
test:mpich/ch4/most

**Pull request merged**
