### PR TITLE
runtests: make it possible to run benchmarks in custom tests

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Often it would be nice to directly run a micro benchmark with-in a PR. This patch makes that possible.

See below for examples.

Note: the first commit is technically unrelated, but a convenient cleanup.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/custom
testlist: $OSU/pt2pt/osu_latency 2

**Comment by hzhou** [comment]
test:jenkins/custom
testlist: $OSU/pt2pt/osu_latency 2

**Comment by hzhou** [comment]
test:jenkins/custom
testlist: $OSU/pt2pt/osu_latency 2

**Comment by hzhou** [comment]
test:jenkins/custom
testlist: $OSU/pt2pt/osu_latency 2

**Comment by hzhou** [comment]
test:jenkins/custom
testlist: $OSU/pt2pt/osu_latency 2

**Comment by hzhou** [comment]
test:jenkins/custom
testlist: $OSU/pt2pt/osu_latency 2

**Comment by hzhou** [comment]
test:jenkins/custom
testlist: $OSU/pt2pt/osu_latency 2

**Comment by hzhou** [comment]
test:jenkins/custom
testlist: $OSU/pt2pt/osu_latency 2

**Comment by hzhou** [comment]
test:jenkins/custom
testlist: $OSU/pt2pt/osu_latency 2

**Comment by hzhou** [comment]
test:jenkins/custom
testlist: $OSU/pt2pt/osu_latency 2

**Comment by pavanbalaji** [comment]
It's unclear how the external test is being compiled before running the test.  Or the location identified.  This is an incomplete PR.  This should be discussed separately before creating a PR.

**Pull request closed without merging**
