### PR TITLE
mpi4.1: add info key `mpi_assert_strict_persistent_collective_ordering`

### LINKED ISSUE #6772: mpi4.1: add info_hint `mpi_assert_strict_persistent_collective_ordering`
mpi-forum/mpi-standard#661
mpi-forum/mpi-standard#666

### PR DESCRIPTION
**Pull request by yfguo**
## Pull Request Description

fixed #6772

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by yfguo** [comment]
test:mpich/ch4/ofi

**Comment by yfguo** [comment]
test:mpich/ch4/ofi

**Review by hzhou — APPROVED** [review]
LGTM

**Comment by hzhou** [comment]
@yfguo The PR is approved. Please fill in the PR descriptions and check the checklist.

**Pull request merged**
