### PR TITLE
romio: Fix mutex lazy init

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

An atomic true/false is not sufficient to prevent multiple threads from
initializing the ROMIO mutex. Instead, use 3 distinct states: uninit,
intializing, ready. An atomic compare-and-swap is used to transition the
mutex state from uninit->initializing by a single thread. Other threads
will just wait until the mutex is ready.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
> This should work -- essentially using a spinlock to initialize the mutex. @raffenet Do you prefer merge this one over #5956?

Yeah, let's give it a shot if @wkliao agrees.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by wkliao** [comment]
I ran a few tests using this PR and they all passed. Thanks.

**Review by hzhou — APPROVED** [review]
LGTM

**Comment by wkliao** [comment]
I do not know which PR should be merged.
Any implication to the performance?

**Comment by hzhou** [comment]
> I do not know which PR should be merged. Any implication to the performance?

With the lazy mutex creation, the first contention can be big -- if multiple threads calls first `MPI_File_open` concurrently. But compared to the overhead of `MPI_File_open` itself, it is likely negligible. Once the mutex is created, this PR has the overhead of a single atomic load, which on x86 is nearly no cost and it is negligible generally. The benefit with this PR is it is ready to be portable to non-pthread systems.

**Pull request merged**
