### PR TITLE
ch4/ofi: pick best provider when optimal matching fails

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

When optimal matching fails, for example, when provider list is filtered with `FI_PROVIDER`, we need match the best matching providers rather than the first provider that matches `MINIMAL` capability set.

Reference #4684 - Added support for the libfabric utility provider verbs;ofi_rxm
[skip warnings]
## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=verbs;ofi_rxm
testlist: attr

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=verbs;ofi_rxm
testlist: attr

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=verbs;ofi_rxm
testlist: attr

**Comment by hzhou** [comment]
@atulkulk This turns out more complicated than I thought. I am still debugging, adding comments and better error messages, etc. Meanwhile, you are welcome to start review the changes -- I could use some help.

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=verbs;ofi_rxm
testlist: attr

**Comment by hzhou** [comment]
test:mpich/warnings/custom
netmod: ch4/ofi
env: MPIR_CVAR_CH4_OFI_CAPABILITY_SETS_DEBUG=1

**Comment by hzhou** [comment]
test:mpich/warnings/custom
netmod: ch4:ofi
env: MPIR_CVAR_CH4_OFI_CAPABILITY_SETS_DEBUG=1

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=verbs;ofi_rxm
testlist: attr

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: attr

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: rma
env: MPIR_CVAR_CH4_OFI_ENABLE_MR_SCALABLE=0

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: rma

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: rma

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=verbs;ofi_rxm

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=verbs;ofi_rxm
env: FI_MR_CACHE_MAX_COUNT=0

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: MPIR_CVAR_OFI_USE_PROVIDER=minimal

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=verbs;ofi_rxm
env: FI_MR_CACHE_MAX_COUNT=0

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=verbs;ofi_rxm
env: FI_MR_CACHE_MAX_COUNT=0

**Comment by hzhou** [comment]
> in which case each NIC is a provider

Does libfabric work with multiple providers simultaneously? Do you mean opening multiple `fi_fabric`? Wouldn't it be cleaner to consider run multiple netmod simultaneously? That should be as simple as expand `is_local`, right?

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=verbs;ofi_rxm
env: FI_MR_CACHE_MAX_COUNT=0

**Comment by zhenggb72** [comment]
Each NIC is one fi_domain. You can discuss with @wesbland  and @nusislam about the implementation. We already have an internal PR for this. This PR creates huge conflicts with that.

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: MPIR_CVAR_OFI_USE_PROVIDER=minimal
env: FI_PROVIDER=sockets

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

test:mpich/custom
netmod: ch4:ofi
env: MPIR_CVAR_OFI_USE_PROVIDER=minimal
env: FI_PROVIDER=sockets

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=tcp;ofi_rxm
env: FI_MR_CACHE_MAX_COUNT=0

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=tcp;ofi_rxm
env: FI_MR_CACHE_MAX_COUNT=0

**Comment by hzhou** [comment]
test:mpich/custom --with-posix-mutex=ticketlock
netmod: ch4:ofi
env: FI_PROVIDER=tcp;ofi_rxm
env: FI_MR_CACHE_MAX_COUNT=0

**Comment by wesbland** [comment]
@hzhou Is it possible to separate out the massive refactoring of initialization from fixing the bug of not properly detecting the correct capability set?

I'm really opposed to refactoring the most complicated part of MPICH, but if there's a problem in the capability set code, we should fix that.

**Comment by hzhou** [comment]
> 
> 
> @hzhou Is it possible to separate out the massive refactoring of initialization from fixing the bug of not properly detecting the correct capability set?
> 
> I'm really opposed to refactoring the most complicated part of MPICH, but if there's a problem in the capability set code, we should fix that.

It is always "possible". 😟 However, this PR is not just fixing a bug, it is changing the mechanism of how we select provider and update settings. It eventually changes every part of the code that are refactored out. Without the refactoring, the changes will be more spread and will not reduce the amount of conflicts.

**Comment by wesbland** [comment]
> It is always "possible". 😟 However, this PR is not just fixing a bug, it is changing the mechanism of how we select provider and update settings. It eventually changes every part of the code that are refactored out. Without the refactoring, the changes will be more spread and will not reduce the amount of conflicts.
> 
> EDIT: There are a few bug fix commits that is trivial and can be split out.

That's what I'm afraid of. 😦 The problem on our end is that the init code is still very different from the main branch because of all of the ongoing work with threading. I'm not sure I could even merge this if I did it manually because there's just too many changes when moving code from one place to the other that Git can't help resolve. I don't know how to resolve this impasse.

**Comment by pavanbalaji** [comment]
I'm not in favor of such a large refactoring at this stage of the release process.

**Comment by hzhou** [comment]
> That's what I'm afraid of. 😦 The problem on our end is that the init code is still very different from the main branch because of all of the ongoing work with threading. I'm not sure I could even merge this if I did it manually because there's just too many changes when moving code from one place to the other that Git can't help resolve. I don't know how to resolve this impasse.


There are three totally separate things in ofi_init.c: provider stuff, dynamic process stuff, vni stuff. Right now they are all in the same file and interleaves each other, so any change in any of them brings conflicts with others. The obvious solution is we should do a clean refactor first -- separate out the 3 pieces into its own files. Since that refactor is just moving code around, while conflicts, it should be trivial to resolve. Once that refactor is done, any future change to any parts of the code will only bring conflicts to its own part, allowing progress to proceed.

**Comment by wesbland** [comment]
> Since that refactor is just moving code around, while conflicts, it should be trivial to resolve. Once that refactor is done, any future change to any parts of the code will only bring conflicts to its own part, allowing progress to proceed.

I don't know if that's true or not. Unless you are moving functions in their entirety, I think the conflicts will still be difficult to resolve due to downstream changes.

**Comment by hzhou** [comment]
> Unless you are moving functions in their entirety,

That was what I am proposing.

**Comment by hzhou** [comment]
Replaced by #5233

**Pull request closed without merging**
