### PR TITLE
pm/util: Allow duplicate keys in PMI KVS

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Duplicate keys are already allowed in the Hydra PMI server. Update the utility PMI server used by gforker and remshell to also support them.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ofi
EXTRA_CONFIG="--with-pm=gforker"

**Comment by raffenet** [comment]
Test failures are just unsupported spawn features of `gforker`.

**Review by hzhou — APPROVED** [review]
LGTM

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Pull request merged**
