### PR TITLE
test/multinic: Minor fixes and improvements

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Fix a minor issue with the multinic pvar test and improve the usability.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ofi

**Review by sagarth — APPROVED** [review]
LGTM, if the results come clean.

**Comment by raffenet** [comment]
Some example output when running on 2 of our Jenkins nodes with 2x Mellanox IB cards.
```
[raffenet@pmrs-centos64-240-01]~/mpich/test/mpi/impls/mpich/threads/pt2pt% MPITEST_VERBOSE=1 ../../../../../../i/bin/mpiexec -n 2 -hosts pmrs-centos64-240-01.cels.anl.gov,pmrs-centos64-240-02.cels.anl.gov -l ./multinic_infohints
[0] detected 2 nics at rank 0
[1] detected 2 nics at rank 1
[0]  No Errors
```

**Comment by raffenet** [comment]
> LGTM, if the results come clean.

We'll have to setup a separate multinic Jenkins job to run on specific nodes and build with multinic pvars enabled to _actually_ test the functionality. After this PR, we should have everything in place to do that.

**Comment by raffenet** [comment]
> > LGTM, if the results come clean.
> 
> We'll have to setup a separate multinic Jenkins job to run on specific nodes and build with multinic pvars enabled to _actually_ test the functionality. After this PR, we should have everything in place to do that.

https://pmrs-jenkins.cels.anl.gov/job/mpich-main-ch4-ofi-multinic/ is now up and building with the psm3 provider. It is bound to a multinic node and should exercise the multinic code. It is configured with `--enable-mpit-pvars=multinic`.

**Comment by sagarth** [comment]
Good to know that @raffenet

**Pull request merged**
