### PR TITLE
pmi: Add support for PMIx_Spawn

### PR DESCRIPTION
**Pull request by sonjahapp**
## Pull Request Description

Add support for `PMIx_Spawn`

Currently supported info keys: `host`, `wdir`, `path`, `env`

Tested with PRRTE.

## Author Checklist
* [X] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [X] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [X] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Review by hzhou — COMMENTED** [review]
Looks good. Very clean commits 👍 I am ready to approve once tests are clear.

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by sonjahapp** [comment]
I've fixed a name ambiguity of a parameter in `pmix_not_supported`. Could we please run the tests again?

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi
test:mpich/pmi

**Review by hzhou — APPROVED** [review]
LGTM

EDIT: looks like the spawn tests are failing

**Comment by sonjahapp** [comment]
Fixed the failing `errors/spawn/unpub` test with an additional commit that fixes `pmix_unpublish` behaviour. However this fix is unrelated to PMIx Spawn.

Regarding the failing spawn tests `threads/spawn/multispawn` and `threads/spawn/th_taskmanager`, indeed there was a synchronization missing between parent and spawned processes to avoid overwriting the preput values in the KVS in threaded spawning. An additional commit adds this synchronization using `PMIx_Fence`. 

Could we run the pmi tests again please? (btw: can I trigger them myself, now that I'm a member of pmodels?)

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by raffenet** [comment]
> I'm not sure what to conclude from the still failing pmi tests.
> 
> For `ch3-tcp` and `ch3-sock` it is the `session-re-init` test that fails with a segfault. Is that expected for ch3?

The test does pass in our nightly tests. I can take a quick look and see where the segfault is coming from.

> 
> For `ch4-ofi` there is a timeout for the entire test suite run. I do not think that this is related to `PMIx_Spawn`...

This is due to hwloc initialization. I recently changed the Jenkins script to disable hwloc in MPICH when using PMIx. We can add it back when we make initializing more efficient. For now, we can test again and it should go faster.

test:mpich/pmi

**Comment by raffenet** [comment]
The `session_re_init` failures are because of a change I made. They should not block this PR. In 4c8428169a9f2c5d6fc08b93c62669c8e87fd197, I made it so we get `pmi_kvs_name` from `PMIx_Init`, which is called only once. When the MPIR_pmi layer is finalized and `pmi_kvs_name` set to `NULL`, it doesn't get re-initialized and causes a segfault when processes try to get their jobid. I'll propose a patch.

**Comment by raffenet** [comment]
#6679 should fix the ch3 `session_re_init` failures.

**Review by raffenet — APPROVED** [review]

**Comment by hzhou** [comment]
I am rebasing and will merge this PR

**Pull request merged**
