### PR TITLE
nodemap: Change max_node_id to n_node.

### PR DESCRIPTION
**Pull request by yfguo**
The max_node_id was used to present the "largest node id" or "number of
nodes" in a mixed way. This patch unifies it to "number of nodes" and
updates the variable names accordingly.

### CODE REVIEW

**Comment by yfguo** [comment]
test:jenkins/ch4/all
test:jenkins/ch3/all

**Comment by raffenet** [comment]
Do we actually need both? I dug this up from the commit log - 0c42a934a6275f42faba8f397ae15957de3893dd

**Comment by raffenet** [comment]
Maybe we don't need both, but my theory is this PR will cause errors if you run the spawn tests with multiple nodes. If so, we should change to consistently return the max node id instead.

**Comment by yfguo** [comment]
Hmm, I need to check CH3. I think CH4 should be working fine because the design assumes it is the "number of nodes".

**Comment by yfguo** [comment]
test:jenkins/ch3/all
test:jenkins/ch4/all

**Comment by raffenet** [comment]
cc: @ddurnov

**Comment by raffenet** [comment]
@yfguo the end result of this looks good to me. can we squash it down and merge? It fixes an existing problem with some startup stuff I am working on.

**Comment by yfguo** [comment]
@raffenet Squashed and rebased on latest master.

**Pull request merged**
