### PR TITLE
(comm,rank) translation optimizations

### PR DESCRIPTION
**Pull request by yfguo**
Fixing the double translation in "checking rank locality" and "getting rank address"
General support for embedding SHM address into AV element.

- [x] add MPIDI_CH4_av_is_local (and corresponding functions in the lower layer)
- [x] replace MPIDI_CH4_rank_is_local
- [x] passing AV to netmod communication functions (Just for 2-sided message, 1-sided does not have the double translation problem?)
- [x] fixing context id in posix SHM for correct behavior on intecomm
- [x] adding support for netmod/shm mixed address (dynamic process is broken, fix later)
- [ ] passing AV to shm communication functions

### CODE REVIEW

**Comment by yfguo** [comment]
test:jenkins/ch4/all

**Comment by yfguo** [comment]
test:jenkins/ch4/all

**Comment by yfguo** [comment]
test:jenkins/ch4/all

**Comment by yfguo** [comment]
test:jenkins/ch4/all

**Comment by wesbland** [comment]
I guess there's a bunch here that goes with #2681 so there's no reason to review this until the other one is done.

**Comment by yfguo** [comment]
Yes. This is just a working branch. And I have something here that will definitely break RMA. 😄

**Comment by ddurnov** [comment]
Are there any plans to propagate "av" to MPIDIG/AM infrastructure?

**Comment by yfguo** [comment]
@ddurnov There is no plan to propagate the "av" to MPIDIG/AM infrastructure for now. Is there a case that it would be useful?

**Comment by SergeyGubanov** [comment]
@yfguo  
It is very useful to have "av" in SHM transport layer for store in "av" some SHM transport specific data.
In the "POSIX SHM new logic #2526" the MPIDIG/AM is used for SHM.
Thus, we need to pass "av" through MPIDIG/AM layer into AM/SHM layer and then into SHM transport layer.

Stack trace in the "POSIX SHM new logic #2526" case:

MPI_Send
MPID_Send  <----- "av" is obtained here by: av = MPIDIU_comm_rank_to_av(comm, rank);
MPIDI_SHM_mpi_send
MPIDI_POSIX_mpi_send
--------------------------------------- MPIDIG/AM layer
MPIDIG_mpi_send
MPIDI_am_isend
--------------------------------------- AM/SHM layer
MPIDI_SHM_am_isend
MPIDI_POSIX_am_isend
--------------------------------------- SHM transport layer
MPIDI_POSIX_eager_send ["virtual function call": MPIDI_POSIX_eager_func->send]
MPIDI_POSIX_eager_send_impl  <----- we need to have "av" here

To have "av" in MPIDI_POSIX_eager_send() we need to pass "av" through all functions listed above.

**Comment by wesbland** [comment]
@yfguo - Should I still review this? It looks like it needs a pretty big rebase at the very least.

**Comment by yfguo** [comment]
@wesbland No, the completed part has been superseded by #2681 and has been merged. The incomplete part needs a lot of work because it is only possible if we can implement intra-node RMA over shared memory (potentially with CMA or more advanced SHMMOD). Maybe we should close this PR and convert the todo point into an issue.

**Comment by wesbland** [comment]
Closing and creating a new issue sounds good. 👍

**Comment by yfguo** [comment]
The todo work is tracked by issue #2752 .

**Pull request closed without merging**
