### PR TITLE
dloop: Handled divide by zero cases

### PR DESCRIPTION
**Pull request by jain-surabhi-23**
Fixes coverity defect #66415, #66416, #66417 in MPICH-CH4 project

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
Rebased for testing purposes.
test:jenkins/ch3/tcp

**Comment by pavanbalaji** [comment]
@jain-surabhi-23 can you rebase this on to the latest master and rerun the tests?  There seem to be some conflicts.

**Comment by pavanbalaji** [comment]
I can't quite follow the github formatting above, so I can't quite tell if @jain-surabhi-23 rebased it or not, but it looks like there are no conflicts at this point.  I'll restart the tests.

test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by jain-surabhi-23** [comment]
Yes. I just rebased this.

**Comment by pavanbalaji** [comment]
Tests look OK.

**Comment by jain-surabhi-23** [comment]
The two tests seem to have failed for a weird reason.

> ## Test output (expected 'No Errors'):
> ##  No Errors
> ## srun: error: freebsd64-2: signal: Communication connection failure

**Comment by pavanbalaji** [comment]
@jain-surabhi-23 you can ignore those errors.

**Comment by pavanbalaji** [comment]
@roblatham00 From the description above, these seem to have been caught by Coverity, and not by a unit test.

**Pull request merged**
