### PR TITLE
draft: picking typerep_pack_external fixes

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
This draft pr picks PR #5163 to 3.4.x branch.

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by ashwinraghu** [comment]
Still working on back-porting this.
Meanwhile, for the record,  4.0.1 does work as far as the user's application is concerned.

**Comment by hzhou** [comment]
@ashwinraghu Try just picking 0e3fd727e97588ec64412f604c4ae7bbcb3fe689 to see if it fixes your issue. That patch fixes the obvious bug in yaksa. The rest of the commits were mainly dealing with big-endian conversions. Big-endian machines are rare these days, so it may not be a big concern.

**Comment by hzhou** [comment]
> > @ashwinraghu Try just picking [0e3fd72](https://github.com/pmodels/mpich/commit/0e3fd727e97588ec64412f604c4ae7bbcb3fe689) to see if it fixes your issue. That patch fixes the obvious bug in yaksa. The rest of the commits were mainly dealing with big-endian conversions. Big-endian machines are rare these days, so it may not be a big concern.
> 
> Thanks. I'll try this. Meanwhile, does the similar problem exist in the dataloop abstraction as well? If yes, does a fix exist there?

I don't think the big-endean treatment is correct or robust in both yaksa and dataloop -- that were those additional commits tried to fix. But if the user issue is on little endean architecture, I think dataloop code is fine.

**Comment by hzhou** [comment]
I believe the bug is issue #5885 is separate from these changes.

**Pull request closed without merging**
