### PR TITLE
Cleanup of the threading fallback code

### PR DESCRIPTION
**Pull request by pavanbalaji**
## Pull Request Description

Cleans up the threading fallback code.

## Expected Impact

Cleaner code.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
I have reservations on the commit "remove nonrecursive mutex calls". In fact, I have the intention of removing the "recursive" ones (after sufficient code cleanup). IMO, recursive locking is a hack for sloppy code. With recursive locking, it becomes muddy whether a piece of code is inside a lock or not. Ideally, we would put a piece of code inside lock only once with a clear understanding of why we need to add the lock when and where. 

About the comment of romio, I have an open PR letting romio use its own mutex. Romio has no direct access to mpich internals, so I don't see a reason to mix the locking mechanism.

**Comment by hzhou** [comment]
Another of my pet peeves is the MPID_xxx macros. We only need and use `MPID_THREAD_CS_{ENTER,EXIT,YIELD}` etc. Why do we wrap the others? Seems to me they are two levels of indirections for no good reasons.

**Comment by pavanbalaji** [comment]
> I have reservations on the commit "remove nonrecursive mutex calls". In fact, I have the intention of removing the "recursive" ones (after sufficient code cleanup). IMO, recursive locking is a hack for sloppy code. With recursive locking, it becomes muddy whether a piece of code is inside a lock or not. Ideally, we would put a piece of code inside lock only once with a clear understanding of why we need to add the lock when and where.

Yes, ideally.  But that's not the case today.  Note that the point of this patch is that we only need one type of locks -- since we already need recursive locks, I removed nonrecursive locks.  If and when you have a patch that doesn't need recursion, we can easily remove the recursion portion of the code to make them nonrecursive locks.  But till that happens, we need the recursion, unfortunately.

> About the comment of romio, I have an open PR letting romio use its own mutex. Romio has no direct access to mpich internals, so I don't see a reason to mix the locking mechanism.

It does have access to some part of the internals, unfortunately.  But that's a separate discussion and I don't want to deviate from this PR over here.

**Comment by pavanbalaji** [comment]
> Another of my pet peeves is the MPID_xxx macros. We only need and use `MPID_THREAD_CS_{ENTER,EXIT,YIELD}` etc. Why do we wrap the others? Seems to me they are two levels of indirections for no good reasons.

I think it's because those are macros, not actual functions.  I admit I haven't tried hiding the remaining `MPID_Thread_` types/functions.

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Pull request merged**
