### PR TITLE
Remove fi_list.h usage

### PR DESCRIPTION
**Pull request by wesbland**
Remove the usage of the fi_list.h because it is an undocumented API from libfabric and causes problems when building an embedded version of libfabric. Transition all of the slist usages to the utarray linked list.

### CODE REVIEW

**Comment by wesbland** [comment]
@raffenet - This is probably one that should go in before the beta as it fixes a problem with embedded builds of libfabric, which we now depend on.

**Comment by wesbland** [comment]
Also ( @yfguo ) , if you're going to be distributing MPICH with an embedded libfabric, I'd suggest that your testing should probably exercise that case, which from what I understand it doesn't do now.

**Comment by yfguo** [comment]
I agree. I can add the tests for embedded option.

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by yfguo** [comment]
@raffenet @wesbland I have added the option `embedded` to jenkins. It just tests the embedded netmod with default configuration.

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
Looks like there's some issues with the new list code. It also looks like the embedded build is using runtime provider selection and choosing the verbs provider. Not sure if this is desired. Many tests are failing on an assertion in libfabric.

**Comment by wesbland** [comment]
Weird. None of these showed up in our internal testing. I'll check it out.

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Pull request merged**
