### PR TITLE
binding/fortran: replace buildiface scripts with python scripts

### LINKED ISSUE #6807: binding/mpif_h: MPI_SESSION_NULL not defined for Fortran
The new MPI 4 constant `MPI_SESSION_NULL` is defined in C but is not defined in Fortran. Its definition seems to be lacking from `mpif.h`.

### LINKED ISSUE #6824: `mpif.h` does not declare `MPI_Aint_add`
The file `mpif.h` does not declare the functions `MPI_Aint_add` nor `MPI_Aint_diff`.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
The Perl script `src/binding/fortran/mpif_h/buildiface` generates
`mpif.h.in` from scraping mpi.h.in and `mpio.h.in`. The old script has
become difficult to maintain and it is missing a few newly added symbols
including -

    MPI_COMBINER_VALUE_INDEX
    MPI_COMM_TYPE_HW_GUIDED
    MPI_COMM_TYPE_HW_UNGUIDED
    MPI_COMM_TYPE_RESOURCE_GUIDED
    MPI_ERRORS_ABORT
    MPI_MAX_PSET_NAME_LEN
    MPI_MAX_STRINGTAG_LEN
    MPI_SESSION_NULL

In addition, it needs declare all functions that does not return
INTEGER. It was missing `MPI_Aint_add` and `MPI_Aint_diff`.

Fixes #6807
Fixes #6824
[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

**Review by raffenet — APPROVED** [review]

**Pull request merged**
