### PR TITLE
maint: generate separate man sources

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Currently, `maint/gen_binding_c.py` will generate in-source comments mixed within source code. Since both code and comments are auto-generated, there is little benefit of mixing them together. This PR let man sources to be generated separately and optionally.

In addition, this PR--
* makes document dependency optional in `maint/release.pl`
* enhances the HTML index page
* Fixes the missing htmldoc generation in `hydra`
* Added back the man page aliases for MPI constants.

## TODO
* [x] Avoid install `man3/Constants.3`
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
Combining man pages for `MPI_Send` and `MPI_Send_c`:

<BODY BGCOLOR="FFFFFF">
<H1 id="MPI_Send">MPI_Send</H1>
Performs a blocking send
<H2>Synopsis</H2>
<PRE>
</PRE>
<PRE>
int MPI_Send(const void *buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm)
</PRE>

<PRE>
int MPI_Send_c(const void *buf, MPI_Count count, MPI_Datatype datatype, int dest, int tag,
               MPI_Comm comm)
</PRE>

<P>
<H2>Input Parameters</H2>
<DL>
<DT><B>buf </B> <DD> initial address of send buffer (choice)

<DT><B>count </B> <DD> number of elements in send buffer (non-negative integer)

<DT><B>datatype </B> <DD> datatype of each send buffer element (handle)

<DT><B>dest </B> <DD> rank of destination (integer)

<DT><B>tag </B> <DD> message tag (integer)

<DT><B>comm </B> <DD> communicator (handle)
</DL>
<P>
<H2>Notes</H2>
<P>
This routine may block until the message is received by the destination
<P>
process.
<P>
<P>
<H2>Thread and Interrupt Safety</H2>
<P>
This routine is thread-safe.  This means that this routine may be
safely used by multiple threads without the need for any user-provided
thread locks.  However, the routine is not interrupt safe.  Typically,
this is due to the use of memory allocation routines such as <tt>malloc
</tt>or other non-MPICH runtime routines that are themselves not interrupt-safe.
<P>
<H2>Notes for Fortran</H2>
All MPI routines in Fortran (except for <tt>MPI_WTIME</tt> and <tt>MPI_WTICK</tt>) have
an additional argument <tt>ierr</tt> at the end of the argument list.  <tt>ierr
</tt>is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
<tt>call</tt> statement.
<P>
All MPI objects (e.g., <tt>MPI_Datatype</tt>, <tt>MPI_Comm</tt>) are of type <tt>INTEGER
</tt>in Fortran.
<P>
<H2>Errors</H2>
<P>
All MPI routines (except <tt>MPI_Wtime</tt> and <tt>MPI_Wtick</tt>) return an error value;
C routines as the value of the function and Fortran routines in the last
argument.  Before the value is returned, the current MPI error handler is
called.  By default, this error handler aborts the MPI job.  The error handler
may be changed with <tt>MPI_Comm_set_errhandler</tt> (for communicators),
<tt>MPI_File_set_errhandler</tt> (for files), and <tt>MPI_Win_set_errhandler</tt> (for
RMA windows).  The MPI-1 routine <tt>MPI_Errhandler_set</tt> may be used but
its use is deprecated.  The predefined error handler
<tt>MPI_ERRORS_RETURN</tt> may be used to cause error values to be returned.
Note that MPI does <em>not</em> guarantee that an MPI program can continue past
an error; however, MPI implementations will attempt to continue whenever
possible.
<P>
<DL>
<DT><B>MPI_SUCCESS </B> <DD> No error; MPI routine completed successfully.
</DL>
<DL>
<DT><B>MPI_ERR_BUFFER </B> <DD> Invalid buffer pointer.  Usually a null buffer where
one is not valid.
</DL>
<DL>
<DT><B>MPI_ERR_COMM </B> <DD> Invalid communicator.  A common error is to use a null
communicator in a call (not even allowed in <tt>MPI_Comm_rank</tt>).
</DL>
<DL>
<DT><B>MPI_ERR_COUNT </B> <DD> Invalid count argument.  Count arguments must be
non-negative; a count of zero is often valid.
</DL>
<DL>
<DT><B>MPI_ERR_RANK </B> <DD> Invalid source or destination rank.  Ranks must be between
zero and the size of the communicator minus one; ranks in a receive
(<tt>MPI_Recv</tt>, <tt>MPI_Irecv</tt>, <tt>MPI_Sendrecv</tt>, etc.) may also be <tt>MPI_ANY_SOURCE</tt>.
</DL>
<DL>
<DT><B>MPI_ERR_TAG </B> <DD> Invalid tag argument.  Tags must be non-negative; tags
in a receive (<tt>MPI_Recv</tt>, <tt>MPI_Irecv</tt>, <tt>MPI_Sendrecv</tt>, etc.) may
also be <tt>MPI_ANY_TAG</tt>.  The largest tag value is available through the
the attribute <tt>MPI_TAG_UB</tt>.
</DL>
<DL>
<DT><B>MPI_ERR_TYPE </B> <DD> Invalid datatype argument.  Additionally, this error can
occur if an uncommitted MPI_Datatype (see <tt>MPI_Type_commit</tt>) is used
in a communication call.
</DL>
<DL>
<DT><B>MPI_ERR_OTHER </B> <DD> Other error; use <tt>MPI_Error_string</tt> to get more information
about this error code.
</DL>
<P>
<H2>See Also</H2>
 MPI_Isend, MPI_Bsend
<br>
</BODY>

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by raffenet** [comment]
I'm trying to test this out on my machine but maybe I am missing a step. I don't get manpages for any MPI functions.
```
raffenet@mcswl036:main/ (2202_mansrc*) $ ls i/share/man/man3
MPI_2DOUBLE_PRECISION.3          MPI_LONG.3
MPI_2INT.3                       MPI_LONG_DOUBLE.3
MPI_2REAL.3                      MPI_LONG_DOUBLE_INT.3
MPI_ANY_SOURCE.3                 MPI_LONG_INT.3
MPI_ANY_TAG.3                    MPI_LONG_LONG.3
MPI_APPNUM.3                     MPI_LONG_LONG_INT.3
MPI_ARGVS_NULL.3                 MPI_LOR.3
MPI_ARGV_NULL.3                  MPI_LXOR.3
MPI_BAND.3                       MPI_MAXLOC.3
MPI_BOR.3                        MPI_MAX_ERROR_STRING.3
MPI_BOTTOM.3                     MPI_MAX_INFO_KEY.3
MPI_BSEND_OVERHEAD.3             MPI_MAX_INFO_VAL.3
MPI_BXOR.3                       MPI_MAX_LIBRARY_VERSION_STRING.3
MPI_BYTE.3                       MPI_MAX_OBJECT_NAME.3
MPI_COMBINER_CONTIGUOUS.3        MPI_MAX_PORT_NAME.3
MPI_COMBINER_DARRAY.3            MPI_MESSAGE_NULL.3
MPI_COMBINER_DUP.3               MPI_MIN.3
MPI_COMBINER_F90_COMPLEX.3       MPI_MINLOC.3
MPI_COMBINER_F90_INTEGER.3       MPI_MODE_APPEND.3
MPI_COMBINER_F90_REAL.3          MPI_MODE_CREATE.3
MPI_COMBINER_HINDEXED.3          MPI_MODE_DELETE_ON_CLOSE.3
MPI_COMBINER_HINDEXED_BLOCK.3    MPI_MODE_EXCL.3
MPI_COMBINER_HINDEXED_INTEGER.3  MPI_MODE_NOPRECEDE.3
MPI_COMBINER_HVECTOR.3           MPI_MODE_NOPUT.3
MPI_COMBINER_HVECTOR_INTEGER.3   MPI_MODE_NOSTORE.3
MPI_COMBINER_INDEXED.3           MPI_MODE_NOSUCCEED.3
MPI_COMBINER_INDEXED_BLOCK.3     MPI_MODE_RDWR.3
MPI_COMBINER_RESIZED.3           MPI_MODE_SEQUENTIAL.3
MPI_COMBINER_STRUCT.3            MPI_MODE_UNIQUE_OPEN.3
MPI_COMBINER_STRUCT_INTEGER.3    MPI_MODE_WRONLY.3
MPI_COMBINER_SUBARRAY.3          MPI_NO_OP.3
MPI_COMBINER_VECTOR.3            MPI_NULL_DELETE_FN.3
MPI_COMM_DUP_FN.3                MPI_OFFSET.3
MPI_COMM_NULL_DELETE_FN.3        MPI_OP_NULL.3
MPI_COMM_SELF.3                  MPI_ORDER_FORTRAN.3
MPI_COMPLEX.3                    MPI_PROC_NULL.3
MPI_COMPLEX16.3                  MPI_PROD.3
MPI_COMPLEX32.3                  MPI_REAL16.3
MPI_COMPLEX8.3                   MPI_REAL4.3
MPI_CONGRUENT.3                  MPI_REAL8.3
MPI_COUNT.3                      MPI_REPLACE.3
MPI_C_BOOL.3                     MPI_REQUEST_NULL.3
MPI_C_COMPLEX.3                  MPI_SEEK_CUR.3
MPI_C_DOUBLE_COMPLEX.3           MPI_SEEK_END.3
MPI_C_FLOAT_COMPLEX.3            MPI_SHORT.3
MPI_C_LONG_DOUBLE_COMPLEX.3      MPI_SHORT_INT.3
MPI_Copy_function.3              MPI_SIGNED_CHAR.3
MPI_DATATYPE_NULL.3              MPI_SIMILAR.3
MPI_DISTRIBUTE_BLOCK.3           MPI_STATUSES_IGNORE.3
MPI_DISTRIBUTE_CYCLIC.3          MPI_SUBVERSION.3
MPI_DISTRIBUTE_DFLT_DARG.3       MPI_SUM.3
MPI_DISTRIBUTE_NONE.3            MPI_TAG.3
MPI_DIST_GRAPH.3                 MPI_THREAD_FUNNELED.3
MPI_DOUBLE.3                     MPI_THREAD_MULTIPLE.3
MPI_DOUBLE_COMPLEX.3             MPI_THREAD_SERIALIZED.3
MPI_DOUBLE_INT.3                 MPI_TYPECLASS_COMPLEX.3
MPI_DOUBLE_PRECISION.3           MPI_TYPECLASS_INTEGER.3
MPI_DUP_FN.3                     MPI_TYPE_DUP_FN.3
MPI_Delete_function.3            MPI_TYPE_NULL_COPY_FN.3
MPI_ERRHANDLER_NULL.3            MPI_TYPE_NULL_DELETE_FN.3
MPI_ERROR.3                      MPI_T_BIND_MPI_COMM.3
MPI_ERRORS_ABORT.3               MPI_T_BIND_MPI_DATATYPE.3
MPI_ERRORS_ARE_FATAL.3           MPI_T_BIND_MPI_ERRHANDLER.3
MPI_ERRORS_RETURN.3              MPI_T_BIND_MPI_FILE.3
MPI_ERR_ACCESS.3                 MPI_T_BIND_MPI_GROUP.3
MPI_ERR_AMODE.3                  MPI_T_BIND_MPI_INFO.3
MPI_ERR_ARG.3                    MPI_T_BIND_MPI_MESSAGE.3
MPI_ERR_ASSERT.3                 MPI_T_BIND_MPI_OP.3
MPI_ERR_BAD_FILE.3               MPI_T_BIND_MPI_REQUEST.3
MPI_ERR_BASE.3                   MPI_T_BIND_MPI_WIN.3
MPI_ERR_BUFFER.3                 MPI_T_BIND_NO_OBJECT.3
MPI_ERR_COMM.3                   MPI_T_CVAR_HANDLE_NULL.3
MPI_ERR_CONVERSION.3             MPI_T_ENUM_NULL.3
MPI_ERR_COUNT.3                  MPI_T_ERR_CANNOT_INIT.3
MPI_ERR_DIMS.3                   MPI_T_ERR_CVAR_SET_NEVER.3
MPI_ERR_DISP.3                   MPI_T_ERR_CVAR_SET_NOT_NOW.3
MPI_ERR_DUP_DATAREP.3            MPI_T_ERR_INVALID.3
MPI_ERR_FILE.3                   MPI_T_ERR_INVALID_HANDLE.3
MPI_ERR_FILE_EXISTS.3            MPI_T_ERR_INVALID_INDEX.3
MPI_ERR_FILE_IN_USE.3            MPI_T_ERR_INVALID_NAME.3
MPI_ERR_GROUP.3                  MPI_T_ERR_INVALID_SESSION.3
MPI_ERR_INFO.3                   MPI_T_ERR_NOT_INITIALIZED.3
MPI_ERR_INFO_KEY.3               MPI_T_ERR_OUT_OF_HANDLES.3
MPI_ERR_INFO_NOKEY.3             MPI_T_ERR_OUT_OF_SESSIONS.3
MPI_ERR_INFO_VALUE.3             MPI_T_ERR_PVAR_NO_ATOMIC.3
MPI_ERR_INTERN.3                 MPI_T_ERR_PVAR_NO_STARTSTOP.3
MPI_ERR_IN_STATUS.3              MPI_T_ERR_PVAR_NO_WRITE.3
MPI_ERR_IO.3                     MPI_T_PVAR_CLASS_AGGREGATE.3
MPI_ERR_KEYVAL.3                 MPI_T_PVAR_CLASS_COUNTER.3
MPI_ERR_LASTCODE.3               MPI_T_PVAR_CLASS_GENERIC.3
MPI_ERR_LOCKTYPE.3               MPI_T_PVAR_CLASS_HIGHWATERMARK.3
MPI_ERR_NAME.3                   MPI_T_PVAR_CLASS_LEVEL.3
MPI_ERR_NOT_SAME.3               MPI_T_PVAR_CLASS_LOWWATERMARK.3
MPI_ERR_NO_MEM.3                 MPI_T_PVAR_CLASS_PERCENTAGE.3
MPI_ERR_NO_SPACE.3               MPI_T_PVAR_CLASS_SIZE.3
MPI_ERR_NO_SUCH_FILE.3           MPI_T_PVAR_CLASS_STATE.3
MPI_ERR_OP.3                     MPI_T_PVAR_CLASS_TIMER.3
MPI_ERR_OTHER.3                  MPI_T_PVAR_HANDLE_NULL.3
MPI_ERR_PENDING.3                MPI_T_PVAR_SESSION_NULL.3
MPI_ERR_PORT.3                   MPI_T_SCOPE_ALL.3
MPI_ERR_QUOTA.3                  MPI_T_SCOPE_ALL_EQ.3
MPI_ERR_RANK.3                   MPI_T_SCOPE_CONSTANT.3
MPI_ERR_READ_ONLY.3              MPI_T_SCOPE_GROUP.3
MPI_ERR_REQUEST.3                MPI_T_SCOPE_GROUP_EQ.3
MPI_ERR_RMA_ATTACH.3             MPI_T_SCOPE_LOCAL.3
MPI_ERR_RMA_CONFLICT.3           MPI_T_SCOPE_READONLY.3
MPI_ERR_RMA_FLAVOR.3             MPI_T_VERBOSITY_MPIDEV_ALL.3
MPI_ERR_RMA_RANGE.3              MPI_T_VERBOSITY_MPIDEV_BASIC.3
MPI_ERR_RMA_SHARED.3             MPI_T_VERBOSITY_MPIDEV_DETAIL.3
MPI_ERR_RMA_SYNC.3               MPI_T_VERBOSITY_TUNER_ALL.3
MPI_ERR_ROOT.3                   MPI_T_VERBOSITY_TUNER_BASIC.3
MPI_ERR_SERVICE.3                MPI_T_VERBOSITY_TUNER_DETAIL.3
MPI_ERR_SIZE.3                   MPI_T_VERBOSITY_USER_ALL.3
MPI_ERR_SPAWN.3                  MPI_T_VERBOSITY_USER_DETAIL.3
MPI_ERR_TAG.3                    MPI_UB.3
MPI_ERR_TOPOLOGY.3               MPI_UINT16_T.3
MPI_ERR_TRUNCATE.3               MPI_UINT32_T.3
MPI_ERR_TYPE.3                   MPI_UINT64_T.3
MPI_ERR_UNKNOWN.3                MPI_UINT8_T.3
MPI_ERR_UNSUPPORTED_DATAREP.3    MPI_UNDEFINED.3
MPI_ERR_UNSUPPORTED_OPERATION.3  MPI_UNDEFINED_RANK.3
MPI_ERR_WIN.3                    MPI_UNEQUAL.3
MPI_FILE_NULL.3                  MPI_UNIVERSE_SIZE.3
MPI_FLOAT.3                      MPI_UNSIGNED.3
MPI_GRAPH.3                      MPI_UNSIGNED_CHAR.3
MPI_GROUP_NULL.3                 MPI_UNSIGNED_LONG.3
MPI_HOST.3                       MPI_UNSIGNED_LONG_LONG.3
MPI_Handler_function.3           MPI_UNSIGNED_SHORT.3
MPI_INFO_NULL.3                  MPI_User_function.3
MPI_INT.3                        MPI_VERSION.3
MPI_INT16_T.3                    MPI_WCHAR.3
MPI_INT32_T.3                    MPI_WEIGHTS_EMPTY.3
MPI_INT64_T.3                    MPI_WIN_CREATE_FLAVOR.3
MPI_INT8_T.3                     MPI_WIN_DISP_UNIT.3
MPI_INTEGER.3                    MPI_WIN_DUP_FN.3
MPI_INTEGER16.3                  MPI_WIN_FLAVOR_ALLOCATE.3
MPI_INTEGER2.3                   MPI_WIN_FLAVOR_DYNAMIC.3
MPI_INTEGER4.3                   MPI_WIN_FLAVOR_SHARED.3
MPI_INTEGER8.3                   MPI_WIN_MODEL.3
MPI_IN_PLACE.3                   MPI_WIN_NULL.3
MPI_IO.3                         MPI_WIN_NULL_COPY_FN.3
MPI_KEYVAL_INVALID.3             MPI_WIN_NULL_DELETE_FN.3
MPI_LAND.3                       MPI_WIN_SIZE.3
MPI_LASTUSEDCODE.3               MPI_WIN_UNIFIED.3
MPI_LB.3                         MPI_WTIME_IS_GLOBAL.3
MPI_LOCK_SHARED.3                mpiconsts.3
MPI_LOGICAL.3
```

**Comment by hzhou** [comment]
> I'm trying to test this out on my machine but maybe I am missing a step. I don't get manpages for any MPI functions.

Did you use the `release.pl` from this PR? It is kinda chicken-and-egg situation that you need download the new `release.pl` first.

**Comment by raffenet** [comment]
> > I'm trying to test this out on my machine but maybe I am missing a step. I don't get manpages for any MPI functions.
> 
> Did you use the `release.pl` from this PR? It is kinda chicken-and-egg situation that you need download the new `release.pl` first.

I just tried using `make mandoc` after regenerating the C binding source along with `-output-mansrc`.

**Comment by hzhou** [comment]
> I just tried using `make mandoc` after regenerating the C binding source along with `-output-mansrc`.

Must be using a stale `Makefile`. Make sure `./configure` after regenerating the C binding source.

**Comment by raffenet** [comment]
> > I just tried using `make mandoc` after regenerating the C binding source along with `-output-mansrc`.
> 
> Must be using a stale `Makefile`. Make sure `./configure` after regenerating the C binding source.

Hm, that must have been it. I got the pages correctly this time. Looks good.

**Review by raffenet — APPROVED** [review]

**Pull request merged**
