### PR TITLE
submodule: Upgrade hwloc

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Includes a build fix for systems with OpenCL.

## Expected Impact

Fix user-reported build issue.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
To be backported to `3.4.x` after approval.

**Comment by raffenet** [comment]
Looks like hwloc leaks some memory. I'll try the new 2.4.1rc3 to see if it is any better.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
2.4.1rc3 looks to be asan clean. Will update this PR when 2.4.1 GA is released.

**Review by hzhou — APPROVED** [review]

**Comment by hzhou** [comment]
> 2.4.1rc3 looks to be asan clean. Will update this PR when 2.4.1 GA is releas

**Comment by raffenet** [comment]
hwloc 2.4.1 tag is the same commit as 2.4.1rc3, so this should be good to go. I will rebase and merge.

**Pull request merged**
