### PR TITLE
datatype: add MPI_Type_get_value_index

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

For initial implementation, we only return the six predefined pair types
if the input is matching and return MPI_DATATYPE_NULL otherwise.
[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by dalcinl** [comment]
You are probably aware of it, but I'll sait anyway, just in case. The two matters this PR should address are:

- [ ] Add `MPI_COMBINER_VALUE_INDEX` as well, as the constant is intimately related to the new function. 
- [ ] The implementation of `MPI_Type_get_value_index` is half-way. You are handling the part related to the predefined named datatypes `MPI_{XXX}_INT` (MPI-1). However, you are not producing any predefined but _unnamed_ datatype for the cross-product of the {floating} x {integral} datatype sets (that is, datatypes that would return `MPI_COMBINER_VALUE_INDEX` if decoded).

**Comment by hzhou** [comment]
> * The implementation of `MPI_Type_get_value_index` is half-way. You are handling the part related to the predefined named datatypes `MPI_{XXX}_INT` (MPI-1). However, you are not producing any predefined but _unnamed_ datatype for the cross-product of the {floating} x {integral} datatype sets (that is, datatypes that would return `MPI_COMBINER_VALUE_INDEX` if decoded).

Acknowledged. Implementations are not obligated to support extra "unnamed" pair types, right? If that's the case, we are going to leave the latter to TODO. Supporting pair types is quite messy.

**Comment by dalcinl** [comment]
> Acknowledged. Implementations are not obligated to support extra "unnamed" pair types, right?

Oh, you may have a point. Example 6.17 on page 232 seems to be on your side.

> Supporting pair types is quite messy.

The datatype part does not seems so complicated, but it all depends on whether internally you can easily know  the types for which MAX and MIN are defined, and whether a type is integral. Then you can create the pair as a struct, and override the combiner and envelope for decoding. And you have to cache the thing. Still, not something you do in a couple minutes.
The actual MINLOC and MAXLOC implementation may be slightly more involved, as you have to generate in advance all the valid combinations.

**Comment by dalcinl** [comment]
FWIW, mpi4py tests pass.

**Review by dalcinl — APPROVED** [review]

**Comment by hzhou** [comment]
[celebrate]     Zhou, Hui reacted to your message:
________________________________

**Review by raffenet — APPROVED** [review]

**Pull request merged**
