### PR TITLE
test: Check for bash for testing scripts

### PR DESCRIPTION
**Pull request by tarudoodi**
## Pull Request Description

Adds a check for availability of bash in autogen since some of the testing scripts use bash syntax.
Exclusively use bash for testing scripts to avoid warnings.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by tarudoodi** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by tarudoodi** [comment]
Hi @pavanbalaji, does this align with what we discussed yesterday.

**Review by pavanbalaji — APPROVED** [review]
LGTM.  Thank you!

**Comment by tarudoodi** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by pavanbalaji** [comment]
@tarudoodi  Can you rebase this on to `main`?  FYI, we don't merge `main` into our PR branches to avoid clutter.  Can you clean that up too?  The above tests seemed to have failed because of the bad singularity setup on our jenkins nodes, which is fixed now.

**Comment by tarudoodi** [comment]
@pavanbalaji  I will create a new PR with a new branch without main in the name. I don't think I can fix it here.

**Comment by pavanbalaji** [comment]
@tarudoodi you can just force push to the same branch.  No need to create a new PR.

**Comment by tarudoodi** [comment]
I think I didn't understand what you meant. I had used the update branch feature on github and it probably introduced the `Merge main..` thing, is that what you were referring to?

**Comment by pavanbalaji** [comment]
If you rebase your current branch on to `mpich/main`, the merge commit should go away (or you should be able to delete it).  Once you do that, you can force push that new branch on to the `check-bash-main` branch, so you can continue to use this PR.

**Comment by tarudoodi** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by tarudoodi** [comment]
I think it is good now. It was introduced by the "update branch" feature, it went after rebasing.
At first I thought that you didn't want the `main` in `check-bash-main`.

**Comment by tarudoodi** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by tarudoodi** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by tarudoodi** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by tarudoodi** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by tarudoodi** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by tarudoodi** [comment]
@pavanbalaji I think it can be merged now. The one failure is an unrelated timeout.

**Comment by pavanbalaji** [comment]
Done.  Thank you, @tarudoodi

**Pull request merged**
