### PR TITLE
ch4/ucx: enable UCX HW RMA atomics

### PR DESCRIPTION
**Pull request by minsii**
This PR is managed by issue #3514

### CODE REVIEW

**Comment by minsii** [comment]
test:jenkins/ch4/ucx

**Comment by minsii** [comment]
test:jenkins/ch4/ucx

**Comment by minsii** [comment]
test:jenkins/ch4/ucx

**Comment by minsii** [comment]
test:jenkins/ch4/ucx

**Comment by minsii** [comment]
test:jenkins/ch4/ucx

**Comment by minsii** [comment]
Included commits in #3443 which fixes a bug

**Comment by minsii** [comment]
test:jenkins/ch4/ucx

**Comment by minsii** [comment]
test:jenkins/ch4/ucx

**Comment by minsii** [comment]
test:jenkins/ch4/ucx

**Comment by pavanbalaji** [comment]
@minsii Is this PR still being pursued?

**Comment by minsii** [comment]
I think we need keep it open. The feature is needed. The PR is outdated but contains critical changes. I will update it when switch back to MPICH dev.

**Comment by minsii** [comment]
Move this PR to https://github.com/minsii/mpich/pull/1 and close the current one.

**Pull request closed without merging**
