### PR TITLE
Cleanup the release gather structure

### PR DESCRIPTION
**Pull request by pavanbalaji**
## Pull Request Description

Cleanup the release gather structure

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:jenkins/warnings
test:mpich/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch4/most

**Comment by jain-surabhi-23** [comment]
test:jenkins/ch4/most

**Comment by jain-surabhi-23** [comment]
Closing this as these patches were merged as part of #4367

**Pull request closed without merging**
