### PR TITLE
misc: cleanup

### PR DESCRIPTION
**Pull request by wesbland**
## Pull Request Description

Move some cleanup patches from https://github.com/pmodels/mpich/pull/5154 to their own PR. These cleanup a few files that need to be ignored and some unused label warnings.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by wesbland** [comment]
test:mpich/ch4/ofi

**Review by hzhou — APPROVED** [review]
Looks good to me.

**Comment by hzhou** [comment]
@wesbland If you rebase, the spell-checker should pass.

**Comment by wesbland** [comment]
Done. Should be good now.

**Pull request merged**
