### PR TITLE
mpi: autogen comm api

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Renamed MPIX_Comm_idup_with_info with MPI_Comm_idup_with_info.

Updated `comm_impl.c` to conform with script generation.

[skip warnings]

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Review by raffenet — APPROVED** [review]
ideally there would be less churn in the generation commit, but splitting it out now would be too much hassle.

to elaborate: what i envision is adding the changes to `_impl` interfaces in a separate commit. the generation commit should be simply deleting code and replacing it with a generated version.

**Comment by hzhou** [comment]
> ideally there would be less churn in the generation commit, but splitting it out now would be too much hassle.
> 
> to elaborate: what i envision is adding the changes to `_impl` interfaces in a separate commit. the generation commit should be simply deleting code and replacing it with a generated version.

Thanks. 

Yeah, I agree ideally I should do that. Well I started with that, but doing that requires patch implement function prototype headers, patch errnames, and the mpi-functions which all just get deleted in the next commit. I am fine if reviewer asks for it. Otherwise, I certainly appreciate to be able to get-away with it :)

**Pull request merged**
