### PR TITLE
Fix: hydra: numa fix to skip mcdram objects

### PR DESCRIPTION
**Pull request by KavithaTipturMadhu**
MCDRAM nodes are listed as NUMA nodes in hwloc, with a cpuset which
might be the same as another NUMA object. When map-by or bind-to
directive is used in Hydra with NUMA as the value, processes are
bound to (or mapped to NUMA nodes) in a round robin manner in the
list of NUMA nodes. Since MCDRAM and NUMA nodes may share the
same cpuset, two processes might get bound to the same set of
PUs, covered by both the NUMA node and the MCDRAM. Hence, we need
to skip cpuset duplicates when binding or mapping.

### CODE REVIEW

**Comment by raffenet** [comment]
What is hydra doing with the MCDRAM node when we set a binding/mapping to NUMA? Shouldn't it just bind a process to a NUMA cpuset and then move to the next NUMA? I'm having a hard time visualizing the problem.

**Comment by KavithaTipturMadhu** [comment]
MCDRAM is listed as a NUMA object in hwloc, and when a NUMA node and MCDRAM object are associated with the same set of PUs, they get the same cpuset in hwloc. This fix skips duplicate NUMA objects that have the same cpuset, in this case the MCDRAM objects and works as expected, moving on to the next real NUMA object.

**Comment by raffenet** [comment]
OK. I think I understand, but this still seems like a hwloc bug, doesn't it? Seems like we're missing a level in the hierarchy or something...

**Comment by KavithaTipturMadhu** [comment]
MCDRAM maybe attached to a set of PUs, and hence gets a cpuset covering those PUs. And they are NUMA objects, so hwloc classifying MCDRAM as NUMA or assoicating cpuset to it seems technically correct to me. We should take care of this in Hydra by either checking if the NUMA object type is MCDRAM or by checking if it's cpuset is the same as another NUMA node previously covered. I chose the latter since other memory objects might be added later which may pose similar problems.

**Comment by raffenet** [comment]
Maybe this is a dumb question, but my laptop only has 1 NUMA object. Will this cause an infinite loop?

**Comment by KavithaTipturMadhu** [comment]
It isn't supposed to, and I checked on mine, and on KNL nodes too.

**Comment by raffenet** [comment]
OK, fair enough. I also tested locally and it seems fine. I'm going to signoff.

**Pull request merged**
