### PR TITLE
comm: fix split_type error checking and remove shmem_topo

### LINKED ISSUE #6789: mpi4.1: `MPI_Comm_split_type` with `MPI_COMM_TYPE_RESOURCE_GUIDED` still broken
#### Reproducer
```
$ python test/main.py test_comm -k testSplitTypeResourceGuided
[0@kw61149] Python 3.11.6 (/usr/bin/python)
[0@kw61149] numpy 1.26.1 (/home/dalcinl/.local/lib/python3.11/site-packages/numpy)
[0@kw61149] MPI 4.1 (MPICH 4.2.0)
[0@kw61149] mpi4py 4.0.0.dev0 (/home/dalcinl/Devel/mpi4py/build/lib.linux-x86_64-cpython-311/mpi4py)
EEEE
======================================================================
ERROR: testSplitTypeResourceGuided (test_comm.TestCommSelf.testSplitTypeResourceGuided)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dalcinl/Devel/mpi4py/test/test_comm.py", line 292, in testSplitTypeResourceGuided
    comm = self.COMM.Split_type(split_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/mpi4py/MPI/Comm.pyx", line 227, in mpi4py.MPI.Comm.Split_type
    with nogil: CHKERR( MPI_Comm_split_type(
mpi4py.MPI.Exception: Invalid argument, error stack:
internal_Comm_split_type(31014): MPI_Comm_split_type(MPI_COMM_SELF, split_type=4, key=0, MPI_INFO_NULL, newcomm=0x7f6d333d2ae0) failed
internal_Comm_split_type(30986): Invalid split_type argument (4)
```

After looking at the generated `src/binding/c/c_binding.c`, the issue is rather obvious:

```c
static int internal_Comm_split_type(MPI_Comm comm, int split_type, int key, MPI_Info info,
                                    MPI_Comm *newcomm)
{
...
            if (split_type != MPI_UNDEFINED && split_type != MPI_COMM_TYPE_SHARED && split_type != MPI_COMM_TYPE_HW_GUIDED && split_type != MPI_COMM_TYPE_HW_UNGUIDED && split_type != MPIX_COMM_TYPE_NEIGHBORHOOD) {
                MPIR_ERR_SET1(mpi_errno, MPI_ERR_ARG, "**splittype", "**splittype %d", split_type);
                goto fn_fail;
            }
```

and the fix is quite trivial:

```diff
diff --git a/src/binding/c/comm_api.txt b/src/binding/c/comm_api.txt
index c4409a1046..a4787ac41a 100644
--- a/src/binding/c/comm_api.txt
+++ b/src/binding/c/comm_api.txt
@@ -177,7 +177,7 @@ MPI_Comm_split_type:
       The 'split_type' must be non-negative or 'MPI_UNDEFINED'.
 */
 { -- error_check --
-    CHECKENUM: split_type, splittype, MPI_UNDEFINED MPI_COMM_TYPE_SHARED MPI_COMM_TYPE_HW_GUIDED MPI_COMM_TYPE_HW_UNGUIDED MPIX_COMM_TYPE_NEIGHBORHOOD
+    CHECKENUM: split_type, splittype, MPI_UNDEFINED MPI_COMM_TYPE_SHARED MPI_COMM_TYPE_HW_GUIDED MPI_COMM_TYPE_HW_UNGUIDED MPI_COMM_TYPE_RESOURCE_GUIDED MPIX_COMM_TYPE_NEIGHBORHOOD
 }
 
 MPI_Comm_test_inter:
```

After applying the patch above, all mpi4py tests run to completion.

PS: I just merged MPI-4.1 support in mpi4py. If you are testing against mpi4py@master, please pull the repository.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Fix a missing error checking in `MPI_Comm_split_type` with `MPIX_COMM_TYPE_RESOURCE_GUIDED`.

Also, remove the experimental `shmem_topo` hints now that its functionality is fully standardized with `MPI_COMM_TYPE_HW_GUIDED` and `MPI_COMM_TYPE_RESOURCE_GUIDED`.

Fixes #6789

[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by dalcinl** [comment]
This PR seems to fix the previously failing tests in mpi4py. 

However, there is also a segfault with hydra+ch3:sock and a deadlock with gforker+ch3:sock.
I'm not sure yet whether these issues are somehow related to this PR. 
You may know better where you have been putting your fingers.
https://github.com/mpi4py/mpi4py-testing/actions/runs/6812828927

**Comment by hzhou** [comment]
test:mpich/ch3/sock

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
> This PR seems to fix the previously failing tests in mpi4py.
> 
> However, there is also a segfault with hydra+ch3:sock and a deadlock with gforker+ch3:sock. I'm not sure yet whether these issues are somehow related to this PR. You may know better where you have been putting your fingers. https://github.com/mpi4py/mpi4py-testing/actions/runs/6812828927

It might be due to missing a rebase. Could you try test again?

**Comment by hzhou** [comment]
@dalcinl Never mind, I reproduced the segfault.

**Comment by hzhou** [comment]
@dalcinl  `MPI_Win_allocate_shared`  may return an error if it can't allocate shared memory for all processes. Only a communicator from `MPI_Comm_split_type` with `MPI_COMM_TYPE_SHARED` can guarantee the communicator to be on a single shared memory domain. 

`ch3-sock` does not support shared memory, thus `MPI_Win_allocate_shared` on `MPI_COMM_WORLD` with `size > 1` will fail. Previously it falls back to `MPI_Win_allocate`, but now it returns error.

**Comment by dalcinl** [comment]
> `ch3-sock` does not support shared memory, thus `MPI_Win_allocate_shared` on `MPI_COMM_WORLD` with `size > 1` will fail. Previously it falls back to `MPI_Win_allocate`, but now it returns error.

Shouldn't we get a proper MPI error rather than a segfault?

**Comment by hzhou** [comment]
> > `ch3-sock` does not support shared memory, thus `MPI_Win_allocate_shared` on `MPI_COMM_WORLD` with `size > 1` will fail. Previously it falls back to `MPI_Win_allocate`, but now it returns error.
> 
> Shouldn't we get a proper MPI error rather than a segfault?

Totally! Fixing it in https://github.com/pmodels/mpich/pull/6792

**Comment by dalcinl** [comment]
mpi4py tests back to [green](https://github.com/mpi4py/mpi4py-testing/actions/runs/6815987167).

**Review by dalcinl — APPROVED** [review]

**Review by raffenet — APPROVED** [review]

**Pull request merged**
