### PR TITLE
misc: correct spelling

### PR DESCRIPTION
**Pull request by eschnett**
## Pull Request Description

Correct spelling of "commutative" in comments.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
@eschnett Thanks for the corrections. Could you sign the  [contribution agreement](http://www.mpich.org/documentation/contributor-docs/) before we can merge it?

**Comment by eschnett** [comment]
I submitted my signed agreement.

**Review by hzhou — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by hzhou** [comment]
test:mpich/warnings

**Pull request merged**
