### PR TITLE
ch4: make progress yield consistent

### PR DESCRIPTION
**Pull request by danghvu**
The ch3 behavior is that: non-blocking progress (such as MPID_Progress_test) never yields. MPID_Progress_wait returns if there is progress, otherwise yields for other threads.

This PR makes ch4 progress consistent with ch3, thus reducing number of yields (such as in `MPI_Waitany/some` -- yield twice in `MPID_Progress_test` and `MPIR_Waitany/some`) and improving performance of message rate. See number below for 44 threads, one per core, in the `it` Omnipath cluster.

before patch
```
size | MB | Msg/s
-- | -- | --
1 | 0.14 | 144205.7
2 | 0.29 | 144368.85
4 | 0.58 | 144149.81
8 | 1.16 | 144565.68
16 | 2.3 | 143940.37
32 | 4.61 | 144112.97
64 | 9.2 | 143733.12
128 | 18.39 | 143699.48
256 | 36.64 | 143123.34
512 | 72.83 | 142238.6
1024 | 148.87 | 145380.8
2048 | 325.82 | 159091.18
4096 | 608.4 | 148534.7
8192 | 1058.7 | 129235.83
16384 | 1874.64 | 114418.69
32768 | 2768.96 | 84501.89
65536 | 4837.29 | 73811.12
131072 | 7277.89 | 55525.87
262144 | 6304.71 | 24050.56
524288 | 6622.97 | 12632.32
1048576 | 6914.09 | 6593.79
2097152 | 7149.23 | 3409.02
4194304 | 8052.21 | 1919.8
```

after

```
size | MB | Msg/s
-- | -- | --
1 | 0.36 | 361524.17
2 | 0.74 | 370091.73
4 | 1.45 | 362206.5
8 | 2.88 | 360046.54
16 | 5.79 | 361663.52
32 | 11.37 | 355278.26
64 | 21.8 | 340600.47
128 | 28.35 | 221510.8
256 | 55.15 | 215441.16
512 | 107.99 | 210911.38
1024 | 214.1 | 209080.84
2048 | 403.63 | 197084.79
4096 | 740.8 | 180860.38
8192 | 1244.56 | 151924.24
16384 | 1701.73 | 103865.13
32768 | 3065.03 | 93537.42
65536 | 5553.38 | 84737.85
131072 | 8150.92 | 62186.56
262144 | 6997.48 | 26693.27
524288 | 6908.54 | 13176.99
1048576 | 7022.73 | 6697.4
2097152 | 7706.46 | 3674.73
4194304 | 8030.88 | 1914.71
```

### CODE REVIEW

**Comment by danghvu** [comment]
test:jenkins/ch4/most

**Comment by danghvu** [comment]
test:jenkins/ch4/most

**Comment by danghvu** [comment]
test:jenkins/ch4/most

**Comment by danghvu** [comment]
test:jenkins/ch4/most

**Comment by danghvu** [comment]
test:jenkins/ch4/most

**Comment by danghvu** [comment]
@halimamer @raffenet for review

**Comment by halimamer** [comment]
The code looks good to me. The only cosmetic comment I have is that I see unnecessary newlines after `CS_YIELD` inconsistently. I'd say just drop them.

Regarding the commit messages, I think they need to elaborate more. The title of the comment for the first and second commits are fine but they need an explanation in the body. As for the 3rd commit message, the title is incomplete (instead of what?) and the body needs a brief explanation.

Maybe @raffenet  has other comments

**Comment by raffenet** [comment]
No additional comments from me. Should be OK to merge after updating with @halimamer suggestions.

**Comment by danghvu** [comment]
@raffenet I removed extra spaces and added more detailed comments.

**Comment by hajimefu** [comment]
test:intel:ch4/ofi/sockets/all/all/all/debug,default

**Comment by hajimefu** [comment]
test:intel:ch4/ofi/sockets/all/all/all/debug,default

**Pull request merged**
