### PR TITLE
Collective selection for ibcast 

### PR DESCRIPTION
**Pull request by rkalidas**
This PR adds collective selection for ibcast similar to bcast using containers. PR #3762 is prerequisite for this PR. I have added my commits (total 7) on top of PR #3762.

### CODE REVIEW

**Comment by rkalidas** [comment]
test:jenkins/ch4/most

**Comment by rkalidas** [comment]
test:jenkins/ch4/most

**Comment by rkalidas** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
@rkalidas There are `FUNCNAME` headers now need be removed, that applies to the parent PR#3762

**Comment by rkalidas** [comment]
> @rkalidas There are `FUNCNAME` headers now need be removed, that applies to the parent PR#3762

Ok, I will update the PR.

**Comment by hzhou** [comment]
@zhenggb72 Could take an assessment to see whether this PR is now obsolete?

**Comment by zhenggb72** [comment]
> @zhenggb72 Could take an assessment to see whether this PR is now obsolete?

Yes, it is obsolete once Pavan merge his collective selection PR.

**Comment by hzhou** [comment]
> > @zhenggb72 Could take an assessment to see whether this PR is now obsolete?
> 
> Yes, it is obsolete once Pavan merge his collective selection PR.

Good. I am closing it then.

**Pull request closed without merging**
