### PR TITLE
build: allow hwloc to be disabled in configure

### PR DESCRIPTION
**Pull request by pavanbalaji**

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
Tests have passed.  I'll add Ken's signoff and merge.

**Comment by jain-surabhi-23** [comment]
@pavanbalaji @raffenet I tried this recently added option to specifically turn off `hwloc` and I am getting the following build errors -
```
tools/topo/hwloc/topo_hwloc.c:150:16: error: ‘HWLOC_OBJ_PACKAGE’ undeclared here (not in a function)
     {"socket", HWLOC_OBJ_PACKAGE},
                ^
tools/topo/hwloc/topo_hwloc.c:151:14: error: ‘HWLOC_OBJ_NUMANODE’ undeclared here (not in a function)
     {"numa", HWLOC_OBJ_NUMANODE},
              ^
tools/topo/hwloc/topo_hwloc.c:154:18: error: ‘HWLOC_OBJ_L1CACHE’ undeclared here (not in a function)
     {"l1dcache", HWLOC_OBJ_L1CACHE},
                  ^
tools/topo/hwloc/topo_hwloc.c:156:18: error: ‘HWLOC_OBJ_L1ICACHE’ undeclared here (not in a function)
     {"l1icache", HWLOC_OBJ_L1ICACHE},
                  ^
tools/topo/hwloc/topo_hwloc.c:158:18: error: ‘HWLOC_OBJ_L2CACHE’ undeclared here (not in a function)
     {"l2dcache", HWLOC_OBJ_L2CACHE},
                  ^
tools/topo/hwloc/topo_hwloc.c:160:18: error: ‘HWLOC_OBJ_L2ICACHE’ undeclared here (not in a function)
     {"l2icache", HWLOC_OBJ_L2ICACHE},
                  ^
tools/topo/hwloc/topo_hwloc.c:162:18: error: ‘HWLOC_OBJ_L3CACHE’ undeclared here (not in a function)
     {"l3dcache", HWLOC_OBJ_L3CACHE},
                  ^
tools/topo/hwloc/topo_hwloc.c:164:18: error: ‘HWLOC_OBJ_L3ICACHE’ undeclared here (not in a function)
     {"l3icache", HWLOC_OBJ_L3ICACHE},
                  ^
tools/topo/hwloc/topo_hwloc.c:166:18: error: ‘HWLOC_OBJ_L4CACHE’ undeclared here (not in a function)
     {"l4dcache", HWLOC_OBJ_L4CACHE},
                  ^
tools/topo/hwloc/topo_hwloc.c:169:18: error: ‘HWLOC_OBJ_L5CACHE’ undeclared here (not in a function)
     {"l5dcache", HWLOC_OBJ_L5CACHE},
                  ^
tools/topo/hwloc/topo_hwloc.c: In function ‘HYDT_topo_hwloc_init’:
tools/topo/hwloc/topo_hwloc.c:533:5: error: implicit declaration of function ‘hwloc_topology_set_io_types_filter’ [-Werror=implicit-function-declaration]
     hwloc_topology_set_io_types_filter(topology, HWLOC_TYPE_FILTER_KEEP_ALL);
     ^
tools/topo/hwloc/topo_hwloc.c:533:5: warning: nested extern declaration of ‘hwloc_topology_set_io_types_filter’ [-Wnested-externs]
tools/topo/hwloc/topo_hwloc.c:533:50: error: ‘HWLOC_TYPE_FILTER_KEEP_ALL’ undeclared (first use in this function)
     hwloc_topology_set_io_types_filter(topology, HWLOC_TYPE_FILTER_KEEP_ALL);
```

The configure line I used was -
```
'--disable-perftest' '--with-custom-version-string=drop27' '--disable-ft-tests' '--with-fwrapname=mpigf' '--with-filesystem=ufs+nfs' '--enable-timer-type=linux86_cycle' '--enable-romio' '--with-mpe=no' '--with-smpcoll=yes' '--with-assert-level=0' '--enable-shared' '--enable-static' '--enable-error-messages=yes' '--enable-visibility' '--enable-large-tests' '--enable-strict' '--enable-collalgo-tests' '--enable-izem=atomic,queue' '--with-zm-prefix=yes' '--enable-g=none' '--enable-error-checking=no' '--enable-fast=all,O3' '--disable-debuginfo' '--with-device=ch4:ofi:sockets' '--enable-handle-allocation=default' '--enable-threads=multiple' '--without-valgrind' '--enable-timing=none' '--enable-embedded' '--enable-ch4-direct=auto' '--enable-ch4-mt=runtime' '--with-ch4-netmod-ofi-args=' '--enable-thread-cs=per-vci' '--with-libfabric=embedded' '--with-ofi=embedded' 'MPICHLIB_CFLAGS=-O3 -Wall -ggdb  -ggdb -Wall -mtune=generic -std=gnu99' 'MPICHLIB_CXXFLAGS=-O3 -Wall -ggdb  -ggdb -Wall -mtune=generic' 'MPICHLIB_FCFLAGS=-O3 -Wall -ggdb  -ggdb -Wall -mtune=generic' 'MPICHLIB_F77FLAGS=-O3 -Wall -ggdb  -ggdb -Wall -mtune=generic' 'MPICHLIB_LDFLAGS=-O3 -L/opt/intel/csr/lib64 -L/usr/lib64  -mtune=generic' 'CC=gcc' 'LDFLAGS= -L/opt/intel/csr/lib64 -Wl,-z,now' 'CXX=g++' 'FC=gfortran' 'F77=gfortran' --with-hwloc-prefix=no
```

Am I missing anything?

**Pull request merged**
