### PR TITLE
ch4/ofi: fix am_isend that am_type may get overwritten

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

MPIDI_OFI_am_isend_short and MPIDI_OFI_am_isend_long are both using
event_id MPIDI_OFI_EVENT_AM_SEND and the completion action differs by
checking am_type in the msg_hdr field of the request object. However,
there is a chance the request need handle long message recv before the
send side completion and the msg_hdr field gets overwritten in
MPIDI_OFI_handle_rdma_read, resulting in loss of send side completion.

Currently, this bug causes the following test failures on FreeBSD:
```
rma/rma_contig 2
rma/at_complete 2
rma/getfence1 2
rma/manyget 2 
```
It is possible this also fixes some of the sporadic rma test failures we see during regular review testings.

## Expected Impact
[skip warnings]
## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [ ] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by hzhou** [comment]
I spent a whole day chasing this bug. The code is so bad that I think I'll have to spend the same amount of time again if I ever need to debug this again. The number one stink is in `ofi_pre.h` that we have multiple similar named structures with similar contents all with fields put together from different usage scenarios. How would anyone keep track of what is for what?

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: freebsd

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: freebsd64

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Review by raffenet — APPROVED** [review]
LGTM

**Pull request merged**
