### PR TITLE
Use MPL atomics in intra-node collectives instead of IZEM

### PR DESCRIPTION
**Pull request by jain-surabhi-23**
## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [ ] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by jain-surabhi-23** [comment]
@hzhou I am using MPL atomics in this PR for intra-node collectives. You can take these patches for your PR.

The patch "Remove volatile" is temporary. It will be taken out once @shintaro-iwasaki adds `volatile` keyword to the MPL API.

**Comment by shintaro-iwasaki** [comment]
@jain-surabhi-23 If `volatile` is found to be necessary, it will be added in MPL; this should be taken care of by the MPL/atomics implementation.

**Comment by hzhou** [comment]
@jain-surabhi-23 which test (which CVARS) tests this function?

**Comment by jain-surabhi-23** [comment]
`MPIR_CVAR_BCAST_POSIX_INTRA_ALGORITHM=release_gather`, `MPIR_CVAR_REDUCE_POSIX_INTRA_ALGORITHM=release_gather`, `MPIR_CVAR_ALLREDUCE_POSIX_INTRA_ALGORITHM=release_gather`

**Comment by hzhou** [comment]
test:mpich/custom

testlist: bcasttest 10
: env=MPIR_CVAR_BCAST_POSIX_INTRA_ALGORITHM=release_gather 
: env=MPIR_CVAR_COLL_SHM_LIMIT_PER_NODE=131072 
: env=MPIR_CVAR_BCAST_INTRANODE_BUFFER_TOTAL_SIZE=16384 
: env=MPIR_CVAR_BCAST_INTRANODE_NUM_CELLS=2 
: env=MPIR_CVAR_BCAST_INTRANODE_TREE_KVAL=8 
: env=MPIR_CVAR_BCAST_INTRANODE_TREE_TYPE=knomial_1

**Comment by hzhou** [comment]
@jain-surabhi-23 Need remove the include of `zm_common.h`: 
```
./src/mpid/ch4/shm/posix/release_gather/release_gather_types.h:16:30: fatal error: common/zm_common.h: No such file or directory
 #include "common/zm_common.h"
                              ^
```

**Comment by jain-surabhi-23** [comment]
@hzhou I pushed the fix. Can you restart the tests?

**Comment by hzhou** [comment]
test:mpich/custom

testlist: coll/bcasttest 10
: env=MPIR_CVAR_BCAST_POSIX_INTRA_ALGORITHM=release_gather
: env=MPIR_CVAR_COLL_SHM_LIMIT_PER_NODE=131072
: env=MPIR_CVAR_BCAST_INTRANODE_BUFFER_TOTAL_SIZE=16384
: env=MPIR_CVAR_BCAST_INTRANODE_NUM_CELLS=2
: env=MPIR_CVAR_BCAST_INTRANODE_TREE_KVAL=8
: env=MPIR_CVAR_BCAST_INTRANODE_TREE_TYPE=knomial_1

**Comment by hzhou** [comment]
test:mpich/custom

testlist: coll/bcasttest 10
: env=MPIR_CVAR_BCAST_POSIX_INTRA_ALGORITHM=release_gather
: env=MPIR_CVAR_COLL_SHM_LIMIT_PER_NODE=131072
: env=MPIR_CVAR_BCAST_INTRANODE_BUFFER_TOTAL_SIZE=16384
: env=MPIR_CVAR_BCAST_INTRANODE_NUM_CELLS=2
: env=MPIR_CVAR_BCAST_INTRANODE_TREE_KVAL=8
: env=MPIR_CVAR_BCAST_INTRANODE_TREE_TYPE=knomial_1

**Comment by hzhou** [comment]
@jain-surabhi-23 Seems good. Last thing, could you remove the xfail for release_gather tests?

**Comment by hzhou** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
@jain-surabhi-23 What's the status?

**Comment by jain-surabhi-23** [comment]
@hzhou Status of? I removed the xfail. Anything else you are waiting on?

**Comment by hzhou** [comment]
Oh, I saw you made another push after the tests, so I thought you changed something. Never mind, let me re-run the tests:

test:jenkins/ch3/tcp
test:jenkins/ch4/most
test:mpich/warnings/more

**Comment by jain-surabhi-23** [comment]
I just reworded the second commit. No other changes were made.

**Comment by hzhou** [comment]
test:mpich/warnings/more

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp
test:jenkins/ch4/most

**Pull request merged**
