### PR TITLE
ch4: separating per-op-type data structure

### PR DESCRIPTION
**Pull request by yfguo**
Separating the data workq element data structure by the type of op to
reduce size and intructions of filling the elements.

### CODE REVIEW

**Comment by hajimefu** [comment]
@yfguo Thanks! I'll take a look and test with the rest of work queue patches. Meanwhile you may want to take a look at the style checker issues.

**Comment by yfguo** [comment]
Yeah, the style checking issue was strange on the curly bracket for the function. Is pmodel/mpich#3117 the latest version for the WORKQ+VNI?

**Comment by hajimefu** [comment]
@yfguo Just updated #3117 to the latest state.

**Comment by hajimefu** [comment]
@yfguo Just FYI, I took this patch and am now trying to adapt it with the latest code.

**Comment by hajimefu** [comment]
I think we can close this -- already merged as a part of #3364.

**Pull request closed without merging**
