### PR TITLE
F77tof90

### PR DESCRIPTION
**Pull request by raffenet**
This is a step-by-step breakdown of the first commit in #2382. Probably me just being overly committed to showing the work involved, but it fixes a few issues I noticed in the other PR.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by ggouaillardet** [comment]
@raffenet the reason why I moved `f77tof90` from `maint` to `test/mpi/maint` is I can run `autogen.sh` in the mpich source directory, and then directly `/.../test/mpi/configure`

If `f77tof90` is left in the `maint` directory, then `configure` will fail unless invoked with `--disable-maintainer_mode`. On one hand, this is not a deal breaker, but on the other hand, since `f77tof90` is only used in `test/mpi`, it could make more sense to have it in `test/mpi/maint`

**Comment by ggouaillardet** [comment]
@raffenet I had a second look at it, and it seems the only missing patch is below

```diff
diff --git a/test/mpi/configure.ac b/test/mpi/configure.ac
index 830251d7c..7ea794751 100644
--- a/test/mpi/configure.ac
+++ b/test/mpi/configure.ac
@@ -81,8 +81,8 @@ if test "X$master_top_srcdir" = "X" -a "$USE_MAINTAINER_MODE" = "yes" ; then
         ;;        
     esac
     # Now, see if we can find the f77tof90 routine
-    if test -x $use_top_srcdir/../../maint/f77tof90 ; then 
-        master_top_srcdir=`cd $use_top_srcdir && cd ../.. && pwd`
+    if test -x $use_top_srcdir/maint/f77tof90 ; then 
+        master_top_srcdir=`cd $use_top_srcdir && pwd`
     else 
         AC_MSG_ERROR([Unable to find master source file - reconfigure using --disable-maintainer_mode])
     fi
diff --git a/test/mpi/maint/f77tof90 b/test/mpi/maint/f77tof90
index fb2168d69..2844d881d 100755
--- a/test/mpi/maint/f77tof90
+++ b/test/mpi/maint/f77tof90
@@ -389,8 +389,8 @@ if MAINTAINER_MODE
 # change its contents
 \$(srcdir)/Makefile.am: \$(srcdir)/Makefile.am-stamp
 
-\$(srcdir)/Makefile.am-stamp: \$(srcdir)/${indir}/Makefile.am \$(srcdir)/maint/f77tof90
-\t( cd \$(srcdir) && ./maint/f77tof90 ${indir} ${outdir} Makefile.am Makefile.ap )
+\$(srcdir)/Makefile.am-stamp: \$(top_srcdir)/${indir}/Makefile.am \$(top_srcdir)/maint/f77tof90
+\t( cd \$(top_srcdir) && ./maint/f77tof90 ${indir} ${outdir} Makefile.am Makefile.ap )
 
 MAINTAINERCLEANFILES ${mcf_plus}= Makefile.am-stamp
 EXTRA_DIST ${ed_plus}= Makefile.am-stamp ${testlist_ap} ${makefile_ap}
```

**Comment by raffenet** [comment]
@ggouaillardet thanks! I was just in the process of tracking down one of these. I'll include the rest and hopefully have this ready to go today.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
Test results look fine for this PR now. Tagging @yfguo for review.

**Comment by gcongiu** [comment]
test:jenkins/ch3/tcp

**Pull request merged**
