### PR TITLE
Collective selection logic: initial phase

### PR DESCRIPTION
**Pull request by AlexeyMalkhanov**

### CODE REVIEW

**Comment by wesbland** [comment]
Why are there three of the same commits here? Shouldn't this either be one commit or a bunch of different commits?

**Comment by AlexeyMalkhanov** [comment]
@wesbland Corrected

**Comment by akhillanger** [comment]
Alexey, Does this PR address what we discussed with Pavan during the hackathon at Austin last month?

**Comment by AlexeyMalkhanov** [comment]
@akhillanger Yes, this approach represents separation of selection and call

**Comment by wesbland** [comment]
Closing this pending a new version that we're working on. Should update and reopen soon.

**Comment by AlexeyMalkhanov** [comment]
@wesbland It seems that you closed it by mistake instead of #2626 which represents collective framework. Could you please reopen this PR #2616  which represents collective selection logic?

**Comment by wesbland** [comment]
I closed both as we have work to do on both.

**Pull request closed without merging**
