### PR TITLE
ch4/ofi: add cvar to allow disable fi_inject_write

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
The tcp provider does not provide accurate remote completion counter with fi_inject_write, and may break the synchronization. Add a cvar for user to disable it.

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Review by raffenet — APPROVED** [review]
Looks OK. Should we report the bug to libfabric?

**Comment by hzhou** [comment]
> Looks OK. Should we report the bug to libfabric?

I am not sure whether this is a bug. The inject_write does not set `FI_DELIVERY_COMPLETE`, so in theory do not need reflect the remote completion in the counter. Besides, isn't `FI_DELIVERY_COMPLETE` defeat the purpose of `inject_write` in the first place? It currently works for the other providers, but I am not sure whether this is just a side effect.

**Comment by raffenet** [comment]
> > Looks OK. Should we report the bug to libfabric?
> 
> I am not sure whether this is a bug. The inject_write does not set `FI_DELIVERY_COMPLETE`, so in theory do not need reflect the remote completion in the counter. Besides, isn't `FI_DELIVERY_COMPLETE` defeat the purpose of `inject_write` in the first place? It currently works for the other providers, but I am not sure whether this is just a side effect.

Oh, I see. I was thinking the counter on the target process, not the origin one. Maybe we should consider removing usage entirely and instead adding an `FI_INJECT` flag to `fi_writemsg` in the small message case?

**Comment by hzhou** [comment]
Yes, I was also thinking about that way. Anyway, I agree we should have a conversation with libfabric folks and see what do they recommend

**Pull request merged**
