### PR TITLE
f08: Support "--disable-romio" case

### PR DESCRIPTION
**Pull request by roblatham00**
## Pull Request Description

the f08 'buildiface' would generate prototypes that used symbols only provided in the --enable-romio case.
## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ X] Commits are self-contained and do not do two things at once
* [ X] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ X] Passes whitespace checkers
* [ X] Passes warning tests
* [ ] Passes all tests
* [X ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by pavanbalaji** [comment]
@roblatham00   Is `ROMIO_VERSION` the right macro to check for?  Would `HAVE_ROMIO` be better?

**Comment by roblatham00** [comment]
I went with ROMIO_VERSION since that is defined in mpio.h -- a header only included in the --enable-romio case.  

I agree that HAVE_ROMIO is more standard, but buildiface doesn't bring in mpichcconf.h  .  Looking at the other language bindings, we seem to be inconsistent about that...

```
src/binding/cxx/buildiface:     # we have mpichconf.h (which we do not, so as to keep the user's
src/binding/cxx/buildiface:    print $OUTFD "#include \"mpichconf.h\"\n"; # Requires for HAVE_FORTRAN_BINDING
src/binding/fortran/mpif_h/buildiface:    print $OUTFD "#include \"mpichconf.h\"\n";
src/binding/fortran/mpif_h/buildiface:    print $OUTFD "#include \"mpichconf.h\"\n";
src/binding/fortran/mpif_h/mpi_fortimpl.h:#include "mpichconf.h"
```

The f08 generated files are not user visible, right? so including the internal, not-distributed mpichconf.h shouldn't be a problem.  Happy to take either approach.

**Comment by pavanbalaji** [comment]
Yeah, it's internal and we do include `mpichconf.h` as you noticed.  I think that'd be a cleaner approach instead of `ROMIO_VERSION`.

**Comment by pavanbalaji** [comment]
Cross-referencing a Gentoo bug report about this here: https://bugs.gentoo.org/686134

**Review by pavanbalaji — APPROVED** [review]

**Pull request merged**
