### PR TITLE
Patching libtool to support the newer IBM XL Fortran compiler

### PR DESCRIPTION
**Pull request by yfguo**
This is the correct fix for #3050 . The new `xlf` already supports dynamic linking. Libtool need to be patched to pass the correct option.

### CODE REVIEW

**Comment by raffenet** [comment]
Looks good in Travis, so I'm OK with this. Maybe @harisubramoni can test on his system?

**Comment by raffenet** [comment]
I've signed off, but will wait for confirmation of the fix before merge.

**Comment by yfguo** [comment]
Sure.

**Comment by raffenet** [comment]
I went ahead and merged because I believe this to be the correct fix. Regardless, it removed the incorrect flag, which is an improvement.

**Pull request merged**
