### PR TITLE
dt: Remove PREPEND_PREFIX from dataloop code

### PR DESCRIPTION
**Pull request by wesbland**
Remove another unnecessary indirection macro that makes
grep'ing/ctag'ing the code hard.

### CODE REVIEW

**Comment by raffenet** [comment]
Do we need to consider the `mpitypes` package here if this is changed? If I understand correctly, that seemed to be the reason for this feature. @roblatham00

**Comment by roblatham00** [comment]
Right. the idea was that MPICH would have a deployment of `mpitypes`.  Well, 11 years later and MPICH is still the one consumer of the dataloop code.   The redirect macros mess up cscope and ctags , and I'd be ok with them going. 

Maybe as a courtesy check with Rob Ross:  I'm sure he'd quickly cede the point to those actually writing code, but it's his handiwork.

**Comment by wesbland** [comment]
Did anybody ping Rob Ross about this? Is it good to go?

**Comment by raffenet** [comment]
He was OK with it overall. Let me give it another quick review.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
Rebased on master for testing purposes.
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
Pretty annoying how github sends old hash values to Jenkins :angry:. Let's try this again.
test:jenkins/ch3/tcp

**Pull request merged**
