### PR TITLE
ch4: add vci parameters to netmode send/recv API

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
# Addressing
* At netmod layer, all vci (or vni to be specific -- TODO: rename to vni) are explicit
* A complete endpoint include both rank and vni
* Rank refers to global rank (world comm)
* A full address table will need the demension of `table[RANKS][VCIS][VCIS]`, specifying end-to-end connections

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by wesbland** [comment]
cc: @sagarth

**Comment by hzhou** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch4/most

**Pull request merged**
