### PR TITLE
Unalign fix rebase test

### PR DESCRIPTION
**Pull request by monicasee**
test:jenkins/ch3/tcp

### CODE REVIEW

**Comment by monicasee** [comment]
test:jenkins/ch3/sock

**Comment by monicasee** [comment]
test:jenkins/ch3/tcp

**Comment by monicasee** [comment]
test:jenkins/ch3/sock

**Comment by monicasee** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
Is there a difference between this and #2392?

**Comment by monicasee** [comment]
It enables special code only enabled when strict alignment is required (e.g., on SPARC). This pull is only for testing use.

**Comment by monicasee** [comment]
test:jenkins/ch3/sock

**Comment by monicasee** [comment]
test:jenkins/ch3/all

**Comment by raffenet** [comment]
Can this be closed?

**Pull request closed without merging**
