### PR TITLE
Modify MPL GPU Abstraction in preparation for ZE support

### PR DESCRIPTION
**Pull request by sagarth**
## Pull Request Description
This PR contains patches that extend and modify the MPL GPU abstraction, including the MPL interfaces. This is done in preparation to support ZE implementation of the GPU abstraction.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by sagarth** [comment]
@pavanbalaji I'm fine squashing those patches. Sure, I'll let you know when this PR is ready for review.

**Comment by sagarth** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by sagarth** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by sagarth** [comment]
@pavanbalaji I've squashed the patches that you suggested. I think this PR is ready for review.

**Comment by pavanbalaji** [comment]
Tests seem to be clean.  @sagarth can you rebase and rerun the warning tests, so we can merge it in?

**Comment by pavanbalaji** [comment]
@sagarth The author checklist also needs to be completed.

**Comment by sagarth** [comment]
@pavanbalaji This PR looks ready to merge.

**Comment by pavanbalaji** [comment]
> @pavanbalaji This PR looks ready to merge.

Can you rebase it on to master?

**Comment by sagarth** [comment]
Just did. Apparently a new PR just got merged while the tests completed from the last rebase 🙂

**Comment by pavanbalaji** [comment]
> Just did. Apparently a new PR just got merged while the tests completed from the last rebase 🙂

I think you did a merge.  Can you do a rebase instead?

**Comment by sagarth** [comment]
Oops, I used the git interface this time. Looks that that was a merge. Let me fix it.

**Pull request merged**
