### PR TITLE
romio: call PMPI in romio/adio/common/*

### PR DESCRIPTION
**Pull request by hzhou**
Fixes issue #5299

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
The use of `MPI_ ` seems to have been intentional, going back to https://github.com/pmodels/mpich-cvs/commit/105eceb790dc5577402bd2657ca97c70412a5d36 in the CVS history. We have https://github.com/pmodels/mpich/blob/main/src/mpi/romio/adio/include/mpipr.h to do the namespace shift by default. There is no config option to control `USE_MPI_VERSIONS` so you'd have to manually control add it via CFLAGS. @roblatham00 @rsth any info on why this shift is used and who the consumers of `USE_MPI_VERSIONS` might be?

**Comment by roblatham00** [comment]
NACK from me without more justification. 

It's been years since anyone did such a thing but boy it sure is satisfying to show an MPE trace in jumpshot of romio's internal MPI usage.   Perhaps state of the art MPI profiling has improved in a decade?  

this change -- by calling PMPI directly -- will make it impossible to perform such a study.

**Comment by rsth** [comment]
I believe all that is needed is to add the missing MPI_Type_create_struct to mpipr.h as the issue reporter suggests.

**Comment by hzhou** [comment]
Closed in favor of #5326

**Pull request closed without merging**
