### PR TITLE
ch4/ucx: enable shmmod

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Draft PR to see if there is any issue enabling shmmod with ucx.

We always can disable shmmod by configure --with-ch4-shmmods=none or set
MPIR_CVAR_NO_LOCAL=1.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ucx

**Review by raffenet — COMMENTED** [review]
Let's add a note to CHANGES about the new default. Otherwise this is good.

**Comment by raffenet** [comment]
Also the flush issues in finalize do not seem to be resolved.

**Comment by hzhou** [comment]
test:mpich/ch4/ucx

**Comment by hzhou** [comment]
> Also the flush issues in finalize do not seem to be resolved.

`if (!MPIR_CVAR_NO_COLLECTIVE_FINALIZE) { ...}` -- I forgot the `!` and inverted the condition

**Comment by hzhou** [comment]
test:mpich/ch4/ucx

**Review by raffenet — APPROVED** [review]

**Pull request merged**
