### PR TITLE
async: fix async test failures

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

To resolve issues running with async progress thread.

## Expected Impact

Once completed, this PR probably will need to be split into several to get merged.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/custom
netmod: sock
config: async

testlist: coll

**Comment by hzhou** [comment]
test:jenkins/custom
netmod: ch3:sock
config: async

testlist: coll

**Comment by hzhou** [comment]
test:jenkins/custom-2
netmod: ch4:ofi
config: async

**Comment by hzhou** [comment]
test:jenkins/warnings/quick

**Comment by hzhou** [comment]
test:jenkins/custom
netmod: ch3:sock
config: async

**Comment by hzhou** [comment]
test:jenkins/custom
netmod: ch3:sock
config: async

**Comment by hzhou** [comment]
test:jenkins/custom-2
netmod: ch4:ofi
config: async

**Comment by hzhou** [comment]
test:jenkins/custom-2
netmod: ch4:ofi
config: async

**Comment by hzhou** [comment]
test:jenkins/warnings/quick

**Comment by hzhou** [comment]
test:jenkins/custom-2
netmod: ch4:ofi
config: async

**Comment by hzhou** [comment]
test:jenkins/custom
netmod: ch3:sock
config: async

**Comment by hzhou** [comment]
test:jenkins/custom-2
netmod: ch4:ofi
config: async

**Comment by hzhou** [comment]
test:jenkins/custom
netmod: ch3:sock
config: async

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:jenkins/custom-2
netmod: ch4:ofi
config: async

**Comment by hzhou** [comment]
test:jenkins/custom-2
netmod: ch4:ofi
config: async

**Comment by hzhou** [comment]
test:jenkins/custom
netmod: ch3:sock
config: async

**Comment by hzhou** [comment]
test:jenkins/custom-2
netmod: ch4:ofi
config: async

**Comment by hzhou** [comment]
test:jenkins/custom
netmod: ch3:sock
config: async

**Comment by hzhou** [comment]
test:jenkins/custom-2
netmod: ch4:ofi
config: async

**Comment by hzhou** [comment]
test:jenkins/custom
netmod: ch3:sock
config: async

**Comment by hzhou** [comment]
test:jenkins/custom-2
netmod: ch4:ofi
config: async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by wesbland** [comment]
cc: @sagarth

**Comment by hzhou** [comment]
A major effort here is trying to remove all recursive mutex usage.  We can't effectively yield or switch to more granular locks with recursive locking.

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/warnings/quick

**Comment by hzhou** [comment]
test:jenkins/warnings/quick
test:jenkins/async

**Comment by hzhou** [comment]
NOTE: now that we made the mutex a bit fairer in per-vci mode, one particular test become much slower. On `ofi`:
```
- ./pt2pt/pingping 2 -type=MPI_INT -sendcnt=1 -recvcnt=1 -seed=19 -testsize=32 | 1 min 39 sec | 
```
It took 100 sec instead of the 5 sec in the single-threaded version.  This is because the async thread accumulates unexpected extries on the recver side, and it only be matched one at a time each time `MPI_Recv` in the main thread is posted. When the `rx_buffered` list is above 10,000, the libfabric sockets provider goes through the entire list every time we poke progress, and it will take hundreds microseconds even thought most entries are unmatched. With two threads each doing this useless queue iterations, the problem escalates. 

I think the proper solution is on the libfabric side -- it has to deal with huge buffered queue because it can legitimately arise. And there is a lot of room to optimize anyway. For example, it could set a threshold so each progress only check up to  threshold entries, and then double the thresh or reset the thresh depends on whether progress are made. 

Certainly the `sockets` provider is not meant to be performant. So just note here. If we came upon the similar issues on other provider, then we can look into it.

**Comment by hzhou** [comment]
test:jenkins/warnings/quick
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:jenkins/async
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/async

**Comment by hzhou** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/async
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:jenkins/ch4/ucx

**Comment by hzhou** [comment]
test:jenkins/async
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test: authorship

**Comment by hzhou** [comment]
test: authorship

**Comment by hzhou** [comment]
test: authorship

**Comment by hzhou** [comment]
test:mpich/authorship

**Comment by hzhou** [comment]
test:mpich/authorship

**Comment by hzhou** [comment]
test:mpich/authorship

**Comment by hzhou** [comment]
test:mpich/authorship

**Comment by hzhou** [comment]
test:jenkins/async
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:mpich/async
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/async
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/async
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/warnings/quick

**Comment by hzhou** [comment]
test:mpich/warnings/custom

**Comment by hzhou** [comment]
Note: the commits to add `wait_count` is nearly the same as revert of PR #3917. It is needed when the yield in ch4 gets too heavy (which may be necessary to avoid thread starvation). If we replace the lock with a fair lock (e.g. ticket_lcok, mcs_lock), then the yield can be as very light and we may not need the wait count (and save the overhead of maintaining this atomic counter).

**Comment by hzhou** [comment]
Last piece (PR #4472) went in, closing...

**Pull request closed without merging**
