### PR TITLE
Coverity fixes

### PR DESCRIPTION
**Pull request by akhillanger**
This pull request fixes a number of coverity issues.

### CODE REVIEW

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by wesbland** [comment]
Looks like we overlapped a few. I must have forgotten to mark them as mine.

#3223

**Comment by raffenet** [comment]
@wesbland @akhillanger now that we merged #3223, can you guys rebase this and fix the conflicts?

**Comment by akhillanger** [comment]
@raffenet done. Only one commit had conflicts.

**Comment by raffenet** [comment]
@akhillanger I'm fairly certain that the bcast failures in the UCX configuration are a bug. we don't have to investigate them in this PR, but should keep it in mind.

**Comment by akhillanger** [comment]
@raffenet yes, I agree. I am looking at those failures. They are not coming from this PR. I am seeing them otherwise as well. I just started working on those.

**Comment by raffenet** [comment]
I made a minor change to the first commit, so re-running a quick test configuration.
test:jenkins/ch4/ofi

**Pull request merged**
