### PR TITLE
ch4/ofi: improve runtime capability set selection

### PR DESCRIPTION
**Pull request by wesbland**
## Updated Description

If the user does not pick a provider with either compile time capability sets, or at runtime using MPIR_CVAR_OFI_USE_PROVIDER, step down through the runtime capability sets in this order:

1. The capability set for the detected fabric (requires a relatively recent version of libfabric)
2. The "default" capability set with reasonable requirements from libfabric (including FI_TAGGED, FI_RMA, immediate data, etc.)
3. The "minimal" capability set which uses only active messages

This is an improvement over before where there was no "default" capability set and the "minimal" set required more from libfabric, but not as much as the current "default".

This also changes the capability sets of the PSM2 and RXM providers to require immediate data, merges the immediate data capability set with the tagged capability set (now requires all tagged providers to support immediate data), removes capability sets that are not at least as good as the "default" sets (GNI, Verbs without RXM, PSM)

## OLD:

PSM2 and RXM now support immediate data so we can use the `fi_tsenddata` and
`fi_tinjectdata` functions.

This necessitates updating the libfabric submodule to https://github.com/ofiwg/libfabric/commits/38dddd1bebc5ba7e7aeb5d4548d271a8f5485457, which is not a released version of the code. We may want to hold this PR until 1.6.0 GA is completed (or at least 1.6.0rc2).

### CODE REVIEW

**Comment by wesbland** [comment]
I assume that the new version of libfabric will be released by 3.3b3 so I've marked that as the milestone. We can merge sooner if we're comfortable or libfabric is released sooner.

**Comment by wesbland** [comment]
I had to update the libfabric submodule again. There was a critical bug fix in https://github.com/ofiwg/libfabric/pull/3836 and this code was broken without it.

**Comment by wesbland** [comment]
This should be good to go after #3053 is merged.

**Comment by wesbland** [comment]
test:intel:ch4/ofi/psm2/all/all/shm-exclusive,shm-no/debug,default

**Comment by wesbland** [comment]
test:intel:ch4/ofi/psm2/all/all/shm-exclusive,shm-no/debug,default

**Comment by wesbland** [comment]
Arg. The xfail for this Jenkins job seems to have gotten messed up...

**Comment by wesbland** [comment]
test:intel:ch4/ofi/psm2/all/all/shm-exclusive,shm-no/debug,default

**Comment by raffenet** [comment]
Resolved conflicts. Re-testing for sanity.
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
What happens when the system PSM2 library is too old to support this? Will MPICH be able to detect it?

**Comment by hajimefu** [comment]
I don't remember if we reached to a clear conclusion, but we have an issue to discuss that: #2952

**Comment by wesbland** [comment]
Sorry for the long comment, but I needed some rationale to the changes I just added to this PR:

## Problem
For this PR, we wanted to be able to validate whether or not the underlying libfabric could support setting `ENABLE_DATA = ON` or not.
* If we set it to `ON` when the underlying provider doesn’t support it, we won’t be able to start up libfabric with `fi_init` because no valid fabrics will be found.
* My initial thought was to try to detect the version number at configure time and set the value with autoconf. There are a number of problems with this idea:
	* The version number of the overall fabric might not be enough information. For instance, if you have a provider that isn’t in the general libfabric installation (pre-release or private), the version number of the library might not match up with the public version number.
	* The version numbers of the providers don’t seem to change with enough regularity to verify that a feature is supported (e.g. the `sockets` provider didn’t change its version number from libfabric `1.5` to `1.6`.
	* None of the provider version numbers are detectable at configure time anyway because they are generated at runtime (sometimes). There isn’t a reliable way to get this information without building libfabric first (which hasn’t yet been done when configuring CH4).

## Solutions
1. Update the capabilities anyway and say that compile-time capability sets require the latest version of libfabric in order to work.
	* This is probably fine except that it will still mess up runtime capabilities because we use the compile-time capabilities as a starting point (with customization allowed via `CVAR`s) even in the runtime case when you specify a provider via `MPIR_CVAR_OFI_USE_PROVIDER`.
	* If we do this, we probably have to drop the idea of using the provider capability set as a starting point for the runtime build.
2. Leave the immediate capability turned off for a longer time (when do we “drop support” for older versions of libfabric?).

**Comment by wesbland** [comment]
I implemented solution 1 here and I would really like to hear feedback from @raffenet and @ddurnov (at the very least) about this as it was the only real solution I could come up with for the problem.

**Comment by wesbland** [comment]
Ok, I've totally re-worked this PR to implement all of the things we discussed above. For a new description, see the top-level comment.

This should be ready for a new review.

test:jenkins/ch4/most

**Comment by wesbland** [comment]
This needs a change in the ch4-ofi am-only build configuration to add `--enable-legacy-ofi`.

@yfguo - Can you add that? The other jobs can ignore it (assuming you don't have the flag on to cause things to fail with unknown configure flags).

**Comment by yfguo** [comment]
@wesbland Will do.

**Comment by wesbland** [comment]
test:jenkins/ch4/most

**Comment by wesbland** [comment]
Yes. All of the up to date providers where we have a capability set support this. AFAIK, the only ones that don't are regular verbs (without the utility providers, which isn't the intended usage anymore and original PSM. For those, you can either use an older libfabric (since neither has been receiving that many updates anyway).

Looking at the latest version of GNI, it appears that it might actually have support for `FI_REMOTE_CQ_DATA` if `FI_RMA_EVENT` is also enabled, which we currently don't have because we don't need remote completion notification.

**Comment by wesbland** [comment]
We found a problem with the runtime provider selection in this PR. I have a fix incoming that's in internal review. Hope to have it out by the end of the day.

**Comment by wesbland** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
This looks mostly OK to me. Does this have the runtime selection fix included?

**Pull request merged**
