### PR TITLE
test: runtests.pl

### PR DESCRIPTION
**Pull request by hzhou**
A rewrite of `runtests`. 

Previous: PR #3627, PR #3635

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/ch3/mxm

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
* unified config options:
    default set in the script
    loads `runtests.config`
    loads environment variables
    loads command line options
    additional post config check

* be able to load multiple testlists
    eg `-tests='testlist testlist.dtp'`

* accepts include/exclude filters
    `-include-dir='coll pt2pt'`
    `-exclude-dir='pt2pt'`
    `-include-pattern='type=MPI_INT'`
    `-exclude-pattern='type=MPI_(?!INT |DOUBLE )'`

    or envrionment variables:
    `MPITEST_INCLUDE_DIR`
    `MPITEST_EXCLUDE_DIR`
    `MPITEST_INCLUDE_PATTERN`
    `MPITEST_EXCLUDE_PATTERN`

* able to run tests in parallel
    `-j=16`

    or envrionment variable:
    `MPITEST_NUM_JOBS`
    `
TODO:

* Limited macros
    to make certain testlists such as collective cvars more readable

* Basic configure
    detect mpi versions and features, simplify configure and toward more
    usability as standalone mpi testsuite

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
On the idea of running tests in parallel, the next natural idea is to write the test framework in MPI itself and package individual tests as library routines that accepts a `communicator` as an argument.  Certainly, some tests can't be run this way but I suspect a larger portion can.

**Comment by hzhou** [comment]
IO tests need to be able to run in parallel -- cross-referencing #3660

**Comment by hzhou** [comment]
Previously I forgot to set `DTP_NUM_OBJS=5` and was wondering why the tests were running slow :LOL.

Now I fixed that and did a quick tests in `pt2pt/`, on a 16 thread machine, running parallel finishes 168 tests in 8.9 sec, versus original script's 46 seconds -- That was 5 times faster, as it should be //relax

**Comment by pavanbalaji** [comment]
> On the idea of running tests in parallel, the next natural idea is to write the test framework in MPI itself and package individual tests as library routines that accepts a `communicator` as an argument. Certainly, some tests can't be run this way but I suspect a larger portion can.

That'd change the test.  Many of them test on multiple communicators including `MPI_COMM_WORLD`.  This is intentional and is meant to catch algorithmic differences between different communicators.

**Comment by hzhou** [comment]
> That'd change the test. Many of them test on multiple communicators including `MPI_COMM_WORLD`. This is intentional and is meant to catch algorithmic differences between different communicators.

I realized that. That's why it only applies to "a large portion" of the tests.

**Comment by pavanbalaji** [comment]
> I realized that. That's why it only applies to "a large portion" of the tests.

Alright.  It'll be good to have an estimate on how many tests it'd affect.  Also, once you have the parallel execution of jobs part done, I don't think this would add any additional benefit.

**Comment by hzhou** [comment]
> > I realized that. That's why it only applies to "a large portion" of the tests.
> 
> Alright. It'll be good to have an estimate on how many tests it'd affect. Also, once you have the parallel execution of jobs part done, I don't think this would add any additional benefit.

( I made some edits to the previous reply as well).

There is the overhead of process starting/finishing. After parallel execution, those overhead will become "exacerbated" :)

**Comment by pavanbalaji** [comment]
> There is the overhead of process starting/finishing. After parallel execution, those overhead will become "exacerbated" :)

I don't think the overhead is noticeably high, plus it allows the programs to be cleanly separated.

**Comment by hzhou** [comment]
> I don't think the overhead is noticeably high, plus it allows the programs to be cleanly separated.

I agree (however how "noticeable" depends on your intention to notice). 

My idea is to have both framework working, so one can choose to run tests in perl/shell or run tests in mpi. Currently our tests contains large amount of duplication in code often with subtle differences. Having tests in standard library routines can help that. We still can generate (potentially with script) individual test programs by simply calling individual test routines, so both framework can coexist.

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
### Misc. Notes
* `io/tst_fileview 1`: a bunch of "Error at line xx: expect MPI_ERR_IO but got No MPI error"

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
test:jenkins/ch3/most

**Comment by hzhou** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
Some of the features are added to `runtests.in`, such as multiple `testlists`, `path/to/test np ...`. This script has been included in some of the jenkins tests, such as `quick-test`, `custom-test`.

**Pull request closed without merging**
