### PR TITLE
modules: Update json-c

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Fix the internal vasprintf fallback function by properly handing
va_args. Fixes pmodels/mpich#4534.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
I submitted the same fix to json-c upstream in https://github.com/json-c/json-c/pull/703. MPICH doesn't use this functionality, but it fixes a `make check` issue that was tripping up packagers, like the referenced issue.

**Review by hzhou — APPROVED** [review]
I trust this is manually verified. @raffenet

**Comment by raffenet** [comment]
> I trust this is manually verified. @raffenet

Yes, I could reproduce the error reliably in our Jenkins nodes. It took forever until I realized the bad read was happening because of misuse of va_args. It's probably worth adding a `make check` step into the Jenkins release jobs to catch these kinds of issues before cutting a tarball.

**Pull request merged**
