### PR TITLE
maint: Add libtool.m4 patch for macOS Big Sur compatibility

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Closes pmodels/mpich#4913.

## Expected Impact

Fix support for macOS Big Sur and later.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
I will note that Homebrew has already applied this patch to libtool, so the patch will fail to apply in that configuration. See. https://github.com/Homebrew/homebrew-core/pull/56809.

**Comment by raffenet** [comment]
If the patch is already applied this will be visible during `autogen.sh`.
```
Patching libtool.m4 for compatibility macOS Big Sur...Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/mpl/confdb/libtool.m4.rej
failed
```

**Comment by raffenet** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: osx

**Comment by raffenet** [comment]
The custom pipeline build doesn't seem to sufficiently clean up previous builds before starting again. Either `make distclean` should be added, or the entire build area should be wiped out.

**Comment by raffenet** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: osx

**Comment by raffenet** [comment]
Updated pipeline script. Results are good. Large message tests failed because my libfabric hasn't yet been merged into the submodule for `main`. I will open a separate PR for that.

**Comment by raffenet** [comment]
@yfguo please review when you have a chance.

**Review by hzhou — APPROVED** [review]
Don't love these libtool patches, but as long as it works...

**Pull request merged**
