### PR TITLE
ch4: remove am_isendv API

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

The ch4 API `MPIDI_NM_am_isendv` and `MPIDI_SHM_am_isendv` add complexity but brings little benefit. It is only used when we need to send *short* flattened datatype along with the header. For the best, we can save a short memcpy. In reality, that is unlikely to have any performance impact. In fact, all our lower layers do the memcpy anyway. 

The lower layer is likely to optimize `am_isend`, potentially with header combination, or GPU IPC, or RDMA. The `am_isendv` will either force the lower layer to duplicate the optimization or, more likely, combine the iov and call `am_isend` anyway. It also brings the possibility that `am_isendv` be less optimized than `am_isend`. Thus, having the `am_isendv` interface brings more harm than its benefit.

[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
> The `am_isend_reply` API should also be removed since it has the same interface as `am_isend`. However, the current `ucx` optimizes only `am_isend_reply` based on the _assumption_ that a large data payload is always sent in a RNDV fashion, thus only occurs in the "reply" message. This is quite bad since the assumptions break the abstractions.

The intention of the "reply" APIs was that they are safe to be called from message handers. In the past, UCX send kicked the progress engine and caused message to be processed out of order, so we had to only enqueue messages to be sent in reply. However UCX semantics changed, and we were able to essentially merge those behaviors. I can't remember if the libfabric integration had a similar issue. To be clear, those APIs were not about optimization.

**Comment by hzhou** [comment]
> To be clear, those APIs were not about optimization.

I see. We can leave the "reply" API, maybe with a rationale comment. I'll update.

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Review by raffenet — APPROVED** [review]

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Pull request merged**
