### PR TITLE
posix: Fix failures/bugs exposed by DT pools in release_gather based intra-node collectives

### PR DESCRIPTION
**Pull request by jain-surabhi-23**
## Pull Request Description
This PR fixes the build errors that were introduced by #3622. It also fixes the bugs in the release_gather framework which were exposed by the recently added DT pool tests.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [ ] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by jain-surabhi-23** [comment]
test:jenkins/ch4/most

**Comment by jain-surabhi-23** [comment]
@yfguo Can you please review this PR? Since you have reviewed this code originally.

**Comment by jain-surabhi-23** [comment]
Also remember to not merge the HACK commit.

**Comment by yfguo** [comment]
I will take care of this.

**Comment by yfguo** [comment]
test:jenkins/ch4/most

**Comment by jain-surabhi-23** [comment]
@yfguo Can you please prioritize this PR? It is creating more confusions at our end, since we run shared memory collectives by default.

**Pull request merged**
