### PR TITLE
Remove old ch3 netmods

### PR DESCRIPTION
**Pull request by pavanbalaji**
ch4 provides alternatives for many of these netmods, while some are simply unmaintained.

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
@janjust @masamichitakagi

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp

**Comment by pavanbalaji** [comment]
Tests look good.  This is ready to merge.  The conflicts are fairly trivial and easy to fix.  I'll force push a fix, but I'll not rerun the tests again.

Just waiting for your signoff, @raffenet.

**Pull request merged**
