### PR TITLE
session: Refactoring, introduce mpir_session.h, session_impl.c and session_util.c

### PR DESCRIPTION
**Pull request by sonjahapp**
This PR:
- Adds `MPIR_Session_create` and `MPIR_Session_release` functions to encapsulate the object creation and release. In addition, it provides macros to add and release references of a session similar to other MPI objects. This is a preparatory step to introduce reference counting for sessions.
- Introduces new files `src/include/mpir_session.h`, `src/mpi/session/session_{impl, util}.c`
- Introduces a separate test folder for session tests

## Author Checklist
* [X] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [X] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [X] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Review by hzhou — COMMENTED** [review]
This looks good.

I think it is time to add `src/include/mpir_session.h` and `src/mpi/session/session_util.c` (or `session_impl.c`.

**Comment by sonjahapp** [comment]
> I think it is time to add `src/include/mpir_session.h` and `src/mpi/session/session_util.c` (or `session_impl.c`).

Would you add these files as part of this PR or rather as a separate PR?

**Comment by sonjahapp** [comment]
As discussed on the MPICH devel telco on 6th April '23, I've extended the scope of this PR quite a bit to introduce separate header and source files for sessions. In addition, it is useful to give sessions their own test directory and split session tests up from the `init` directory.

Comments are welcome.

**Comment by hzhou** [comment]
test:mpich/warnings
test:mpich/ch3/most
test:mpich/ch4/most

**Pull request merged**
