### PR TITLE
ch4: fix missing patch on recvq

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

The recvq are moved to per vci structure but we neglected a patch for
HAVE_DEBUGGER_SUPPORT path.

[skip warnings]

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by sagarth** [comment]
@hzhou It seems, we still have another related problem:
```
src/mpid/ch4/src/ch4r_recvq.c:21:5: warning: initialization of ‘MPIR_Request ** const’ {aka ‘struct MPIR_Request ** const’} from incompatible pointer type ‘MPIDI_Devreq_t **’ {aka ‘struct MPIDI_Devreq_t **’} [-Wincompatible-pointer-types]
   21 |     &MPIDI_global.per_vci[0].posted_list;
      |     ^
src/mpid/ch4/src/ch4r_recvq.c:23:5: warning: initialization of ‘MPIR_Request ** const’ {aka ‘struct MPIR_Request ** const’} from incompatible pointer type ‘MPIDI_Devreq_t **’ {aka ‘struct MPIDI_Devreq_t **’} [-Wincompatible-pointer-types]
   23 |     &MPIDI_global.per_vci[0].unexp_list;

```

**Comment by raffenet** [comment]
> @hzhou It seems, we still have another related problem:
> 
> ```
> src/mpid/ch4/src/ch4r_recvq.c:21:5: warning: initialization of ‘MPIR_Request ** const’ {aka ‘struct MPIR_Request ** const’} from incompatible pointer type ‘MPIDI_Devreq_t **’ {aka ‘struct MPIDI_Devreq_t **’} [-Wincompatible-pointer-types]
>    21 |     &MPIDI_global.per_vci[0].posted_list;
>       |     ^
> src/mpid/ch4/src/ch4r_recvq.c:23:5: warning: initialization of ‘MPIR_Request ** const’ {aka ‘struct MPIR_Request ** const’} from incompatible pointer type ‘MPIDI_Devreq_t **’ {aka ‘struct MPIDI_Devreq_t **’} [-Wincompatible-pointer-types]
>    23 |     &MPIDI_global.per_vci[0].unexp_list;
> ```

That part is my fault. We should probably just move the next/prev pointers up to MPIR_Request level. The issue is that UTlist macros used in ch4 can't handle the pointers being defined in a sub-struct. But both ch3 and ch4 have list pointers in the request, so its not imposing anything, I don't think.

**Comment by hzhou** [comment]
> 
> 
> > @hzhou It seems, we still have another related problem:
> > ```
> > src/mpid/ch4/src/ch4r_recvq.c:21:5: warning: initialization of ‘MPIR_Request ** const’ {aka ‘struct MPIR_Request ** const’} from incompatible pointer type ‘MPIDI_Devreq_t **’ {aka ‘struct MPIDI_Devreq_t **’} [-Wincompatible-pointer-types]
> >    21 |     &MPIDI_global.per_vci[0].posted_list;
> >       |     ^
> > src/mpid/ch4/src/ch4r_recvq.c:23:5: warning: initialization of ‘MPIR_Request ** const’ {aka ‘struct MPIR_Request ** const’} from incompatible pointer type ‘MPIDI_Devreq_t **’ {aka ‘struct MPIDI_Devreq_t **’} [-Wincompatible-pointer-types]
> >    23 |     &MPIDI_global.per_vci[0].unexp_list;
> > ```
> 
> That part is my fault. We should probably just move the next/prev pointers up to MPIR_Request level. The issue is that UTlist macros used in ch4 can't handle the pointers being defined in a sub-struct. But both ch3 and ch4 have list pointers in the request, so its not imposing anything, I don't think.

Why don't we type `MPID_Recvq_posted_head_ptr` and `MPID_Recvq_unexpected_head_ptr` as `void **const`? The debugger is not supposed to access our internal structure anyway, so I think a void pointer makes more sense here.

**Comment by hzhou** [comment]
I am not sure about the intention of the usage. If we'd like to enable debugger to peek into message queue list, then we may need to move the next pointer back into `MPIR_Request`. Is there an official standard or documentation on the assumptions and requirements?

**Comment by raffenet** [comment]
> I am not sure about the intention of the usage. If we'd like to enable debugger to peek into message queue list, then we may need to move the next pointer back into `MPIR_Request`. Is there an official standard or documentation on the assumptions and requirements?

The message queue interface is documented here: https://www.mpi-forum.org/docs/msgq.5.pdf. Tools don't access those pointers directly. Our debugger library (libtvmpich) does and exposes the information via the API.

**Comment by raffenet** [comment]
I'll submit a PR to move the list pointers up and squash the warning.

**Comment by raffenet** [comment]
Included in #5560.

**Pull request closed without merging**
