### PR TITLE
Fixes for 3.3.2 release

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Cherry-picked fixes from master for inclusion in a 3.3.2 bug-fix release.

## Expected Impact

Fix known bugs and compiler warnings.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
@hzhou this does not include the sockaddr changes, as the ch3 portions did not apply cleanly to the 3.3.x branch. We also need to include the runtests lockfile changes in order to test this thoroughly in Jenkins, right?

**Comment by hzhou** [comment]
> @hzhou this does not include the sockaddr changes, as the ch3 portions did not apply cleanly to the 3.3.x branch. We also need to include the runtests lockfile changes in order to test this thoroughly in Jenkins, right?

Good that I saved the original branch, which applies cleanly. You can pick them from my branch `hzhou:1910_release_3.3.2` https://github.com/hzhou/mpich/tree/1910_release_3.3.2

**Comment by hzhou** [comment]
> We also need to include the runtests lockfile changes in order to test this thoroughly in Jenkins, right?

The worst could happen is some tests may fail due to out-of memory.

**Comment by raffenet** [comment]
OK, let me pick up your sockaddr changes and then I'll run the tests and see how it goes.

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most
test:mpich/warnings

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most

**Comment by raffenet** [comment]
@hzhou any idea about the warnings test failure for this PR? Not obvious to me from the console output.

**Comment by hzhou** [comment]
> @hzhou any idea about the warnings test failure for this PR? Not obvious to me from the console output.

The warnings script runs a customized autogen, so I guess the `extracterrmsg` is inconsistent to this branch due to some missing commits. Let's ignore warnings test for this PR.

**Comment by hzhou** [comment]
The previous warnings script failure is due to missing cvars patch which defines extra cvar error messages. Also it is missing the `FCNAME` patches. The script generated `mpir_cvars.c` does not define `FCNAME`. I updated the script to make it backward compatible. Re-run tests:

test:mpich/warnings

**Comment by raffenet** [comment]
ch3/tcp is now warning clean. ch3/sock is diverged a bit from master, making it harder to integrate existing warning cleanups. I think we can ignore them. Re-running MPICH tests.
test:jenkins/ch3/all
test:jenkins/ch4/most

**Comment by raffenet** [comment]
Test results look as expected. I will merge this and work on remaining items.

**Pull request merged**
