### PR TITLE
coll: gentran optimizations

### PR DESCRIPTION
**Pull request by zhenggb72**
## Pull Request Description

Many optimizations to GenTran, including:

1. remove unnecessary incoming dependence vertex list 
2. using utarray in a way to avoid internal malloc

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Review by hzhou — APPROVED** [review]
Looks okay. Just make sure to clear the tests.

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by zhenggb72** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by wesbland** [comment]
Looks like the tests all passed. @zhenggb72 can you rebase onto the latest `main` branch?

**Comment by zhenggb72** [comment]
> 
> 
> Looks like the tests all passed. @zhenggb72 can you rebase onto the latest `main` branch?

done

**Pull request merged**
