### PR TITLE
ch4/ofi: Use general iovec density CVAR

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

This CVAR already existed and is based on the threshold used in ch3.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ofi

**Comment by raffenet** [comment]
> I would have preferred this goes with the same PR that introduces `MPIR_CVAR_CH4_IOV_DENSITY_MIN`.

`MPIR_CVAR_CH4_IOV_DENSITY_MIN` existed before your CVAR was added.

**Comment by hzhou** [comment]
> `MPIR_CVAR_CH4_IOV_DENSITY_MIN` existed before your CVAR was added.

Added by https://github.com/pmodels/mpich/pull/4455, newly merged. Sorry for the noise 😄

**Comment by raffenet** [comment]
Re-based on master.

**Comment by raffenet** [comment]
I was not aware of that. Now warning test fails...
test:mpich/warnings

**Pull request merged**
