### PR TITLE
coll: nbh_allgather tsp linear

### PR DESCRIPTION
**Pull request by jain-surabhi-23**
Implement neighborhood Allgather using transport (TSP) API

This is the 3rd PR in the series of the PRs for neighborhood collectives - #3371 (tests), #3372 (alltoallw), #3375 (allgather), #3376 (allgatherv), #3377 (alltoall), #3378 (alltoallv).

### CODE REVIEW

**Comment by hzhou** [comment]
I assume "nhb" refers to "neighborhood" which should be "nbh"?

The diff seems to show 3 combined PRs, probably due to unclean rebase. It is not necessary to clean it up for review, but it would be nice to comment and clarify -- @jain-surabhi-23

**Comment by jain-surabhi-23** [comment]
"nhb" was taken from the **n**eig**hb**orhood.
As the top comment in the PR says, this is the 3rd PR in the series of PRs. Ideally second PR should be merged before merging this. The first PR was already merged.

**Comment by hzhou** [comment]
@jain-surabhi-23 That is cool. Could you add a comment listing the 5 PRs (by title or collective function names) and put that comment to each of these PRs?

**Comment by jain-surabhi-23** [comment]
@hzhou I am not sure what you are asking for. Because that comment is already there on all the PRs, clearly stating all the PRs and the position of that PR in the queue.

**Comment by hzhou** [comment]
> @hzhou I am not sure what you are asking for. Because that comment is already there on all the PRs, clearly stating all the PRs and the position of that PR in the queue.

I just like to see the list by title rather than click through them. Never mind, I'll just edit your comments adding the titles.

**Comment by jain-surabhi-23** [comment]
@hzhou Oh. I see it now. Thanks for doing it !

**Comment by jain-surabhi-23** [comment]
This series of PRs have been consolidated into #3593

**Pull request closed without merging**
