### PR TITLE
ch4: refactor dynamic process

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Miscellaneous simplification and cleanup for ch4-layer process management. 

* All dynamic processes are non-local because of missing shared memory initialization for them. Thus we don't need to manage node_map beyond `MPIR_Process.node_map`.
* AV table manager (`MPIDI_global.avt_mgr`) designs are simplified.
* Shmmod has nothing to do with process management and such shm APIs (all empty stubs) are removed.
* `lupid` is renamed to `gpid` and comments added to explain the terms.

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: spawn

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Review by yfguo — APPROVED** [review]
LGTM

**Pull request merged**
