### PR TITLE
Shared Memory Branches

### PR DESCRIPTION
**Pull request by wesbland**
Adds appropriate branches for shared memory in the CH4 layer so branching doesn't always blindly go to the netmod, even when sending to an intra-node process.

This PR also includes some prereqs that are necessary for the branching code.

Without an additional patch, this will cause all of the RMA tests to fail with the normal code paths when communicating with a local process. With active messages being forced, the collectives will also fail. This is due to all of the assertions in the existing POSIX AM code. That should be fixed by the #2526 PR eventually, but we might want to add a stopgap to have the shared memory code call back to the netmod in the meantime.

### CODE REVIEW

**Comment by wesbland** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by wesbland** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by wesbland** [comment]
There's still a bunch of netmod direct calls in `ch4_win.h`, but since they're not calls that generally involve a particular rank, it's a bit tricky to decide whether to call the netmod or shared memory. We can't do both. For now, I'll leave those as just netmod calls.

**Comment by wesbland** [comment]
test:jenkins/ch4/most

**Comment by wesbland** [comment]
Ok. Tests are passing now. @raffenet , you can take a look and/or bring in the Cray folks. I don't think I can tag Krishna or Steve on here.

**Comment by raffenet** [comment]
This seems pretty uncontroversial to me at first look. I attempted to add Krishna to pmodels the same we have the Intel collab group. In the meantime, tagging him directly: @kkandalla

**Comment by kkandalla** [comment]
Ken, Wes,

Yep. This looks like a good first step to me too.


Thanks,
Krishna Kandalla, Ph.D.
Direct: +1-651-967-9554

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Pull request merged**
