### PR TITLE
request: Add list pointers to MPIR_Request

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Add list pointers to top-level MPIR_Request and use them in place of ch3 and ch4 definitions.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch3/most

**Comment by raffenet** [comment]
We could drop the ch3 patch from this PR if we decide its more trouble than its worth to tinker over there. I don't feel strongly one way or the other.

Though it did raise this question for me...should we make the request lists in ch4 singly linked?

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
config: debuginfo

**Review by hzhou — APPROVED** [review]
LGTM.

**Pull request merged**
