### PR TITLE
Use "allcomm" for communicator-type independent algorithms

### PR DESCRIPTION
**Pull request by AlexeyMalkhanov**
Introducing `allcomm` keyword into names for communicator-type independent algorithms

### CODE REVIEW

**Comment by pavanbalaji** [comment]
Signed off.  Testing once more.

test:jenkins/ch3/all
test:jenkins/ch4/all

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
@AlexeyMalkhanov tests are failing.

**Comment by AlexeyMalkhanov** [comment]
@pavanbalaji @raffenet I've fixed the issue and built it with --enable-strict option for configure. Could you please relaunch the tests?

**Comment by pavanbalaji** [comment]
Tests look fine.  I've updated the commit message and signed off.

**Pull request merged**
