### PR TITLE
CH4 Warning Fixes

### PR DESCRIPTION
**Pull request by wesbland**
Cleanup minor warnings in POSIX and CH4 general code

test:jenkins/ch4/ofi

### CODE REVIEW

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by hajimefu** [comment]
Oh, I had a same patch for `mpi_errno` initialization in #3116.

**Comment by wesbland** [comment]
Ah. I knew I'd seen that somewhere. I just couldn't remember where it was. Sorry. 🙁

**Comment by hajimefu** [comment]
No worries.

**Comment by hajimefu** [comment]
In #3116 I also have a patch for OFI netmod for similar `mpi_errno` initialization.

**Pull request merged**
