### PR TITLE
Cherry-picked fixes for 3.2.x

### PR DESCRIPTION
**Pull request by raffenet**
More to come. Just wanted to save my work after a massive conflict resolution.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
TCP tests look OK. Testing all ch3 configs now before merge.
test:jenkins/ch3/all

**Comment by raffenet** [comment]
test:jenkins/ch3/all

**Comment by raffenet** [comment]
test:jenkins/ch3/armci-mpi

**Comment by pavanbalaji** [comment]
Apart from the known mac os failure, hcoll seems to be failing.  @raffenet do we need to cherry-pick the hcoll patches that we skipped?

**Comment by raffenet** [comment]
Investigating now. mpich/master currently behaves the same way, so I don't think those patches address this particular issue.

**Comment by raffenet** [comment]
It is related to collectives called using derived datatypes. The integration code in MPICH is supposed to detect this and fallback to MPICH collectives, but it is hanging in practice. Need to dig a little more to find out why.

**Comment by raffenet** [comment]
@pavanbalaji I managed to port the concurrent non-contig recv patch into the series. So this includes everything but the hcoll patches we skipped, and like I mentioned I don't think they will solve the current failures we are seeing. Maybe we should merge to kickoff the more thorough tests?

**Comment by pavanbalaji** [comment]
That patch has nothing to do with hcoll, right?  Why are only the hcoll tests failing?

**Comment by raffenet** [comment]
Because hcoll support is broken both in master and 3.2.x branch, as far as I can tell.

**Comment by pavanbalaji** [comment]
Why is that patch that you just integrated relevant then?

**Comment by pavanbalaji** [comment]
In any case, if hcoll issue is known, then we can merge to `master`, right?

**Comment by raffenet** [comment]
Right, it's not relevant to the hcoll issue. I shouldn't have mentioned it in that context. IMO, yes, this is OK to merge to master as it is.

**Comment by pavanbalaji** [comment]
OK.  I think we both meant the `3.2.x` branch when we said `master`.  Can you go ahead and merge?

**Comment by raffenet** [comment]
Will do.

**Pull request merged**
