### PR TITLE
Implement intra-node barrier using release_gather 

### PR DESCRIPTION
**Pull request by jain-surabhi-23**
## Pull Request Description

- Implement release_gather algorithm for posix_barrier
- Add barrier into CH4 level json file. For some reason it was missing

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by jain-surabhi-23** [comment]
@yfguo Can you please review this? Since you have reviewed other release_gather framework PRs in the past

**Comment by yfguo** [comment]
will do

**Comment by jain-surabhi-23** [comment]
@yfguo I have rebased on top of latest master. Can you please start the tests?

**Comment by jain-surabhi-23** [comment]
test:jenkins/ch4/most

**Comment by jain-surabhi-23** [comment]
test:jenkins/ch4/most

**Comment by jain-surabhi-23** [comment]
Not sure why `ucx` build will fail. Testing again
test:jenkins/ch4/ucx

**Pull request merged**
