### PR TITLE
xfail: ofi/direct-nm /rma/lockall_dt_flush

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
refer to issue #3886

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Passes tests (included warning check)
* [x] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [x] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
@raffenet Could you review it?

**Comment by raffenet** [comment]
Several more lockall_dt tests are close to the timeout limit, not just the flush version. You can see the execution time here for successful tests, as well, and see that many are 2m40s+.

**Comment by hzhou** [comment]
Fixed by #3965.

**Pull request closed without merging**
