### PR TITLE
Update CHANGES for ch4 netmod configure

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Configure will now try to select a preferred ch4 netmod, and only
prompt the user if it cannot determine one.

## Expected Impact

Better convey configure behavior to the user.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by wesbland** [comment]
It might be helpful to say what that check entails.

**Comment by raffenet** [comment]
> It might be helpful to say what that check entails.

True, will post a revised version.

**Comment by raffenet** [comment]
@wesbland please check the new text if you have a chance.

**Review by hzhou — APPROVED** [review]
FWIW, it looks good to me.

**Comment by raffenet** [comment]
> FWIW, it looks good to me.

Thanks. I'll give Wes an hour or so in case he is online today. This and the version update should be the last changes before 3.4 GA.

**Review by wesbland — APPROVED** [review]

**Pull request merged**
