### PR TITLE
mpl/gpu: Update MPL_gpu_query_pointer_attr

### PR DESCRIPTION
**Pull request by BKitor**
Handle hipPointerGetAttributes changes introduced in ROCm 6

## Pull Request Description
ROCm6 changed how `hipPointerGetAttributes` works. #6860 and in https://github.com/pmodels/mpich/commit/8e58a6874438e86862350004117e3047b48962c5 try to address this issue, but fall short.

In ROCm6, `hipPointerGetAttributes` returns `hipMemoryTypeUnregistered` for unregistered memory, instead of an error code. 
`hipMemoryTypeManaged` is also introduced for managed memory. 

This patch should be able to compile for the old and new versions of hipPointerGetAttributes.

### CODE REVIEW

**Comment by hzhou** [comment]
Thanks @BKitor for the fix. I was wondering why ROCm would rename a field. The new logic does make sense.

Could you sign the contribution agreement so we can merge your contribution? -- http://www.mpich.org/documentation/contributor-docs/

**Comment by BKitor** [comment]
Individual CLA has been signed and sent to ***@***.***

**Comment by hzhou** [comment]
test:mpich/authorship
test:mpich/warnings

**Comment by hzhou** [comment]
test:mpich/authorships

**Comment by hzhou** [comment]
test:mpich/warnings

**Review by raffenet — APPROVED** [review]

**Comment by hzhou** [comment]
Thanks @BKitor for the fix!

**Comment by raffenet** [comment]
We need to do this for Yaksa, too.

**Pull request merged**
