### PR TITLE
Ucx am simpler

### PR DESCRIPTION
**Pull request by LenaO**

### CODE REVIEW

**Comment by LenaO** [comment]
test:jenkins/ch4/ucx

**Comment by LenaO** [comment]
test:jenkins/ch4/ucx

**Comment by LenaO** [comment]
test:jenkins/ch4/ucx
Add more functionality for put

**Comment by LenaO** [comment]
Updated the branch after rebasing
 test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
@LenaO I've cleaned up and included 3/5 patches from this PR (the last few are in #2452). I'd like to drop the large AM modifications and wait for the real UCP active message API to make a clear decision on how to handle those. If you object, re-open and we can discuss.

**Pull request closed without merging**
