### PR TITLE
binding: add MPIX_Query_ze_support

### PR DESCRIPTION
**Pull request by zhenggb72**
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
Looks ok. @zhenggb72 just post a comment to confirm that you have manually tested it, and I'll approve the review.

**Comment by zhenggb72** [comment]
Yes, it was tested manually.

**Review by hzhou — APPROVED** [review]
LGTM.

**Comment by hzhou** [comment]
test:mpich/whitespace

**Comment by hzhou** [comment]
test:mpich/spellcheck

**Pull request merged**
