### PR TITLE
Remove MPL_ namespace from utlist library

### PR DESCRIPTION
**Pull request by akhillanger**
There is an API change in the latest utlist library version that may also have performance impact, so I didn't update this library from the source.

This PR is to be applied after PR#2808 that updates the uthash library.

### CODE REVIEW

**Comment by akhillanger** [comment]
test:jenkins/ch4/all
test:jenkins/ch3/all

**Comment by wesbland** [comment]
@akhillanger - Looks like the CH3 builds didn't compile.

**Comment by akhillanger** [comment]
test:jenkins/ch3/all

**Comment by pavanbalaji** [comment]
Looks good to me.  Once the builds complete fine, it should be OK to merge.

**Comment by pavanbalaji** [comment]
Ugh.  How did I signoff on this patch?  This has random white space changes in it.  Gross.

**Comment by wesbland** [comment]
These were just renames. I don't think we usually fix whitespace when we do that.

**Comment by pavanbalaji** [comment]
I’m not referring to the renames.  There are spurious white space changes in files that weren’t touched.  I should have done a better job reviewing the patches.  My fault.

**Comment by wesbland** [comment]
Oh well. The problem will be solved when we run the magic script and can automate it.

**Comment by pavanbalaji** [comment]
Plus, if I were not so sleep deprived, I would have noticed the namespace removal patch has been squashed with the utlist upgrade patch, which is also gross.  They are two different things and should be separate patches.  Hind sight 20-20.

**Comment by wesbland** [comment]
Oh, I see the problem now. Yeah, I agree. Oh well.

**Pull request merged**
