### PR TITLE
Hierarchy support in hydra process manager

### PR DESCRIPTION
**Pull request by vkolodie**
Hierarchy support includes options parsing, tree-based application process startup, hydra, and pmi commands propagation.
Added new "-branch-count <num>" Hydra's option to restrict the number of child management processes launched by the Hydra PM, or by each pmi_proxy management process.

Tree-based startup currently is not supported for spawned processes.

### CODE REVIEW

**Comment by ddurnov** [comment]
test:jenkins/ch4/ofi
test:jenkins/ch3/ofi

**Comment by ddurnov** [comment]
test:jenkins/ch4/ofi
test:jenkins/ch3/ofi

**Comment by raffenet** [comment]
Not sure why Jenkins isn't paying attention to Dmitry's comments. I'll kick off the tests for now...
test:jenkins/ch4/ofi
test:jenkins/ch3/ofi

**Comment by wesbland** [comment]
Is this all combined with https://github.com/pmodels/mpich/pull/2573?

**Comment by wesbland** [comment]
@vkolodie - THere are now merge conflicts on this patch. Is this PR still necessary or has @pavanbalaji's patch superseded this one?

**Comment by vkolodie** [comment]
@wesbland this PR is unnecessary since @pavanbalaji's patch superseded it

**Pull request closed without merging**
