### PR TITLE
coll: allreduce recursive exchange without data copy [WIP]

### PR DESCRIPTION
**Pull request by rkalidas**

### CODE REVIEW

**Comment by rkalidas** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
@zhenggb72 Could you give a status update on this PR?

**Comment by zhenggb72** [comment]
This one is more than a year old. I think it is obsolete, we will upstream the latest version.

**Comment by hzhou** [comment]
> This one is more than a year old. I think it is obsolete, we will upstream the latest version.

Sounds good.

**Pull request closed without merging**
