### PR TITLE
misc: use MPIR_Datatype_is_contig over MPIR_Datatype_iscontig

### PR DESCRIPTION
**Pull request by abrooks98**
## Pull Request Description

Use `MPIR_Datatype_is_contig` over the former `MPIR_Datatype_iscontig` (which was removed in https://github.com/pmodels/mpich/pull/6390). This should resolve build failures when GPU support is enabled.

Reference https://github.com/pmodels/mpich/pull/6390/commits/04c6f0d0faf0afdf23d2568ba0b6d95a7fe6f388
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by abrooks98** [comment]
test:mpich/ch4/ofi
test:mpich/ch4/ofi/gpu

**Comment by abrooks98** [comment]
test:mpich/ch4/gpu/most

**Review by raffenet — APPROVED** [review]
Not sure why the GPU tests aren't triggering, but this looks good to me.

**Comment by raffenet** [comment]
test:mpich/ch4/gpu/ofi

**Comment by raffenet** [comment]
This just caught our Jenkins at a bad time. Re-testing...
test:mpich/ch4/ofi
test:mpich/ch4/gpu/ofi

**Pull request merged**
