### PR TITLE
ch4: move mpidig sources and unify mpidig prefix

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

The generic implementation code are split between ch4r, mpidig, and
mpdiig_am prefix. This makes navigating code difficult. This patch moves
all generic code back into src/mpid/ch4/src folder and unify the prefix
to use mpidig_.

[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Review by raffenet — COMMENTED** [review]
This is bound to be a little painful for downstream folks, but hopefully they stay mostly out of the generic code. Ultimately this makes the code better. 1 minor request, can you update these comments ch4r->mpidig?
```
raffenet@mcswl034:src/ (2108_am_move) $ git grep -i -w ch4r
ch4_request.h:   The net/shm mods can upcall to CH4R to create a request, or
ch4_request.h:   the ch4r/netmod/shmmod fields of the request.
```
Also I'm not totally sure what to do with the ch4r_proc.h|c files that remain. Those functions have a prefix indicating they are "utilities" (MPIDIU), but in practice I think they act much more like generic code. The idea was to let netmods handle locality info if they wanted, or call the fallback/generic implementation.

**Comment by hzhou** [comment]
> Also I'm not totally sure what to do with the ch4r_proc.h|c files that remain. Those functions have a prefix indicating they are "utilities" (MPIDIU), but in practice I think they act much more like generic code. The idea was to let netmods handle locality info if they wanted, or call the fallback/generic implementation.

All the proc implementations have been moved to ch4 layer now, ref https://github.com/pmodels/mpich/pull/5447 and https://github.com/pmodels/mpich/pull/5465. Ch4 layer need manage the locality before dispatch into the netmod. Unlike other fallback routines, the locality management has to be integral or it's a mess to manage potential conflicts. Thus, "fallback" does not really apply. What we could use is a macro or CVAR that switches from one set of proc management to another set. Anyway, we don't need to worry about multiple proc implementations until the need arises.

We should discuss what better prefix to use. I am tempted to just move them to `MPIDI_` and `ch4_` . If we stick to `MPIDIU_`, we probably will need another set of macro that maps `MPIDI_xxx` to `MPIDIU_xxx`. The latter will allow vendors to switch to their own locality system.

**Comment by hzhou** [comment]
> This is bound to be a little painful for downstream folks, but hopefully, they stay mostly out of the generic code. Ultimately this makes the code better.

I agree. Hopefully, the ch4-layer design and code structure are finally stabilizing. If we can get the 4.0 branch a really stable basis, I think the vendors will benefit for the long term.

> 1 minor request, can you update these comments ch4r->mpidig?

done.

**Comment by raffenet** [comment]
> We should discuss what better prefix to use. I am tempted to just move them to `MPIDI_` and `ch4_` . If we stick to `MPIDIU_`, we probably will need another set of macro that maps `MPIDI_xxx` to `MPIDIU_xxx`. The latter will allow vendors to switch to their own locality system.

I think `MPIDI_` is probably right for now.

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
@raffenet `ch4r_proc.[hc]` are renamed to `ch4_proc.[hc]`. We can change the `MPIDIU_` prefix separately.

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Review by raffenet — APPROVED** [review]

**Pull request merged**
