### PR TITLE
ch4: remove workq

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
The workq in ch4 has not been in use for a while and there is no plan to revive it. Thus we are removing it.

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/most

test:mpich/custom --enable-ch4-mt=runtime
netmod: ch4:ofi
config: vci

**Comment by sagarth** [comment]
I'm running our internal Jenkins testing with these patches.

**Comment by sagarth** [comment]
> I'm running our internal Jenkins testing with these patches.

These tests passed.

**Comment by hzhou** [comment]
@sagarth Would you review it as well?

**Comment by sagarth** [comment]
> @sagarth Would you review it as well?

@hzhou The PR looked fine to me when I reviewed it earlier. Currently, I'm checking with the team to see if anyone is using the `izem` submodule.

**Comment by sagarth** [comment]
> > @sagarth Would you review it as well?
> 
> @hzhou The PR looked fine to me when I reviewed it earlier. Currently, I'm checking with the team to see if anyone is using the `izem` submodule.

We're cleared here.

**Pull request merged**
