### PR TITLE
config: do not reset flags config subsystems

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Subsystems include romio and hydra, and we need at least the strict
CFLAGS to be applied. This commit removes the reset. We can reset
particular flags or add customization once we understand what is needed.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
The warnings check works for hydra now. Let's see how it works for general testing --

test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by raffenet** [comment]
So we just added this in 6cff62e0ab3bcc8eca8432c0c78c098accd83ba9 and I thought it was a good change at the time. Hydra uses `PAC_ARG_STRICT`, so I'm a little surprised that it isn't getting the same flags as MPICH even with the reset. ROMIO doesn't use `PAC_ARG_STRICT`, so it should probably be added there regardless.

**Comment by hzhou** [comment]
Right, we need revisit the rationale in https://github.com/pmodels/mpich/commit/6cff62e0ab3bcc8eca8432c0c78c098accd83ba9. The commit message was:

> This avoids pass CPPFLAGS with embedded hwloc path to hydra. Otherwise,
on systems with outdated external hwloc, it may result in hydra to be
build with embedded headers but linked to external hwloc.

**Comment by hzhou** [comment]
Reverted https://github.com/pmodels/mpich/commit/6cff62e0ab3bcc8eca8432c0c78c098accd83ba9 and added new fix to prevent hwloc inconsistency.

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
The test failure -- `ch3-centos32-io/async` -- was unrelated. This PR is ready for review.

**Comment by hzhou** [comment]
test:mpich/ch3/sock

**Comment by hzhou** [comment]
Added a commit to remove PAC_CC_STRICT from hydra. 

test:mpich/ch3/tcp

**Review by raffenet — APPROVED** [review]

**Pull request merged**
