### PR TITLE
maint: fix libtool patch for IBM XL compilers

### PR DESCRIPTION
**Pull request by yfguo**
## Pull Request Description

Previous patches no longer correctly applies to the libtool 2.4.7

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by yfguo** [comment]
Need to test on Summit. To see if this is relevant.

**Comment by yfguo** [comment]
test:mpich/ch4/ofi

**Review by hzhou — APPROVED** [review]
LGTM

**Comment by raffenet** [comment]
Is the patch still needed with 2.4.7? On my laptop with libtool 2.4.7 installed from Homebrew:
```
Patching src/pmi/confdb/libtool.m4 with ibm-xlf.patch...Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/pmi/confdb/libtool.m4.rej
```

**Comment by yfguo** [comment]
> Is the patch still needed with 2.4.7? On my laptop with libtool 2.4.7 installed from Homebrew:
> 
> ```
> Patching src/pmi/confdb/libtool.m4 with ibm-xlf.patch...Reversed (or previously applied) patch detected!  Skipping patch.
> 1 out of 1 hunk ignored -- saving rejects to file src/pmi/confdb/libtool.m4.rej
> ```

I double checked, the patches are not needed on libtool 2.4.7.  I guess I will just add the `libtool.m4.rej` and `libtool.m4.orig` to the ignore list.

**Pull request closed without merging**
