### PR TITLE
refactor: replace all internal use of size_t with MPI_Aint

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Trying out the other side of idea in issue #3365: replace all internal use of size_t with MPI_Aint.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Commits are self-contained and do not do two things at once
* [x] Remove xfail from the test suite when fixing a test
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Add Devel Docs in the `doc/` directory for any new code design
* [ ] Passes tests (included warning check)

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
Can't seem to reproduce. Try it again:

test:jenkins/ch4/ofi
test:mpich/custom

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/warnings
test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by hzhou** [comment]
The warnings are all from ROMIO's `MPI_Offset` type mismatch, which is being fixed elsewhere.
Test agains:

test:mpich/warnings --disable-romio

**Comment by hzhou** [comment]
Now it passes all tests, it confirms my belief that we should never use `size_t`. There are 3 commits, the first one is a blind search & replace; the second one patches up ucx function callbacks, as ucx interface uses size_t; the third one clamps down the limits from libfabric as they return limits above `MPIR_AINT_MAX`. Both patches are only required becase other library uses `size_t`, and we simply need `cast`/`clamp` at the interface.

The principle should be: use unsigned for symbols (char) and ids (such as flags and handles that applies bitmasks). For all integer numbers, always use signed -- unless one is really certain that he need that 1 bit extra range (he is very likely wrong).

**Comment by pavanbalaji** [comment]
Large refactoring change.  Should be delayed till the next major release.

**Pull request closed without merging**
