### PR TITLE
makefile: remove mpi_f77_sources from libpmpi.la

### LINKED ISSUE #6780: fortran: MPI_Type_create_f90_XXX with --disable-fortran
If we  `./configure --disable-fortran`, then the `MPI_Type_create_f90_XXX`  symbol is missing from `libmpi.so`.

Would it be possible to generate these routines anyway?  Rationale: If for whatever reason a power user decides to build MPICH without Fortran support, a pre-built binary (e.g. mpi4py conda-forge packages and Python wheels) would not be able to load due to missing symbols in `libmpi.so`. mpi4py is a wrapper, so if has to reference all MPI symbol, but mpi4py users do not necessarily use all of MPI in their applications, nor they necessarily interact with Fortran.

The implementation is up to you. The hard way is to map the p/r arguments to a duplicate of a C datatype that fits the requested precision and range, just to produce something as a fallback that sort of work the expected way. The easy way is to generate an error, as the MPI standard says _Attempting to access an element of the array with an index (p, r) not supported by the compiler is erroneous_. Or maybe the best is to output `MPI_DATATYPE_NULL` but return `MPI_SUCCESS`, given the fact that with `--disable-fortran`, all named Fortran datatypes are defined as `MPI_DATATYPE_NULL` in `mpi.h`. 

I personally prefer the last option (output NULL and return SUCCESS). It is easy for users to detect the situation (check the output for NULL) without having to deal error handling (otherwise, users would have to override the default FATAL handler). As the output datatype is NULL, any attempt to use it unchecked will generate an error anyway, so errors do not pass silently. Finally, the behavior is is somewhat symmetric with the other Fortran datatypes being defined to NULL.

### LINKED ISSUE #6814: Duplicate file in C/Fortran MPICH libraries
I am building MPICH 4.1.2. statically (but with `-fPIC`) on Apple. I find that both libraries `libpmpi.a` and `libmpifort.a` contain the object file `setbotf.o`. I later link both libraries into a shared library I create, and this fails because of duplicate symbols.

Postprocessing the MPICH libraries via
```sh
# Delete duplicate file
if ar t ${prefix}/lib/mpich/lib/libpmpi.a | grep -q setbotf.o; then
    ar d ${prefix}/lib/mpich/lib/libmpifort.a setbotf.o
fi
```
resolves the issue.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
`mpi_f77_sources` was double included in libpmpi.la when building without weak symbols, e.g. on osx.

Fixes #6814 
Fixes #6780

This one supersedes #6817
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
label: osx

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
label: osx
env: WRAPPER_FCFLAGS=-fallow-mismatched-args

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
label: osx
env: FCFLAGS=-fallow-mismatched-args

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

test:mpich/custom/pipeline
label: osx

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: osx

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: osx

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: osx

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Review by raffenet — APPROVED** [review]

**Comment by raffenet** [comment]
Didn't notice the conflict, but looks like it should be straightforward to resolve.

**Comment by hzhou** [comment]
> Didn't notice the conflict, but looks like it should be straightforward to resolve.

Yeah, just the comments in Makefile.am touching those changes for abi sources.

**Pull request merged**
