### PR TITLE
 thread: let VCI thread model use VCI specific mutexes

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Let VCI thread model use its own mutexes to better compartmentize code
under different thread models. VCI thread model and POBJ thread model
are very similar, only with different granular-levels. Eventually, both
models will be consolidated.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch4/ucx

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
cc: @sagarth

**Pull request merged**
