### PR TITLE
mtest: Add timing to test script and output

### PR DESCRIPTION
**Pull request by wesbland**
Add simple timing to the MPICH test suite scripts and show that time in the ouptut junit and tap files.

### CODE REVIEW

**Comment by wesbland** [comment]
test:jenkins/ch4/all

**Comment by wesbland** [comment]
@raffenet - Looks like I lost my ability to start test jobs. Oh well.

**Comment by wesbland** [comment]
test:jenkins/ch4/all

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
This seems like a good idea. Just want to make sure the Perl module is available on all our testing platforms first.

**Pull request merged**
