### PR TITLE
ch4/ipc: refactor ipc to use ch4 am rndv framework

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

After #5485, ch4 am framework can handle different rndv protocols via registration and callbacks, we can simply use the ch4 am to handle the message matching and have it callback the handlers to handle IPC specific work. The shm control facilities are no longer needed and removed.

[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi
test:mpich/ch4/xpmem

**Comment by hzhou** [comment]
test:mpich/ch4/ofi
test:mpich/ch4/xpmem

**Review by yfguo — APPROVED** [review]
LGTM

**Pull request merged**
