### PR TITLE
ch3: POBJ refactor and fixes

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
In order to proceed with new thread model, we need better compartmentalize old thread models so the new code won't accidentally break, or in the POBJ case, make the broken code further broken. While the POBJ do not share `ENTER/EXIT` macros with other models, it does share the usage of `MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX`. We'll first try to fix the POBJ build; then we'll replace the `ALLFUNC_MUTEX` with POBJ-specific global mutex, so that the POBJ will be completely isolated from all other thread models, including the "global" model.

MPICH_THREAD_GRANULARITY__POBJ is currently broken in ch3. One of the
outstanding error is due to missing pobj_mutex in the MPIDI_VC_t
struct. The patch adds the field back.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/custom
config: pobj-sock

**Comment by hzhou** [comment]
NOTES for `MPIDI_CH3I_Sock_wait()` in `src/mpid/ch3/channels/sock/src/sock.c`:

It tries to poll events assuming under a global lock (by caller). When immediate events are not available, it has to enter blocking wait. To allow other threads to proceed while it wait, it need to unlock and lock -- essentially a yield but with a explicit poll in between.

It is ugly as the callee is asserting assumptions on the callers -- taking a particular global lock in a particular manner. One such particular manner is the mutex has owner and count field to allow potentially multiple entering and exiting. In this case, it has to use a state variable to save and restore this potential multiple nest.

If we could eliminate the recursive locking, the situation will be much simpler. First, add assertions to alert recursive locking calls. Second, unlock before entering the potential recursive locking call (and retake the lock afterwards).

**Comment by hzhou** [comment]
The yield is only needed inside `MPID_Progress_wait`, which is mostly called by `MPI_Wait` and `MPI_Waitall`. Both functions call `MPID_THREAD_CS_ENTER(GLOBAL, MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX);` 

The other places that call `MPID_Progress_wait` are for connection stuff, mostly in non-performance-critical paths ( means having extra calls to unlock and lock is probably okay).

If we study what really need protection in `MPID_Progress_wait`, then we can take off that global lock, and only protect fine-grained components where necessary -- just as we did in the `per-vci` model. That should simplify the situation a lot.

**Comment by hzhou** [comment]
test:jenkins/custom
config: pobj-sock

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/custom
config: pobj-tcp

**Comment by rzambre** [comment]
@hzhou What do you mean when you say `POBJ` shares the usage of MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX with the other critical section models? When we compile with `POBJ` support, only `POBJ` macros are used and when we compile with `per-VCI` support, only `VCI` macros are used. So, how is the `MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX` being shared between the models?

**Comment by hzhou** [comment]
Need a lot of work and is now superseded by per-vci model.

**Pull request closed without merging**
