### PR TITLE
mtest: Add algo tests

### PR DESCRIPTION
**Pull request by tarudoodi**
## Pull Request Description
This PR will add the tests for collective algos(for the algos which were merged without tests) in the new testing script.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [ ] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by tarudoodi** [comment]
@hzhou I created this new PR for adding just the tests for algos being merged.

**Comment by tarudoodi** [comment]
I rebased this. This PR should go in as all of the algorithm that its testing has already been merged.

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by tarudoodi** [comment]
test:jenkins/ch4/most

**Comment by tarudoodi** [comment]
@hzhou the original bug from these patches was fixed. The failure in `ch4-ofi/strict` is due to a warning introduced in hwloc.

**Pull request merged**
