### PR TITLE
coll: Iallreduce ring algorithm

### PR DESCRIPTION
**Pull request by tarudoodi**

### CODE REVIEW

**Comment by tarudoodi** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by tarudoodi** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by tarudoodi** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by tarudoodi** [comment]
Rebased and testing.

**Comment by tarudoodi** [comment]
Fixed the rebase.

**Comment by tarudoodi** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by tarudoodi** [comment]
The failed tests do not seem related to the PR.

**Comment by hzhou** [comment]
@tarudoodi Could you rebase this PR?

**Comment by tarudoodi** [comment]
@hzhou done.

**Comment by tarudoodi** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch4/most

**Comment by tarudoodi** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch4/ucx

**Comment by tarudoodi** [comment]
test:jenkins/ch4/ucx

**Comment by tarudoodi** [comment]
I rebased this PR to resolve the conflicts for testing script.

**Pull request merged**
