### PR TITLE
submodule: Update libfabric to add a macOS fix

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Added a patch (also submitted to upstream) to fix a configure check
that caused builds to fail with Intel compilers on macOS.

## Expected Impact

fix macOS Intel compiler build

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: intel

**Comment by raffenet** [comment]
test:mpich/custom
netmod: ch4:ofi
label: osx
compiler: intel

**Comment by raffenet** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: osx
compiler: intel

**Comment by raffenet** [comment]
The patch in question was accepted into upstream: https://github.com/ofiwg/libfabric/pull/6358.

**Comment by hzhou** [comment]
The issue was -- `alias` was not supported by intel compilers on mac and `libfabric` uses alias if configure detects its support. The old configure in libfabric failed to do that check thoroughly (what was failure message from our Jenkins?). This PR pulls the patch that fixes this issue.

Is this description accurate?

**Comment by raffenet** [comment]
> The issue was -- `alias` was not supported by intel compilers on mac and `libfabric` uses alias if configure detects its support. The old configure in libfabric failed to do that check thoroughly (what was failure message from our Jenkins?). This PR pulls the patch that fixes this issue.
> 
> Is this description accurate?

`alias` is not supported by Intel compilers on macOS, correct. However the configure test did not detect that lack of support, because `icc` on macOS only issued a warning for the definition.

```
configure:15408: checking for __alias__ attribute support
configure:15425: icc -std=gnu99 -o conftest -O2 -DNDEBUG -fvisibility=hidden -Wall -Wundef -Wpointer-arith   conftest.c -lpthread -ldl  >&5
conftest.c(39): warning #1787: alias definitions not supported on this platform; attribute ignored
                int foo2(int arg) __attribute__ (( __alias__("foo")));
                                                   ^

configure:15425: $? = 0
configure:15427: result: yes
```

Jenkins tests would fail at the linking stage of the embedded `libfabric.la` convenience library. This patch strengthens the check so that `__alias__` detected will fail with `icc` on macOS, as expected, and disable its use in libfabric.

**Comment by raffenet** [comment]
config.log output after picking up this patch:
```
configure:15408: checking for __alias__ attribute support
configure:15425: icc -std=gnu99 -o conftest -O2 -DNDEBUG -fvisibility=hidden -Wall -Wundef -Wpointer-arith   conftest.c -lpthread -ldl  >&5
conftest.c(39): warning #1787: alias definitions not supported on this platform; attribute ignored
                int foo2(int arg) __attribute__ (( __alias__("foo")));
                                                   ^

Undefined symbols for architecture x86_64:
  "_foo2", referenced from:
      _main in iccKNIJfd.o
ld: symbol(s) not found for architecture x86_64
configure:15425: $? = 1

<snip>

configure:15433: result: no
```

**Review by hzhou — APPROVED** [review]
Thanks for the details

**Pull request merged**
