### PR TITLE
ch4: rename global structs

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
@yfguo I don't know if we're at a good point with the un-inlining work to fix these remaining namespace inconsistencies. I'll defer to you. If the un-inlining is not sufficiently far along, I would also suggest we merge #3065 before going further.

**Comment by raffenet** [comment]
FWIW, these commits were created by script, so there is no urgency to merge.

> maint/mpich-replace.sh MPIDI_CH4_Global MPIDI_global

 and 

> maint/mpich-replace.sh MPIDI_Global MPIDI_OFI_global

**Comment by yfguo** [comment]
Thanks. I missed those two names. I think we can merge this first. Cleanup un-inlining is not to bad at the moment.

**Pull request merged**
