### PR TITLE
mtest: Split f77/pt2pt/allpairf into multiple tests

### PR DESCRIPTION
**Pull request by wesbland**
The existing allpairf test is testing lots of different types of sends.
This should be split into multiple tests so things can be tested on a
more fine grained level.

### CODE REVIEW

**Comment by wesbland** [comment]
This was split off from #2923

**Comment by wesbland** [comment]
@raffenet mentioned on #2923:

> For one thing, I think the name allpair is no longer applicable to the new tests.

That's fine. I could just drop the `allpair` part of the name and have them just be the name of the MPI function. The were never really `allpair` anyway as the test was only run with two processes.

**Comment by wesbland** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by wesbland** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by pavanbalaji** [comment]
>> For one thing, I think the name allpair is no longer applicable to the new tests.

> That's fine. I could just drop the allpair part of the name and have them just be the name of the MPI function. The were never really allpair anyway as the test was only run with two processes.

@wesbland can you update the patch based on this comment?

**Comment by wesbland** [comment]
Done

test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by wesbland** [comment]
So the psend tests are still expected to fail in ch4/ofi (as per #2923).

**Comment by pavanbalaji** [comment]
The jenkins xfail will need to be updated for these failures.  Do you want me to signoff on the patches?

**Pull request merged**
