### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by wesbland**
A couple of prerequisite patches to help get the code formatted correctly, then a massive patch to reset all of the formatting in MPICH (other than CH3).

### CODE REVIEW

**Comment by wesbland** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by wesbland** [comment]
So apparently GNU indent doesn't honor autoconf macros. Still working on a fix for that. [StackOverflow is not being helpful.](https://stackoverflow.com/questions/47125199/gnu-indent-is-breaking-my-autoconf-macros)

**Comment by wesbland** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by wesbland** [comment]
Looks like the build/test problems from earlier are resolved This should be ready to go now I think.

**Comment by wesbland** [comment]
The last commit is just a placeholder and should definitely be regenerated before merging. For instance, it doesn't include hydra or mpl and will need to be re-run after those are put back in the code base. This patch (maint: Add files to cleanup ignore list) should be able to detect those files now.

**Comment by wesbland** [comment]
Updated to sit on the submodule revert.

**Comment by wesbland** [comment]
So I hacked up a quick pre-commit hook to test that we don't violate this with new commits. Once this goes in, I'd recommend that everyone set up this as a minimum:

https://gist.github.com/wesbland/3546c4483ceffe129a6e7fc4105fbf75
```
#!/bin/sh

MIRROR=/tmp/${USER}/mpich-tmp-mirror
TMP_FILENAME=/tmp/${USER}/mpich-tmp-file

# Checkout a copy of the current index into MIRROR
git checkout-index --prefix=$MIRROR/ -af

# Remove files from MIRROR which are no longer present in the index
git diff-index --cached --name-only --diff-filter=D -z HEAD | \
    (cd $MIRROR && xargs -0 rm -f --)

filestring=`git diff --cached --name-only --diff-filter=ACM`
IFS=', ' read -r -a file_array <<< "$filestring"

# Everything else happens in the temporary build tree
pushd $MIRROR > /dev/null

ret=0

for file in "${file_array[@]}"
do
    cp ${file} ${TMP_FILENAME}
    maint/code-cleanup.sh ${file}
    diff ${file} ${TMP_FILENAME}
    if [ $? != 0 ] ; then
        ret=1
    fi
done

rm -rf ${MIRROR} ${TMP_FILENAME}

if [ $ret != 0 ] ; then
    echo "== CODE CLEANUP SCRIPT FAILED == "
    exit $ret
fi

popd > /dev/null

# If there are whitespace errors, print the offending file names and fail.
# This will catch adding extra newlines where the above script will not catch that
exec git diff-index --check --cached $against --
```

Still working on a Jenkins script for this. It's slightly more tricky.

**Comment by wesbland** [comment]
Ugh...this doesn't work if you've changed a submodule. I don't know why you'd be updating a submodule and changing code at the same time at the moment, but know that if you're updating a submodule, you'd have to skip this hook with `git commit -n`.

**Comment by wesbland** [comment]
I've updated the Gist above with an improved pre-commit hook as well as a Jenkins PR hook for automated testing.

@raffenet / @yfguo  - IIRC, we're not using the same plugin for Jenkins+GitHub integration so you might have make some tweaks to how the hook picks up the base branch and whatnot. Essentially the checker is the same as the pre-commit hook, but it uses `git diff HEAD~1` instead of `git diff` since it's being run on the commit after the fact instead of the commit in progress.

**Comment by pavanbalaji** [comment]
Can this be rebased on to `mpich/master` and the white space patch rerun?

**Comment by wesbland** [comment]
Yep. I'm working on it now. It turns out GNU indent doesn't expand tabs to spaces in all cases. There are also some other things that were missed.

I'm just making sure everything compiles one last time. Should be done soon.

**Comment by wesbland** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by wesbland** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by wesbland** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
`git blame` stops here. :( 

I think such code clean-up and on-going enforcement is doing more harm than its worth.

**Pull request merged**
