### PR TITLE
ch4/ofi: Disable RMA for OFI/RxM by default

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
MPIDI_OFI_ENABLE_RMA path doesn't work for providers that use Basic MR.
The OFI/RxM provider Scalable MR support is disabled for RxM provider
by default.
This patch sets default value of ENABLE_RMA for RxM provider to OFF
for a while.

### CODE REVIEW

**Comment by gladkovdmitry17** [comment]
@wesbland @hajimefu @minsii Could you take a look, please? This fixes all RMA tests for the OFI/RxM provider

**Comment by wesbland** [comment]
So using:

    MPIDI_OFI_ENABLE_MR_SCALABLE = OFF
    MPIDI_OFI_ENABLE_RMA = ON

doesn't ever work? If so, that's a problem that should be solved.

**Comment by gladkovdmitry17** [comment]
Yes, this should solve the issue, if core provider support Scalable MR. 
So RxM support of Scalalble MR relies on core provider. The Verbs (core of RxM provider for OFI/RxM/verbs stack) doesn't support Scalable MR.

**Comment by wesbland** [comment]
My question is, if we were to fix `MR_BASIC` support, would we be able to use the RMA interface in the RxM provider? If so, then this solution is a temporary solution that I don't like. We should go fix `MR_BASIC` support.

**Comment by gladkovdmitry17** [comment]
> would we be able to use the RMA interface in the RxM provider?

Yes, this will work.

>We should go fix MR_BASIC support.

It would be great. I'll take a look, but I don't know when it will happen

**Comment by gladkovdmitry17** [comment]
I found that the LMT is broken for the MR Basic -- see PR #3014 
I'm not sure that MR Basic related code tested well. right?

**Comment by wesbland** [comment]
Correct. As far as I know, we haven't been testing that setup because the providers we've been using up to now all used MR scalable AFAIK.

**Comment by wesbland** [comment]
> @wesbland I found that the LMT is broken for the MR Basic -- see PR #3014
I'm not sure that MR Basic related code tested well. right?

This looks good. Let's close this PR and work on that one instead.

**Comment by gladkovdmitry17** [comment]
> Correct. As far as I know, we haven't been testing that setup because the providers we've been using up to now all used MR scalable AFAIK.

Yes, you're right. I tested RMA for sockets and psm2 (both providers use MR Scalable) and they work fine 👍

**Comment by wesbland** [comment]
If you're team is going to be supporting RxM, then I think we can safely lean on you for that.

**Comment by gladkovdmitry17** [comment]
> If you're team is going to be supporting RxM, then I think we can safely lean on you for that.

Yes, we're going to support RxM provider on OFI level and in MPICH/CH4/OFI level.

**Pull request closed without merging**
