### PR TITLE
libfabric: patch sockets provider for shallow progress

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

When libfabric accumulates unexpected messages to significant size, each progress test takes longer and longer going through all the entries. The slow progress test takes up critical section longer, blocks posting mpi operations (such as `MPI_Recv`), exacerbates the unexpected message queue problem.

This PR adds a patch to libfabric forcing a shallow approach. Each progress test will only go through 10 entries (configurable) and each time pick up where last time left off. This ensures snappy progress test and avoids needless spin on thousands of entries that can't progress anyway (due to corresponding operation slow to post).

## Note

Ignore the first 8 or so commits.
The PR is based on #4456 relying on a fix of fire mutex to clear the async tests. This PR addresses the netmod issues once the fair mutex is achieved.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/async

**Comment by hzhou** [comment]
test:mpich/async

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/async
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/async
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
The ucx netmod is slow because we always do `ucp_tag_probe_nb` inside `MPIDI_UCX_progress` for active messages. When the message queue gets big, `ucp_tag_probe_nb` become very expensive. In the `pingping` tests, there is no active messages, so we are just enduring the latency for nothing.

The proper fix is to re-work the way we do active message in UCX. We should issue a certain number of `recv` with a fixed buffer size. For active messages that is within the buffer size, the single `recv` can handle it directly. For large active message, we'll simply split the message to two parts. The pre-issued recv will recv the header part, then allocate buffer to recv the payload. This is the same way I did in legion.

**Comment by raffenet** [comment]
> The ucx netmod is slow because we always do `ucp_tag_probe_nb` inside `MPIDI_UCX_progress` for active messages. When the message queue gets big, `ucp_tag_probe_nb` become very expensive. In the `pingping` tests, there is no active messages, so we are just enduring the latency for nothing.

I'm surprised by this. All `ch4/ucx` active messages have the same matching information. A probe should always return the first message in the queue.

**Comment by hzhou** [comment]
> I'm surprised by this. All `ch4/ucx` active messages have the same matching information. A probe should always return the first message in the queue.

You are right in the case of only active messages. In the pingping tests, there is no active messages but with accumulating long message queues, so every probe will traverse the long queue for nothing.

Long message queue will arise for real applications if they are not optimized.

**Comment by raffenet** [comment]
> You are right in the case of only active messages. In the pingping tests, there is no active messages but with accumulating long message queues, so every probe will traverse the long queue for nothing.

Ah, this makes sense. Then we should remove the dependence on probe.

**Comment by pavanbalaji** [comment]
> You are right in the case of only active messages. In the pingping tests, there is no active messages but with accumulating long message queues, so every probe will traverse the long queue for nothing.

Sorry, I'm still confused.  `Probe` has matching information too, right?  Why does it need to traverse the entire queue?

**Comment by hzhou** [comment]
> > You are right in the case of only active messages. In the pingping tests, there is no active messages but with accumulating long message queues, so every probe will traverse the long queue for nothing.
> 
> Sorry, I'm still confused. `Probe` has matching information too, right? Why does it need to traverse the entire queue?

Probe is trying to check every message in the entire queue against the matching information. I probably will exit as soon as it finds the match. But in the pingping case, there is not active messages, so the probe always fails, but it always fails after going through the entire message queue.

**Comment by pavanbalaji** [comment]
> > Sorry, I'm still confused. `Probe` has matching information too, right? Why does it need to traverse the entire queue?
> 
> Probe is trying to check every message in the entire queue against the matching information.

Yes, I got that part.  My question is: *WHY* does it need to traverse the entire queue?

**Comment by wesbland** [comment]
Is the libfabric patch here being submitted upstream?

**Comment by hzhou** [comment]
> Is the libfabric patch here being submitted upstream?

No, not yet. I'll do that. I need some libfabric discussions anyway.

**Comment by hzhou** [comment]
ref: https://github.com/ofiwg/libfabric/pull/5891

**Comment by pavanbalaji** [comment]
Looks like this patch is already upstreamed.

**Pull request closed without merging**
