### PR TITLE
config: Add minimum version check for hwloc

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Adds version check for external hwloc library. I remember a user running into a build failure related to this issue, but I have not yet located the actual report...

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Review by hzhou — APPROVED** [review]

**Comment by raffenet** [comment]
My first version had an error in brackets/parens of AC_COMPILE_IFELSE which is now fixed. I also added an error message if the user specifies a too old hwloc, otherwise we do silent fallback to embedded.
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
> My first version had an error in brackets/parens of AC_COMPILE_IFELSE which is now fixed. I also added an error message if the user specifies a too old hwloc, otherwise we do silent fallback to embedded.

Sounds good 👍

**Comment by raffenet** [comment]
tweaked the error case, hopefully last time
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test failure should not be related to this fix. going to rebase and merge.

**Pull request merged**
