### PR TITLE
refactor: unroll BEGIN_FUNC/END_FUNC macros in ch3 ofi

### PR DESCRIPTION
**Pull request by hzhou**
Make the practice consistent with the rest of the code base. Facilitate future refactoring.

### CODE REVIEW

**Comment by hzhou** [comment]
@wesbland This PR unrolls those BEGIN_FUNC/END_FUNC macros so that future refactorization (whatever it maybe) can be applied more uniformly.

**Comment by raffenet** [comment]
test:jenkins/ch3/ofi
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/ofi

**Comment by raffenet** [comment]
I removed my signoff from this branch when Jenkins tests failed to compile. Needs fixing.

**Comment by hzhou** [comment]
> I removed my signoff from this branch when Jenkins tests failed to compile. Needs fixing.

Oops, missed one. Did a `push -f`. Let's test is again.

test:jenkins/ch3/ofi

**Comment by yfguo** [comment]
I think the CH3 code is in bug-fix-only mode at the moment. It is really necessary to also do this in CH3?

**Comment by raffenet** [comment]
This particular macro made scripting the FCNAME/FUNCNAME removal more difficult.

**Comment by wesbland** [comment]
> I think the CH3 code is in bug-fix-only mode at the moment. It is really necessary to also do this in CH3?

That's a good point. We didn't do the formatting cleanup there either to avoid downstream conflicts.

**Comment by hzhou** [comment]
Can we relax the bug-fix-only mode a bit to allow certain clean up? -- just need be more careful. For example, how about  feature freeze mode? It is quite bad if we allow creating inconsistency or even widening it.

**Comment by pavanbalaji** [comment]
> Can we relax the bug-fix-only mode a bit to allow certain clean up? -- just need be more careful. For example, how about feature freeze mode? It is quite bad if we allow creating inconsistency or even widening it.

I agree that inconsistency is bad and it should be fixed.  It's not a real requirement that `ch3` is bug-fix only.  The intent was that we be careful how much effort we put into it.

**Comment by yfguo** [comment]
Is #3531 the CH4 version of this PR?

**Comment by hzhou** [comment]
> Is #3531 the CH4 version of this PR?

That PR applies to entire codebase.

**Comment by yfguo** [comment]
Another question that we should figure out is what functions should have this macro. At least not all CH4 functions it at the moment.

**Comment by hzhou** [comment]
> Another question that we should figure out is what functions should have this macro. At least not all CH4 functions it at the moment.

Which macro are you referring to? I am unrolling `BEGIN_FUNC`, `END_FUNC` in this PR, so after the PR, none should use these macros.

**Comment by yfguo** [comment]
OK. I see.

**Pull request merged**
