### PR TITLE
group: expand group lpid and ch4 gpid into 64bit

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

The term `lpid` in MPIR-layer group and `gpid` in ch4-layer process map are equivalent despite the name differences. Both refers to a local process id including those from dynamic processes. For ch4, this is a combination of `avtid` (av table index) and `lpid` (av entry index). Using 32-bit to represent this combination puts arbitrary limit on the range of `avtid` and `lpid`. In fact, there is no check for overflow and it is simply a matter of testing coverage to reveal this potential bug.

In this PR, we expand this id into 64-bit to ensure its safety.

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/ofi
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
retest to confirm:
test:mpich/ch3/sock

**Comment by hzhou** [comment]
retest to confirm:
test:mpich/ch3/sock

**Review by yfguo — APPROVED** [review]

**Pull request merged**
