### PR TITLE
debugger: Remove unused prev variable to fix compiler warning

### PR DESCRIPTION
**Pull request by nitbhat**
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by nitbhat** [comment]
I can't access the details of the contribution-checker, getting a 404 error. @raffenet, @hzhou : Do you know why the contribution-checker is failing?

**Comment by hzhou** [comment]
> 

I sent you an invite to join `mpich-intel` team on github. Could you check?

**Comment by nitbhat** [comment]
Yes, I just joined the organization. I'd missed it earlier. Thanks @hzhou

**Comment by hzhou** [comment]
test:mpich/authorship
test:mpich/warnings
test:mpich/custom
config: debuginfo

**Comment by hzhou** [comment]
test:mpich/authorship

**Pull request merged**
