### PR TITLE
ch4/ofi: Disable shared TX context by default

### PR DESCRIPTION
**Pull request by hajimefu**
This PR disables shared TX (STX) context by default.

Enabling STX makes each process consume one more context by default, thereby limiting the number of processes a user can launch.

There was a bug that MPICH simply ignored `MPIR_CVAR_CH4_OFI_ENABLE_SHARED_CONTEXTS`, making it impossible to turn off STX if a provider supported it. It was the case for sockets and psm2. This bug is also fixed in this PR.

**Note on performance regression:**
Right now, disabling STX is known to hurt small message rate on psm2 systems. Try setting `MPIR_CVAR_CH4_OFI_ENABLE_SHARED_CONTEXTS=1` if higher message rate is needed. See pmodels/mpich#3341 for details.

### CODE REVIEW

**Comment by hajimefu** [comment]
@minsii This is the PR I promised on Slack a few days back.

**Comment by hajimefu** [comment]
test:jenkins/ch4/ofi

**Comment by minsii** [comment]
@hajimefu After discussing with @raffenet , we think we need to better understand the reason of the send/receive performance impact before disabling the shx context creation by default. Both issues are significant enough. 

I will do some more performance study and reactive the "Performance drop when removing `fi_stx_context` in MPI_Init()" email conversion.

**Comment by hajimefu** [comment]
@minsii Fair enough. I have allocated some time next week to investigate this performance issue as well. Will sync up with you on my findings.

**Comment by yfguo** [comment]
I will try this fix on the JLSE machine and get back to you.

**Comment by hajimefu** [comment]
@yfguo Thanks. Just to be clear, this branch does not fix the performance drop issue, but this branch allows you to easily turn on or off STX (by setting `MPIR_CVAR_CH4_OFI_ENABLE_SHARED_CONTEXTS`), which should be helpful for performance comparison.

**Comment by yfguo** [comment]
@hajimefu I have tried this PR on JLSE seeing the same results you got. Enabling/disabling the shared TX context only results in ~1% performance difference.

**Comment by raffenet** [comment]
It sounds like it should be OK to merge this then. @yfguo do you agree?

**Comment by raffenet** [comment]
Oops, should have tagged @minsii

**Comment by minsii** [comment]
Great news ! I would like to merge this PR. Let me finish review quickly today.

**Comment by hajimefu** [comment]
@minsii I think that comment is still correct (though a little bit odd now). If a user specifies "-1", meaning "don't care", MPICH still tries to use it (given the provider supports it).

**Comment by minsii** [comment]
I actually read it as if the user does not care (i.e., do not explicitly specify a CVAR), then shared_contexts will be used for RMA. It would be better if we can make the comment clear (e.g., "if the user doesn't care" -> "if the user specifies -1")

**Comment by wesbland** [comment]
What `-1` usually means with the capability set code is that the user "doesn't care" or "didn't explicitly set the value". In practice what this means it that we'll check the capability set and use whatever is in there (whether it's specific to the provider or one of the generic ones for fallback code paths.

**Comment by minsii** [comment]
Locally tested that the MPI program can run with `ppn=num of cores` with this PR.

**Comment by hajimefu** [comment]
I'm happy to hear a suggestion for a better comment there! @minsii 😄

**Comment by hajimefu** [comment]
> I actually read it as if the user does not care (i.e., do not explicitly specify a CVAR), then shared_contexts will be used for RMA.

Yeah, before this patch it was actually the case (no CVAR <=> don't care). Now that the default has changed, maybe it's better to reword it a little bit as you suggested.

**Comment by minsii** [comment]
I just deleted the "Temporarily revert commit 54feb7 for RMA testing" commit which was for testing only.

**Comment by hajimefu** [comment]
@minsii Update the comment based on your suggestion, and updated the commit message of "ch4/ofi: Disable shared TX context by default" to reflect the latest performance observation.

Other part of the code did not change, so probably further review/testing is not necessary.

**Pull request merged**
