### PR TITLE
some autogen fixes

### PR DESCRIPTION
**Pull request by raffenet**
Fixes bad `git clean` behavior noticed on LCRC machines. Also removes some redundant code I noticed while digging around.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp
test:jenkins/ch4/most

**Comment by raffenet** [comment]
est:jenkins/ch3/tcp
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by yfguo** [comment]
The PR looks fine. I will signed and merge after the tests are passed.

**Pull request merged**
