### PR TITLE
MPL_sockaddr fixes (3.3.x)

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Cherry-picked fixes for MPL_sockaddr usage in 3.3.x. See #4318.

## Expected Impact

Fix user-visible bugs.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most

**Comment by hzhou** [comment]
@raffenet You may also want to pick this patch: #4281.

**Comment by raffenet** [comment]
test:jenkins/ch3/most

**Pull request merged**
