### PR TITLE
coll: use MPI_BYTE for temporary buffer in Allgatherv

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
Fixes a bug reported from downstream. Will add test case. Marking as WIP for now.
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
I don't want this patch to get stale, so I'm removing the needs test label. The existing non-contig tests verify the correctness for this patch, so I think it is safe to include. Tagging @yfguo for review.

**Comment by raffenet** [comment]
Actually, since @hzhou is currently spinning up on the collectives code, I will assign this review to him.

**Comment by hzhou** [comment]
@raffenet Do you have a link to the bug-report?

**Comment by hzhou** [comment]
@raffenet The same patch should apply to `MPIR_Allgather`, right? If so, could you add another commit to `Allgather`?

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
test:jenkins/ch3/most

**Comment by hzhou** [comment]
fixed whitespaces and bug in `ialltoall_intra_bucks.c`, retesting...

test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
fixed another bug in `ialltoallw_intra_inplace`, retesting...
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
@raffenet I have pushed additional commits to this PR. The tests seems good. Could you give it a review?

**Comment by raffenet** [comment]
All the changes look good to me. I'm not sure they all need to be separate commits. Would you be opposed to squashing everything into one with a commit message explaining the reason for the change?

**Comment by hzhou** [comment]
> All the changes look good to me. I'm not sure they all need to be separate commits. Would you be opposed to squashing everything into one with a commit message explaining the reason for the change?

**Pull request merged**
