### PR TITLE
test/dtpools: add default test configuration

### PR DESCRIPTION
**Pull request by gcongiu**
Set default test configuration to only 2 basic datatypes and pool size
of 5.

### CODE REVIEW

**Comment by gcongiu** [comment]
@pavanbalaji this should fix the default test configuration for stand alone runs

**Comment by gcongiu** [comment]
@pavanbalaji this is the fix for the default case. Hopefully this is ok. I have tried it and seems to work

**Comment by pavanbalaji** [comment]
@gcongiu I'm not sure I understand this patch.  If no environment variables are set, isn't `runtests` interpreting it to mean some values for the two environment variables?  Why can't that be changed?

**Comment by gcongiu** [comment]
@pavanbalaji I have updated the patch to modify the `runtest` script as suggested.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by wesbland** [comment]
test:intel:ch4/ofi/sockets/gnu/force-am-disabled/shm-exclusive/debug

**Comment by raffenet** [comment]
@gcongiu this patch seems a little inconsistent. One default value is pushed into the runtime environment, while the other is a local variable.

**Comment by gcongiu** [comment]
@raffenet `DTP_RUNTIME_TYPES` is only used by the `runtest` script, there is no need to push it to environment. `DTP_NUM_OBJS` is used by DTPools so it has to be pushed.

**Comment by pavanbalaji** [comment]
This patch seems weird to me.  Why can't both environments be handled in runtests?

**Comment by gcongiu** [comment]
I am not sure I get your point. The thing is `DTP_RUNTIME_TYPES` does not need to be set if the environment does not define it. The runtests script will generate a local version by default and use it internally. No other parts of the code need to know about it. `DTP_NUM_OBJS`, on the other hand, is needed by `test/mpi/dtpools/src/dtpools.c` to set the pools size.

**Comment by raffenet** [comment]
Hmm, I see. So the types is basically a compile-time value used to build the correct test binaries? And the number of objects is a dtpools runtime option. Am I understanding it?

**Comment by gcongiu** [comment]
Yes the types to test can be chosen by the user by setting the corresponding env var. If the user does not set it `runtests` sets it and then checks across the tests in `testlist` those that match the defined types and run only those. The pool size is a runtime option as you said.

**Comment by raffenet** [comment]
Alright then I think I am OK with this, but will wait if @pavanbalaji would still like changes.

**Comment by pavanbalaji** [comment]
Oh, sorry, I didn't refresh and was seeing the old code.  I see the new patch now and it's exactly what I had in mind.  I'll approve in a bit.

**Pull request merged**
