### PR TITLE
ROMIO: fix flatten.c

### PR DESCRIPTION
**Pull request by wkliao**
## Pull Request Description
See 4 commit messages.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [x] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Review by roblatham00 — APPROVED** [review]
zero length types are tricky.  rebased onto latest main and let's see how the tests do

**Comment by roblatham00** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by roblatham00** [comment]
I ran the ROMIO tests on my laptop:  if nothing else, I feel good that `types_with_zeros` passed

**Comment by roblatham00** [comment]
Wei-keng sorry for the absurdly long review time.  I lost track of this one until yesterday when I was going through MPICH pull requests.

**Pull request merged**
