### PR TITLE
request: Fix handling of inactive persistent collective requests

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Persistent collective requests in inactive state should complete the same as other inactive requests. Fixes a hang in MPI_WAIT with such a request. Depends on #6333 for early return binding changes.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
I have a fixup commit to fix the copyright header in the new test. Will add/squash once the tests complete.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Review by hzhou — APPROVED** [review]
LGTM. Approved pending on clean test results.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
I messed up the `automake` install on some Jenkins nodes. Hopefully fixed now...
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Pull request merged**
