### PR TITLE
Avoid dereferencing NULL pointers

### PR DESCRIPTION
**Pull request by sagarth**
## Pull Request Description
Avoid dereferencing a NULL pointer if hwloc returns a NULL pointer.

Fixes Klocwork issues.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Review by hzhou — APPROVED** [review]
LGTM. Please check the author checklist and clear the tests

**Comment by sagarth** [comment]
@hzhou Would you recommend running any other test for sanity check?  e.g., `test:mpich/ch4/most` or a subset for `ofi`.

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by sagarth** [comment]
It looks to me like the failing test `./pt2pt/rqfreeb 4` under `ch4-ucx` is unrelated to this PR. All other tests passed.

**Comment by hzhou** [comment]
> It looks to me like the failing test `./pt2pt/rqfreeb 4` under `ch4-ucx` is unrelated to this PR. All other tests passed.

Created tracking issue #6378

**Pull request merged**
