### PR TITLE
test: Add eager message limit to testlist

### PR DESCRIPTION
**Pull request by wesbland**
## Pull Request Description

Add an eager limit to some relevant multi-threading tests to avoid missing failures because of a very large eager limit.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
> Add an eager limit to some relevant multi-threading tests to avoid missing failures because of a very large eager limit.

Do you have examples that without the CVAR the test will miss?

**Comment by wesbland** [comment]
> > Add an eager limit to some relevant multi-threading tests to avoid missing failures because of a very large eager limit.
> 
> Do you have examples that without the CVAR the test will miss?

By default, the eager limit is usually 2GB and these tests generally don't send messages that large. This makes sure we're testing the rendezvous code paths even if we're below the default limit that comes out of OFI.

**Comment by wesbland** [comment]
test:mpich/ch4/ofi

**Comment by raffenet** [comment]
> By default, the eager limit is usually 2GB and these tests generally don't send messages that large. This makes sure we're testing the rendezvous code paths even if we're below the default limit that comes out of OFI.

I think there some debate whether this is actually an "eager" limit, since internally OFI may be using a rendezvous that is not visible to the caller. Rather, this appears to be a threshold for which the OFI netmod will use the "huge" protocol (and also maybe striping related code paths?). Anyway, I think the end result is good here.

**Comment by wesbland** [comment]
Ugh... I was afraid the tests would do this... I'll probably have to wait until I'm back in the office on Monday to look at this.

**Comment by wesbland** [comment]
Ugh... I was afraid the tests would do this... I'll probably have to wait until I'm back in the office on Monday to look at this.

**Comment by hzhou** [comment]
> Ugh... I was afraid the tests would do this... I'll probably have to wait until I'm back in the office on Monday to look at this.

Which supports the point of your PR :) There is always a risk to look under the carpet 😄

**Comment by wesbland** [comment]
> Which supports the point of your PR :) There is always a risk to look under the carpet 😄

Yeah, this PR is another in our series of getting all of the internal patches upstreamed. We might have some relevant xfails that I need to migrate. I'll figure it out...

**Comment by wesbland** [comment]
Apparently this was a known issue. @hajimefu pointed this out a couple of years ago in our internal repo:

> The huge message transfer protocol inside OFI netmod does not seem to be thread-safe, as MPIDI_posted_huge_recv_head and MPIDI_unexp_huge_recv_head etc. are not protected from race.

So I'm probably not going to fix this quickly. Should I create an issue for this and xfail?

**Comment by hzhou** [comment]
> 
> 
> Apparently this was a known issue. @hajimefu pointed this out a couple of years ago in our internal repo:
> 
> > The huge message transfer protocol inside OFI netmod does not seem to be thread-safe, as MPIDI_posted_huge_recv_head and MPIDI_unexp_huge_recv_head etc. are not protected from race.
> 
> So I'm probably not going to fix this quickly. Should I create an issue for this and xfail?

I have that issue already -- https://github.com/pmodels/mpich/issues/5359. I discovered that separately a month ago

**Comment by wesbland** [comment]
> I have that issue already -- #5359. I discovered that separately a month ago

Ah. I guess we've got it then. I'll update the xfails here.

**Comment by hzhou** [comment]
> 
> 
> > I have that issue already -- #5359. I discovered that separately a month ago
> 
> Ah. I guess we've got it then. I'll update the xfails here.

Actually, @wesbland , the issues here may be slightly different from what I discovered, since the tests here is not per-vci. Could you supplement that issue?

**Comment by wesbland** [comment]
I think it's probably the same. This is still a multi-threading test.

**Comment by wesbland** [comment]
test:mpich/ch4/ofi

**Comment by wesbland** [comment]
@raffenet The tests passed here. I guess this is good to go even though it doesn't do a lot.

**Review by raffenet — APPROVED** [review]

**Pull request merged**
