### PR TITLE
[DO NOT MERGE] bc exchange

### PR DESCRIPTION
**Pull request by raffenet**
Creating PR for testing purposes.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi
test:jenkins/ch3/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi
test:jenkins/ch3/ofi

**Comment by raffenet** [comment]
cc @ddurnov

**Comment by raffenet** [comment]
One improvement I want to look at is using `MPIR_Find_local_and_external` to replace the scattered locality calculations in this PR.

**Comment by alexander-sannikov** [comment]
@raffenet @ddurnov I've recheck this patch and it works well.   We just shouldn't perform any communications in MPID_Comm_create_hook (for COMM_WORLD and nested communicators at least).

In Dmitry's reproducer Allreduce was called in MPID_Comm_create_hook for COMM_WORLD->node_comm, before MPID_Comm_create_hook (with real names exchange/connections establishment) on COMM_WORLD was called. In case of ch4-shm enabled, point-to-point communication goes via shm, so BC exchange isn't  mandatory for intranode communications in this case. But as soon as ch4-shm is disabled, you will get situation when you are trying to perform allreduce via OFI w/o connections established.

**Comment by raffenet** [comment]
most of this was merged in #3144

**Pull request closed without merging**
