### PR TITLE
romio: pipelining in adio lustre driver

### PR DESCRIPTION
**Pull request by swblaster**
This patch implements the pipelined I/O method proposed in [1] that uses a multi-buffer pipelining approach to overlap the request-aggregation phase with file-access phase (the two-phase I/O strategy) in the MPI collective I/O functions. The pipelined method is designed for MPI collective write functions and the Lustre file system only. It first divides the collective buffers into several sub-buffers. The collective I/O proceeds in several rounds of two-phase I/O, each of which uses a sub-buffer. The rounds are carried out in a pipeline fashion.  The method pipelines the two-phase I/O on the individual sub-buffers by overlapping the MPI asynchronous send-receive calls and the file access phase alternatively. This method improves the I/O performance, particularly for collective writes with large aggregate I/O amount.

Configuration -- The pipelined I/O feature can be activated by adding the command-line option “--enable-pipelining-io” at the configure time. The default setting for this feature is “disabled”.

Testing -- This patch has been tested using the MPICH test programs under test/mpi/io and src/mpi/romio/test. We also tested it using all PnetCDF test programs, and BTIO, FLASH-IO benchmarks.

This work is sponsored in part by the DOE Exascale Computing Project (ECP), Project Number 17-SC-20-SC.

Developers: Sunwoo Lee, Saba Sehrish, and Wei-keng Liao, Northwestern University.

Reference:
[1] S. Sehrish, S. Son, W. Liao, A. Choudhary, and K. Schuchardt. “Improving Collective I/O Performance by Pipelining Request Aggregation and File Access”, in the 20th EuroMPI Conference, September 2013.

### CODE REVIEW

**Comment by roblatham00** [comment]
Great.  Please run your code through the "whitespace checker":   https://github.com/pmodels/mpich/wiki/Code-Cleanup-Procedure has a very detailed process but `maint/code-cleanup.sh` on the files you've changed should get you most of the way there

Second,  I don't think there's a need to gate this with a configure option.   A hint might be the way to go here.

**Comment by swblaster** [comment]
I removed the configure option and added a hint for the pipelining I/O. The update is committed and pushed to my forked repository. 

I ran the code-cleanup script a few times and it does not show any bad whitespaces. Could you let me know the reason for the failing check? Thank you in advance.

**Comment by pavanbalaji** [comment]
@swblaster or @roblatham00   What's the status of this PR?  If it's abandoned, please close this PR instead of leaving it hanging.

**Comment by pavanbalaji** [comment]
@roblatham00 intends to work on this when he finds the time.  Marking it as WIP, so it doesn't need to be monitored till it's ready for review.

**Pull request closed without merging**
