### PR TITLE
mtest: Simplify make rules for utilities

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Build rules for mtest utilities were unnecessary complex. Simplify them to ease future maintenance.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
I got here because of a nag message during autoreconf:

> libtoolize: `AC_PROG_RANLIB' is rendered obsolete by `LT_INIT'

test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
oof, this is more complex than i thought. marking WIP and will update with more changes.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Review by hzhou — APPROVED** [review]
LGTM as long as tests are good.

**Pull request merged**
