### PR TITLE
Fixed Allgather_intra_k_brucks Csel_container

### PR DESCRIPTION
**Pull request by WHMHammer**
The original codes were mistakenly setting the csel container struct for Alltoall when the algorithm was Allgather.

### CODE REVIEW

**Review by hzhou — APPROVED** [review]
Thanks for the fix!

The union structure for `alltoall` and `allgather` happen to be the same. I guess that's why it escaped the tests. Good catch!

**Comment by hzhou** [comment]
@WHMHammer Do you mind sign the contribution agreement -- http://www.mpich.org/documentation/contributor-docs/? Our policy requires a contribution agreement before we can merge the patches.

**Comment by WHMHammer** [comment]
Hi @hzhou . How should I send it back?

**Comment by WHMHammer** [comment]
@hzhou Sent.

**Comment by hzhou** [comment]
Please scan and email a pdf file of this Agreement to ***@***.***
________________________________

**Comment by hzhou** [comment]
@WHMHammer I accidentally closed the PR when trying to rebase it, partly because you used `main` branch. Could you re-open the PR? I believe you can simply re-push to your own branch.

**Comment by hzhou** [comment]
In case there is trouble restore the PR, here is the diff:
```
--- a/src/mpi/coll/src/csel_container.c
+++ b/src/mpi/coll/src/csel_container.c
@@ -236,7 +236,7 @@ static void parse_container_params(struct json_object *obj, MPII_Csel_container_
                 json_object_object_foreach(obj, key, val) {
                     ckey = MPL_strdup_no_spaces(key);
                     if (!strncmp(ckey, "k=", strlen("k=")))
-                        cnt->u.alltoall.intra_k_brucks.k = atoi(ckey + strlen("k="));
+                        cnt->u.allgather.intra_k_brucks.k = atoi(ckey + strlen("k="));
                     MPL_free(ckey);
                 }
             }

```

**Comment by WHMHammer** [comment]
@hzhou #6096

**Pull request closed without merging**
