### PR TITLE
modules: Add json-c submodule

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

This is a prereq patch for collective selection. This may not be the
final location for the json code, but is useful for testing now.

## Expected Performance Changes

none

## Known Issues

none

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Passes tests (included warning check)
* [x] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [x] Commits are self-contained and do not do two things at once
* [x] Remove xfail from the test suite when fixing a test
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by pavanbalaji** [comment]
Can this be moved to `src` instead of `ch4`?  We might use it in the MPI layer too.

**Comment by hzhou** [comment]
> Can this be moved to `src` instead of `ch4`? We might use it in the MPI layer too.

Can we move all submodules into `$top_srcdir/modules`?

**Comment by raffenet** [comment]
Sure. Will move it. More testing to see if this works on other platforms.
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/sock

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
These `-Wshadow` warnings reported by the ib64 nodes seem bogus to me. I'm going to do some more investigating. Might need to disable with older compilers.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
Updated to use a post-autogen version of json-c omitting the autoconf-archive macros from the source. I did so by installing them same macros locally on my laptop in order to produce the `configure` script, then did `make dist` and placed the output into pmodels/json-c-module.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
This is now working with the pre-autogen'd code added as a submodule. The last detail is to solve the build issues with `--enable-strict` on BSD and Solaris.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
Hopefully I fixed the strict build issues in this version.
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
I find this thread (https://lists.freebsd.org/pipermail/freebsd-standards/2004-March/000471.html) a good source for why defining `POSIX_C_SOURCE` causes so many issues for BSD and Solaris builds. Those platforms interpret that as a restrictive request for *only* POSIX functionality. Linux platforms do not treat it this way, so it's easy to get crossed up. MPICH on macOS adds `-D_DARWIN_C_SOURCE` to `CFLAGS` when building in strict mode, which may override the restriction. Adding `-D__BSD_VISIBLE`on BSD, however, can result in undefined behavior.

**Comment by raffenet** [comment]
@pavanbalaji reported problems building this PR, but I have not been able to reproduce. Have others run into issues? I disabled maintainer mode on the json-c submodule so that it would never require autotools to build.

**Comment by raffenet** [comment]
@rkalidas forgot to tag you on my last comment. I think this is more or less ready to go. If you cherry-pick this version, I think we can close this PR and just merge it with the collective selection PR when it is ready.

**Comment by rkalidas** [comment]
Sure, I will get back to the collective selection PR work early next week.

**Comment by raffenet** [comment]
OK, sounds good. In that case I'm going to close those the PR and just keep the branch in my fork for now.

**Pull request closed without merging**
