### PR TITLE
submodule: Update libfabric to v1.11.2

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Update libfabric to latest release + additional patches for MPICH fixes.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ofi

**Comment by raffenet** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
Looks like now the socket provider will return `max_order_war = 0`, which doesn't guarantee ordering, causing the assertion error.

**Comment by hzhou** [comment]
> 
> 
> Looks like now the socket provider will return `max_order_war = 0`, which doesn't guarantee ordering, causing the assertion error.

I was puzzling what changed only to find, half a day debugging later, that now our default capability set chooses `verbs;ofi_rxd` provider instead of `sockets`.

**Comment by hzhou** [comment]
Reproduced the test failure with `sockets` provider. Backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff76cb427 in sock_comm_is_disconnected ()
   from /home/zhouh/MPI/lib/libmpi.so.0
#0  0x00007ffff76cb427 in sock_comm_is_disconnected ()
   from /home/zhouh/MPI/lib/libmpi.so.0
#1  0x00007ffff76c5f3f in sock_pe_progress_tx_entry ()
   from /home/zhouh/MPI/lib/libmpi.so.0
#2  0x00007ffff76c9598 in sock_pe_progress_tx_ctx ()
   from /home/zhouh/MPI/lib/libmpi.so.0
#3  0x00007ffff76ca44b in sock_pe_progress_ep_tx ()
   from /home/zhouh/MPI/lib/libmpi.so.0
#4  0x00007ffff76b806b in sock_cq_progress.part.11 ()
   from /home/zhouh/MPI/lib/libmpi.so.0
#5  0x00007ffff76b8e55 in sock_cq_sreadfrom ()
   from /home/zhouh/MPI/lib/libmpi.so.0
#6  0x00007ffff5d5fd4d in fi_cq_read (count=8, buf=0x7fffffffd5d0,
    cq=<optimized out>) at mymake/libfabric/include/rdma/fi_eq.h:394
#7  MPIDI_OFI_progress (vci=vci@entry=0, blocking=blocking@entry=0)
    at src/mpid/ch4/netmod/ofi/ofi_progress.c:74
#8  0x00007ffff5ba84a3 in MPIDI_OFI_win_do_progress (vni=0,
    win=0x7ffff7dd7040 <MPIR_Win_direct>)
    at ./src/mpid/ch4/netmod/include/../ofi/ofi_win.h:33
#9  MPIDI_NM_rma_win_cmpl_hook (win=0x7ffff7dd7040 <MPIR_Win_direct>)
    at ./src/mpid/ch4/netmod/include/../ofi/ofi_win.h:321
#10 MPIDIG_mpi_win_fence (win=0x7ffff7dd7040 <MPIR_Win_direct>,
    massert=<optimized out>) at ./src/mpid/ch4/src/ch4r_win.h:522
#11 MPID_Win_fence (win=0x7ffff7dd7040 <MPIR_Win_direct>, assert=16384)
    at ./src/mpid/ch4/src/ch4_win.h:186
#12 PMPI_Win_fence (assert=assert@entry=16384, win=-1610612736)
    at src/binding/c/rma/win_fence.c:108
#13 0x0000000000401ab8 in main (argc=1, argv=0x7fffffffd988)
    at cas_type_check.c:47
```

**Comment by hzhou** [comment]
Okay, I am gonna stop digging for now. It is definitely some regression going on in the `libfabric`  code handling atomics. For now, seems the remedy is to disable `ATOMICS`, either via capability set or with `MPIR_CVAR_CH4_OFI_ENABLE_ATOMICS`

**Comment by hzhou** [comment]
@raffenet would you like to import the commits I made a few months ago to enhance the `embedded` mode -- https://github.com/pmodels/libfabric/commits/mpich/v1.10.1

**Comment by raffenet** [comment]
test:mpich/ch4/ofi

**Comment by raffenet** [comment]
Picked up extra embed commits and rebased.

**Comment by hzhou** [comment]
@raffenet The sockets provider has a regression as I mentioned in the comments. What should we do?
1. Wait for upstream to fix. Due to the deprecated status, I am not sure how long or will it ever happen
2. Disable atomics. That means we won't be able to test the direct atomic path.
3. Switch to tcp provider. TCP provider has incomplete atomic support (missing "WAR" ordering). So we may also disable atomics, or we could pass window hints to ignore the "WAR" ordering -- might work for our tests.

Also to switch to tcp provider, the current selection logic won't work and it will need to hack the capability set. I really would merge https://github.com/pmodels/mpich/pull/4705 to solve the provider matching issue once for all.

**Comment by raffenet** [comment]
I'm open to reviving #4705. Obviously we need to get other OFI stakeholders on board. One simple thing we can do, after briefly scanning the old PR, would be to split refactoring patches into a separate PR from the functional changes. That way we can isolate the review of the new matching logic on its own.

**Comment by hzhou** [comment]
refresh the test status:
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
Rebased to `main`:
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
Picked fix https://github.com/ofiwg/libfabric/pull/6765

test:mpich/ch4/ofi

**Comment by hzhou** [comment]
Rebased and try again:
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: FI_PROVIDER=tcp;ofi_rxm

**Review by hzhou — APPROVED** [review]
The tests have passed with the new libfabric patch. 
https://github.com/pmodels/mpich/pull/4932#issuecomment-842805279

**Comment by hzhou** [comment]
@raffenet Since you cannot review your own PR, how about add your review/approval in the comment?

**Comment by raffenet** [comment]
LGTM 👍

**Pull request merged**
