### PR TITLE
mpir/topo: generic cleanup and namespace refactoring

### PR DESCRIPTION
**Pull request by gcongiu**
## Pull Request Description

Remove unused topology functions and refactor namespace.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by gcongiu** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by gcongiu** [comment]
@hzhou it looks like some test is timing out. I will update the PR and re-run the tests.

**Comment by hzhou** [comment]
I noticed. I just extended the timeout on review tests to 5 hours, effectively disabled the timeout.

**Comment by gcongiu** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by gcongiu** [comment]
@hzhou I would not merge this actually. Let me see if I can rework everything in a separate PR and use this as reference for some of the changes.

**Comment by gcongiu** [comment]
This is no longer needed, closing it

**Pull request closed without merging**
