### PR TITLE
ch4/ofi: Support large active messages without FI_READ

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by hajimefu** [comment]
@raffenet I'll review this. Ping me if it becomes ready.

**Comment by raffenet** [comment]
Thanks! Hoping to wrap it up soon. Still debugging a few issues.

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
Since FI_READ capability is necessary to utilize the RxM utility provider, this is probably not worth pursuing at the moment. Most providers we aim to support will have FI_READ.

**Pull request closed without merging**
