### PR TITLE
runtests: use read permission when obtaining the filelock

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
When the lockfile is already exist and owned by another user, typical
permission will not allow the file to be opened with write permission.
Since we don't really need write permission for flock, change it to read
permission to have a better chance succeeding.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
According to https://perldoc.perl.org/functions/flock.html:
```
Note that the fcntl(2) emulation of flock(3) requires that FILEHANDLE be open with read intent to use LOCK_SH and requires that it be open with write intent to use LOCK_EX.
```
Does this break exclusive lock acquisitions?

**Comment by hzhou** [comment]
I tested on a local linux and it seems working for both shared lock and exclusive lock

**Comment by hzhou** [comment]
The man page on the system call https://linux.die.net/man/2/flock doesn't mention about opening the file for read or write. Perl do the direct system calls on linux or systems that have the flock system call, but it will do emulation on windows. So the man page on Perl could be stricter as it need account for behavior on all systems.

**Comment by raffenet** [comment]
OK I think that's good enough for the systems we test on.

**Pull request merged**
