### PR TITLE
hcoll: Remove the use of attributes

### PR DESCRIPTION
**Pull request by raffenet**
The use of attributes in hcoll is redundant, since the only
information we store (hcoll_context), is also stored in the private
area of the communicator struct. This fixes a memory leak for
attributes and keyvals that were not properly freed.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/mxm
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
@janjust can you verify this branch works as expected in your testing? As far as I can tell, the attributes and extended communicator struct are accomplishing the same thing. Since we prefer the extended struct method, I just deleted the code related to attributes.

**Comment by janjust** [comment]
will do

**Comment by janjust** [comment]
@raffenet I tested over some internal tests and I do not see any crashes; I do see the following when the application finalizes.

```
In direct memory block for handle type GROUP, 2 handles are still allocated
[0] 768 at [0x0000000002828c10], src/mpi/group/grouputil.c[80]
[0] 768 at [0x00000000028281a0], src/mpi/group/grouputil.c[80]
```

**Comment by raffenet** [comment]
Hmm, that is odd. Can you verify the leak warning goes away without the new commit?

**Comment by janjust** [comment]
I still see it, even with with master (hcoll is off).

```
tomislavj@hpchead /hpc/mtr_scrap/users/tomislavj/workspace/mpich$  git log --oneline -n 5
1105dc9 test/mpi: Update bcast coll algo tests
94d5124 test/mpi: Change configure option name for coll algo testing
d810cb0 test/dtpools: Fix autoconf to allow separated autotools
7036f69 ch4: Expose MPIDI_Progress_test to CH4
51ed7f1 configure: Add configure option for izem queues
```

**Comment by janjust** [comment]
It's the[ intel imb](https://software.intel.com/en-us/articles/intel-mpi-benchmarks) benchmarks that use for smoke-testing. I have mine compiled with data checks.

This particular test is running just the barrier test.

**Pull request merged**
