### PR TITLE
ch4/shm: Simplify glue layer

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Remove no longer relevant function table infrastructure. Eliminate an unnecessary namespace indirection.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
If we ever want to add a different (incompatible) shmmod, e.g. PIP, will we adding these infrastructure back again?

Since the shmmod infrastructure is nearly identical to netmod, I think keeping them actually maintains certain symmetry, and does not necessarily add complexity. What I am rather looking for is to have script generate these boilerplate instead of manually editing them.

**Comment by raffenet** [comment]
I am under the impression that the glue layer will not be replaced. Instead, new shmmods will need to be integrated into it in order to be used. This is the asymmetry between nm/shm that exists today.

**Comment by pavanbalaji** [comment]
@raffenet   What's the status of this PR?  It looks like it was approved, but never merged.

**Comment by raffenet** [comment]
It was approved by Wesley, but there was not consensus within ANL. I can update it if folks agree. IMO the glue layer does *not* need function pointer infrastructure.

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
@wesbland re-requesting review in case this will cause painful conflict resolution.

**Comment by raffenet** [comment]
Gotta love a PR that nets a negative 3000 lines of code 😄 .

**Comment by hzhou** [comment]
> Gotta love a PR that nets a negative 3000 lines of code 😄 .

Hehe, here is another one https://github.com/pmodels/mpich/pull/4510

**Pull request merged**
