### PR TITLE
Pr/3.2.x prep

### PR DESCRIPTION
**Pull request by pavanbalaji**

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/all

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/all

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/all

**Comment by raffenet** [comment]
Added fix for Solaris strict builds.
test:jenkins/ch3/all

**Comment by raffenet** [comment]
Another Solaris strict related commit.
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
Build and ROMIO issues are resolved in current version. Test the rest of ch3 configurations. test:jenkins/ch3/all

**Comment by raffenet** [comment]
Some additional fixes for ch3:ofi, including one that affects all ch3 channels. test:jenkins/ch3/all

**Comment by raffenet** [comment]
@pavanbalaji all ch3 review tests are green with the current PR branch.

**Pull request merged**
