### PR TITLE
pm: increase PMI max length to 4096

### LINKED ISSUE #6810: Feature request: Dynamic processes management with gforker + ch4:ucx
As discussed in https://github.com/pmodels/mpich/issues/6797#issuecomment-1824988107, dynamic process management do work with gforker and ch4:ofi. For the sake of completeness, it would be nice to extend such support for gforker with ch4:ucx.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
This allows gforker and remshell to handle longer pmi commands and commodate longer kvs values. This is needed to handle larger port names such as the case for ch4:ucx.

Fixes #6810
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/pm

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/custom --with-pm=gforker
netmod: ch4:ucx

**Comment by hzhou** [comment]
test:mpich/custom --with-pm=gforker
netmod: ch4:ucx

**Review by raffenet — APPROVED** [review]

**Pull request merged**
