### PR TITLE
ch4: Eliminate use of uint64_t for request pointers

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Fix lots of warnings on 32-bit builds.

## Expected Performance Changes

none

## Known Issues

32-bit ch4 builds are still broken. This is just one issue that needs fixing.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Passes tests (included warning check)
* [x] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [x] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by hajimefu** [comment]
@hzhou In MPIDIG code, sometimes an origin sends a raw pointer value over the network, and the peer sends it back later, and the origin retrieves a request object from that pointer value (by simply casting `uint64_t` to `MPIR_Request *`).

In that sense I think `uintptr_t` is the right type, but I wouldn't bother too much.

**Comment by hzhou** [comment]
I see. Will it be a concern in a heterogeneous settings, then?

One possible solution could be a union type: `union { MPIR_Request * req, char dummy[64] }`. Any take?

**Comment by hajimefu** [comment]
Definitely it wouldn't work in a heterogeneous environment but if I understand correctly MPICH gave up heterogeneous configuration long time ago, if not from the beginning, didn't it?

**Comment by raffenet** [comment]
Heterogeneous is definitely not supported at this time. One thing that occurs to me, though, is that ch3 uses request handles in pkt headers, as opposed to pointers. This would also fix the hetero issue if we ever decide to add it back.

**Comment by hajimefu** [comment]
Yeah handle seems to be a better way. It would add a few extra instructions on each path, but hopefully these instructions are not too heavy (a few mask and shift operations).

**Pull request merged**
