### PR TITLE
Standardize Line Endings

### PR DESCRIPTION
**Pull request by wesbland**
Add a `.gitattributes` file to ensure that no one accidentally commits the wrong types of line endings. There are downstream vendors that work with Windows and we want to avoid accidentally committing Windows line endings here.

Also fix existing bad line endings in a file in ROMIO.

This uses https://help.github.com/articles/dealing-with-line-endings/#platform-all as a starting point and includes a recommendation that people use this to help solve this problem locally as well.

```
$ git config --global core.autocrlf input
# Configure Git on OS X or Linux to properly handle line endings

$ git config --global core.autocrlf true
# Configure Git on Windows to properly handle line endings
```

### CODE REVIEW

**Comment by wesbland** [comment]
cc @ddurnov

**Comment by raffenet** [comment]
@wesbland will the code cleanup patch fix this, or is it still needed?

**Comment by wesbland** [comment]
This is separate and still needed. This is to help people who develop on Windows avoid messing up line endings in the future. I don’t think gnu indent helps with that.

**Comment by raffenet** [comment]
Looks fine. Let me just get a sanity check before merge.
test:jenkins/ch3/tcp

**Pull request merged**
