### PR TITLE
coll: add two high radix algorithms to MPI_Barrier

### PR DESCRIPTION
**Pull request by zhenggb72**
add two blocking barrier high radix algorithm:

1. high radix dissemination algorithm
2. simply calling MPI_Allreduce recursive exchange algorithm

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by zhenggb72** [comment]
test:mpich/ch4/ofi

**Comment by yfguo** [comment]
test:mpich/ch4/most

**Comment by yfguo** [comment]
@zhenggb72 I am wondering if the k-dissemination should be integrated with the existing dissemination algorithm (basically k==1).

**Comment by zhenggb72** [comment]
> @zhenggb72 I am wondering if the k-dissemination should be integrated with the existing dissemination algorithm (basically k==1).

add one commit to merge the dissemination to k-dissemination.

**Comment by zhenggb72** [comment]
test:mpich/ch4/most

**Comment by zhenggb72** [comment]
test:mpich/ch4/most

**Review by yfguo — APPROVED** [review]
LGTM.

**Comment by yfguo** [comment]
test:mpich/ch4/most

**Pull request merged**
