### PR TITLE
ch4/ofi: Update submodule to v1.8.0

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Update submodule to v1.8.0.

## Expected Performance Changes

n/a

## Known Issues

none

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Passes tests (included warning check)
* [x] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [x] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:mpich/warnings

**Comment by raffenet** [comment]
@hajimefu @wesbland any issue with updating? I'm assuming you folks have done this long ago, tbh...

**Comment by wesbland** [comment]
> @hajimefu @wesbland any issue with updating? I'm assuming you folks have done this long ago, tbh...

Honestly, we hadn't gotten to that one yet. Let me run this on the internal build and get back to you.

**Comment by raffenet** [comment]
test:mpich/warnings

**Comment by wesbland** [comment]
I think this was fine on our end. 👍 

I haven't checked to see if any of the capability sets need to change (if any of the providers have different features that might change the performance).

**Comment by raffenet** [comment]
Re-based to include some warning fixes.
test:mpich/warnings

**Pull request merged**
