### PR TITLE
modules: Update libfabric

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Include https://github.com/ofiwg/libfabric/pull/10223. Fixes verbs provider compilation on FreeBSD systems.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/submodules

**Comment by hzhou** [comment]
So now `verbs` works on FreeBSD?

**Comment by raffenet** [comment]
> So now `verbs` works on FreeBSD?

Yes, it can successfully build 😄. I haven't yet run the testsuite. Maybe a custom job string can try it?

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
label: freebsd

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
label: freebsd64
env: FI_PROVIDER=verbs

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
label: freebsd64
netmod: ch4:ofi
env: FI_PROVIDER=verbs

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
label: freebsd64
netmod: ch4:ofi

**Comment by raffenet** [comment]
> test:mpich/custom/pipeline label: freebsd64 netmod: ch4:ofi env: FI_PROVIDER=verbs
> 
> Looks like we don't have Infiniband on freebsd or it didn't find it.

Yeah, `ibstat` reports this:
```
pmrs-freebsd64-240-02% ibstat
ibwarn: [22440] umad_init: can't read ABI version from sys.class.infiniband_mad.abi_version (No such file or directory): is ibcore module loaded?
ibpanic: [22440] main: can't init UMAD library: No such file or directory
```

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
label: freebsd64
netmod: ch4:ofi

**Pull request merged**
