### PR TITLE
groups: Improve error return of MPI Group routines in combination with MPI Sessions

### PR DESCRIPTION
**Pull request by sonjahapp**
**Remark:** This PR is based on https://github.com/pmodels/mpich/pull/6578 (Session reference counting). Only the last three commits add additional content. To avoid confusion, https://github.com/pmodels/mpich/pull/6578 should be reviewed and merged first, before we continue with this PR.

## Pull Request Description

For a better error reporting of MPI Group routines in the context of MPI Sessions, this PR enables MPI  Group routines that operate on one group, to use the error handler provided to the MPI Session to which they belong (if any). If we are in the world model and the group does not belong to any session, the error return is done as before.

The routine `MPI_Comm_create_from_group` is a somewhat special case in this regard as it has an error handler as parameter. This PR adds an error return function just for this case so that the provided error handler is used (if any).
The PR adds a new test for the error return behaviour of `MPI_Comm_create_from_group`.

The error return of MPI group routines that operate on multiple groups (e.g. `MPI_Group_compare`) is not touched by this PR. It is unclear whether or not MPI Groups that originate from different MPI Sessions can be combined in such operations and which error handler should be used. The MPI standard should provide some clarity here first.

## Author Checklist
* [X] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [X] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [X] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Review by hzhou — APPROVED** [review]
LGTM

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

**Comment by sonjahapp** [comment]
Rebased on main incl #6578.

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

**Pull request merged**
