### PR TITLE
Common dispatch

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/all

**Comment by raffenet** [comment]
cc: @charlesarcher @ddurnov

**Comment by raffenet** [comment]
The commits in this branch now are a rough draft of where I am heading regarding:

1. Moving AM handler arrays out of the transport layer
2. Putting "generic" code+globals into a separate component in `src/mpid/ch4/common`.
3. (just for the heck of it) Outlining non-"hot path" code as it's defined in the new MPIDIG component.

Also cc: @pavanbalaji for feedback.

**Comment by raffenet** [comment]
Rebased and squashed to single commit.

test:jenkins/ch4/all

**Comment by raffenet** [comment]
Rebased again...

test:jenkins/ch4/all

**Comment by pavanbalaji** [comment]
This looks good to me.  👍

**Comment by raffenet** [comment]
I extracted out some of the CH4U global variables from this commit since it was incomplete and a remnant of a commit chain that was eventually squashed. Testing one more time then will merge if results are normal.

test:jenkins/ch4/all

**Comment by raffenet** [comment]
Found a few more conflicts. Hopefully this test run is clean...

test:jenkins/ch4/all

**Pull request merged**
