### PR TITLE
mpir: Move function declaration across files

### PR DESCRIPTION
**Pull request by akhillanger**
This is a simple pull request. Since request function implementations moved to its own request folder, move these function declarations also to the appropriate file. Tagging @raffenet for review.

### CODE REVIEW

**Comment by akhillanger** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
Do we want to prefix this patch with `mpir` to make it clear at a glance?

**Comment by akhillanger** [comment]
@wesbland Done. It was passing all the tests, so I will not run the tests again as I just changed the commit msg.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Pull request merged**
