### PR TITLE
test/mpi: Remove logical floating point reductions

### PR DESCRIPTION
**Pull request by raffenet**
Support of these operations is non-standard. We removed support for
them in [d81fc87980ed]. Clean up the test cases to avoid any failures.

### CODE REVIEW

**Comment by hzhou** [comment]
@raffenet It is pure deletion, so not much code to review :)  

However, this is some change on behavior, we definitely need keep an entry in change log. Should we add an entry in CHANGES with this commit?

**Comment by raffenet** [comment]
Yes, I suppose that's a good idea. I'll add some text and push it to this branch.

**Comment by hzhou** [comment]
This PR is good to go.

@raffenet You can add my sign-off at commit. I need do this (the sign-off and commit thing) with you a few times to get comfortable.

**Comment by raffenet** [comment]
K, sounds good. Thanks for quick turnaround.

**Pull request merged**
