### PR TITLE
Ipc shmmod coop copy

### PR DESCRIPTION
**Pull request by gcongiu**
## Pull Request Description

The PR is the base for coop copy protocol integration into IPC shmmod. It is based on PR https://github.com/pmodels/mpich/pull/4527 that introduced the IPC shmmod using XPMEM as base infrastructure. Such PR simplified the data movement protocols by getting rid of the coop copy, which this PR's goal is to reintroduce.
 

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by gcongiu** [comment]
@minsii

**Comment by wesbland** [comment]
@minsii - Are you taking over this now?

**Comment by raffenet** [comment]
@KaimingOuyang @minsii is it worth keeping this open, or can we close it?

**Comment by minsii** [comment]
I think there are some dependencies with Yanfei' genq work. @KaimingOuyang  can you please confirm? 

We can close the PR for now and reopen it when it is ready for review.

**Comment by KaimingOuyang** [comment]
This IPC non-contig p2p PR https://github.com/pmodels/mpich/pull/4696 depends on GenQ. I think we can close this coop-copy PR and reopen it when we start to work on it.

**Pull request closed without merging**
