### PR TITLE
ch4/ucx: Add native partitioned communication over pt2pt

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Provide an initial implementation of partitioned communication over tagged
send/recv interfaces. This is mostly a port of the generic implementation,
including active message-based handshake. Data is sent all at once when all
partitions are marked as ready. Future work will investigate more fine-grained
data transfer methods.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by hzhou** [comment]
So far so good. However, I don't think we have to merge it at this point since it adds no real improvement over the generic path yet, and it poses no conflicts to any other work.

The eventual design has to include some scheme of partitioned send and recv. I think we should at least try some basic implementation of the partitioned schemes in this PR. The control protocols probably will change once we add that partition scheme. So trying it within the PR gives you more flexibility. Once we had the basic scheme working, we'll have a better picture reviewing the PR.

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
Latest push sets up finer-grained partitioning, but still uses VCI 0 for all thread safety.

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
Getting performance out of the multi-vci code has proved difficult so far. I'm going to drop those patches for now so we can add in the version using UCX native pt2pt. Here's some data showing the benefits pretty much across the board. msgrate and bandwidth test provided by Sandia. Source is in https://github.com/pmodels/partSendBenchmark (private).

Setup: JLSE Thing Nodes, 2 nodes, 1ppn, GCC 7.5 w/ OpenMP
Test args: --minT=1 --maxT=8 --minB=32 --maxB=131072 --test=2 --tm --i=10000

### ch4 am:
```
[0] bufSize 32, numThreads 1, threadPart 8, time 0.032164, bandwidth 9.949 MB/s, msgRate 310911.070 msg/sec, 0.000004
[0] bufSize 32, numThreads 2, threadPart 4, time 0.033867, bandwidth 9.449 MB/s, msgRate 295270.147 msg/sec, 0.000003
[0] bufSize 32, numThreads 4, threadPart 2, time 0.100083, bandwidth 3.197 MB/s, msgRate 99917.070 msg/sec, 0.000010
[0] bufSize 32, numThreads 8, threadPart 1, time 0.100848, bandwidth 3.173 MB/s, msgRate 99159.561 msg/sec, 0.000010
[0] bufSize 64, numThreads 1, threadPart 16, time 0.031648, bandwidth 20.222 MB/s, msgRate 315972.818 msg/sec, 0.000003
[0] bufSize 64, numThreads 2, threadPart 8, time 0.032598, bandwidth 19.633 MB/s, msgRate 306771.135 msg/sec, 0.000003
[0] bufSize 64, numThreads 4, threadPart 4, time 0.074247, bandwidth 8.620 MB/s, msgRate 134686.164 msg/sec, 0.000007
[0] bufSize 64, numThreads 8, threadPart 2, time 0.104204, bandwidth 6.142 MB/s, msgRate 95965.208 msg/sec, 0.000010
[0] bufSize 128, numThreads 1, threadPart 32, time 0.032782, bandwidth 39.046 MB/s, msgRate 305046.038 msg/sec, 0.000003
[0] bufSize 128, numThreads 2, threadPart 16, time 0.034051, bandwidth 37.591 MB/s, msgRate 293678.589 msg/sec, 0.000003
[0] bufSize 128, numThreads 4, threadPart 8, time 0.073365, bandwidth 17.447 MB/s, msgRate 136303.945 msg/sec, 0.000007
[0] bufSize 128, numThreads 8, threadPart 4, time 0.101084, bandwidth 12.663 MB/s, msgRate 98927.232 msg/sec, 0.000010
[0] bufSize 256, numThreads 1, threadPart 64, time 0.032633, bandwidth 78.447 MB/s, msgRate 306434.737 msg/sec, 0.000003
[0] bufSize 256, numThreads 2, threadPart 32, time 0.033931, bandwidth 75.446 MB/s, msgRate 294712.133 msg/sec, 0.000003
[0] bufSize 256, numThreads 4, threadPart 16, time 0.075322, bandwidth 33.987 MB/s, msgRate 132762.994 msg/sec, 0.000008
[0] bufSize 256, numThreads 8, threadPart 8, time 0.101051, bandwidth 25.334 MB/s, msgRate 98959.752 msg/sec, 0.000010
[0] bufSize 512, numThreads 1, threadPart 128, time 0.034517, bandwidth 148.334 MB/s, msgRate 289715.606 msg/sec, 0.000003
[0] bufSize 512, numThreads 2, threadPart 64, time 0.035157, bandwidth 145.631 MB/s, msgRate 284436.483 msg/sec, 0.000004
[0] bufSize 512, numThreads 4, threadPart 32, time 0.073664, bandwidth 69.505 MB/s, msgRate 135752.191 msg/sec, 0.000007
[0] bufSize 512, numThreads 8, threadPart 16, time 0.106897, bandwidth 47.897 MB/s, msgRate 93548.131 msg/sec, 0.000011
[0] bufSize 1024, numThreads 1, threadPart 256, time 0.037523, bandwidth 272.903 MB/s, msgRate 266506.457 msg/sec, 0.000004
[0] bufSize 1024, numThreads 2, threadPart 128, time 0.038502, bandwidth 265.960 MB/s, msgRate 259726.410 msg/sec, 0.000004
[0] bufSize 1024, numThreads 4, threadPart 64, time 0.072671, bandwidth 140.909 MB/s, msgRate 137606.630 msg/sec, 0.000007
[0] bufSize 1024, numThreads 8, threadPart 32, time 0.102871, bandwidth 99.543 MB/s, msgRate 97209.573 msg/sec, 0.000010
[0] bufSize 2048, numThreads 1, threadPart 512, time 0.041842, bandwidth 489.462 MB/s, msgRate 238995.277 msg/sec, 0.000004
[0] bufSize 2048, numThreads 2, threadPart 256, time 0.043134, bandwidth 474.802 MB/s, msgRate 231836.868 msg/sec, 0.000004
[0] bufSize 2048, numThreads 4, threadPart 128, time 0.068661, bandwidth 298.276 MB/s, msgRate 145642.343 msg/sec, 0.000007
[0] bufSize 2048, numThreads 8, threadPart 64, time 0.104578, bandwidth 195.834 MB/s, msgRate 95622.238 msg/sec, 0.000010
[0] bufSize 4096, numThreads 1, threadPart 1024, time 0.050421, bandwidth 812.355 MB/s, msgRate 198328.806 msg/sec, 0.000005
[0] bufSize 4096, numThreads 2, threadPart 512, time 0.051612, bandwidth 793.614 MB/s, msgRate 193753.451 msg/sec, 0.000005
[0] bufSize 4096, numThreads 4, threadPart 256, time 0.084662, bandwidth 483.805 MB/s, msgRate 118116.462 msg/sec, 0.000008
[0] bufSize 4096, numThreads 8, threadPart 128, time 0.106193, bandwidth 385.712 MB/s, msgRate 94167.858 msg/sec, 0.000011
[0] bufSize 8192, numThreads 1, threadPart 2048, time 0.064974, bandwidth 1260.813 MB/s, msgRate 153907.852 msg/sec, 0.000006
[0] bufSize 8192, numThreads 2, threadPart 1024, time 0.066944, bandwidth 1223.714 MB/s, msgRate 149379.121 msg/sec, 0.000007
[0] bufSize 8192, numThreads 4, threadPart 512, time 0.098489, bandwidth 831.770 MB/s, msgRate 101534.375 msg/sec, 0.000010
[0] bufSize 8192, numThreads 8, threadPart 256, time 0.130638, bandwidth 627.079 MB/s, msgRate 76547.691 msg/sec, 0.000013
[0] bufSize 16384, numThreads 1, threadPart 4096, time 0.097529, bandwidth 1679.914 MB/s, msgRate 102533.788 msg/sec, 0.000010
[0] bufSize 16384, numThreads 2, threadPart 2048, time 0.097895, bandwidth 1673.626 MB/s, msgRate 102150.020 msg/sec, 0.000010
[0] bufSize 16384, numThreads 4, threadPart 1024, time 0.113113, bandwidth 1448.462 MB/s, msgRate 88407.121 msg/sec, 0.000011
[0] bufSize 16384, numThreads 8, threadPart 512, time 0.142937, bandwidth 1146.236 MB/s, msgRate 69960.715 msg/sec, 0.000014
[0] bufSize 32768, numThreads 1, threadPart 8192, time 0.145447, bandwidth 2252.920 MB/s, msgRate 68753.663 msg/sec, 0.000015
[0] bufSize 32768, numThreads 2, threadPart 4096, time 0.146825, bandwidth 2231.779 MB/s, msgRate 68108.486 msg/sec, 0.000015
[0] bufSize 32768, numThreads 4, threadPart 2048, time 0.155177, bandwidth 2111.650 MB/s, msgRate 64442.430 msg/sec, 0.000016
[0] bufSize 32768, numThreads 8, threadPart 1024, time 0.167252, bandwidth 1959.195 MB/s, msgRate 59789.879 msg/sec, 0.000017
[0] bufSize 65536, numThreads 1, threadPart 16384, time 0.250112, bandwidth 2620.267 MB/s, msgRate 39982.108 msg/sec, 0.000025
[0] bufSize 65536, numThreads 2, threadPart 8192, time 0.259280, bandwidth 2527.613 MB/s, msgRate 38568.307 msg/sec, 0.000026
[0] bufSize 65536, numThreads 4, threadPart 4096, time 0.265072, bandwidth 2472.385 MB/s, msgRate 37725.606 msg/sec, 0.000027
[0] bufSize 65536, numThreads 8, threadPart 2048, time 0.277779, bandwidth 2359.289 MB/s, msgRate 35999.895 msg/sec, 0.000028
[0] bufSize 131072, numThreads 1, threadPart 32768, time 0.520111, bandwidth 2520.077 MB/s, msgRate 19226.665 msg/sec, 0.000052
[0] bufSize 131072, numThreads 2, threadPart 16384, time 0.521838, bandwidth 2511.739 MB/s, msgRate 19163.048 msg/sec, 0.000052
[0] bufSize 131072, numThreads 4, threadPart 8192, time 0.530151, bandwidth 2472.352 MB/s, msgRate 18862.549 msg/sec, 0.000053
[0] bufSize 131072, numThreads 8, threadPart 4096, time 0.544320, bandwidth 2407.995 MB/s, msgRate 18371.544 msg/sec, 0.000054
```

### ch4/ucx:
```
[0] bufSize 32, numThreads 1, threadPart 8, time 0.004002, bandwidth 79.964 MB/s, msgRate 2498890.492 msg/sec, 0.000001
[0] bufSize 32, numThreads 2, threadPart 4, time 0.026978, bandwidth 11.862 MB/s, msgRate 370674.900 msg/sec, 0.000006
[0] bufSize 32, numThreads 4, threadPart 2, time 0.064835, bandwidth 4.936 MB/s, msgRate 154236.907 msg/sec, 0.000014
[0] bufSize 32, numThreads 8, threadPart 1, time 0.092570, bandwidth 3.457 MB/s, msgRate 108026.840 msg/sec, 0.000019
[0] bufSize 64, numThreads 1, threadPart 16, time 0.005093, bandwidth 125.668 MB/s, msgRate 1963568.731 msg/sec, 0.000001
[0] bufSize 64, numThreads 2, threadPart 8, time 0.028648, bandwidth 22.340 MB/s, msgRate 349066.335 msg/sec, 0.000006
[0] bufSize 64, numThreads 4, threadPart 4, time 0.056620, bandwidth 11.303 MB/s, msgRate 176616.436 msg/sec, 0.000011
[0] bufSize 64, numThreads 8, threadPart 2, time 0.089704, bandwidth 7.135 MB/s, msgRate 111477.409 msg/sec, 0.000018
[0] bufSize 128, numThreads 1, threadPart 32, time 0.005664, bandwidth 226.007 MB/s, msgRate 1765678.563 msg/sec, 0.000001
[0] bufSize 128, numThreads 2, threadPart 16, time 0.031267, bandwidth 40.937 MB/s, msgRate 319823.560 msg/sec, 0.000006
[0] bufSize 128, numThreads 4, threadPart 8, time 0.059074, bandwidth 21.668 MB/s, msgRate 169279.785 msg/sec, 0.000012
[0] bufSize 128, numThreads 8, threadPart 4, time 0.093760, bandwidth 13.652 MB/s, msgRate 106655.321 msg/sec, 0.000018
[0] bufSize 256, numThreads 1, threadPart 64, time 0.005723, bandwidth 447.319 MB/s, msgRate 1747341.725 msg/sec, 0.000002
[0] bufSize 256, numThreads 2, threadPart 32, time 0.038890, bandwidth 65.827 MB/s, msgRate 257138.545 msg/sec, 0.000008
[0] bufSize 256, numThreads 4, threadPart 16, time 0.060855, bandwidth 42.067 MB/s, msgRate 164325.391 msg/sec, 0.000012
[0] bufSize 256, numThreads 8, threadPart 8, time 0.098281, bandwidth 26.048 MB/s, msgRate 101748.602 msg/sec, 0.000020
[0] bufSize 512, numThreads 1, threadPart 128, time 0.005978, bandwidth 856.505 MB/s, msgRate 1672860.712 msg/sec, 0.000001
[0] bufSize 512, numThreads 2, threadPart 64, time 0.036733, bandwidth 139.385 MB/s, msgRate 272236.495 msg/sec, 0.000008
[0] bufSize 512, numThreads 4, threadPart 32, time 0.061953, bandwidth 82.643 MB/s, msgRate 161412.363 msg/sec, 0.000012
[0] bufSize 512, numThreads 8, threadPart 16, time 0.099359, bandwidth 51.530 MB/s, msgRate 100645.038 msg/sec, 0.000020
[0] bufSize 1024, numThreads 1, threadPart 256, time 0.007194, bandwidth 1423.359 MB/s, msgRate 1389998.957 msg/sec, 0.000001
[0] bufSize 1024, numThreads 2, threadPart 128, time 0.057565, bandwidth 177.885 MB/s, msgRate 173715.880 msg/sec, 0.000011
[0] bufSize 1024, numThreads 4, threadPart 64, time 0.061232, bandwidth 167.232 MB/s, msgRate 163312.983 msg/sec, 0.000012
[0] bufSize 1024, numThreads 8, threadPart 32, time 0.100480, bandwidth 101.910 MB/s, msgRate 99521.820 msg/sec, 0.000020
[0] bufSize 2048, numThreads 1, threadPart 512, time 0.008287, bandwidth 2471.238 MB/s, msgRate 1206659.069 msg/sec, 0.000002
[0] bufSize 2048, numThreads 2, threadPart 256, time 0.043875, bandwidth 466.777 MB/s, msgRate 227918.436 msg/sec, 0.000008
[0] bufSize 2048, numThreads 4, threadPart 128, time 0.061861, bandwidth 331.066 MB/s, msgRate 161653.535 msg/sec, 0.000012
[0] bufSize 2048, numThreads 8, threadPart 64, time 0.100089, bandwidth 204.618 MB/s, msgRate 99911.175 msg/sec, 0.000020
[0] bufSize 4096, numThreads 1, threadPart 1024, time 0.034887, bandwidth 1174.061 MB/s, msgRate 286635.902 msg/sec, 0.000007
[0] bufSize 4096, numThreads 2, threadPart 512, time 0.060252, bandwidth 679.814 MB/s, msgRate 165970.319 msg/sec, 0.000012
[0] bufSize 4096, numThreads 4, threadPart 256, time 0.075060, bandwidth 545.695 MB/s, msgRate 133226.237 msg/sec, 0.000015
[0] bufSize 4096, numThreads 8, threadPart 128, time 0.111820, bandwidth 366.304 MB/s, msgRate 89429.766 msg/sec, 0.000022
[0] bufSize 8192, numThreads 1, threadPart 2048, time 0.043153, bandwidth 1898.366 MB/s, msgRate 231734.190 msg/sec, 0.000008
[0] bufSize 8192, numThreads 2, threadPart 1024, time 0.049082, bandwidth 1669.051 MB/s, msgRate 203741.517 msg/sec, 0.000010
[0] bufSize 8192, numThreads 4, threadPart 512, time 0.070924, bandwidth 1155.032 MB/s, msgRate 140995.059 msg/sec, 0.000014
[0] bufSize 8192, numThreads 8, threadPart 256, time 0.107966, bandwidth 758.756 MB/s, msgRate 92621.554 msg/sec, 0.000021
[0] bufSize 16384, numThreads 1, threadPart 4096, time 0.057612, bandwidth 2843.856 MB/s, msgRate 173575.167 msg/sec, 0.000012
[0] bufSize 16384, numThreads 2, threadPart 2048, time 0.061551, bandwidth 2661.878 MB/s, msgRate 162468.125 msg/sec, 0.000012
[0] bufSize 16384, numThreads 4, threadPart 1024, time 0.084236, bandwidth 1945.023 MB/s, msgRate 118714.770 msg/sec, 0.000017
[0] bufSize 16384, numThreads 8, threadPart 512, time 0.120578, bandwidth 1358.788 MB/s, msgRate 82933.851 msg/sec, 0.000024
[0] bufSize 32768, numThreads 1, threadPart 8192, time 0.078066, bandwidth 4197.498 MB/s, msgRate 128097.482 msg/sec, 0.000016
[0] bufSize 32768, numThreads 2, threadPart 4096, time 0.084875, bandwidth 3860.758 MB/s, msgRate 117820.992 msg/sec, 0.000017
[0] bufSize 32768, numThreads 4, threadPart 2048, time 0.108288, bandwidth 3025.998 MB/s, msgRate 92346.138 msg/sec, 0.000021
[0] bufSize 32768, numThreads 8, threadPart 1024, time 0.146347, bandwidth 2239.068 MB/s, msgRate 68330.944 msg/sec, 0.000029
[0] bufSize 65536, numThreads 1, threadPart 16384, time 0.137708, bandwidth 4759.065 MB/s, msgRate 72617.571 msg/sec, 0.000028
[0] bufSize 65536, numThreads 2, threadPart 8192, time 0.158764, bandwidth 4127.900 MB/s, msgRate 62986.758 msg/sec, 0.000032
[0] bufSize 65536, numThreads 4, threadPart 4096, time 0.186472, bandwidth 3514.520 MB/s, msgRate 53627.319 msg/sec, 0.000036
[0] bufSize 65536, numThreads 8, threadPart 2048, time 0.212953, bandwidth 3077.487 MB/s, msgRate 46958.721 msg/sec, 0.000043
[0] bufSize 131072, numThreads 1, threadPart 32768, time 0.235831, bandwidth 5557.875 MB/s, msgRate 42403.221 msg/sec, 0.000047
[0] bufSize 131072, numThreads 2, threadPart 16384, time 0.241710, bandwidth 5422.704 MB/s, msgRate 41371.951 msg/sec, 0.000048
[0] bufSize 131072, numThreads 4, threadPart 8192, time 0.281167, bandwidth 4661.710 MB/s, msgRate 35566.025 msg/sec, 0.000055
[0] bufSize 131072, numThreads 8, threadPart 4096, time 0.305565, bandwidth 4289.499 MB/s, msgRate 32726.280 msg/sec, 0.000061
```

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
Here's a visual of the bandwidth performance. The benefits are clear for larger messages. Perhaps we should add a threshold. part-bw

**Comment by raffenet** [comment]
I just realized I haven't added the `parts + 1` ready counter implementation (from #5504) to the ucx code in this branch. It should help avoid some lock contention. Will add and post more data.

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
bandwidth with latest branch
part-bw

**Comment by raffenet** [comment]
Closing this. It may be revived at a later date, but is not being actively looked at.

**Pull request closed without merging**
