### PR TITLE
dbg: Update comment with correct configure option

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Fixes pmodels/mpich#4128.

## Expected Impact

Readers of the comment will know the correct configure option, otherwise none.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
I saw your issue comment. Do you want to add a commit to refactor `MPII_wait_for_debugger` away and use `MPII_Wait_for_debugger` directly? I would prefer move the `#ifdef` into `MPII_Wait_for_debugger` as the `#ifdef-`macro is only meaningful within the debugger code context.

**Comment by raffenet** [comment]
Sure, I'll review if you want to add it.

**Comment by hzhou** [comment]
> Sure, I'll review if you want to add it.

OK.

**Comment by hzhou** [comment]
@raffenet I pushed a commit to simplify `MPII_wait_for_debugger` and `MPII_debugger_set_abort`.

**Comment by hzhou** [comment]
test:jenkins/custom

**Comment by hzhou** [comment]
@raffenet I merged this PR so tonight's nightly tests will get triggered.

**Pull request merged**
