### PR TITLE
CXI Optimized Memory Regions

### PR DESCRIPTION
**Pull request by wesbland**
## Pull Request Description

Optimized memory regions are a feature of the CXI provider that provide better performance at the cost of some ordering restrictions. A MR is optimized if it gets an `mr_key < MPIDI_OFI_NUM_OPTIMIZED_MEMORY_REGIONS`. These memory regions have relaxed restrictions around ordering that require the user to opt-in to using them by setting the window info hint `optimized_mr` and no accumulate ordering.

Because RMA support is still not working in CXI in the https://github.com/pmodels/mpich/pull/5708 PR, this capability is still turned off, but the code to use it is provided here to enable collaboration.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by wesbland** [comment]
Obviously this PR includes all of the patches in https://github.com/pmodels/mpich/pull/5708 for now. Once that PR is merged, this will need to be rebased again. The review should only cover the last two patches.

**Comment by wesbland** [comment]
test:mpich/ch4/ofi

**Review by hzhou — APPROVED** [review]
LGTM

**Comment by hzhou** [comment]
@wesbland The test in this PR breaks `ch3` testing. I am not sure what will be a good fix. Maybe we should split the experimental hints into a separate test and move into `impls/mpich`?

**Comment by wesbland** [comment]
Hmmm... good point. I forgot to test this with CH3. Do/could we have any sort of `#define` in `mpi.h` to say which device we're using? Something like `#define MPICH_ADI ch4/ofi` or something? Then we could put these sorts of checks in an `#if` guard.

**Comment by hzhou** [comment]
> Hmmm... good point. I forgot to test this with CH3. Do/could we have any sort of `#define` in `mpi.h` to say which device we're using? Something like `#define MPICH_ADI ch4/ofi` or something? Then we could put these sorts of checks in an `#if` guard.

It's a burden to expose ch3/ch4 internals. Is it so much trouble to just enable the hint in ch3 as well? We can always set it to false there. MPICH-specific feature is fine, we can test it in `impls/mpich`.

**Comment by wesbland** [comment]
Putting it in CH3 is no issue. I can do that too.

**Comment by hzhou** [comment]
@wesbland Is there a reason that we do not enable `optimized_mr` by default?

**Comment by wesbland** [comment]
At the moment, MPICH still has an issue with RMA with the CXI provider. Once that's fixed, we'll be able to test this code a little better and should turn it on.

**Comment by hzhou** [comment]
> At the moment, MPICH still has an issue with RMA with the CXI provider. Once that's fixed, we'll be able to test this code a little better and should turn it on.

My question is why we need this info hint at all since we internally decide whether to enable it anyway. In another word, is it important for user to be able to set info hint of `optimized_mr=false`?

**Comment by wesbland** [comment]
Yes. At least for the CXI provider, optimized MRs can only be used if the user relaxes some requirements around atomics.

**Comment by hzhou** [comment]
> Yes. At least for the CXI provider, optimized MRs can only be used if the user relaxes some requirements around atomics.

Relaxing atomic ordering? So the correct hint would be `atomic_ordering`?

**Pull request merged**
