### PR TITLE
ch4: generic init cleanup

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Cleanup some init/finalize mess related to the generic infrastructure and builtin comms.

## Expected Performance Changes

none

## Known Issues

none

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Passes tests (included warning check)
* [x] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [x] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
The 2 "move up a layer" commits could probably be squashed as they are logically the same change, assuming they are accepted.

**Comment by raffenet** [comment]
@sagarth does this PR fix the issue you were seeing?

**Comment by sagarth** [comment]
@raffenet yes it fixes the issue. Tests are passing with these patches.

**Comment by raffenet** [comment]
@yfguo I think you are tackling a similar area in #4040. How to you want to handle these 2 PRs?

**Comment by hzhou** [comment]
@yfguo I also have a quick patch #4039, so would you want to handle these 3 PRs? :)

**Comment by raffenet** [comment]
@yfguo I would like to merge this to fix a known bug. Do you think you can rebase your changes on it?

**Pull request merged**
