### PR TITLE
coll: refactor allreduce tree types

### PR DESCRIPTION
**Pull request by zhenggb72**
Each tree type, for example, kary, knomial, had different
algorithms to their name - tree_kary, tree_knomial, respectively.
This is not very scalable as we add more tree types. This commit
adds a single function to select tree algorithm and then the tree
type can be selected through a CVAR - MPIR_CVAR_IALLREDUCE_TREE_TYPE.
With this change, as we add more tree types, we do not have to
add new functions to the code to call that tree_type algorithm.
Tree type can be selected just through the CVAR.

This is similar to the changes that were done to Bcast/Reduce previously.

### CODE REVIEW

**Comment by wesbland** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by zhenggb72** [comment]
not sure why gather_big test timeout. But this patch only changes allreduce tree CVARs.

**Comment by zhenggb72** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by zhenggb72** [comment]
Not sure about the failures. This code basically is just to restructure the way tree environment is setting. it should not affect the tests.

**Comment by hzhou** [comment]
@zhenggb72 The same argument can be made toward different transport as we try/add new transport type. I don't think our interest is to host a garden of algorithms for completeness. I think as we add tree types, not all algorithms will win and we shall consider pruning losers as we adding new ones. Therefore, I don't think it will be a real situation that we host every possible combination of algorithms, so a single level algorithm cvars seems more appropriate.

PS: in another perspective, we select/tune algorithms by comm size and message size, that only arises a handful choices anyway.

**Comment by zhenggb72** [comment]
I don't entirely agree. I agree eventually it may come down to a few good algorithms for a PARTICULAR machine. And at this point, we don't know what are those for A21. Therefore, at this point, we do need to maintain all algorithms which potentially give advantage for certain configurations. The auto algorithm selection will eventually boil down to a few algorithms, but the selection logic is different story. btw, the selection logic does not necessarily constraint to comm size and message size. It may also dynamically depending on available hardware resource for triggered op-based collective for example.

@wesbland

**Comment by zhenggb72** [comment]
don't entirely agree. I agree eventually it may come down to a few good algorithms for a PARTICULAR machine. But we don't know what those are for a target machine. Therefore, at this point, we do need to maintain all algorithms which potentially give advantage for certain configurations. The auto algorithm selection will eventually boil down to a few algorithms, but the selection logic is different story. btw, the selection logic does not necessarily constraint to comm size and message size. It may also dynamically depending on available hardware resource for some hardware-enabled collective algorithms. 

@wesbland

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/mxm

**Pull request merged**
