### PR TITLE
Random pool obj selection

### PR DESCRIPTION
**Pull request by gcongiu**

### CODE REVIEW

**Comment by gcongiu** [comment]
test:jenkins/ch3/tcp

**Comment by gcongiu** [comment]
test:jenkins/ch3/tcp

**Comment by pavanbalaji** [comment]
@gcongiu: This code seems to be overly complicated.  I don't understand why you have to change dtpools at all (apart from removing the min/max limits in the pool size).  Can't this be accomplished simply by having the tests do something like this:

```
for (i = 0; i < whatever_count; i++) {
   DTP_obj_create(target_dtp, rand() % pool_size, ...);
}
```

In this way DTPools itself does not need to know anything about how many objects the test will actually create.

**Comment by gcongiu** [comment]
@pavanbalaji how do we handle collisions in this way? I suppose we want to pick unique objects from the pool.

**Comment by pavanbalaji** [comment]
> @pavanbalaji how do we handle collisions in this way? I suppose we want to pick unique objects from the pool.

We are picking randomly so collisions can happen.  We can't avoid that.

**Pull request closed without merging**
