### PR TITLE
Initial draft of the SHM glue layer.

### PR DESCRIPTION
**Pull request by pavanbalaji**
This layer is the first point of entry to the shmmods.  It uses the
message information (e.g., message size) to decide on which shmmod to
use.

This commit comments out the glue layer since the shmmod namespacing
needs to be resolved before it can be enabled.

### CODE REVIEW

**Comment by charlesarcher** [comment]
👍

**Comment by pavanbalaji** [comment]
test:jenkins/ch4/all

**Comment by raffenet** [comment]
This is ready to merge, right? If so, I will do it and ping Dmitry to re-target his work.

**Comment by pavanbalaji** [comment]
Note that this patch disables the glue layer.  If you enable it, there'll be duplicate symbols since all of the POSIX symbols are also called `MPIDI_SHM_` now.  I think it's OK to merge, but needs more cleanup to rename the POSIX symbols.

**Comment by pavanbalaji** [comment]
test:jenkins/ch4/all

**Comment by pavanbalaji** [comment]
test:jenkins/ch4/ofi

Most of the glue functionality should be in now.  There's still some code refactoring to be done to make the glue layer more explicit, and to split the glue functionality into multiple files instead of one giant file.

**Comment by pavanbalaji** [comment]
test:jenkins/ch4/ofi

**Comment by pavanbalaji** [comment]
@raffenet or @ddurnov: this is ready for your review at this point

**Pull request merged**
