### PR TITLE
ch4/part: Additional cleanup

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Add a few more commits to cleanup the initialization workflow. Now the ch4 layer directly calls the generic init functions, then lower level hooks for optimization. Remove several `is_local` function parameters that are not needed.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Review by hzhou — APPROVED** [review]
The changes look good to me. Approved pending on clean tests.

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Pull request merged**
