### PR TITLE
coll: Warning cleanups

### PR DESCRIPTION
**Pull request by hajimefu**
This PR removes multiple compiler warnings, mainly around collectives.

Tagging @akhillanger for review.

### CODE REVIEW

**Comment by hajimefu** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/tcp

**Comment by akhillanger** [comment]
Approved.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by hajimefu** [comment]
I believe CH3 failures are machine issues rather than the issues in this PR.

**Comment by raffenet** [comment]
FWIW, I rebooted the Solaris node in Jenkins to see if that clears those failures up for future runs.

**Pull request merged**
