### PR TITLE
Fixes for 4.0rc2

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Pull in hwloc configuration fixes and update version to 4.0rc2.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
picked up a couple more recent fixes. this should hopefully be it for rc2.
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
I added the release_gather per-comm fix. Hopefully thats it (for real this time).

**Comment by hzhou** [comment]
> I added the release_gather per-comm fix. Hopefully thats it (for real this time).

Maybe we can postpone this commit. It is an issue when user changes their CVAR during runtime, which I don't think it's a big issue. I think the commit can use more time to stablize.

**Review by hzhou — APPROVED** [review]
LGTM

**Comment by raffenet** [comment]
> > I added the release_gather per-comm fix. Hopefully thats it (for real this time).
> 
> Maybe we can postpone this commit. It is an issue when user changes their CVAR during runtime, which I don't think it's a big issue. I think the commit can use more time to stablize.

OK, fair enough. I'll drop it an merge since tests passed without it.

**Pull request merged**
