### PR TITLE
pmi: Add support for Slurm PMI2 library

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Slurm ships both PMI-1 and PMI-2 libraries. Gives users the choice to use either --with-pmi=slurm or --with-pmi=slurm/pmi2.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/pmi

**Comment by raffenet** [comment]
Closing this since there's some additional brokenness that needs fixing first.

**Comment by hzhou** [comment]
> Closing this since there's some additional brokenness that needs fixing first.

What are the issues?

**Comment by raffenet** [comment]
> > Closing this since there's some additional brokenness that needs fixing first.
> 
> What are the issues?

See #5865 for the pmi.h header include issue.

For Slurm PMI2 support, there are also some data structure issues.
1. Slurm PMI2 still uses `MPID_Info` objects while MPICH has renamed them to `struct MPIR_Info`. https://github.com/SchedMD/slurm/blob/4801c60da4784346c4bf830a0b198364012e44ee/contribs/pmi2/pmi2.h#L227-L236
2. In `mpir_pmi.c` we assume PMI_keyval_t is available with both PMI1 and PMI2, but Slurm PMI2 doesn't provide it. https://github.com/SchedMD/slurm/blob/4801c60da4784346c4bf830a0b198364012e44ee/contribs/pmi2/pmi2.h#L150-L158

**Pull request closed without merging**
