### PR TITLE
test: remove collective release_gather tests

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Release gather algorithms are now tested by the default tests. Explicit CVAR tests for them no longer needed.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by jain-surabhi-23** [comment]
@hzhou These tests are not multi-threaded and it should not be failing anyway. When I take a close look, it not only tests `release_gather` algos but also different tuning params like buffer_sizes, tree_radix etc. So I propose lets keep these tests as it is. What do you think?

**Comment by hzhou** [comment]
> @hzhou These tests are not multi-threaded and it should not be failing anyway. When I take a close look, it not only tests `release_gather` algos but also different tuning params like buffer_sizes, tree_radix etc. So I propose lets keep these tests as it is. What do you think?

They fail when we do `async`. When your team do `hand-off` tests, they also should fail, right?

**Comment by hzhou** [comment]
@jain-surabhi-23 Do you prefer xfail them, like
 https://github.com/pmodels/mpich/pull/4385/commits/82c2b49feeef11a4adabf07d77bff0bebcc26fa8 
?

**Comment by jain-surabhi-23** [comment]
> @jain-surabhi-23 Do you prefer xfail them, like
> [82c2b49](https://github.com/pmodels/mpich/commit/82c2b49feeef11a4adabf07d77bff0bebcc26fa8)
> ?

Yes. Lets xfail them. Sorry it was not clear to me earlier.

**Pull request closed without merging**
