### PR TITLE
Adding LUPID for intercomm create and merge, and Addressing PR #2364

### PR DESCRIPTION
**Pull request by yfguo**
I don't think I have the permission to update the topic branch in https://github.com/pmodels/mpich/pull/2364. So I create this pull request to address the all the comments in the above PR. @charlesarcher @raffenet

### CODE REVIEW

**Comment by yfguo** [comment]
test:jenkins/ch3/all
test:jenkins/ch4/all

**Comment by wesbland** [comment]
We should probably just have @charlesarcher click the button on the other PR so you can update it properly. Or close the other one.

**Comment by charlesarcher** [comment]
I have the "allow edits" checkbox, but it's only for maintainers.  I guess @yfguo is not a maintainer?
Anyways, I'll close the other PR.

**Comment by yfguo** [comment]
I checked the test results. The patch did not introduce new failures (comparing to master). I think it is ready for merge.

**Comment by charlesarcher** [comment]
The warnings I was seeing have been addressed in my builds.

**Comment by raffenet** [comment]
Hmm, it looks like you just appended fixes to the end of the branch. How much trouble would it be to re-roll the series so it looks like the original number of commits?

**Comment by yfguo** [comment]
@charlesarcher Is there any warning on this branch? I added the fixes on top of your branch in PR #2364. So I assume it has addressed all the warnings. @raffenet What do you mean by "re-roll the series so it looks like the original number of commits"?

**Comment by raffenet** [comment]
Your original branch was something like 5 commits. Now there are 13, several of which are fixes for the original code. Can those fixes be squashed/merged with the original commits?

**Comment by charlesarcher** [comment]
I'm not seeing the warnings any more.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp
test:jenkins/ch4/all

**Comment by raffenet** [comment]
Looks good. Applied.

**Comment by yfguo** [comment]
test:jenkins/ch4/ucx

**Pull request closed without merging**
