### PR TITLE
Return request for complete NBCs

### PR DESCRIPTION
**Pull request by raffenet**
Arises from discussion in #2319. This PR includes some chages to ch4 to replace a common pattern, as well.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
Hmm, looks like this approach breaks down because I didn't assign a kind to the completed request. The reasoning is that it can be used for multiple kinds (send, coll, rma). I suppose we can modify the completion processing function to account for this, or just assign send kind and hope for the best? Open to suggestions...

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
The PR looks good. I only have a few discussion points. For one, is it possible to declare static allocation (inside MPIR_Process) so we don't need code in MPI_Init and MPI_Finalize?

Second, MPIR_Request_create_complete don't really need the kind parameter other than for the debugger purpose. Seems odd that the code go out of way to meet tool rather than the other way around.

**Comment by raffenet** [comment]
Static allocation is tricky. In order for the request to walk and talk like any other request, it needs a handle that all other functions understand. We could fiddle with the bits in the handle avlue to avoid the alloc/free, but that's probably OK to safe for future work :).

The second point is well taken. We can add a kind parameter back if/when we determine it is useful. I will make the change.

**Comment by raffenet** [comment]
Oh, I think I spoke to fast on the second point. It's still useful to differentiate the type of request for the debugger. Changing the debugger interface is non-trivial.

**Comment by raffenet** [comment]
@hzhou the message queue debugging interface for reference: https://www.mpi-forum.org/docs/msgq.5.pdf

**Comment by raffenet** [comment]
I have cleaned up and squashed the commits here. All tests should be passing, but I'll run the ch4 set one more time.
test:jenkins/ch4/most

**Comment by raffenet** [comment]
@hzhou any other thoughts on my responses? Otherwise I think these changes are good to go.

**Comment by hzhou** [comment]
@raffenet I agree these changes are good to go.

**Pull request merged**
