### PR TITLE
hydra2: abstract OS-dependent code

### PR DESCRIPTION
**Pull request by michael-chuvelev**
Unification of Linux/Windows Hydra support

### CODE REVIEW

**Comment by raffenet** [comment]
@michael-chuvelev this type of OS portability stuff is preferably done in MPL, now that I think about it. I'm not sure how much extra effort it would be in this case to try and abstract it that way. Any thoughts?

**Comment by michael-chuvelev** [comment]
@raffenet  I agree that the final state would be MPL-kind abstraction. I believe that's the reasonable goal, but efforts could be significant compared to what we did so far. I'd suggest leave abstraction layer as in this PR for some time and back to the OS abstraction re-arrangement after we close functionality gaps, which is I presume is more important.
The reason I wouldn't start with MPL-kind re-arrangement now is that Windows part is still under development, so we can't say whether some more functionality would require abstraction layers, or not. So this intermediate step would allow us to keep at least current development in order.

**Comment by raffenet** [comment]
Alright, it sounds like we are on the same page. We can put off the MPL work until later.

**Comment by raffenet** [comment]
@michael-chuvelev these changes look fine to me.

**Comment by pavanbalaji** [comment]
Is this PR still needed?

**Pull request closed without merging**
