### PR TITLE
modules: upgrade hwloc to v2.9.0

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Fixes pmodels/mpich#6342.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/submodules

**Review by hzhou — APPROVED** [review]
LGTM

**Comment by raffenet** [comment]
Appears this update broke OSX builds when using embedded hwloc 😦.

**Comment by hzhou** [comment]
This commit https://github.com/pmodels/mpich/pull/6337/commits/f61dd7694731236739f06ccbdba9735b114195a4 fixes it. The upgraded hwloc need `framework` argument in the LDFLAGS but not picked up with the embedded build

**Pull request merged**
