### PR TITLE
ch4: miscellaneous patches related to VCI/VNI address

### PR DESCRIPTION
**Pull request by sagarth**
## Pull Request Description
This PR includes small patches to fix problems during VCI/VNI address setup and access:
* Use vci 0 at init time under multiple-domains
* Use vci 0 for intercomm and tainted comm
* Propagate `tainted` flags to sub-comms

Base PR: https://github.com/pmodels/mpich/pull/5175

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by sagarth** [comment]
test:mpich/ch4/most
test:mpich/custom
netmod: ch4:ofi
config: async

**Comment by sagarth** [comment]
All of above tests passed except for 4 pingping test timeouts under `mpich-review-custom`. Those timeout should be unrelated to this PR, and were seem in an another PR as well.

**Comment by sagarth** [comment]
Rebased again.

**Comment by hzhou** [comment]
These commits are fine. But they are part of implicit vci selection. They are irrelevant and can't be tested without implicit vci selection, so they need to be in the same implicit vci PR. Sorry I may have advised you otherwise.

**Comment by sagarth** [comment]
@hzhou I think these patches will go along the PR for custom hints based vci selection: https://github.com/pmodels/mpich/pull/5488/. Any thoughts?

**Comment by hzhou** [comment]
The hints don't affect communications during init, so the first commit is irrelevant. The two other commits can go with the hints-based vci selection only if the PR observes the flag, e.g. ignores the hints when the flag is set.

**Comment by sagarth** [comment]
Yes, the hints are ignored when the flag is set.

**Pull request closed without merging**
