### PR TITLE
ch4: use MPL_timer in symheap allocation.

### PR DESCRIPTION
**Pull request by yfguo**
Symheap allocation should use MPL's timer rather than `gettimeofday` in
case it is not availble on the target platfrom.

### CODE REVIEW

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi

**Comment by yfguo** [comment]
Hmm, actually I think the PR needs more work. I should add an `MPL_wtime_touint` to the conversion because the `MPL_time_t` is platform dependent.

**Comment by yfguo** [comment]
Now it handles the different `MPL_time_t` correctly.

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
Is there anything a user can do with `MPL_time_t` besides converting it to `unsigned`? I guess what I am asking is, should we make that an internal type and directly return a usable value instead?

**Comment by raffenet** [comment]
Hmm, now that I look there are a handful of functions that use `MPL_time_t` and no easy way to 100% hide it. Retracting my comment. Looks good to me. 👍

**Pull request merged**
