### PR TITLE
Introduce MPL_aligned_alloc

### PR DESCRIPTION
**Pull request by hajimefu**
The CH4 OFI netmod relied on an implicit assumption that `malloc(3)` and its family return 16-byte aligned buffer on 64-bit platform. While it was true for glibc malloc, it was not a portably safe thing to assume. Moreover, recent changes in memory tracing (3329c1eea43c0501907701bad546bf2517fe51bc) broke that assumption in tracing-enabled builds.

Therefore this PR introduces an aligned malloc, `MPL_memalign` to fix that problem cleanly.

Currently, I define `MPL_memalign` as follows, following the `posix_memalign(3)` signature:
```
int MPL_memalign(void **ptr, size_t alignment, size_t size);
```
Also, two error codes `MPL_EINVAL` and `MPL_ENOMEM` are defined in MPL to express return value from it.

Initially I was thinking of this signature
```
void *MPL_memalign(size_t alignment, size_t size);
```
to match `malloc(3)` look-and-feel. Either way has pros and cons. Let me know your opinion on this. 

@raffenet could you prioritize this review? It would be better to include this MPL changes sooner than later.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
@hajimefu FWIW the function signature makes sense to me.

**Comment by raffenet** [comment]
Looks like this doesn't compile as-is. Needs definition of `MPL_EINVAL`. https://jenkins.mpich.org/job/mpich-review-ch3-tcp/2500/compiler=gnu,jenkins_configure=default,label=ib64/console

**Comment by raffenet** [comment]
Also, we probably need a check in the MPL configure to make sure `posix_memalign` is available and a fallback for when it is not.

**Comment by hajimefu** [comment]
@raffenet Ouch, my apologies... forgot to include one patch "mpl: Define MPL_ENOMEM and MPL_EINVAL". Now added.

For `posix_memalign` fallback, I think we need some discussion on how to fallback. Essentially we have to find an alternative or implement such an alternative by ourselves. I had some thoughts on it.
1. as the first step, we can detect `posix_memalign` and fail the build if it doesn't exist
2. try to find (obsolete) alternatives like `memalign`, `valloc`.
3. If nothing above is available, I can think of a few ways to fallback
    3a. Always use the traced version of `MPL_memalign`. This would require all `MPL_malloc/calloc/etc` to be always traced as well, otherwise `MPL_free` wouldn't work.
    3b. Introduce `MPL_memalign_free` and mandate that any memory block returned from `MPL_memalign` should be passed to `MPL_memalign_free`, not `MPL_free`. This will allow us to embed special metadata block for memory blocks allocated by `MPL_memalign` in non-trace builds (assuming we are using `malloc(3)` underneath) while not sacrificing `MPL_malloc` performance, but this is a departure from `posix_memalign` look-and-free and may confuse users.

My personal preference would be: implement 1 for now, and if we encounter a platform which doesn't have `posix_memalign`, then we can implement 2 and 3a.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
FYI, I see this warning when compiling with `--enable-strict`.
```
src/mem/mpl_trmem.c: In function ‘MPL_trmemalign’:
src/mem/mpl_trmem.c:138:17: warning: declaration of ‘err’ shadows a previous local [-Wshadow]
             int err;                                                    \
                 ^
src/mem/mpl_trmem.c:475:5: note: in expansion of macro ‘TR_THREAD_CS_ENTER’
     TR_THREAD_CS_ENTER;
     ^~~~~~~~~~~~~~~~~~
src/mem/mpl_trmem.c:473:9: note: shadowed declaration is here
     int err;
         ^~~
src/mem/mpl_trmem.c:148:17: warning: declaration of ‘err’ shadows a previous local [-Wshadow]
             int err;                                                    \
                 ^
src/mem/mpl_trmem.c:477:5: note: in expansion of macro ‘TR_THREAD_CS_EXIT’
     TR_THREAD_CS_EXIT;
     ^~~~~~~~~~~~~~~~~
src/mem/mpl_trmem.c:473:9: note: shadowed declaration is here
     int err;
         ^~~
```

**Comment by hajimefu** [comment]
Just updated the branch to address the shadowing warning above, also added a patch `mpl: check for posix_memalign availability`. Right now it simply checks if `posix_memalign` is available and fail if not.

@raffenet do you have any opinion on how to fallback?

**Comment by raffenet** [comment]
@hajimefu I'm thinking maybe there is no fallback and `HAVE_MPL_MEMALIGN` is checked when building `ch4:ofi` and configure fails if it is not available. Thoughts?

Also, after thinking about the signature some more, do we want to mimic `aligned_alloc` instead? That seems to be the way the language is going. `posix_memalign` is just the most widely available implementation.

**Comment by hajimefu** [comment]
@raffenet Regarding fallback, I agree with your plan. I'll fix my patches accordingly.

For signature, it sounds good to me. I'd change the function name to `MPL_aligned_alloc` in that case.

**Comment by raffenet** [comment]
Sounds good to me.

**Comment by hajimefu** [comment]
@raffenet updated the branch based on what we agreed above.
Now the point is: MPL uses either `aligned_alloc` or `posix_memalign`, whichever is available on the system. If neither of them is available, MPL doesn't define `MPL_aligned_alloc` and OFI netmod fails to configure.

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
This looks mostly good. I think we can squash commits 1-2 and 3-4 so that we end up with just 3 commits in this series. Does that sound good? I can do so when signing off.

**Comment by hajimefu** [comment]
@raffenet Makes sense. Go ahead and squash them. Thanks!

**Comment by raffenet** [comment]
After I dove in, I decided to re-order the commits to first fix the existing bugs, then add the new functionality. Hopefully that is OK. Just going to run the tests one more time to make sure I didn't screw up.
test:jenkins/ch4/most

**Comment by raffenet** [comment]
@hajimefu there's some warnings as a result of these commits when building with `--enable-strict`. Can you take a look at them? I am using GCC 6.3.0.

**Comment by raffenet** [comment]
> ./src/mpid/ch4/netmod/include/../ofi/ofi_recv.h: In function ‘MPIDI_OFI_do_irecv’:
./src/mpid/ch4/netmod/include/../ofi/ofi_impl.h:721:23: warning: cast from function call of type ‘struct iovec *’ to non-matching type ‘long unsigned int’ [-Wbad-function-cast]
         MPIR_Assert((((uintptr_t)p) & (MPIDI_OFI_IOVEC_ALIGN - 1)) == 0); \
                       ^

**Comment by hajimefu** [comment]
@raffenet Thanks. Moreover I see build failure in non-debug+`--enable-strict` build. Let me look at them.

**Comment by hajimefu** [comment]
@raffenet just pushed #2906 to fix the above warning you mentioned.

**Comment by hajimefu** [comment]
Also, build failure is fixed in #2904.

**Pull request merged**
