### PR TITLE
CH4/OFI: added atomics flag to capability set

### PR DESCRIPTION
**Pull request by hoopoepg**
- added 'atomics' flag to capability set: some interconnects
  have hardware support of RDMA, but have no support of
  RDMA/atomic operations (for example OFI/verbs provider).
  For such interconnects additional flag may be used to
  wrap atomics by AM implementation.

- minor refactoring of capability set initialization:
  used value-based initialization of structures instead of
  unnamed enumeration for better code reading & avoid
  potential issues in parameter ordering

- added OFI/verbs provider flags

Signed-off-by: Oblomov, Sergey <sergey.oblomov@intel.com>

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by hoopoepg** [comment]
hi
does CH4/OFI builds are broken? I see a lot of failed tests, but this PR could not make such affect
thank you

**Comment by raffenet** [comment]
@hoopoepg yes, there are a number of existing failures with CH4/OFI. it does not look like this PR caused any additional failures.

**Comment by raffenet** [comment]
@hoopoepg would it be much trouble to split this PR into 2 commits? One to modify the initialization and one to add the new cap?

**Comment by hoopoepg** [comment]
no problemo
I will exclude new cap from this request & create new PR later for new cap

**Comment by hoopoepg** [comment]
done

**Comment by wesbland** [comment]
You don't need to create two PRs. There can just be two commits in this one PR.

**Comment by hoopoepg** [comment]
done:
- init refactoring
- added verbs flags
- added atomics caps

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
Looks good. Just a heads up, we use Signed-off-by for code review in the MPICH project, unlike other git projects. I removed yours from these commits and added Wesley's, as he noted approval above.

**Pull request merged**
