### PR TITLE
debugger: Use MPIR_Request list pointers

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Request next pointers have moved from device struct to
MPIR_Request. Update debugger code that uses these pointers for the new
location.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ofi
EXTRA_CONFIG: --enable-debuginfo

**Comment by raffenet** [comment]
test:mpich/ch4/ofi
EXTRA_CONFIG: --enable-debuginfo

**Comment by raffenet** [comment]
Manual testing shows this fixed message queue debugging for ch3 and ch4 after breaking in #5560.

**Review by hzhou — APPROVED** [review]
LGTM.

**Pull request merged**
