### PR TITLE
macOS fixes for 3.4.x

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Fix xfail configuration and update libfabric to pickup a bug fix in socket communication.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: osx

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: osx

**Comment by raffenet** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: osx
compiler: intel

**Comment by raffenet** [comment]
FWIW, the libfabric folks said my patch would work for the sockets provider, but not tcp. I am going to revise the upstream PR to improve it. Since we don't really support the tcp provider yet, we can merge this as-is, or delay it for the more comprehensive fix.

**Review by hzhou — APPROVED** [review]
I agree with merge now. We always can revise later to use upstream patches when they adds it.

**Comment by raffenet** [comment]
FWIW, the comprehensive fix was merged and should be available in the next libfabric release. https://github.com/ofiwg/libfabric/pull/6399

**Pull request merged**
