### PR TITLE
libfabric: upgrade to version 1.6.0

### PR DESCRIPTION
**Pull request by yfguo**

### CODE REVIEW

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi
test:jenkins/ch3/ofi

**Comment by wesbland** [comment]
I'm very in favor of this, though obviously the build errors need to be fixed. It looks like things are fine when using the embedded libfabric. Is the problem just because the external one doesn't match?

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi
test:jenkins/ch3/ofi

**Comment by yfguo** [comment]
I have fixed the libfabric on Jenkins. The test should be fine now. I will merge the PR once the tests are green @wesbland

**Comment by wesbland** [comment]
The CH3 failures here are interesting. I think we're seeing the same failures on `master` with CH4 using the PSM2 provider. We don't see those failures with CH4 sockets.

**Comment by hajimefu** [comment]
@wesbland I can't tell the entire logic, but for CH4/OFI/psm2, looks like the recent changes around tag bits (from @wesbland and @raffenet) seemed to cause these failures. Applying #2985 would fix the failure (of course, only for CH4 but not for CH3.) #2985 expands the tag bits, which I guess is the key part.

**Comment by wesbland** [comment]
Thanks @hajimefu. I didn't realize those were some of the tests that would be fixed by that patch.

That still doesn't explain the CH3 failures here though.

**Comment by yfguo** [comment]
It is strange. I cannot reproduce the problem on BB manually. Let's try it again.

**Comment by yfguo** [comment]
test:jenkins/ch3/ofi

**Pull request merged**
