### PR TITLE
ch3: suppress warnings under noerrorchecking

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Make the warnings test clean under `noerrorchecking`.

* Use `MPIR_Assertp` in the non-critical path and where the assertion checking is important.
* Use `MPIR_AssertDeclValue` to protect variables only used for assertions.
* Protect `strerrbuf` with `#ifdef HAVE_ERROR_CHECKING`

[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/warnings/new

**Comment by hzhou** [comment]
test:mpich/warnings/new

**Comment by hzhou** [comment]
test:mpich/warnings/new

**Comment by hzhou** [comment]
test:mpich/warnings/new

**Comment by hzhou** [comment]
test:mpich/warnings/new

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Review by wesbland — APPROVED** [review]
Looks fine to me, though I don't care about ch3 performance so the `assertp` changes don't matter to me.

**Review by raffenet — APPROVED** [review]

**Pull request merged**
