### PR TITLE
comm: early_return in MPI_Intercomm_create_from_groups

### LINKED ISSUE #6902: comm: Segmentation fault in MPI_Intercomm_create_from_groups
According to MPI 4.1 (Section 7.6, p. 355), `MPI_Intercomm_create_from_groups` should be a local operation and return `MPI_COMM_NULL` if `MPI_GROUP_EMPTY` is supplied as the `local_group` or `remote_group` or both.  However, MPICH 4.2.0rc2 crashes with a segmentation fault in this case.  Please find a minimal reproducer below.  (Note that this is the "extreme" case with both groups being empty.  The segfault also occurs if one of the two groups is non-empty.)

```c
#include <mpi.h>

int main(int argc, char** argv)
{
    MPI_Init(&argc, &argv);

    MPI_Comm newcomm;
    MPI_Intercomm_create_from_groups(MPI_GROUP_EMPTY, 0,
                                     MPI_GROUP_EMPTY, 0,
                                     "42",
                                     MPI_INFO_NULL,
                                     MPI_ERRORS_ARE_FATAL,
                                     &newcomm);
    if (newcomm != MPI_COMM_NULL)
    {
        MPI_Comm_free(&newcomm);
    }
    MPI_Finalize();

    return 0;
}
```

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
When either local group or remote group is MPI_GROUP_EMPTY, we should return MPI_COMM_NULL, rather than segfaults.

Fixes #6902 

[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
Hmm, something wrong with the osx testing

**Review by raffenet — APPROVED** [review]

**Comment by raffenet** [comment]
> Hmm, something wrong with the osx testing

Homebrew updated to GCC 13. Scripts should be updated to get the right version.

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
Somehow osx can't link common symbols in `libmpifort.dylib` --
image

**Comment by hzhou** [comment]
@raffenet Could you review the 3 commits I added since your last review?

**Pull request merged**
