### PR TITLE
test: add a test for persistent request with anysource.

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Extracting just the test commit from #3196.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:mpich/warnings

**Comment by raffenet** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by pavanbalaji** [comment]
@raffenet   What's the status of this PR?

**Comment by raffenet** [comment]
I believe this bug still exists. I will rebase and mark configurations for xfail so we can merge.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
Nice to see the bug appears to be fixed now. I'll rebase again and try to get this merged.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Pull request merged**
