### PR TITLE
refactor: logging calls with script preprocessing

### PR DESCRIPTION
**Pull request by hzhou**
This is an attempt to test a refactor plan to clean up the logging calls around major functions.

Commit 2 removes all logging calls. Adding a comment to be functioned as a #pragma but for customized preprocessing.

Commit 3 demonstrates adding the logging calls back with a script. 

The goal: Removing all logging calls should build cleanly even without script preprocessing. After script preprocess (in autopen.sh or manually), the code should also build cleanly and honor the logging configurations.

### CODE REVIEW

**Comment by hzhou** [comment]
I limited the files to `src/mpi/coll` for review. It should apply to the entire code base.

**Comment by hzhou** [comment]
The `/* F: ... */ ` line can be expanded for additional preprocessing, for example, mutex lock, error signature, fn_exit/fn_fail boiler-plate, etc.

**Comment by wesbland** [comment]
`refactor: Normalize function header line`

How will this work with the code style script?

**Comment by wesbland** [comment]
I'm concerned that (for the first) patch, this is going to cause similar problems unless we have a script that enforces this rule in the same way that we do for code style. Otherwise we'll end up with some functions that just get silently ignored.

**Comment by hzhou** [comment]
> I'm concerned that (for the first) patch, this is going to cause similar problems unless we have a script that enforces this rule in the same way that we do for code style. Otherwise we'll end up with some functions that just get silently ignored.

My initial script give me the alert on these odd cases so definitely it's possible to detect in style checker. I wonder `GNU Indent` may have such option.

I made that first patch so my script become much simpler. However, that script is just to be used once for initial refactoring. Moving on, the idea is us developers maintain that `/* F: ... */` line just as we did with `#define FCNAME...` and `MPIR_FUNC_...`. The second script, which supposed to be used in `autogen.sh` only checks `/* F: ... */`, which is both simpler and more reliable. It can easily invoke a build error when `/* F: ... */` didn't follow  a normal detectable function pattern, then we can fix it.

**Comment by akhillanger** [comment]
@hzhou the DECL and ENTER macro statements were called after the variable declarations in a function. This was done because code in the mpi layer still follows C89 standard in which all statements follow variable declarations. This is to be consistent with reset of the mpich code at mpi layer.

**Comment by hzhou** [comment]
> When would the script be applied? I assume it would modify the code in the source tree (as opposed to doing it with autoconf macros where it ends up in the build tree). So it will need to handle cases where the script has already been applied (e.g. building the same code twice).
> 
> This will also make Git commits a nightmare because you'll have all of these code changes that you have to remove before committing, right?
> 
> Yikes, this whole thing is pretty scary. I'm much more inclined to just leave in the empty macros as suggested on #3534 since that removes pretty much all of my concerns.

Building the same code multiple times are not a problem, since the script removes `/* F: ... */` line as it processes, so it won't patch the same function twice. In fact, it will even work partially. 

I have the habit of separating my source code (for git) and build code (for developing/testing/debugging) separate, so it is not a problem for me. during developing, one doesn't need run the script (since it only add logging and non-essential stuff), then, the code can be kept raw (I mean ready to commit). I am going to modify `autogen.sh` so by default it does less and only apply all with `-release` option -- it doesn't make sense to have an `autogen` that is bulk of your developing compile cycle  :).  Then, even when accident happens that an accidental `autogen` step messes up the repository, it is just a `git reset --hard` away. 

It is not really a problem, but I understand it will take some getting used to.

The real solution for adopting this general purpose preprocessing layer is to have all real source in one place and preprocessed output in another place. It will take even more getting used to to embrace that work-flow -- but with much more opened freedom.

**Comment by wesbland** [comment]
> I have the habit of separating my source code (for git) and build code (for developing/testing/debugging) separate, so it is not a problem for me. during developing, one doesn't need run the script (since it only add logging and non-essential stuff), then, the code can be kept raw (I mean ready to commit). I am going to modify `autogen.sh` so by default it does less and only apply all with `-release` option -- it doesn't make sense to have an `autogen` that is bulk of your developing compile cycle :). Then, even when accident happens that an accidental `autogen` step messes up the repository, it is just a `git reset --hard` away.

I would argue that during development is the *only* time to have these macros. Users don't care about debugging the internals of MPICH so putting it in a `-release` flag seems silly. 😄 Also, since this isn't an autoconf macro (where every file is a `*.in` file that gets turned into something else in your build tree), it *will* impact your source tree and make the entire Git history tainted.

> It is not really a problem, but I understand it will take some getting used to.

That's a really dismissive way of saying, it's fine for me so get used to it everyone else. Which, in this case, isn't even true.

> The real solution for adopting this general purpose preprocessing layer is to have all real source in one place and preprocessed output in another place. It will take even more getting used to to embrace that work-flow -- but with much more opened freedom.

So you want to make every file in MPICH a `*.c.in` and `*.h.in`? I think this conversation is done...

**Comment by hzhou** [comment]
> @hzhou the DECL and ENTER macro statements were called after the variable declarations in a function. This was done because code in the mpi layer still follows C89 standard in which all statements follow variable declarations. This is to be consistent with reset of the mpich code at mpi layer.

The script is optional -- it adds debug logging -- so one can simply skip it to still use `C89` compiler. So in a sense, we didn't break C89. That said, we have been discussing and seems it is time for us to move on to C99. While I could make the script to work smarter to find where the variable declaration block ends, it will make the script complex, and therefore less reliable.

**Comment by hzhou** [comment]
> > It is not really a problem, but I understand it will take some getting used to.
> 
> That's a really dismissive way of saying, it's fine for me so get used to it everyone else. Which, in this case, isn't even true.

I didn't start this PR as pushing. I did this as an experiment and base for discussion. I was not prepared for everyone to accept my idea -- just want to see some feedback. Now as a discussion, I need state my side of reasoning, which anyone could disagree and I would like to hear the reasoning behind that disagreement. As I state my side of reasoning, that is by its nature, from my side of perspective. Sorry that sounds dismissive, but I was anything but. I was acknowledging that habit or getting used to is important factor. And I was and am respecting it. 
> 
> > The real solution for adopting this general purpose preprocessing layer is to have all real source in one place and preprocessed output in another place. It will take even more getting used to to embrace that work-flow -- but with much more opened freedom.
> 
> So you want to make every file in MPICH a `*.c.in` and `*.h.in`? I think this conversation is done...

In one of my old project, every file is a `.def` file, it is just one preprocessing step added to the toolchain just like `cpp` did with C compiler. So that works. But I didn't mean that...

What I meant was having the preprocessor script process every file into a build directory. It is just like we did with off-tree build.

**Comment by hzhou** [comment]
We are not ready for adding custom preprocessing at this point.

**Pull request closed without merging**
