### PR TITLE
coll: fix ibcast_intra_sched_scatter_ring_allgather.c

### LINKED ISSUE #4413: coll: ibcast fails with root !=0 for sched_scatter_ring_allgather pattern
MPI_Ibcast occasionally fails when root rank is not zero and its _sched_scatter_ring_allgather_ is involved:
`Fatal error in PMPI_Waitall: See the MPI_ERROR field in MPI_Status for the error code`

Please check the attached test with np>1 and the following algorithm selections:
`MPIR_CVAR_IBCAST_INTRA_ALGORITHM=auto|sched_scatter_ring_allgather|sched_smp`

[ibcast_root.zip](https://github.com/pmodels/mpich/files/4369604/ibcast_root.zip)

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

The algorithm should not distiguish root in the second step but mistakenly
did.

Fixes #4413.

TODO:
* [x] Expand collective CVAR tests 
       Expanded in PR #5368 

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
Are other implementations of this algorithm wrong, also? https://github.com/pmodels/mpich/blob/b1b700c6f9ec6e59519b211cc74365e6b3220eb2/src/mpi/coll/bcast/bcast_intra_scatter_ring_allgather.c#L101-L102

**Comment by hzhou** [comment]
> 
> 
> Are other implementations of this algorithm wrong, also?
> 
> https://github.com/pmodels/mpich/blob/b1b700c6f9ec6e59519b211cc74365e6b3220eb2/src/mpi/coll/bcast/bcast_intra_scatter_ring_allgather.c#L101-L102

Strangely, that algorithm works okay. I'll try to understand.

**Comment by hzhou** [comment]
The nonblocking `ibcast_intra_sched_scatter_...` algorithm use `MPII_Iscatter_for_bcast_sched`, while the blocking `bcast_intra_scatter_...` algorithm use `MPII_Scatter_for_bcast`. The two pre-scatter do not have the same behavior. The nonblocking version scatters contents start at rank-0, while the blocking version scatters contents start at `root`. Thus the `allgather` stage also need differ accordingly.

I guess a better fix is to fix `MPII_Scatter_for_bcast`. I like the version that distributes contents at rank 0 since that makes the code easier to follow (1-less variable to track).

**Comment by hzhou** [comment]
Updated with the new fix.

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Review by raffenet — APPROVED** [review]

**Pull request merged**
