### PR TITLE
Bsend thread fix with progress

### PR DESCRIPTION
**Pull request by wesbland**

### CODE REVIEW

**Comment by wesbland** [comment]
I'm not sure why this has a WIP tag. As far as I know, it's ready for review unless someone has a specific concern.

**Comment by wesbland** [comment]
test:jenkins/ch4/all
test:jenkins/ch3/all

**Comment by wesbland** [comment]
test:jenkins/ch4/all
test:jenkins/ch3/all

**Comment by pavanbalaji** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by pavanbalaji** [comment]
@wesbland This might need to be rebased on to `mpich/master` and the tests retriggered before it can be reviewed again.

**Comment by wesbland** [comment]
This was rebased yesterday. I think we're just waiting for all of the tests to finish at this point.

**Comment by pavanbalaji** [comment]
This is failing on platforms without weak symbols, i.e., `osx`.  The `MPICH_MPI_FROM_PMPI` protection might need to be moved a bit.

**Comment by wesbland** [comment]
That problem should be fixed now.

test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by halimamer** [comment]
@wesbland, AFAIK this PR was created during the confusion that `progress_test` might give up the lock (https://github.com/pmodels/mpich/issues/2441), which is done wrongly in CH4 because `progress_test` is implemented as `progress_wait` (https://github.com/pmodels/mpich/blob/master/src/mpid/ch4/src/ch4_progress.h#L125). Let me work up a patch that fixes this misuse of `progress_test` and document the progress routines properly once the progress revamp PR that @hajimefu and @danghvu are working on is merged

**Comment by wesbland** [comment]
So you're saying this PR should just be dropped?

**Comment by halimamer** [comment]
that's my recommendation. We can leave it until I provide the above patch. Do we have a test in the testsuite that triggers the progress bug the first commit is addressing?

**Comment by wesbland** [comment]
I believe this is fixing `threads/pt2pt/ibsend`.

**Comment by wesbland** [comment]
Ok. I'm going to close this PR and you can work on this in the future @halimamer.

**Pull request closed without merging**
