### PR TITLE
Misc build cleanup

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
@roblatham00 speaking of autotools, would you have a chance to review this? I'm going to get a fresh set of Jenkins results.
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by roblatham00** [comment]
All seems redundant to me, too.  Thanks for wading through this mess.   If Jenkins is happy I'm happy

**Comment by raffenet** [comment]
Thanks! Jenkins isn't happy, but I'm guessing that is my branch being woefully out of date. I'll rebase and re-test with your signoff.

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Pull request merged**
