### PR TITLE
misc: update pull_request_template

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Having too many checklist items is not effective. Combine some of them
and omit those we automatically enforce using GitHub merge policy.

The new ones look like following:
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Review by raffenet — APPROVED** [review]
LGTM

**Comment by hzhou** [comment]
@raffenet I formatted the text a little to make it easier to read. What do you think?

**Comment by hzhou** [comment]
@wesbland What do you think?

**Comment by raffenet** [comment]
> @raffenet I formatted the text a little to make it easier to read. What do you think?

👍

**Review by wesbland — APPROVED** [review]

**Pull request merged**
