### PR TITLE
maint: add pre-commit script maint/hooks/spellchecker

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
This script is to be used for CI testing, similar to the one used for
whitespace checker (maint/hooks/pre-commit).

Add jenkins job "spell-checker", triggered by comment "test:mpich/spellcheck". Once this merged, we'll have the test automatically run every time.

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/spellcheck

**Comment by hzhou** [comment]
test:mpich/whitespace
test:mpich/spellcheck

**Comment by hzhou** [comment]
test:mpich/whitespace
test:mpich/spellcheck

**Comment by hzhou** [comment]
test:mpich/spellcheck

**Comment by hzhou** [comment]
test:mpich/spellcheck

**Comment by hzhou** [comment]
test:mpich/spellcheck

**Comment by hzhou** [comment]
test:mpich/spellcheck

**Comment by hzhou** [comment]
test:mpich/spellcheck

**Comment by hzhou** [comment]
test:mpich/spellcheck

**Review by yfguo — APPROVED** [review]

**Comment by wesbland** [comment]
My knowledge of Git hooks might be insufficient here, but doesn't this need to be in the `pre-commit` file to be used as a pre-commit hook?

**Comment by hzhou** [comment]
> 
> 
> My knowledge of Git hooks might be insufficient here, but doesn't this need to be in the `pre-commit` file to be used as a pre-commit hook?

Our current jenkins script:
```
#!/bin/bash

set -xe

PYTHON=python3.6
PREFIX=$HOME/software/codespell
GIT=$HOME/software/git-2.23.0/bin/git

export PATH=$PREFIX/bin:$PATH
export PYTHONPATH=$PREFIX/lib/$PYTHON/site-packages

$GIT --version
    
$GIT remote add pmodels git://github.com/pmodels/mpich.git
$GIT fetch pmodels

$GIT rebase --verbose --exec maint/hooks/spellchecker pmodels/$ghprbTargetBranch
```

**Comment by wesbland** [comment]
I see. So it’s not a pre-commit hook that runs on peoples' laptops. It’s just a script for Jenkins.

**Comment by hzhou** [comment]
I use the same script to check on my laptop as well, just not automatic.

**Pull request merged**
