### PR TITLE
Update release info for 3.4.3

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

CHANGES and version.m4 updates.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
Ignoring warning issues since they are either false positives, or pre-existing from the noerrorchecking configuration. Run tests for sanity.
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
Need to tweak expected failures for older branches now that scripts have updated.

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
> Need to tweak expected failures for older branches now that scripts have updated.

Oops, I forgot the stable branch testing :(

I see your solution of running a extra configure in test/mpi. That works. Alternatively, we can check whether we are testing stable branch, and if so, simply concatenate `$test_config_opt` onto the main `$config_opt` before the main configure.

**Comment by raffenet** [comment]
> > Need to tweak expected failures for older branches now that scripts have updated.
> 
> Oops, I forgot the stable branch testing :(
> 
> I see your solution of running a extra configure in test/mpi. That works and it is clever. Alternatively, we can check whether we are testing stable branch, and if so, simply concatenate `$test_config_opt` onto the main `$config_opt` before the main configure.

This would require some way to check if a PR is submitted against a stable branch, which I don't think we have right now. I guess we could just enumerate the stable branches since there is never going to be more than one or two.

**Review by hzhou — APPROVED** [review]
LGTM.

**Review by yfguo — APPROVED** [review]

**Pull request merged**
