### PR TITLE
Fix bug in split_type test

### PR DESCRIPTION
**Pull request by rithwiktom**
## Pull Request Description
A variable was used without initialization in the f08 tests.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Review by hzhou — APPROVED** [review]
LGTM. Thanks for the fix!

**Comment by hzhou** [comment]
@rithwiktom Could you sign the [contribution agreement](http://www.mpich.org/documentation/contributor-docs/)?

**Comment by hzhou** [comment]
test:mpich/warnings
test:mpich/ch4/most

**Comment by rithwiktom** [comment]
@hzhou  I found out from my team that I do not need to sign the contribution agreement. Is there anything else I need to do? Thanks.

**Comment by hzhou** [comment]
test:mpich/authorship

**Review by hzhou — APPROVED** [review]
LGTM

The CI servers are down this week. But the changes are simple enough that I'll go ahead merge it.

**Pull request merged**
