### PR TITLE
shm: Implement intra-node Allreduce using release_gather based framework

### PR DESCRIPTION
**Pull request by jain-surabhi-23**

### CODE REVIEW

**Comment by jain-surabhi-23** [comment]
@yfguo This is the last follow up PR of shared memory based intra-node collectives. It implements Allreduce, (earlier ones implemented Bcast and Reduce).
This also has a HACK patch which is just for testing.
This also adds tests to the "test_coll_algos.sh", so we would have to xfail it the way you did for the first PR.

**Comment by jain-surabhi-23** [comment]
test:jenkins/ch4/ofi

**Comment by jain-surabhi-23** [comment]
@yfguo The tests have passed earlier. Now I removed the HACK patch and created the patch to xfail the tests (the same way you did for Bcast and Reduce earlier).
Can you please take a look?

**Comment by yfguo** [comment]
Looks ok. Rebased and retest

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi

**Comment by jain-surabhi-23** [comment]
@yfguo The tests came out clean. I guess this PR is good to go?

**Pull request merged**
