### PR TITLE
coll: Fix integer overflow in MPI_Bcast

### PR DESCRIPTION
**Pull request by sudheer9**
Promoted an internal type to MPI_Aint to avoid integer overflow when
verifying number of bytes transferred.

Fixes pmodels/mpich#2257
Fixes pmodels/mpich#2311

### CODE REVIEW

**Comment by raffenet** [comment]
@sudheer9 just adding a note here about what we discussed. We should add a test case that verifies this fix.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by sudheer9** [comment]
test:jenkins/ch3/tcp

**Comment by sudheer9** [comment]
test:jenkins/ch3/tcp

**Comment by sudheer9** [comment]
test:jenkins/ch3/tcp

**Comment by sudheer9** [comment]
test:jenkins/ch3/tcp

**Comment by sudheer9** [comment]
test:jenkins/ch3/tcp

**Comment by sudheer9** [comment]
test:jenkins/ch3/tcp

**Comment by sudheer9** [comment]
test:jenkins/ch3/tcp

**Comment by sudheer9** [comment]
Given #5153 this issue and the proposed fix is no longer relevant. @raffenet any issue with closing this?

**Comment by raffenet** [comment]
> Given #5153 this issue and the proposed fix is no longer relevant. @raffenet any issue with closing this?

Nope. I think we can close it.

**Pull request closed without merging**
