### PR TITLE
test/mpi: Add test for truncation with MPI_Mrecv

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/all
test:jenkins/ch4/all

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/portals

**Comment by raffenet** [comment]
test:jenkins/ch3/portals4

**Comment by raffenet** [comment]
test:jenkins/ch3/all
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
@raffenet This PR looks fine.  Should it be rebased and retested?

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by wesbland** [comment]
Radical idea here. How about naming it `truncmsg_mrecv` instead of `truncmsg3`?

I know it's a drop in the bucket, but I'd so very much like to see the MPICH test suite have clearer, shorter, better contained tests.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
> Radical idea here. How about naming it `truncmsg_mrecv` instead of `truncmsg3`?
> 
> I know it's a drop in the bucket, but I'd so very much like to see the MPICH test suite have clearer, shorter, better contained tests.

Sure, just updated the name.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
Updated xfail only. Re-testing ch4 to confirm.
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
@raffenet Are these `ch3-debug` failures expected? https://jenkins-pmrs.cels.anl.gov/job/mpich-master-ch3-centos/lastCompletedBuild/testReport/

**Comment by raffenet** [comment]
Huh, I must have missed those during testing. I will submit an updated xfail patch.

**Comment by hzhou** [comment]
> 
> 
> > Radical idea here. How about naming it `truncmsg_mrecv` instead of `truncmsg3`?
> > I know it's a drop in the bucket, but I'd so very much like to see the MPICH test suite have clearer, shorter, better contained tests.
> 
> Sure, just updated the name.

Seems the change got lost.

**Pull request merged**
