### PR TITLE
warnings: fix missing returns

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Certain compiler (sun) will complain for extra return that is
unreachable. However, last patch (98da430) was over zealous and removed
a couple return that should not be removed. This commit fixes that.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:more/warnings

**Comment by hzhou** [comment]
For reference, the nightly warnings failures are here: https://jenkins-pmrs.cels.anl.gov/job/mpich-master-warnings/lastCompletedBuild/

**Comment by hzhou** [comment]
Originally the compiler (I believe it was succ) was complaining of this:
```
if (...) {
    return A;
} else {
    return B;
}
return NULL;
```
The last return is unreachable. So I removed them. But I wasn't careful and removed a few cases that have leaking branches. I am OK with either styles, sometime preferring one over the other depend on the cases. For that file, I think at least we need make it consistent.

**Comment by raffenet** [comment]
Agreed we should make it consistent in that file. Conceptually I think of the last return as the "default" collective algo (which can also be NULL). Everything else is a special case.

**Comment by hzhou** [comment]
> Agreed we should make it consistent in that file. Conceptually I think of the last return as the "default" collective algo (which can also be NULL). Everything else is a special case.

Well, not in this file. I think NULL is just a error case. Normally the selection should always return a valid container.

**Pull request merged**
