### PR TITLE
[4.1.x] Fixes and version info for 4.1.3

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

A batch of fixes and preparation for a 4.1.3 release, which will be the last in the 4.1.x branch.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
Is this PR https://github.com/pmodels/mpich/pull/6815 merged here? I am seeing the same ch3 failures in https://github.com/pmodels/mpich/pull/6903. It is due to common blocks not being recognized in `libmpifort.dylib`.  I am not sure if this regression is due to PR#6815 or due to Xcode upgrade.

**Comment by raffenet** [comment]
> Is this PR #6815 merged here? I am seeing the same ch3 failures in #6903. It is due to common blocks not being recognized in `libmpifort.dylib`. I am not sure if this regression is due to PR#6815 or due to Xcode upgrade.

#6815 is not in the 4.1.x branch, so must be something else.

**Comment by raffenet** [comment]
macOS failures are determined to be a platform issue resulting from a recent upgrade. They will be ignored in this PR.

**Pull request merged**
