### PR TITLE
hydra: fix singleton init (again)

### LINKED ISSUE #6269: mpi4py: Regression running testsuite on GitHub Actions
* All build using `hydra` fail in singleton init mode [[logs]](https://github.com/mpi4py/mpi4py-testing/actions/runs/3449138542). Unfortunately, the failure prevented GH Actions for generating a proper, informative logs.
* The build using `gforker` and `ch4:ofi` failed with the following assertion:
```
...
testGetAccumulate (test_rma_nb.TestRMASelf) ... Assertion failed in file ./src/include/mpir_request.h at line 380: equal_ && (*(MPID_Thread_mutex_t *) MPIR_Request_mem[pool].lock).count >= 1
```

It is not easy for me right now to try to reproduce these issues with local builds.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Try Fix the singleton init again.

Fixes #6269
## TODO
* [ ] Explain it.

## Notes
* The breaking commit was https://github.com/pmodels/mpich/pull/6231/commits/7d7823455ef2b128a4ebe4cfb6fb617d35e2cc41
[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
quick: yes
env: MPITEST_SINGLETON=1
env: VERBOSE=1
env: PMI_DEBUG=1
testlist: attr/baseattr2 1

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
quick: yes
env: MPITEST_SINGLETON=1
env: VERBOSE=1
env: PMI_DEBUG=1
testlist: attr/baseattr2 1

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
quick: yes
env: MPITEST_SINGLETON=1
env: VERBOSE=1
env: PMI_DEBUG=1
testlist: attr/baseattr2 1

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
quick: yes
env: MPITEST_SINGLETON=1
env: VERBOSE=1
env: PMI_DEBUG=1
testlist: attr/baseattr2 1

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
quick: yes
env: MPITEST_SINGLETON=1
env: VERBOSE=1
env: PMI_DEBUG=1
testlist: attr/baseattr2 1

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
quick: yes
env: MPITEST_SINGLETON=1
env: VERBOSE=1
env: PMI_DEBUG=1
testlist: attr/baseattr2 1

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
quick: yes
env: MPITEST_SINGLETON=1
env: VERBOSE=1
env: PMI_DEBUG=1
testlist: attr/baseattr2 1

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
quick: yes
env: MPITEST_SINGLETON=1
env: VERBOSE=1
env: PMI_DEBUG=1
testlist: attr/baseattr2 1

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
env: MPITEST_SINGLETON=1

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
@raffenet I am still not exactly sure how `fd=0` interacts with Jenkins "master-agent` IO but the fix in this PR works. Since `fd=0` may be hardwired as stdin in many code, it is likely a good idea to avoid the collision anyway. I am still trying to understand how we broke it, but I think we can merge this to fix the CI in the mean time.

**Review by raffenet — APPROVED** [review]

**Comment by hzhou** [comment]
@dalcinl could you do a quick test on this branch?

**Pull request merged**
