### PR TITLE
coll: Updates to bcast/reduce ring algos

### PR DESCRIPTION
**Pull request by akhillanger**
This pull request simplifies ring algorithms code. Bcast/Reduce ring algorithm can be implemented as kary tree with k=1. Currently, we have code that just implements ring algorithm for bcast/reduce. This is redundant code. This pull request changes that by calling kary tree algorithm with k=1, and deleting the specific ring algo implementation.

It also fixes some issues related to ring CVARs for bcast/reduce collectives.

### CODE REVIEW

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
Fixed usage of tree_type for non-commutative cases.
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
doing a compile test to make sure conflict resolution worked.
test:jenkins/ch4/ofi

**Pull request merged**
