### PR TITLE
Sched dump

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
Should have compile tested this first. Test again.
test:jenkins/ch3/tcp

**Comment by yfguo** [comment]
The PR looks fine. I am merging it.

**Pull request merged**
