### PR TITLE
coll: Add MPIR_TSP_sched_free function for GenTran scheduler

### PR DESCRIPTION
**Pull request by zhenggb72**
Make free'ing of a schedule as a separate function as this will
be called from different places.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [ ] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
Rebased to master.

test:jenkins/ch3/most
test:jenkins/ch4/most
test:mpich/warnings

**Comment by hzhou** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
Fails `errors/coll/bcastlength 4` in `ucx` `am-only`. Seems the fix still does not work. @zhenggb72 Could your team do some investigation? We can xfail it, but at least we should add more details to #3775 narrowing down the bug to some degree.

**Comment by wesbland** [comment]
@hzhou - I added a comment about the collective errors issues in UCX on #3775. If you'd like to add an xfail and point to that issue, that'd be fine. It's not expected that those tests would pass.

**Pull request merged**
