### PR TITLE
ulfm: add MPIX_Comm_get_failed

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Add MPIX_Comm_get_failed. This function is in the current ULFM working proposal. 
Ref: https://github.com/mpi-forum/mpi-issues/issues/20#issuecomment-1021458776

This is a discovery function, the base of most ULFM applications.  Let's support it.

Fixes: https://github.com/pmodels/mpich/issues/5788

[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
A key here is when a sending process is killed, a recv from that process should return `MPIX_ERR_PROC_FAILED`. That is not working with `ch4` as I tested. Wonder how did it work originally.

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Review by raffenet — APPROVED** [review]

**Pull request merged**
