### PR TITLE
ch4/ofi: Passing and reusing av variable in netmod/ofi

### PR DESCRIPTION
**Pull request by huansong**
OFI's `av` variable was retrieved twice (by calling `MPIDIU_comm_rank_to_av`) for `put|get|accumulate|...` Therefore, we can pass the parameter down and reuse it in netmod/ofi. Also, we can make the names of OFI `av` variable (`MPIDI_av_entry_t *`) consistent across all function definations in netmod/ofi.

### CODE REVIEW

**Comment by hajimefu** [comment]
Oh this is a nice work... in fact I was just about to open a pretty similar PR. Let me do it anyway and let us discuss how we merge our work together.

**Comment by hajimefu** [comment]
@huansong I just opened #3480, which is pretty similar to this PR. At a quick glance, I think the OFI netmod RMA part is almost identical between two PRs. I like your idea of renaming `addr` -> `av` for consistency, so we can pick that patch. I think then we can also pick the ucx change and OFI pt2pt change from my PR. Let me know what you think.

**Comment by hajimefu** [comment]
test:jenkins/ch4/ofi

**Comment by huansong** [comment]
@hajimefu I agree. We should go with your https://github.com/pmodels/mpich/pull/3480 which is more inclusive and succinct. You can pick my renaming part if it works. But there seem to be some issues with testing in both PRs though.

**Comment by hajimefu** [comment]
@huansong Okay. I bet these failures are unrelated to either of PRs. I think I see them on other PRs as well, and I don't see then the Intel-internal tests (some failures are due to the fact that `master` has not merged all bug fix PRs yet.) If you agree, I'll add you as a co-author to some of the patches.

**Comment by huansong** [comment]
@hajimefu Yes sure. :)

**Pull request closed without merging**
