### PR TITLE
Coverity fixes

### PR DESCRIPTION
**Pull request by wesbland**

### CODE REVIEW

**Comment by wesbland** [comment]
After the tests pass, I plan to merge all but the MPIDU/SHM patch.

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
I've now merged everything but the non-OFI commit. Can someone else take a look at this?

**Comment by raffenet** [comment]
Coverity has stopped complaining about this one, and I'm not 100% sure of the approach here. Can we shelve this one for now or do you want to iterate on it?

**Comment by wesbland** [comment]
If Coverity is happy, I'm happy.

**Pull request closed without merging**
