### PR TITLE
test/coll: add tests for collective compositions

### PR DESCRIPTION
**Pull request by tarudoodi**
## Pull Request Description
This PR adds tests for some collectives by setting ch4-layer composition CVARs. For example, with blocking bcast, we want to test by setting `MPIR_CVAR_BCAST_COMPOSITION` (taking value of 0, 1, 2, and 3).

We use the special syntax `composition:xxx` in `test/mpi/maint/coll_cvars.txt` to generate these tests.
 
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by tarudoodi** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
The results confirm the tests were added and ran successfully.

image

**Comment by tarudoodi** [comment]
I'll add the tests for other compositions as well.

**Comment by tarudoodi** [comment]
test:mpich/ch4/ofi

**Comment by tarudoodi** [comment]
@yfguo  All tests are passing.

**Review by yfguo — APPROVED** [review]

**Pull request merged**
