### PR TITLE
initial skeleton for qthreads support

### PR DESCRIPTION
**Pull request by npe9**

### CODE REVIEW

**Comment by pavanbalaji** [comment]
@npe9 This needs to be rebased on to `mpich/master`.

**Comment by npe9** [comment]
Hey @pavanbalaji I'm doing that right now. It looks like there's a regression in the configure.ac introduced somewhere and I'm running a bisect to find the culprit.

**Comment by npe9** [comment]
Also, @pavanbalaji what is the proper way to add external libraries to the CI infrastructure?

**Comment by pavanbalaji** [comment]
> Also, @pavanbalaji what is the proper way to add external libraries to the CI infrastructure?

We'll need to install the external library (`qthreads` in this case) on our servers.  @raffenet or @yfguo can probably help with that.  Once that's done, we'll need to setup a new jenkins job that does qthreads testing, which can be triggered from GitHub.

**Comment by pavanbalaji** [comment]
@npe9  Is this PR still being pursued?  I'll close it for now as it's been inactive for some time, but we can reopen it once it's rebased to the latest master (it seems to have conflicts).

**Pull request closed without merging**
