### PR TITLE
warnings: misc PGI warning fix

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Some compilers can't deal with preprocessing whthin a macro argument
expansion.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:more/warnings

**Comment by hzhou** [comment]
test:more/warnings --enable-g=all

**Comment by raffenet** [comment]
I'm curious - now that POSIX shm uses MPIDIG pkts, is this sequence number stuff redundant? Can we just remove it?

**Comment by hzhou** [comment]
test:more/warnings --enable-g=all

**Comment by hzhou** [comment]
test:more/warnings
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
test:mpich/warnings/more

**Comment by hzhou** [comment]
Seems the warnings have been fixed in master

**Pull request closed without merging**
