### PR TITLE
ch4/ucx: Basic partitioned communication implementation over pt2pt

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

This PR adds a basic native implementation of partitioned communication in UCX. Unfortunately, using the generic layer matching with lower-level hooks isn't as clean as I envisioned, which creates some headaches in the lower layer when attempting additional setup information exchange.

There are 2 main issues:

1. `MPIDI_UCX_precv_matched_hook` might execute *before* `MPIDI_UCX_mpi_precv_init_hook`, so netmod initialization of the request may not yet be done. That can be solved by either doing redundant initialization (if needed), or delaying the matched hook until later in the generic layer.
2. The generic layer match may occur after start has already been called on the recv request (in `MPIDIG_part_send_init_target_msg_cb`). This will result in a CTS message being issued in the generic layer, even though it has no relevance to the operation in UCX. The message is harmless, but it modifies the AM portion of the request. In order to avoid colliding with lower-layer fields, we need to isolate the AM portion. Ideally AM/netmod/shm would be a union, like with regular send/recv requests.

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
Hmm, I used the `_nbx` interfaces to implement this PR, but that would require raising the minimum version. Or maybe falling back to the generic when not available.

**Comment by raffenet** [comment]
> Hmm, I used the `_nbx` interfaces to implement this PR, but that would require raising the minimum version. Or maybe falling back to the generic when not available.

_nbx interfaces were added in v1.9.0.

**Comment by hzhou** [comment]
> 
> 
> > Hmm, I used the `_nbx` interfaces to implement this PR, but that would require raising the minimum version. Or maybe falling back to the generic when not available.
> 
> _nbx interfaces were added in v1.9.0.

Yeah, but if it is not GPU safe we can't use it, unless we have separate branch to do the GPU buffer swaps.

**Comment by raffenet** [comment]
> EDIT: oh I am commenting the am_nbx stuff. Maybe you are referring to a different API?

Yes. This uses `ucp_tag_send_nbx` and `ucp_tag_recv_nbx`, which are new/better interfaces for the tagged send/recv functionality. These significantly clean up the request handling by allowing the caller to supply a `void *` context returned at completion like Portals or libfabric.

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Pull request closed without merging**
