### PR TITLE
ch4/gpu: bug fixes for gpu pipelining

### PR DESCRIPTION
**Pull request by zhenggb72**
## Pull Request Description

1. fix a bug when merging - handle GPU task on receiver side
2. some fixes to suppress memory leak warnings

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by abrooks98** [comment]
test:mpich/ch4/ofi
test:mpich/ch4/gpu/ofi

**Comment by zhenggb72** [comment]
test:mpich/ch4/ofi
test:mpich/ch4/gpu/ofi

**Review by hzhou — APPROVED** [review]
LGTM

There is a handle leak in `impls/mpich/cuda/stream`. I will fix it separately.

**Comment by hzhou** [comment]
Note: CI testing for gpu pipelining is missing currently. `psm3` currently doesn't support the features required by the GPU pipelining feature.

**Pull request merged**
