### PR TITLE
mpi/comm: Fix function declaration

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Fix arguments for MPIX_Comm_idup_with_info in weak alias declaration.

## Expected Impact

Fix clang builds.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
Clang fails with this error. Should we add a clang configuration into the PR warnings test?
```
src/mpi/comm/comm_idup_with_info.c:16:5: error: conflicting types for 'MPIX_Comm_idup_with_info'
int MPIX_Comm_idup_with_info(MPI_Comm comm, MPI_Comm * newcomm, MPI_Request * request)
    ^
./src/include/mpi.h:1381:5: note: previous declaration is here
int MPIX_Comm_idup_with_info(MPI_Comm comm, MPI_Info info, MPI_Comm *newcomm,
    ^
1 error generated.
```

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/custom
compiler: clang
netmod: ch4:ofi

**Review by hzhou — APPROVED** [review]

**Comment by hzhou** [comment]
Seems there is additional similar errors.

**Comment by raffenet** [comment]
test:mpich/custom
compiler: clang
netmod: ch4:ofi

**Review by hzhou — APPROVED** [review]
This looks good. Should we rebase and merge it?

**Pull request merged**
