### PR TITLE
Prerequisite fixes for code uninlining

### PR DESCRIPTION
**Pull request by yfguo**
The master has two building problems:

1. When building with `--disable-ch4-netmod-inline` only, the `posix_probe.h` is missing some functions that are indirectly included through `mpidch4r.h`.

2. When building with `--disable-ch4-shm-inline` only, the `eager/fbox/func_table.c` generates empty object which breaks the build at link time (the func table is missing). 

None of these problems show up when setting `--enable-ch4-netmod-inline=no` or `--enable-ch4-shm-inline=no` which are equivalent to the ones that break the build, respectively. Yet, the build behavior is different for reasons that is not clear to me.

After digging for quite a long time and rebuilding the library for many times, I conclude that the problem is caused by `eager/stub` being always ON when building SHM. This PR fixes the problem and is required by the upcoming uninlining PR.

Apart from the above fixes, the PR also include other minor fixes for the problem when buiding with different combinations of --enable(disable)-ch4-netmod-inline/--enable(disable)-ch4-shm-inline.

### CODE REVIEW

**Comment by yfguo** [comment]
Since these problems won't show up in Jenkins job (because the script uses `--enable-ch4-shm-inline=no`), the PR need to be manually tested.

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi

**Comment by yfguo** [comment]
missed the `subconfigure.m4` in previous push.

**Comment by yfguo** [comment]
Do not merge for now. I found more problems in the SHM code that need to be fixed.

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
All looks good to me. Thanks.

**Pull request merged**
