### PR TITLE
ch4: Remove unsupported ticketlock

### PR DESCRIPTION
**Pull request by raffenet**
This was experimental code that is no longer under development.

## Pull Request Description

Remove dead code.

## Expected Performance Changes

none

## Known Issues

none

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [ ] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by hajimefu** [comment]
@raffenet Do you know if this is broken or simply not used by default?

**Comment by raffenet** [comment]
There is no configuration option to enable it, from what I can tell. I did not attempt to compile/test it. I know that izem has a ticket lock implementation in addition to this one, but am not sure how to two compare.

**Comment by hajimefu** [comment]
Ah I see. As I look into more details, this seems to be an experimental implementation and not ready to replace the default (pthread?) one, e.g. lacking conditional variable implementation.

In case we do need a ticket lock we can use/improve the one in izem, I agree. Opinions? @zhenggb72

**Pull request merged**
