### PR TITLE
tag bit management

### PR DESCRIPTION
**Pull request by raffenet**
I made a bunch of changes to #3111. Making a new PR for testing.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch3/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/most
test:jenkins/ch3/ofi

**Comment by raffenet** [comment]
@gcongiu @alexander-sannikov I have re-organized the commits some in this new version. It looks like the test output is good, so I'm ready to merge. The only commit that doesn't have signoff is the last tone. @gcongiu can you do a quick review so that I can add your signoff if it is OK?

**Comment by gcongiu** [comment]
@raffenet the last commit is ok

**Pull request merged**
