### PR TITLE
Revert "autogen: add libtool patch for NVIDIA HPC compilers"

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

This reverts commit 9801fb56273dd38b155db338250866452b57969d.

## Expected Impact

Fix builds using PGI compilers.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/warnings/custom
compiler: pgi

**Comment by raffenet** [comment]
test:mpich/custom
netmod: ch4:ofi
compiler: pgi

**Comment by raffenet** [comment]
PGI builds have been broken since the application of this patch. They fail when linking the C++ binding library. 
```
/usr/lib64/crti.o: In function `_init':
(.init+0x0): multiple definition of `_init'
/usr/lib64/crti.o:(.init+0x0): first defined here
/usr/lib64/crti.o: In function `_fini':
(.fini+0x0): multiple definition of `_fini'
/usr/lib64/crti.o:(.fini+0x0): first defined here
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbeginS.o:(.data.rel.ro+0x0): multiple definition of `__dso_handle'
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbeginS.o:(.data.rel.ro+0x0): first defined here
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtendS.o:(.tm_clone_table+0x0): multiple definition of `__TMC_END__'
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtendS.o:(.tm_clone_table+0x0): first defined here
make[2]: *** [lib/libmpicxx.la] Error 2
```
We should revert this patch so it can be properly fixed and tested. cc @yfguo

**Comment by raffenet** [comment]
@yfguo please take a look.

**Review by yfguo — APPROVED** [review]

**Pull request merged**
