### PR TITLE
L-0 implementation of MPL wrappers for GPU IPC

### PR DESCRIPTION
**Pull request by sagarth**
## Pull Request Description
Implementation of Level-zero ZE API of MPL interfaces for GPU IPC and GPU memory operations.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by sagarth** [comment]
@pavanbalaji Here's a draft PR for ZE IPC support.

**Comment by sagarth** [comment]
@pavanbalaji This MPL IPC PR is ready for review.

**Comment by pavanbalaji** [comment]
> @pavanbalaji This MPL IPC PR is ready for review.

@sagarth Can you rebase it to master when you add fresh commits?

**Comment by pavanbalaji** [comment]
The MPL changes that are not related to ZE should be split out as a separate PR, instead of merging with this PR.  Also, this PR doesn't follow some of the mpich coding conventions, such as error checking macros, etc.

Was this really reviewed internally at Intel first?   Tagging @wesbland

**Comment by wesbland** [comment]
I didn't review this personally, but that doesn't mean no one else did. @sagarth is this intended to be a draft for early review?

**Comment by pavanbalaji** [comment]
> I didn't review this personally, but that doesn't mean no one else did. @sagarth is this intended to be a draft for early review?

I already did an early review for it earlier and recommended that it go through an Intel internal review, so we don't need to waste too much time going to nit-picks.

**Comment by sagarth** [comment]
We did go through internal review. Now I realize we probably focused more on the API changes and the ZE usage and missed the parts you pointed out. We'll do another round of internal review focusing on the coding convention and software engineering part. Also will separate the MPL changes and the ZE support into different PRs.

**Comment by zhenggb72** [comment]
hmm, this PR is still under review internally as this morning. Some changes are still need to be made. I don't think it is ready.

**Comment by pavanbalaji** [comment]
Let's reopen this when it's ready to be upstreamed.

**Pull request closed without merging**
