### PR TITLE
ch4: probe external libfabric/ucx and default netmod selection

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Always probe external libfabric and ucx. If found, use them as a preference.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
tagging @yfguo @raffenet

**Comment by hzhou** [comment]
test:mpich/custom
testlist: attr

**Comment by hzhou** [comment]
test:jenkins/custom --with-libfabric=embedded
netmod=ch4:ofi

**Comment by wesbland** [comment]
What's the goal for this PR? It looks like the end result is the same.

**Comment by hzhou** [comment]
Currently we default to use embedded libfabric or ucx. This PR probes system libs and use external libs by default when found. In addition, when user do not specify netmod, we use the  libfabric or ucx probe to decide which netmod to build.

This is a step toward making ch4 the default build in the coming 3.4a2 release.

**Comment by hzhou** [comment]
The implication for us is to pass explicit `--with-libfabric=embedded` in order to test embedded version (for consistency) if a external lib is also present. Otherwise, yes, the result is the same.

**Pull request merged**
