### PR TITLE
config: Update embedded hwloc settings

### PR DESCRIPTION
**Pull request by raffenet**
We already add visibility flags to AM_CFLAGS in Makefile.am. No need
for the extra setting here.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
@pavanbalaji let me know what you think of the changes here. They fix the embedded UCX build issue we were seeing. If these look OK, I can also update Hydra.

**Comment by pavanbalaji** [comment]
@raffenet this is reverting the hwloc visibility flags fix that I had previously done.  I believe this will break for platforms that do not have weak symbols (e.g., mac os).

**Comment by raffenet** [comment]
We already control visibility flags for libmpi.so here: https://github.com/pmodels/mpich/blob/master/configure.ac#L2973.

**Comment by pavanbalaji** [comment]
You are losing `HWLOC_EMBEDDED_VISIBILITY_CFLAGS`.

**Comment by raffenet** [comment]
Those are only useful if you are building hwloc as a shared library, though. We are embedding it, and control the visibility of symbols in our libraries our own way.

**Comment by pavanbalaji** [comment]
Hmm.  I remember having problems with it.  If the above build is passing with mac os, maybe it's not needed.  In that case, the relevant patch should be removed from our hwloc repo too.

**Comment by raffenet** [comment]
Hmm, I see where we could get into trouble if we let visibility flags be set in `HWLOC_CFLAGS` then unconditionally add them to `CFLAGS` when building libmpi. That issues remains without your patch to hwloc.

**Comment by raffenet** [comment]
IMO, this is an issue that the hwloc folks should address. Embedding hwloc shouldn't force you to setup your library for symbol visibility. I'll create an issue and reference our patch to see what they think.

**Comment by raffenet** [comment]
@pavanbalaji added a patch that should make it possible to revert https://github.com/pmodels/hwloc/commit/60ea104cb718e7e6bd8c8cf8cd35a9741f959fc6.
test:jenkins/ch3/most

**Comment by raffenet** [comment]
Made a tweak to avoid stomping on `--enable/disable-visibility` when set by `./configure`.
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
test:jenkins/ch3/most

**Comment by raffenet** [comment]
I opened https://github.com/open-mpi/hwloc/issues/283 about the visibility flags issue. In the meantime, I think my workaround is good enough. I'll update the Hydra config in a separate patch.

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
This PR looks good, but the tests seem to be failing.

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
Embedded UCX built successfully, but now there are test failures. Might need to update to the latest. I'll do so and re-retest. The failures in ch3/tcp are related to slurm, it looks like.

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Pull request merged**
