### PR TITLE
Remove accidently added POBJ EXIT/ENTER in ch3

### PR DESCRIPTION
**Pull request by jain-surabhi-23**
## Pull Request Description
Partial fixup for 4e0525483f3dce5a6d7a4f40fa0839595cddcabf

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:jenkins/warnings
test:jenkins/ch3/most

**Comment by hzhou** [comment]
What does this fix?

`POBJ` is not working last time I checked. 

test:jenkins/custom --enable-thread-cs=per-object
config: async
netmod: ch3:tcp

**Comment by jain-surabhi-23** [comment]
> What does this fix?
> 
> `POBJ` is not working last time I checked.
> 
The patch 4e0525483f3dce5a6d7a4f40fa0839595cddcabf touched `POBJ`, which was not intended. So undoing it here.

**Comment by hzhou** [comment]
> 
> 
> > What does this fix?
> > `POBJ` is not working last time I checked.
> 
> The patch [4e05254](https://github.com/pmodels/mpich/commit/4e0525483f3dce5a6d7a4f40fa0839595cddcabf) touched `POBJ`, which was not intended. So undoing it here.

I see. Should delete, not comment out then. Also describe exactly what this is doing in both the title and description. For example: "Commit [4e05254] accidentally added POBJ EXIT/ENTER. This commit undoes it. "

**Comment by jain-surabhi-23** [comment]
> Please delete the accidentally inserted line instead of commenting out and leave dead code. Also update the PR title and commit message stating exactly what this is.

I commented out the lines because before that patch, those lines were in comments. Anyway, I can just take it out.

**Comment by hzhou** [comment]
> > Please delete the accidentally inserted line instead of commenting out and leave dead code. Also update the PR title and commit message stating exactly what this is.
> 
> I commented out the lines because before that patch, those lines were in comments. Anyway, I can just take it out.

I see. In that case, just update the PR title and commit message then. I prefer not to have those commented-out code, but we can do that separately when we finally get to fix `POBJ` :).

**Comment by jain-surabhi-23** [comment]
@hzhou Fixed.

**Comment by jain-surabhi-23** [comment]
@hzhou Should I go ahead and merge it? Or you want to take care of that?

**Comment by hzhou** [comment]
> @hzhou Should I go ahead and merge it? Or you want to take care of that?

Go ahead :)

**Pull request merged**
