### PR TITLE
RMA: use winattr flag to optimize check for support of netmod native RMA

### PR DESCRIPTION
**Pull request by minsii**
## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by minsii** [comment]
test:mpich/ch4/most

**Review by raffenet — CHANGES_REQUESTED** [review]
Can you split the addition of the attribute and the change to ch4/ofi? That way ch4/ofi or ch4/ucx changes can be cleanly reversed, if needed. Otherwise looks good!

**Comment by minsii** [comment]
Fixed.

Retest after commit split and rebase over main:
test:mpich/ch4/most

**Review by raffenet — APPROVED** [review]
Change looks good to me. Need to investigate the ch4/ofi failures, but I think they exist outside of this PR.

**Comment by minsii** [comment]
Rerun ofi after rebasing and see if the ofi failure is consistent (but it should be irrelevant to this OR)

test:mpich/ch4/ofi

**Comment by minsii** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
> 
> 
> Change looks good to me. Need to investigate the ch4/ofi failures, but I think they exist outside of this PR.

It is a pipeline bug and @yfguo had fixed it and merged to main a few hours ago. :)

**Comment by minsii** [comment]
Great. The current run should already include Yanfei's fix. I will merge after the jobs done.

**Pull request merged**
