### PR TITLE
ch4/ofi: fix for build without shm

### PR DESCRIPTION
**Pull request by AlexeyMalkhanov**

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
What is the configuration you're using to build that's failing? We build without ch4/shm and haven't seen this problem.

**Comment by AlexeyMalkhanov** [comment]
@wesbland the options are the following: ```./configure --prefix=<install dir> --enable-ch4-shm=no --enable-g=dbg --enable-debuginfo --enable-fast=O0 --with-device=ch4:ofi,stubnm --with-libfabric=<path_to_libfabric> --disable-ft-tests --enable-nemesis-dbg-localoddeven --enable-large-tests --disable-perftest```

**Comment by wesbland** [comment]
Interesting. That's essentially the same as what I'm using. I'll see if I can figure out why it wasn't causing problems for us.

**Comment by AlexeyMalkhanov** [comment]
@wesbland I use gcc 4.4.7

**Comment by wesbland** [comment]
Apparently it's because you include `stubnm` in your device string.

**Comment by raffenet** [comment]
I pushed this to master directly, rather than overwriting your master branch so I could click the merge button.

**Pull request closed without merging**
