### PR TITLE
coll: Remove overwriting request ptr to NULL in non-blocking collectives

### PR DESCRIPTION
**Pull request by shawnccx**
Request prt is passed down from device level, it is already to set to
NULL or allocated. Overwriting to NULL here will conflict second case.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [x] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [x] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
Can you give an example program or call path that would run into this issue? I'm having a hard time understanding the problem exactly. All other nonblocking collectives appear to do the same thing, FWIW, so we should fix all of them, if necessary.

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by shawnccx** [comment]
@raffenet , this is issue coming from our threading handoff model and collectives composition. Our threading handoff model will create request in advance and enqueue collective operation into scheduling queue. When the coll is dispatched from scheduling queue, we should not overwrite request pointer to NULL, since it was pre-allocated before.

Why this happens only for ibcast? The reason is at our side, we are only offloading ibcast, ireduce, and iallreduce to threading handoff model, and currently ibcast changes internal calling sequence and rises this issue.

TBH, I'm not sure if I should sync this change to master. But by looking at any collective code, request pointer is set to NULL in MPI_functions, there is no need to do it again in MPIR_func_impl. Like you said above, it should apply the same change to all other nonblocking collectives.

**Comment by raffenet** [comment]
Ah, I see. Handoff was the piece I was missing for my understanding. You are probably right about this being redundant, though. I'm not opposed to removing it still, but want to make sure we consider all the possible uses.

**Comment by shawnccx** [comment]
I didn't see all the spawn failures on our side, need to check why master branch has those failures.

**Comment by raffenet** [comment]
Oh, those should be fixed if you rebase onto the latest master.

**Comment by shawnccx** [comment]
Got it. Just rebased.

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
The change looks OK to me. Tests are clean. Can you update the PR to do the same thing for all NBCs?

**Comment by shawnccx** [comment]
@raffenet Updated for all non-blocking collectives.

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by shawnccx** [comment]
@raffenet Are you aware the ch3 failures here are related to this commit? We didn't test CH3 on our side.

**Comment by raffenet** [comment]
@shawnccx I will check and see what is causing them.

**Comment by raffenet** [comment]
ch3 is calling `MPIR_Ibarrier` during `MPID_Win_fence` and expecting either `NULL` or a valid request back. This change is breaking that expectation. There's probably a couple of ways to fix this. I will look at it more closely tomorrow.

**Comment by raffenet** [comment]
test:jenkins/ch3/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most

**Comment by raffenet** [comment]
@shawnccx FWIW, I'm hesitant to merge this without the full picture. I.e. "handoff model and collectives composition" you mentioned above. Is it OK to wait for this change until the larger work is ready?

**Comment by shawnccx** [comment]
Sure, understand. FYI @hajimefu

**Comment by raffenet** [comment]
Closing for now. This can be revived when there is additional code that takes advantage of the change.

**Pull request closed without merging**
