### PR TITLE
Large test

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
@hajimefu @wesbland This is an alternative to #2370. Let me know if it works for the original use case. We'll also have to modify our Jenkins scripts to enable the large tests in our review and nightly testing.
test:jenkins/ch3/all

**Comment by raffenet** [comment]
A caveat here might be that this creates an **exactly** 8GB datatype. If we need to go a little bigger to trip the threshold in libfabric, I can make a modification.

**Comment by wesbland** [comment]
The one thing I'd like to see along the lines of things we'd discussed previously is to shorten the test to just run the large iteration (it's already running all of the previous iterations just before). Things like that would simplify the test suite run time dramatically.

Maybe that's a separate issue, but I'd still love to see the tests shortened have more tests that run more quickly.

**Comment by raffenet** [comment]
The test in this PR does a single send/recv with large datatype, unlike the previous submission. Are you suggesting running just the 8GB version and dropping the 2 and 4GB variants? We could probably do that...

**Comment by wesbland** [comment]
Ok, I misunderstood then. I thought it was going to run the same thing as all the previous tests (iterate up to the large size). This is fine then.

**Comment by raffenet** [comment]
@hajimefu reminder to test this out and see if it trips the threshold you were testing for. Also check if there are additional cases to look for (e.g. underflow, truncation).

**Pull request merged**
