### PR TITLE
[DO NOT MERGE] ch4/ofi: Update to latest 1.7.x revision

### PR DESCRIPTION
**Pull request by raffenet**
For testing.

## Pull Request Description

Draft PR for testing libfabric 1.7.x branch in anticipation of 1.7.2 release.

## Expected Performance Changes

n/a

## Known Issues

n/a

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [ ] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/warnings

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
@hzhou this is warning clean at least for the compilers in the base warning checker. Can you run the other configurations that are available? We can keep this open and re-run it as libfabric 1.7.2 nears release.

**Comment by hzhou** [comment]
test:more/warnings

**Comment by hzhou** [comment]
Actually the warnings scripts uses separately built submodules to isolate the warnings, so it won't even check the submodule update. The "custom" test goes through the normal build process, but only for one compiler at a time.

test:mpich/custom --with-device=ch4:ofi

**Comment by hzhou** [comment]
test:mpich/custom --with-device=ch4:ofi
compiler=gcc-4.6

**Comment by hzhou** [comment]
test:mpich/custom --with-device=ch4:ofi
compiler=gcc-4.6
testlist: coll/allgather2 10

**Comment by hzhou** [comment]
test:mpich/custom --with-device=ch4:ofi --enable-strict
compiler=gcc-4.6
testlist: coll/allgather2 10

**Comment by raffenet** [comment]
test:mpich/custom --with-device=ch4:ofi --enable-strict
compiler=gcc-4.6
testlist: coll/allgather2 10

**Comment by raffenet** [comment]
test:mpich/custom --enable-strict
compiler=gcc-4.6
testlist: coll/allgather2 10

**Comment by hzhou** [comment]
The tests reveals one missing warning in `hydra` -- wonder why my warnings script didn't catch it.

The `ucx` won't build with `--enable-strict` (known).

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi
test:mpich/warnings

**Comment by raffenet** [comment]
test:mpich/warnings

**Comment by raffenet** [comment]
This has gone stale. Will re-open a new PR for v1.8.0.

**Pull request closed without merging**
