### PR TITLE
CH4/OFI: changed default OFI capability flags

### PR DESCRIPTION
**Pull request by hoopoepg**
- updated supported capabilities for verbs provider
- FI_RMA capability is mandatory
- FI_DELIVERY_COMPLETE flag is required for native RMA support only

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
added prov/verbs config to jenkins. testing again:
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
@hoopoepg these changes look okay to me, but should I be able to run CH4 on top of OFI/verbs with this branch? Our Jenkins tests bomb out choosing a provider at init time. See: https://jenkins.mpich.org/job/mpich-review-ch4-ofi/395/compiler=gnu,jenkins_configure=default,label=ib64,ofi_prov=verbs/console

**Comment by hoopoepg** [comment]
hi
yes, verbs provider should work in partial fallback (all RMA operations should be wrapped to active messaging) mode, not completely because fallback/AM mode is under development.
verbs provider may be enabled on infiniband interconnects only (by default it looks for ib** network interface)

**Pull request merged**
