### PR TITLE
ch3/ch4: Communicator infohints infrastructure

### PR DESCRIPTION
**Pull request by sagarth**
**Scope of this PR**
- This PR adds device-level communicator infohints infrastructure for MPICH. 
- It migrates the earlier supported CH3 and CH4 hints from MPIR-based to to this infrastructure.
- It adds communicator hints that are added in the MPI 4.0 standard.
- It does NOT introduce any hint-based new optimization.

**Commit sub-categories**
Each commit in this PR falls under one of the following sub-categories:
- Introduce new infrastructure support
- Migrate MPI communicator hints from the old (MPIR) to the new (MPID) infrastructure
- Cleanup / Remove the unused code from the old infrastructure
- Add new tests

**Two types of hints**
Comm info hints can be of two types: `immutable` and `mutable`. `Immutable` hints can be applied only when a communicator is created and its value cannot be modified at a later time by using MPI_Comm_set_info. On the contrary, `mutable` hints can be set or modified at both communicator creation time and a later time. 

There are separate device level hooks to set the immutable and mutable hints:

- `MPID_Comm_set_info_immutable`
- `MPID_Comm_set_info_mutable`

The get routune `MPI_Comm_get_info` returns both mutable and immutable hints.

**Comm info hints at different levels**
A comm info hint can be stored at one of: `CH4`, `NM` or `SHM` level. Hints stored at `CH4` level is applicable to all devices and providers. However, the hints stored at `NM` or `SHM` level are applicable only to that level. 

**PowerPoint slide deck from a CH4 call discussion.**
[ST-MPICH_CH4-CommHintsInfrastructure-Nov012018.pptx](https://github.com/pmodels/mpich/files/2784582/ST-MPICH_CH4-CommHintsInfrastructure-Nov012018.pptx)

### CODE REVIEW

**Comment by pavanbalaji** [comment]
@sagarth I need a bit more context on this:

1. Is the idea that some info hints are mutable and some are immutable?  And when a hint is set, we mark it as such?

2. What kinds of hints are mutable?

3. Why do we need hooks all the way down to the netmod?  Is the idea that a hint is "mutable" by default, but it can be set to immutable by any layer in MPICH?

Btw, the stud MPID routines for ch3 and ch3 patches should be squashed together.  Otherwise, with only the ch3 patch, ch4 won't build.

**Comment by sagarth** [comment]
I just attached to the PR description PowerPoint slides that was used during a CH4 call discussion. That may also be helpful in understanding the design.

**Comment by sagarth** [comment]
@pavanbalaji Sure, let me try to elaborate on this. 

**What kinds of hints are mutable?**

As I mentioned above, mutable hints are those whose value can change even after a communicator is created. It maybe helpful to look at the both categories to understand the mutable:
- immutable: hints that can be sent only at communication creation time and
- mutable: hints that do not have this restriction and therefore can be set or modified at anytime/"runtime"

The MPI standard indicates that an implementation can put the above restriction of the immutable hints to some hints. But the standard also indicates this restriction may not be applicable to all hints - which means some hints are treated in a more relaxed as in the case of mutable hints here.

**A common solution**
We used this internal categorization also as a common solution way to support the multiple code paths that can operate on the comm hint values, e.g., `MPI_Comm_dup_with_info`, `MPI_Set_info`, `MPI_Dist_graph_create` etc.

**Tentative names**
We chose the names `mutable` and `immutable` as tentative names during the implementation. But we  can consider changing the names, e.g., to `creationtime` and `runtime`, if you would be more comfortable with it.

When you asked this question, were you looking for specific examples of mutable hints or a general description like this?

**Comment by sagarth** [comment]
@pavanbalaji I see - thanks for clarifying. I had a little double that you could be asking for an example instead (my last sentence above). 🙂  

Here are few potential scenarios where we can use mutable hints:
- Currently netmod/ofi has a boolean comm hint `eagain` that is used to control whether to retry when an OFI call returns `FI_EAGAIN`. We could utilize the mutable behavior to flip `eagain` from true to false in a certain phase of an application and make MPI not do the retry.
- User can use a mutable hint to switch between multiple internal algorithms on the fly, e.g., choose different collective algorithms for different collective calls or during different phases of an application, while using the same communicator.
- Lets say in a communicator is collecting some kind of data (e.g., log). We could use a mutable hint to turn this feature on and off as required, on the fly. (this is just a possible scenario for future)

**Comment by pavanbalaji** [comment]
@sagarth For those hints (such as `EAGAIN`), what happens when one thread is issuing an operations while another thread is changing it?  I think that would need to be restricted to comm-create time too.  I have two major comments:

1. While I agree that some infrastructure to keep track of when a hint can be updated is good to have, I'm not sure when we'd use anything more than immutable.  So should we delay this till we actually have a hint that can use this?  I'm OK either way and I appreciate the cleanliness of having such a framework.

2. I'd recommend generalizing this further than just immutable or mutable.  What you are really trying to do is limit the scope in which an info key can be updated.  That can be comm-create time only, init-time only (e.g., hints that are not specific to communicators), whenever the user wants, or maybe some other scope that we come up in the future.  Just mutable and immutable might not be sufficient.

**Comment by pavanbalaji** [comment]
If we are doing this, we should do it the right way.

The scope should just be a parameter for the function, rather than a part of the function name so we can extend it to more scopes later.

Also, the scope information should be stored in a global table somewhere so when the user asks to update an info key, the upper layer can simply check its modification scope and either accept the change or reject it.

I still don’t understand this hooks for each layer when the user tries to edit a hint.  Each layer is managing its own hints.  So why does it need to tell the other layers what the scope of it’s mutability is?

**Comment by raffenet** [comment]
The hook-based design was chosen because that is the way MPICH accepts info settings for RMA windows (in ch3 and ch4).

**Comment by pavanbalaji** [comment]
I guess my point is, each layer already sees the hints when they are set (though the hooks during info set time), and it stores it in its layer.  Why does it need to expose whether the hint is mutable or not to others?

**Comment by sagarth** [comment]
Those are good ideas. When we provide full support for the different scope types, a global table, adding a hook function parameter, and potentially checking modification scope at upper layer would he helpful.

What I was suggesting for this PR was, let's introduce changes that would support only "comm-create-time" modification scope, but in a way such that it could be easily extended in future to support the multiple scopes.

I agree function parameter would be better to handle the mutability type than a part of the function name, especially when we could potentially have many types. But for now, if we are supporting a single type, the addition of the parameter can be optional. We could either add it now, or add it in future when we support the multiple types. 

Similarly, we could postpone the addition of global table mechanism for the future extension as well. We could document some of these ideas/requirements somewhere, maybe as brief code comments.

**Comment by sagarth** [comment]
@pavanbalaji For the hook layers, I think each layer is not exposing mutability of its hints to the other layers. Currently, only MPID layer informs each of CH4R, NM, and SHM layers to whether work on mutable or immutable hints. Those layers then use that info to process the relevant hints. But as discussed above, we could refine this further, e.g., by using function parameters instead. 

I'm not sure if I was able to completely address your question on this issue. Let me know.

**Comment by sagarth** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
@sagarth should this PR be closed

**Comment by sagarth** [comment]
Superseded by #4260

**Pull request closed without merging**
