### PR TITLE
datatype: clean up argument error testing

### PR DESCRIPTION
**Pull request by hzhou**
The PR is related to issue #1738, a very old issue and apparently, nobody really cared :). But as it is valid enough to have an issue for it, there is as much valid reason to take care of it -- mostly it is because it was assigned to me. As I look into it, a few gross points stick out: 

1. Why we have two `ERROR_CHECKING` blocks? 

2. Why the `_x` and none `_x` versions are different?

3. Why did we choose to manually add more datatype argument tests and duplicating everywhere rather than amending the existing macro `MPIR_ERRTEST_DATATYPE`?

So I went ahead did some cleaning (more than the original issue suggested). Let reviewers and tests to see if I had misunderstandings and broke something.

EDIT: this PR at this point serves as a demonstration of how much redundancy are in the MPI layer. Rather than merging this PR (and potentially many more to come), I am leaning toward the solution of scripting away the entire MPI layer based on man pages. 

The script will not only ensure the consistency of error checking, it will also make future changes -- updates or fixes -- easier to handle. The script can also take option to generate code with or without macros, concise or verbose versions, therefore, facilitate static analysis, debugging, or profiling.

### CODE REVIEW

**Comment by hzhou** [comment]
Personally, I dislike padding `\` in the multi-line macros very much and prefer the style of single space ' \'. I am ok to do the reformat before committing.

**Comment by hzhou** [comment]
test:jenkins/ch3/sock

**Comment by hzhou** [comment]
The MPI layer in mpich are largely boiler-plates yet there are enough details, especially in argument checking that we tend to introduce inconsistencies and potentially hidden errors. We could use a script to generate the entire MPI layer based on, e.g. man pages. It'll be a great pleasure for me take on this task if I get support of the team. :)

**Comment by hzhou** [comment]
There are two versions of `datatype` argument check: `MPIR_ERRTEST_DATATYPE_BASIC` does not require the datatype to be committed; `MPIR_ERRTEST_DATATYPE` checks whether the datatype is committed as well.

**Comment by hzhou** [comment]
Added a patch for collective datatype errtest code, removing more than 700 lines. This is just a demonstration of how much duplicated code are there.

**Comment by hzhou** [comment]
test:jenkins/ch3/sock

**Comment by hzhou** [comment]
MPI functions for communication will require the datatype to be committed. MPI functions in the datatype subtree may or may not require committed datatype. The man pages should clearly declare such and the script can easily generate the right version of argument test according to the man pages.

**Comment by hzhou** [comment]
Cleaned up the macros for the entire `datatype` subtree. Retesting...

test:jenkins/ch3/sock

**Comment by pavanbalaji** [comment]
This is generally a good change (conceptually), but it creates a lot of code churn.  It should be delayed till the next major release.

**Pull request closed without merging**
