### PR TITLE
move all submodules to a single directory

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Consolidate submodule locations instead of scattering among the repo.

## Expected Impact

Developer working copies may be confused if switching between the new and old locations.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by wesbland** [comment]
One of the reasons we put things where they are currently is to preserve the modularity of a particular netmod (or anything else that contains a submodule. For example, the OFI submodule is only used inside the ch4/ofi netmod so it makes sense to live there along with all of the detection/configure logic that goes along with it.

My moving everything into a single location, you lose that isolation.

**Comment by hzhou** [comment]
Only the third-party code is moved to `modules` folder. Just because the ofi-netmod uses `libfabric` does not mean `libfabric` is part of ofi-netmod. To illustrate the point, ofi-netmod uses libc and mpl, one wouldn't think either as part of ofi-netmod, right? The argument that only `ofi-netmod` uses `libfabric` is more a temporary fact than a design choice. What if we accommodate two netmods that both uses `libfabric`? As for the detection/configure logic, I have a open PR #3430, that is trying to move that logic to `confdb`. The reason is the same, that the detection/configure logic of `libfabric` is not netmod-specific.

**Comment by wesbland** [comment]
Ok, but I think this and #3430 would need to move together then. Otherwise things won't build, right?

**Comment by hzhou** [comment]
> Ok, but I think this and #3430 would need to move together then. Otherwise things won't build, right?

#3430 is too big to be reviewed. I will break them into smaller PRs next. It is trivial to rebase on top of this PR if it gets merged first.

**Comment by pavanbalaji** [comment]
Why is this dependent on #3430?  This is just moving the location of third-party modules, isn't it?  This should either be merged or closed.  It's been sitting open for 6 months now.

**Comment by pavanbalaji** [comment]
@hzhou   Is this being pursued or should it be closed?

**Comment by hzhou** [comment]
> @hzhou Is this being pursued or should it be closed?

To clarify, my comment was we should also unify the library checking and configure routines, which was what's in #3430. This PR is simply moving submodule locations, it is not dependent on other PR. Just need update.

**Comment by pavanbalaji** [comment]
> > @hzhou Is this being pursued or should it be closed?
> 
> To clarify, my comment was we should also unify the library checking and configure routines, which was what's in #3430. This PR is simply moving submodule locations, it is not dependent on other PR. Just need update.

I agree.  This is not dependent on other PRs.  This can be merged once it's rebased.

**Comment by pavanbalaji** [comment]
@raffenet Is this PR still being pursued?

**Comment by raffenet** [comment]
Yes, I will get it back into shape today.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Pull request merged**
