### PR TITLE
coll: fix warnings in MPII_COLLECTIVE_FALLBACK_CHECK

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Try a better fix than previous PR #4381 

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/warnings/quick

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
@pavanbalaji Would you like review?

**Comment by hzhou** [comment]
@jain-surabhi-23 Could you take a look and make sure the change work with `MPITUNE`?

**Comment by zhenggb72** [comment]
This prints an additional line which will affect our mpitune scripts. But I don't think it is a big deal, we can fix that.

**Pull request merged**
