### PR TITLE
Fix MPL/ROMIO build failure with `--enable-strict`

### PR DESCRIPTION
**Pull request by hajimefu**
Introducing `MPL_aligned_alloc` (6d2f601) broke MPL/ROMIO builds with `--enable-strict`. This PR fixes it by defining `AC_USE_SYSTEM_EXTENSIONS` in MPL/ROMIO configure scripts.

@raffenet Could you invoke the test for FreeBSD in addition to Linux? We hope that this fix will also fix the FreeBSD build failure with `--enable-strict`.

### CODE REVIEW

**Comment by hajimefu** [comment]
@raffenet have you tested these patches?

**Comment by hajimefu** [comment]
Or do you think #2906 is enough?

**Comment by raffenet** [comment]
Oh, shoot. I missed these. Let me test them, as they are probably still needed.

**Comment by raffenet** [comment]
test:jenkins/ch3/most

**Comment by raffenet** [comment]
rebased on latest master.
test:jenkins/ch3/most

**Comment by raffenet** [comment]
These look fine, but they aren't fixing anything in our current test setup, so I'm going to hold them until after the beta just to study a little more.

**Comment by raffenet** [comment]
@pmodels/mpich-core can anyone think of a good reason not to enable `AC_USE_SYSTEM_EXTENSIONS` in mpl or romio? We recently added it to the main MPICH configure, so it's probably less controversial at this point, but it still makes me somewhat uneasy.

**Comment by pavanbalaji** [comment]
I had added it to mainline mpich for the hwloc integration.  The only downside that I can think of is that system-specific extensions will no longer generate warnings during the build.  So we'll need to be extra careful when we write code.

**Comment by raffenet** [comment]
Given the long-term goal of integrating ROMIO, I think any objection will expire at this point. I'm inclined to go ahead with this change. I'll resolve the current conflict and re-test.

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Pull request merged**
