### PR TITLE
mpl: two fixes for local address resolution

### PR DESCRIPTION
**Pull request by keszybz**
## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Review by hzhou — APPROVED** [review]
Looks good to me

**Comment by hzhou** [comment]
@keszybz Could you sign the Contributor's agreement: https://wiki.mpich.org/mpich/index.php/Contributing_to_MPICH ?

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most
test:mpich/warnings

**Comment by raffenet** [comment]
> @keszybz Could you sign the Contributor's agreement: https://wiki.mpich.org/mpich/index.php/Contributing_to_MPICH ?

Signed agreement has been received.

**Comment by hzhou** [comment]
test:mpich/authorship

**Comment by hzhou** [comment]
test:mpich/warnings/auto

**Comment by hzhou** [comment]
test:mpich/warnings/quick

**Comment by hzhou** [comment]
test:mpich/warnings

**Pull request merged**
