### PR TITLE
ch4: fix thread safety in dynamic process related code

### LINKED ISSUE #4536: bug/jenkins: sporadic threads/spawn/th_taskmaster timeout
We are seeing sporadic time out in `ch4/ofi` review tests in `./threads/spawn/th_taskmaster`, both `1` and `2` process versions. 

I reproduced it locally, but it is very rare, in fact I failed to reproduce it twice. We'll track this. Each time we see the failure, add a record here, until we have some clue.

image

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Previously we missed a couple places for thread safety, which caused sporadic test failures, in particular, `./threads/spawn/th_taskmaster 2`. This PR fixes it.

The very reason that such bug escaped detection for so long is because the code is not grouped with code that share the same context. To prevent these mistakes, we now move these code together.

## Reference

Really fixes #4536

NOTE: we should revert #4544 - add lock to `MPIR_pmi_spawn_multiple` -- to verify that whether that is necessary.

Now tried and verified -- `PMI` protection is necessary.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
> 
> 
> This looks fine to me. Someone from @pmodels/mpich-intel should ACK the `ch4/ofi: move proc functions from ofi_init.c to ofi_spawn.c` patch. In case it causes conflicts, we should just drop it, so my approval is conditional.

Sounds good. Note that this particular move of code is entirely dynamic process related, should not cause conflicts with other components (other than the boundary).

**Comment by wesbland** [comment]
Yeah, there's a few conflicts, but I think it's probably fine.

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
@raffenet Turns out that PMI lock is also crucial. I added that lock back and also added a couple commits to clean up the mutex code. Could you take another look?

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Pull request merged**
