### PR TITLE
Fix hcoll integration (ch3 and ch4)

### PR DESCRIPTION
**Pull request by raffenet**
Based on the new collective framework branch, this branch does some general hcoll cleanup and moves the call/fallback logic into the device layer.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/mxm

**Comment by raffenet** [comment]
I just rebased this on mpich/master. If there is a better way to integrate the calls to hcoll collectives in the device layer, I am open to suggestions.

**Comment by raffenet** [comment]
One thing to consider, hcoll is basically providing `MPID_` functionality. Would it make more sense to do this integration one layer up instead?

**Comment by pavanbalaji** [comment]
It's specific to `mxm` and `ucx`, so I'm not sure moving it up a layer is a good idea.  In fact, even the `MPID common` layer is a little too high for it, but we only do that so we can share it between `ch3:mxm` and `ch4:ucx`.

**Comment by raffenet** [comment]
Right, `ch3` gets in our way a little bit here since there's nothing below the device layer for calling collectives. I'll move the integration down into the `ch4/ucx` netmod, since it sounds like that's preferred.

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/ucx

**Comment by pavanbalaji** [comment]
Are you suggesting dropping support for `hcoll` in `ch3`?  That's a big change.

**Comment by raffenet** [comment]
No, I'm saying leave it as it is in `ch3`, and only moving it lower in `ch4`.

**Comment by pavanbalaji** [comment]
It's right now in the `mpid/common` layer, so it's shared between `ch3` and `ch4`.  If you move it lower, it'll not be accessible by either `ch3` or `ch4`.

**Comment by raffenet** [comment]
Ah, I was only referring to the calls to `hcoll`, not the glue code. Strictly speaking, `hcoll` is an independent collectives library. Transport information is transparent to the caller, so I'm not sure moving the glue any lower makes sense. In fact, it probably *should* move up with the other collectives.

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch3/mxm

**Comment by raffenet** [comment]
testing a new Jenkins config...
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
testing a new Jenkins config...
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
testing a new Jenkins config...
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
testing one more time...
test:jenkins/ch4/ucx

**Comment by janjust** [comment]
@raffenet, Can we run this through some internal tests - I think we resolved all issues. The last issue hiding symbols is a configure issue.

**Comment by raffenet** [comment]
Test away! Things look pretty OK from our side. I have another set of patches I want to get in after the beta, in addition to the non-contig stuff, but those can wait.

**Comment by raffenet** [comment]
I'm looking at that now. Will have more info shortly.

**Comment by janjust** [comment]
OK, just fyi - all we did was pass this to configure to hide them, LDFLAGS="-Wl,--exclude-libs -Wl,libhwloc_embedded.a", worked like a charm. Similarly we'll do the same to HCOLL.

**Comment by raffenet** [comment]
I was under the impression our symbol visibility settings would hide all hwloc symbols, but it doesn't appear to be doing that. Let me give this a closer look today and see if there's anything I can do to make that happen.

**Comment by raffenet** [comment]
@janjust this last patch I added should effectively hide all hwloc symbols in `libmpi.so`. At least that is what I see in my experiments. I'm still going through the history to figure out why we set things up the way we did in case I am missing something. In the meantime, if you want to test this new version and confirm no extra flags are needed, that would be great.

**Comment by janjust** [comment]
They're still visible for me

```
00000000004a3bf0 T hwloc_topology_get_allowed_cpuset
00000000004a3c47 T hwloc_topology_get_allowed_nodeset
00000000004a3bae T hwloc_topology_get_complete_cpuset
00000000004a3c05 T hwloc_topology_get_complete_nodeset
00000000004a3b57 T hwloc_topology_get_depth
00000000004a2d34 T hwloc_topology_get_flags
00000000004a3b68 T hwloc_topology_get_support
00000000004a3bcf T hwloc_topology_get_topology_cpuset
00000000004a3c26 T hwloc_topology_get_topology_nodeset
00000000004a3023 T hwloc_topology_get_type_filter
00000000004a3b99 T hwloc_topology_get_userdata

tomislavj@hpchead ~/mtr/workspace/mpich$  git branch
* hcoll_integration
  master
tomislavj@hpchead ~/mtr/workspace/mpich$  git log --oneline -n 5
12e802a [WIP] stop mucking with hwloc visibility
a12000b hcoll: Check for init first in comm create hook
f8f2988 hcoll: Fix includes
a70a70b ch4/ucx: Call hcoll collectives if available
4ccc93c ch3: Call hcoll collectives if available
tomislavj@hpchead ~/mtr/workspace/mpich$  

```

**Comment by raffenet** [comment]
Hmm, that's weird. I force-pushed one more time to tweak the configure logic a little more. Not sure it will fix what you're seeing, but it's worth a shot.

**Comment by janjust** [comment]
sure I'll try it

**Comment by janjust** [comment]
still failing, and symbols are visible.

```
2467:00000000004a3c47 T hwloc_topology_get_allowed_nodeset
2468:00000000004a3bae T hwloc_topology_get_complete_cpuset
2469:00000000004a3c05 T hwloc_topology_get_complete_nodeset
2470:00000000004a3b57 T hwloc_topology_get_depth
2471:00000000004a2d34 T hwloc_topology_get_flags
2472:00000000004a3b68 T hwloc_topology_get_support
2473:00000000004a3bcf T hwloc_topology_get_topology_cpuset
2474:00000000004a3c26 T hwloc_topology_get_topology_nodeset
2475:00000000004a3023 T hwloc_topology_get_type_filter
2476:00000000004a3b99 T hwloc_topology_get_userdata
2478:00000000004a2b38 T hwloc_topology_init
2479:000000000049ecf6 T hwloc_topology_insert_group_object
2480:000000000049efd9 T hwloc_topology_insert_misc_object
2481:00000000004a3b43 T hwloc_topology_is_thissystem
```

**Comment by janjust** [comment]
I wonder, in your build, are they visible before the commits?
Do you see a difference in visibility when using nm?

**Comment by raffenet** [comment]
Yeah, before my changes I was seeing a mix of `t` and `T` hwloc symbols. After, I only see `t`. Let me double check my compiler.

**Comment by raffenet** [comment]
Ack, I had made a modification to the embedded hwloc. Need to re-test...

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by janjust** [comment]
👍  works now
and symbols are hidden

**Comment by raffenet** [comment]
Great, thanks for checking. I'll wait for this round of tests to run to ensure no regressions.

**Comment by raffenet** [comment]
OK one more set of tests, since I re-ordered things while adding signoffs...
test:jenkins/ch3/most
test:jenkins/ch4/most

**Pull request merged**
