### PR TITLE
remove obsolete defenitions and rename some structures

### PR DESCRIPTION
**Pull request by AlexeyMalkhanov**
This PR is polishing to collective selection infrastructure: remove obsolete definitions and introducing generic containers type

### CODE REVIEW

**Comment by AlexeyMalkhanov** [comment]
@raffenet I wanted to ask your advice on the following theme. In ch4_coll_params.h we have definition of MPIDI_coll_algo_container_t type. The name of this type doesn't specify that it applicable on ch4 level. At the same time in ofi(posix)_coll_params.h we define MPIDI_OFI(POSIX)_coll_algo_container_t which directly specifies  the level of applicability. Should not we rename MPIDI_coll_algo_container_t to MPIDI_CH4_coll_algo_container_t? The idea came to me when in the latter PR we have a need to create generic container type.

**Comment by raffenet** [comment]
@AlexeyMalkhanov no, `MPIDI_` prefix is sufficient for this case. Because we can only build one device implementation at a time, we decided that having `CH4` in function prefixes was redundant. We obviously have lots of instances where it is there, still, but hopefully they will be removed over time.

**Comment by AlexeyMalkhanov** [comment]
@raffenet, I got the idea. Could you please launch tests execution with these changes?

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Pull request merged**
