### PR TITLE
ch4/ucx: Update submodule to v1.6.0

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Update UCX to 1.6.0 for testing.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Passes tests (included warning check)
* [x] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [x] Commits are self-contained and do not do two things at once
* [x] Remove xfail from the test suite when fixing a test
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
testing rc5
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
Added a copy of pkg.m4 into UCX submodule to fix autoconf issue on some systems.

test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
@minsii ignoring the Travis test results, this should be OK to review. I'm trying to figure out why Travis is failing, but the failure looks similar to a previous version of the submodule that I explicitly fixed in this version.

**Comment by raffenet** [comment]
Hmm, the Travis CI failures are real and need to be resolved. I have created https://github.com/openucx/ucx/issues/4021 to track a dependency issue that complicates the UCX build process. Hopefully a fix will be quick, as a similar issue was recently resolved.

**Comment by raffenet** [comment]
Travis build issues are resolved. Re-testing on Jenkins one more time...
test:jenkins/ch4/ucx

**Comment by minsii** [comment]
That is great ! Thanks !

**Comment by raffenet** [comment]
All tests passed. There's not much here to review, but shall I add your approved tag to the merge @minsii?

**Comment by minsii** [comment]
I just merged as a practice for the new merge model :-)

**Pull request merged**
