### PR TITLE
mtest: split collective algorithm test variable

### PR DESCRIPTION
**Pull request by rkalidas**
The collective test variable "coll_algo_tests" has become too big and the build does not compile if we
add more algorithms.

### CODE REVIEW

**Comment by hzhou** [comment]
Why don't we produce a simple straight testlist: `test/mpi/coll/testlist.cvar`, which contains the output of this shell script?

**Comment by ruba1391** [comment]
You mean just eliminating the script and add the tests directly in a testlist file say `testlist.cvar`?

**Comment by hzhou** [comment]
> You mean just eliminate the script entirely and add the tests directly in a testlist file say `testlist.cvar`?

Yes. The script can still be kept in `maint` folder so we can regenerate the whole list again if we choose to. We can concatenate `testlist.cvar` in autogen.sh just as the way dtp tests are done.

**Comment by rkalidas** [comment]
Adding all the tests to `testlist.cvar` is a good idea. But do we have to keep on updating the script in maint whenever we add a new algorithm?

**Comment by hzhou** [comment]
> Adding all the tests to `testlist.cvar` is a good idea. But do we have to keep on updating the script in maint whenever we add a new algorithm?

I am glad you like it. No, I suppose we don't need keep on updating the script since that would defeat the purpose. The script is there for reference -- and we should have clear comments indicating so. Since these CVAR tests may need whole sale changes at some point, for example, add tests for certain collectives, expand or shrink the range of certain parameters, having a script to regenerate the change is more convenient. But for day to day, I suppose just updating the `testlist.cvar` directly makes more sense.

**Comment by rkalidas** [comment]
Ok, sounds good. I will make the changes and update the PR.

**Comment by hzhou** [comment]
@rkalidas Now we can simply generate `coll/testlist.cvar` in the same way `testlist.dtp`s are generated. Could you try it?

**Pull request closed without merging**
