### PR TITLE
testsuite: MPI_COMM_TYPE_HW_GUIDED is MPI-4.  do not assume it.

### PR DESCRIPTION
**Pull request by jeffhammond**
conditionalize MPI_COMM_TYPE_HW_GUIDED usage on MPI_VERSION > 4 to allow the test suite to function with more implementations.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Review by hzhou — APPROVED** [review]
LGTM

**Comment by hzhou** [comment]
Approved. But something is weird. I see 2 commits but only 1 showed up in "Files changed". I'll wait until that is sorted out.

**Comment by jeffhammond** [comment]
I committed twice to the same file. Changes macro method. Just squash on merge.

**Comment by hzhou** [comment]
I am merging it. But for next PRs, please follow the checklist, in particular:
* Commit message is of the form: module: short description

**Comment by jeffhammond** [comment]
ok, sorry.  i'll try to write them properly in the future.

**Comment by hzhou** [comment]
No worries 😄 Thanks for the contributions!

**Pull request merged**
