### PR TITLE
netmod API changes

### PR DESCRIPTION
**Pull request by yfguo**
Adding "addr" @raffenet

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
One small set of squashed changes. Testing once more before merge.
test:jenkins/ch4/ofi
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
Another fix for `am-only` UCX configuration:
test:jenkins/ch4/ofi
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
last test didn't trigger for some reason...
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
Unrolled the startall macros to make API change commit cleaner.
test:jenkins/ch4/ofi
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
@wesbland can you give a quick thumbs up or down to the first commit in this branch? I think we might have discussed at one point but can't remember. If you agree, I will merge these changes and move on to the ones from @hajimefu.

**Comment by wesbland** [comment]
👍  More of these types of patches are always welcome.

**Comment by hajimefu** [comment]
:+1: I'll create another PR for the VNI stuffs.

**Comment by hajimefu** [comment]
Created #2611.

**Pull request merged**
