### PR TITLE
AM fixes

### PR DESCRIPTION
**Pull request by raffenet**
1. Fix an issue with CH4 AM callbacks for RTS/CTS.
2. Implement missing functionality in UCX netmod.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/all

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
@monicasee As the current CH4 active message expert, can you review the first commit in this PR? As far as I can tell, it does not cause any regressions in the `am-only` configurations.

**Comment by monicasee** [comment]
OK, I will look this.

**Comment by raffenet** [comment]
@monicasee I updated this PR based on our discussion. Ready for review again when you have a chance.

**Pull request merged**
