### PR TITLE
test/mpi: remove accumulate tests using heterogeneous struct types

### PR DESCRIPTION
**Pull request by gcongiu**
`MPI_Accumulate` only supports homogeneous struct types (i.e., struct built
using the same predefined MPI datatype). We have now replaced the old
erroneous tests with new ones that use the same predefined datatypes.

### CODE REVIEW

**Comment by gcongiu** [comment]
test:jenkins/ch3/tcp

**Comment by gcongiu** [comment]
test:jenkins/ch3/tcp

**Comment by gcongiu** [comment]
test:jenkins/ch3/tcp

**Comment by yfguo** [comment]
test:jenkins/ch3/tcp

**Comment by gcongiu** [comment]
test:jenkins/ch4/most

**Comment by minsii** [comment]
OK. I will review it. Thanks !

**Pull request merged**
