### PR TITLE
Abstract out dataloop and segment code

### PR DESCRIPTION
**Pull request by pavanbalaji**
Hide dataloop and segment code and abstract it through a higher-level API that functions directly on the datatypes.

This is a prereq patch for #1985.

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp

**Comment by pavanbalaji** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/sock
test:jenkins/ch3/tcp
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/ofi

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch3/ofi

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch3/ofi

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by gcongiu** [comment]
@pavanbalaji I will look at this once back to office

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
Thanks, @yfguo.  This PR contains a subset of the recent warning cleanups, and is based on the older `libfabric` before the recent upgrade.  So a direct merge makes me uncomfortable.  Let me rebase on to `mpich/master` and rerun the tests one more time.

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most
test:mpich/warnings/more

**Comment by pavanbalaji** [comment]
Force pushed some warning squashes.  Testing again.

test:jenkins/ch3/most
test:jenkins/ch4/most
test:mpich/warnings/more

**Comment by pavanbalaji** [comment]
@yfguo I did some warning squashes compared to the previous version and rebased on to the latest `mpich/master`.  Would you like to review this again or can I go ahead and merge once the tests complete?

**Comment by yfguo** [comment]
@pavanbalaji I think the PR is good to go. You can merge it.

**Pull request merged**
