### PR TITLE
coll: refactor gen_coll.py

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Previously extra parameters in coll_algorithms.txt only applied to tsp
algorithms since only tsp algorithms have extra parameters. Refactor to
allow any algorithm to have extra parameters. We have to add more
wrapper functions so different types of "standard" extra parameters,
e.g. errflag in blocking collectives, can be dealt with as well.

[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
@nusislam Could you check if this PR works for your new algorithm?

**Comment by nusislam** [comment]
> @nusislam Could you check if this PR works for your new algorithm?

@hzhou - This works for my algorithms.

**Review by raffenet — APPROVED** [review]

**Pull request merged**
