### PR TITLE
binding/f90: Add `c_ptr` interface for `MPI_Alloc_mem`

### LINKED ISSUE #6691: fortran: MPI_Alloc_mem mismatch in argument
[From discuss mailinglist]

I'm sort of new to MPICH and I'm encountering one call that works with Open MPI but not MPICH. As such, I'm wondering if I built MPICH incorrectly or incompletely (always easy to miss a configure flag!).

To wit, I have a code like:
 ```
program main
   use mpi
   use iso_fortran_env, only: INT64
   use iso_c_binding, only: C_PTR

   integer(kind=INT64) :: sz
   type (c_ptr) :: ptr

   call MPI_Alloc_mem(sz, MPI_INFO_NULL, ptr, ierror)
end program main
```
 
If I compile with GCC 12.1 + Open MPI 4.1.3, all is well:
```
$ mpifort --showme:version

mpifort: Open MPI 4.1.3 (Language: Fortran)

mathomp4@discover23 ~/MPITests/CPtr master ?25

$ mpifort support_for_mpi_alloc_mem_cptr.F90

mathomp4@discover23 ~/MPITests/CPtr master ?25

$ echo $?

0
```
I'll also say Intel MPI builds this code as well.

But with MPICH 4.1.2 I just built:
```
$ mpifort support_for_mpi_alloc_mem_cptr.F90

support_for_mpi_alloc_mem_cptr.F90:9:53:

    9 |    call MPI_Alloc_mem(sz, MPI_INFO_NULL, ptr, ierror)

      |                                                     1

Error: Type mismatch in argument 'baseptr' at (1); passed TYPE(c_ptr) to INTEGER(8)
```
 

Now, my configure lines to Open MPI and MPICH are pretty boring, so the resulting mpiforts are as well:

```
$ mpifort -show

gfortran -I/discover/swdev/gmao_SIteam/MPI/openmpi/4.1.3/gcc-12.1.0/include -pthread -I/discover/swdev/gmao_SIteam/MPI/openmpi/4.1.3/gcc-12.1.0/lib -L/discover/swdev/gmao_SIteam/MPI/openmpi/4.1.3/gcc-12.1.0/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi

$ mpifort -show

gfortran -I/discover/swdev/gmao_SIteam/MPI/mpich/4.1.2/gcc-12.1.0/include -I/discover/swdev/gmao_SIteam/MPI/mpich/4.1.2/gcc-12.1.0/include -L/discover/swdev/gmao_SIteam/MPI/mpich/4.1.2/gcc-12.1.0/lib -lmpifort -Wl,-rpath -Wl,/discover/swdev/gmao_SIteam/MPI/mpich/4.1.2/gcc-12.1.0/lib -Wl,--enable-new-dtags -lmpi
```
 
But I see Open MPI has that "mpi_usempi_ignore_tkr", is it possible that's what is doing it?

Perhaps we just need to recode the code (using transfer, etc?)

EDIT:
The option flag doesn't seem to help:
```
$ mpifort -fallow-argument-mismatch support_for_mpi_alloc_mem_cptr.F90

support_for_mpi_alloc_mem_cptr.F90:9:53:

    9 |    call MPI_Alloc_mem(sz, MPI_INFO_NULL, ptr, ierror)
      |                                                     1
Error: Type mismatch in argument 'baseptr' at (1); passed TYPE(c_ptr) to INTEGER(8)
```
I did test and, yes, mpi_f08 does let it work. I think the issue is I'm not sure the library this is in can assume mpi_f08 support for all supported compilers.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Add `c_ptr` interface for `MPI_Alloc_mem` in Fortran `use mpi` binding.

[skip warnings]
Fixes #6691

## Notes
I added a test `test/mpi/f90/misc/alloc_mem.f90`. It assumes the Fortran compiler supports ISO_C_BINDING c_ptr.
Should we add conditionals to check the feature availability? -- Seems messy since this is Fortran.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Review by raffenet — APPROVED** [review]
LGTM

**Pull request merged**
