### PR TITLE
CH4 Collectives framework

### PR DESCRIPTION
**Pull request by akhillanger**
Work in progress. Request for comment/feedback.
Review entire PR instead of individual commits. Commits will be squashed.

### CODE REVIEW

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by akhillanger** [comment]
Closing this. Will open a new one with the latest version.

**Pull request closed without merging**
