### PR TITLE
hcoll

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/mxm

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch3/mxm

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch3/mxm

**Comment by raffenet** [comment]
@vspetrov @janjust I have cleaned up the initial integration commit and split it into a number of smaller commits. Testing on our side looks good. Note that I have consolidated the envvars to enable hcoll. A user must specify `MPIR_CVAR_ENABLE_HCOLL=1` or `MPIR_CVAR_CH3_ENABLE_HCOLL=1 (not preferred)`.

Let me know if this looks OK. I am ready to merge into master, if so.

**Comment by janjust** [comment]
:+1: Looks good to me, datatypes can go in as a separate PR

**Pull request merged**
