### PR TITLE
Add support for Intel OneAPI compilers

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Add in checks for icx and ifx compilers, which are replacing icc and
ifort.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ofi
compiler: intel-oneapi

**Comment by raffenet** [comment]
test:mpich/ch4/ofi
compiler:intel-oneapi

**Comment by raffenet** [comment]
test:mpich/ch4/ofi
compiler:intel-oneapi

**Comment by raffenet** [comment]
test:mpich/ch4/most
compiler:intel-oneapi

**Comment by raffenet** [comment]
test:mpich/ch4/most
compiler:intel-oneapi

**Comment by raffenet** [comment]
Something changed in the Jenkins results. When I initially ran this, the mpi_f08 module would build and only the subarray tests would fail because that feature isn't yet supported with `ifx`. Now mpi_f08 doesn't get built or tested at all. Maybe related to #5794? It's weird because building this example by hand works just fine.
```
configure:38647: checking for Fortran 2008 support
configure:38678: icx -c    -O2 -DNETMOD_INLINE=__netmod_inline_ofi__ -D__HIP_PLATFORM_AMD__ -I/var/lib/jenkins-slave/workspace/mpich-review-ch4-ofi@4/jenkins_configure/default/label/centos64_review/src/mpl/include -I/var/lib/jenkins-slave/workspace/mpich-review-ch4-ofi@4/jenkins_configure/default/label/centos64_review/modules/json-c -I/var/lib/jenkins-slave/workspace/mpich-review-ch4-ofi@4/jenkins_configure/default/label/centos64_review/modules/hwloc/include -D_REENTRANT -I/var/lib/jenkins-slave/workspace/mpich-review-ch4-ofi@4/jenkins_configure/default/label/centos64_review/src/mpi/romio/include conftest.c >&5
configure:38678: $? = 0
configure:38786: ifx -o conftest     conftest.f conftest1.o  >&5
conftest.f(3): error #5149: Illegal character in statement label field  [M]
MODULE F08TS_MODULE
^
conftest.f(3): error #5149: Illegal character in statement label field  [O]
MODULE F08TS_MODULE
-^
conftest.f(3): error #5149: Illegal character in statement label field  [D]
MODULE F08TS_MODULE
--^
conftest.f(3): error #5149: Illegal character in statement label field  [U]
MODULE F08TS_MODULE
---^
conftest.f(3): error #5149: Illegal character in statement label field  [L]
MODULE F08TS_MODULE
----^
conftest.f(3): error #5118: First statement in file must not be continued
MODULE F08TS_MODULE
-----^
conftest.f(4): error #5149: Illegal character in statement label field  [I]
IMPLICIT NONE
^
conftest.f(4): error #5149: Illegal character in statement label field  [M]
IMPLICIT NONE
-^
conftest.f(4): error #5149: Illegal character in statement label field  [P]
IMPLICIT NONE
--^
conftest.f(4): error #5149: Illegal character in statement label field  [L]
IMPLICIT NONE
---^
conftest.f(4): error #5149: Illegal character in statement label field  [I]
IMPLICIT NONE
----^
conftest.f(7): error #5149: Illegal character in statement label field  [R]
REAL, PUBLIC       :: x
^
conftest.f(7): error #5149: Illegal character in statement label field  [E]
REAL, PUBLIC       :: x
-^
conftest.f(7): error #5149: Illegal character in statement label field  [A]
REAL, PUBLIC       :: x
--^
conftest.f(7): error #5149: Illegal character in statement label field  [L]
REAL, PUBLIC       :: x
---^
conftest.f(7): error #5149: Illegal character in statement label field  [,]
REAL, PUBLIC       :: x
----^
conftest.f(4): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: ( : % [ . = =>
IMPLICIT NONE
-------------^
conftest.f(8): error #5149: Illegal character in statement label field  [R]
REAL, PRIVATE      :: y
^
conftest.f(8): error #5149: Illegal character in statement label field  [E]
REAL, PRIVATE      :: y
-^
conftest.f(8): error #5149: Illegal character in statement label field  [A]
REAL, PRIVATE      :: y
--^
conftest.f(8): error #5149: Illegal character in statement label field  [L]
REAL, PRIVATE      :: y
---^
conftest.f(8): error #5149: Illegal character in statement label field  [,]
REAL, PRIVATE      :: y
----^
conftest.f(9): error #5149: Illegal character in statement label field  [L]
LOGICAL, PROTECTED :: z
^
conftest.f(9): error #5149: Illegal character in statement label field  [O]
LOGICAL, PROTECTED :: z
-^
conftest.f(9): error #5149: Illegal character in statement label field  [G]
LOGICAL, PROTECTED :: z
--^
conftest.f(9): error #5149: Illegal character in statement label field  [I]
LOGICAL, PROTECTED :: z
---^
conftest.f(9): error #5149: Illegal character in statement label field  [C]
LOGICAL, PROTECTED :: z
----^
conftest.f(12): error #5149: Illegal character in statement label field  [A]
ABSTRACT INTERFACE
^
conftest.f(12): error #5149: Illegal character in statement label field  [B]
ABSTRACT INTERFACE
-^
conftest.f(12): error #5149: Illegal character in statement label field  [S]
ABSTRACT INTERFACE
--^
conftest.f(13): catastrophic error: Too many errors, exiting
compilation aborted for conftest.f (code 1)
configure:38786: $? = 1
configure: failed program was:
| 
| 
| MODULE F08TS_MODULE
| IMPLICIT NONE
| 
| ! Test public, private, protected
| REAL, PUBLIC       :: x
| REAL, PRIVATE      :: y
| LOGICAL, PROTECTED :: z
| 
| ! Test abstract
| ABSTRACT INTERFACE
|     SUBROUTINE user_func(x, y)
|         INTEGER  :: x(*)
|         REAL     :: y
|     END SUBROUTINE
| END INTERFACE
| 
| ! Test TS 29113 assumed type , assumed rank and bind(C)
| INTERFACE
|     FUNCTION FOO(A, B, C) &
|         BIND(C,name="foo_c") RESULT(err)
|         USE, intrinsic :: iso_c_binding, ONLY : c_int
|         TYPE(*), DIMENSION(..) :: A, B, C
|         INTEGER(c_int) :: err
|     END FUNCTION FOO
| END INTERFACE
| 
| 
| ! Test assumed-rank + asynchronous
| INTERFACE TEST_ASSUMED_RANK_ASYNC
|     SUBROUTINE TEST_ASSUMED_RANK_ASYNC_IMPL(BUF) &
|         BIND(C,name="test_assumed_rank_async_impl_c")
|         IMPLICIT NONE
|         TYPE(*), DIMENSION(..), ASYNCHRONOUS :: BUF
|     END SUBROUTINE TEST_ASSUMED_RANK_ASYNC_IMPL
| END INTERFACE TEST_ASSUMED_RANK_ASYNC
| 
| CONTAINS
| 
| ! Test TS 29113 asynchronous attribute and optional
| SUBROUTINE test1(buf, count, ierr)
|     INTEGER, ASYNCHRONOUS :: buf(*)
|     INTEGER               :: count
|     INTEGER, OPTIONAL     :: ierr
| END SUBROUTINE
| 
| ! Test procedure type and non-bind(c) x in C_FUNCLOC(x)
| SUBROUTINE test2(func)
|     USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_FUNLOC, C_FUNPTR
|     PROCEDURE(user_func)  :: func
|     TYPE(C_FUNPTR) :: errhandler_fn
|     errhandler_fn = C_FUNLOC(func)
| END SUBROUTINE
| 
| ! Test intrinsic storage_size
| SUBROUTINE test3(x, size)
|     CHARACTER, DIMENSION(..) :: x
|     INTEGER, INTENT(OUT) :: size
|     size = storage_size(x)/8
| END SUBROUTINE test3
| 
| END MODULE
| 
| !==============================================
| PROGRAM MAIN
| USE :: F08TS_MODULE, ONLY : FOO, TEST_ASSUMED_RANK_ASYNC
| IMPLICIT NONE
| 
| INTEGER, DIMENSION(4,4) :: A, B
| INTEGER, DIMENSION(2,2) :: C
| INTEGER                 :: ERRCODE
| INTEGER, DIMENSION(10), ASYNCHRONOUS :: IAR
| 
| ! Test contiguous and non-contiguous array section passing
| ! and linkage with C code
| ERRCODE = FOO(A(1:4:2, :), B(:, 2:4:2), C)
| CALL TEST_ASSUMED_RANK_ASYNC(IAR(2:7))
| 
| END PROGRAM
| 
configure:38810: result: no
```

**Comment by hzhou** [comment]
> Something changed in the Jenkins results.
> ...
> compilation aborted for conftest.f (code 1)
> ...

It was compiling the test code as `f77`. It should be `conftest.f90`. I think it must missing a `AC_PUSH_LANG(FC)` somewhere.

**Comment by SteveO-Cray** [comment]
> > Something changed in the Jenkins results.
> > ...
> > compilation aborted for conftest.f (code 1)
> > ...
> 
> It was compiling the test code as `f77`. It should be `conftest.f90`. I think it must missing a `AC_PUSH_LANG(FC)` somewhere.

FYI - if you are using a front-end wrapper for Fortran the wrapper may look at the ".f" and decide you want to compile with f77.  Or if there is only one Fortran compiler that handles f77, f90, and f08.

**Comment by raffenet** [comment]
> FYI - if you are using a front-end wrapper for Fortran the wrapper may look at the ".f" and decide you want to compile with f77. Or if there is only one Fortran compiler that handles f77, f90, and f08.

The `ifx` behavior does differ based on file extension, and the test will pass if using `.f90` but not with `.f`. I wonder how it ever got past the configure test in previous Jenkins runs. At least we know the issue.

**Comment by raffenet** [comment]
test:mpich/ch4/most
compiler:intel-oneapi

**Comment by raffenet** [comment]
test:mpich/ch4/most
compiler:intel-oneapi

**Comment by raffenet** [comment]
Everything but sanitizer builds pass now. This should be good to go. We can remove the F08 subarray xfails once the compiler supports them.

**Comment by raffenet** [comment]
test:mpich/ch4/most
compiler:intel-oneapi

**Comment by raffenet** [comment]
Removed `block` construct usage from subarray tests. Now everything passes (except sanitizers) and no xfails are added.

**Review by hzhou — APPROVED** [review]
LGTM.

**Comment by hzhou** [comment]
The tests failed. Make sure to resolve them

**Comment by raffenet** [comment]
> The tests failed. Make sure to resolve them

Only sanitizer configurations, which are not supported it seems. Our normal sanitizer builds use a specific GCC, so it shouldn't impact those builds. Review jobs that use these compilers will remain problematic, though. Same for any other compiler that doesn't support sanitizers. I presume we have a few others in the Jenkins scripts.

**Comment by hzhou** [comment]
> > The tests failed. Make sure to resolve them
> 
> Only sanitizer configurations, which are not supported it seems. Our normal sanitizer builds use a specific GCC, so it shouldn't impact those builds. Review jobs that use these compilers will remain problematic, though. Same for any other compiler that doesn't support sanitizers. I presume we have a few others in the Jenkins scripts.

I see. I guess we don't need to worry about it for now.

**Pull request merged**
