### PR TITLE
hydra: fix proxy topolib init

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

The topolib cannot be initialized until the procinfo has been read, since it contains the binding information.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
@thomasgillis confirmed this patch fixed not being able to see the binding information with `HYDRA_TOPO_DEBUG=1` in the environment. Since `HYD_pmcd_pmip.user_global.binding` was `NULL` while initializing the topology module, `ignore_binding` was set and no binding was actually done.

**Comment by raffenet** [comment]
Added a patch to hopefully enable the Hydra binding tests into the Jenkins results.
test:mpich/ch4/most

**Comment by raffenet** [comment]
> Added a patch to hopefully enable the Hydra binding tests into the Jenkins results. test:mpich/ch4/most

Oops, this won't work since there's no testlist in that directory. I'll have to amend...

**Comment by raffenet** [comment]
> > Added a patch to hopefully enable the Hydra binding tests into the Jenkins results. test:mpich/ch4/most
> 
> Oops, this won't work since there's no testlist in that directory. I'll have to amend...

And turns out those tests are going to need to be updated to work with recent hwloc versions, so I'm going to postpone that to a future PR/issue.

**Review by hzhou — APPROVED** [review]
LGTM

**Pull request merged**
