### PR TITLE
 coll: Add pipelined ring ibcast algorithm

### PR DESCRIPTION
**Pull request by akhillanger**

### CODE REVIEW

**Comment by akhillanger** [comment]
The renaming of the tsp based tree algorithm files has been done in the prereq PR #3035

**Comment by akhillanger** [comment]
Tagging @pavanbalaji for review.

**Comment by akhillanger** [comment]
@raffenet Fixed the conflicts and pushed. Yes, this is straight-forward, mimicking the tree-based ibcast that is already in. It is OK for others to review. There was no prior discussion. Thanks.

**Comment by raffenet** [comment]
test:jenkins/ch3/tcp

**Pull request merged**
