### PR TITLE
dummy commit to test whitespace checker

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
bot:retest

**Comment by danghvu** [comment]
My test is failing this whitespace checker, how do I know where to fix it @raffenet ?

**Comment by raffenet** [comment]
Just ignore it. I've disabled the checker as the hook isn't working correctly yet.

**Comment by raffenet** [comment]
@danghvu please add the pre-commit hook to your local git repo to check locally before submitting, though. That would help. See https://github.com/pmodels/mpich/wiki/Code-Cleanup-Procedure which includes a link to the hook.

**Pull request closed without merging**
