### PR TITLE
ch4/gpu: Remove visible to global id mapping

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

This mapping information is unused. The GPU code uses APIs provided by MPL to get the local-to-global id mapping.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Review by hzhou — APPROVED** [review]
This code allgathers each process's visibility table. I am okay with removing this unused code on the understanding that we will have a clean re-implementation.

**Comment by raffenet** [comment]
test:mpich/ch4/gpu

**Comment by hzhou** [comment]
@zhenggb72 Could you check whether there is Intel code depend on the code removed in this PR?

**Comment by raffenet** [comment]
I am trying to understand the GPU initialization process a little better, which led me to remove this code since it was unused. However, now I see that this code is gathering information that I actually want for a new feature.

My goal is to do this in a simpler way, but maybe that is more challenging than I think. At this stage of init, we in the pre-commit stage of `MPI_COMM_WORLD`. I suspect it and its associated subcomms are not yet ready for use, which is why the init_shm segment is being used directly. Is that correct? Otherwise I would just use `MPIR_Allgather`.

**Comment by hzhou** [comment]
> At this stage of init, we in the pre-commit stage of `MPI_COMM_WORLD`. I suspect it and its associated subcomms are not yet ready for use, which is why the init_shm segment is being used directly. Is that correct? Otherwise I would just use `MPIR_Allgather`.

Since it is shm domain, init_shm is efficient and with the least dependency. I do like the allgather interface. Maybe create a utility wrapper e.g. `initshm_allgather`? But I also think moving this code to comm_commit time (w MPIR_Allgather) should be fine as well if we are not concerned with the extra allgather. I think the code is cleaner that way.

**Comment by zhenggb72** [comment]
We used to use this code to handle ZE_AFFINITY_MASK, we even changed from int to int8 to deal with large number of devices. But we changed our implementation since then, so we don't use this code now. It is fine for us if you want to remove it.

**Pull request merged**
