### PR TITLE
Ethernet prefix update for comm_split_type

### PR DESCRIPTION
**Pull request by KavithaTipturMadhu**

### CODE REVIEW

**Comment by pavanbalaji** [comment]
The patches look fine to me.  Starting the tests.

test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by KavithaTipturMadhu** [comment]
Some rma and spawn tests are timing out/failing. The chages in this PR don't affect these tests. Shall I merge the pr @pavanbalaji?

**Comment by pavanbalaji** [comment]
@KavithaTipturMadhu No.  There are tests failing.  Please look at why they are failing.

**Comment by KavithaTipturMadhu** [comment]
test:jenkins/ch3/tcp
test:jenkins/ch3/sock
test:jenkins/ch4/ofi

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
Rebased on to the latest master and restarted the tests.

**Pull request merged**
