### PR TITLE
test/main: new collective cvar testlist generator

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Add a new cvar testlist generation script. The new approach splits the
generation script and the configuration data to allow better control of
the tests being generated.

Add cvar tests for non-gentran algorithms.

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ofi
testlist: coll/testlist.cvar

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
The generation script seems fine. I don't understand what is going on in the 3rd commit. Maybe someone else can review it.

**Comment by hzhou** [comment]
> 
> 
> The generation script seems fine. I don't understand what is going on in the 3rd commit. Maybe someone else can review it.

In the bcast algorithm, the `curr_bytes` is being updated during the execution. Thus, when we re-run the schedule in a persistent bcast, the `curr_bytes` need reset to the initial value before the rest of the execution. The only way to reset the value is to add the reset step as a `sched_cb` and also store the initial value with the state.

**Comment by raffenet** [comment]
> > The generation script seems fine. I don't understand what is going on in the 3rd commit. Maybe someone else can review it.
> 
> In the bcast algorithm, the `curr_bytes` is being updated during the execution. Thus, when we re-run the schedule in a persistent bcast, the `curr_bytes` need reset to the initial value before the rest of the execution. The only way to reset the value is to add the reset step as a `sched_cb` and also store the initial value with the state.
> 
> This fixes an already existing bug. The extended cvar tests revealed it.

OK, the fix seems fine. I guess I'm surprised there is no general persistent collective "reset state" API that gets called at every `MPI_START`, but that can be done separately if it turns out to be a good idea.

**Review by raffenet — APPROVED** [review]

**Comment by hzhou** [comment]
>  I guess I'm surprised there is no general persistent collective "reset state" API that gets called at every `MPI_START`, but that can be done separately if it turns out to be a good idea.

For the bcast case here, the state is a custom algorithm-specific state, and the general reset function has no knowledge of how to reset it -- resetting to zero would be wrong. So it has to be an algorithm specific reset (as callback).

**Comment by raffenet** [comment]
> > I guess I'm surprised there is no general persistent collective "reset state" API that gets called at every `MPI_START`, but that can be done separately if it turns out to be a good idea.
> 
> For the bcast case here, the state is a custom algorithm-specific state, and the general reset function has no knowledge of how to reset it -- resetting to zero would be wrong. So it has to be an algorithm specific reset (as callback).

Sure, I'm not envisioning a single reset function, but a general API implemented by all the persistent algos. I guess that's basically the same as sticking a callback in the schedule, or a function pointer in the request object. This  particular fix seems hyper specific to me, when I think overall the need for reseting state is broadly applicable.

**Comment by hzhou** [comment]
> This particular fix seems hyper specific to me, when I think overall the need for reseting state is broadly applicable.

I guess all the other algorithms are not dynamic enough that either doesn't need a state (most of them) or the state is initialized at creation and never need to be updated during executions.

**Pull request merged**
