### PR TITLE
ch4/ofi: Handle max msg size limit from OFI provider for RMA

### PR DESCRIPTION
**Pull request by shawnccx**
This PR contains 2 commits for ch4/ofi RMA:

- Fix number of iovecs estimation for Acc/Get_Acc.
- Handle max msg size limit from OFIprovider in RMA.

### CODE REVIEW

**Comment by shawnccx** [comment]
@raffenet can you kick off test for this PR? Only a few minor changes related to ch4/ofi in this PR.

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Pull request merged**
