### PR TITLE
coll: add MPIR_ERR_COLL_CHECKANDCONT macro

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

We repeat this 8-line error checking in collective paths many many times and it affects the readability and maintenance. Propose using a macro to improve.
 
## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by hzhou** [comment]
@wesbland I was going over coverity scan log and find this 8-line collective error checking makes code quite difficult to read. Besides, I am not sure about the implication of these usages -- what if in some cases we simply can continue or maybe we need more detailed error code. In either way, I think having a macro so we have easier time to locate the points and a single place to tuning will be nice.

What do you think? I only did this to `release_gather.c`. If we agree to proceed, I'll apply the changes to the rest of the collectives.

**Comment by wesbland** [comment]
I’m not excited about all the merge conflicts from making this change everywhere. It’s probably a good change though.

**Comment by hzhou** [comment]
> 
> 
> I’m not excited about all the merge conflicts from making this change everywhere. It’s probably a good change though.

Thanks for giving me feedback, although I would wish a clearer one :). If you support it, I'll move ahead. If you against it, I'll keep patching it -- adding one more straw to the existing pile. Ambiguous signal doesn't help me out of the difficult position 😄

**Comment by wesbland** [comment]
I guess go ahead...

**Comment by pavanbalaji** [comment]
This is barely a 100-odd line code change, that are basically almost entirely restricted to a single file.  I wouldn't be too worried about the conflicts.  This needs to be rebased and tested to prepare for merging.

**Comment by hzhou** [comment]
> 
> 
> This is barely a 100-odd line code change, that are basically almost entirely restricted to a single file. I wouldn't be too worried about the conflicts. This needs to be rebased and tested to prepare for merging.

Let me finish up the rest and you'll have a better picture :)

**Comment by hzhou** [comment]
test:mpich/warnings/quick

**Comment by hzhou** [comment]
test:mpich/warnings/quick

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by pavanbalaji** [comment]
> > This is barely a 100-odd line code change, that are basically almost entirely restricted to a single file. I wouldn't be too worried about the conflicts. This needs to be rebased and tested to prepare for merging.
> 
> Let me finish up the rest and you'll have a better picture 😄

Oh, god.  This suddenly became a lot more intrusive.  Now it's no longer OK to merge in this way.  This should be delayed to the next major release.

**Comment by wesbland** [comment]
I'd imagine this one won't actually generate that many conflicts since it's not very likely that anyone has changed the code being removed here.

**Comment by pavanbalaji** [comment]
We can reopen it if it's not a problem to merge this in.

**Comment by pavanbalaji** [comment]
> We can reopen it if it's not a problem to merge this in.

Actually, Cray makes a lot of collectives changes too.  So they might not be happy with this.  Maybe it's better to delay it.

**Pull request closed without merging**
