### PR TITLE
ch4: re-inlining ch4 progress functions

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

While the performance benefit of inlining progress is small, it is
nevertheless measurable. Besides, whenever we have performance issues,
the inlining/uninlining always come as a suspect. Let's keep the
progress functions inlined to simplify our performance analysis.

We only inline the ch4-layer progress, which is most heavy and
complex. We'll leave the netmod/shmmod progress inlined for now until
further necessity.

[skip warnings]
## Reference

PR #3877 - ch4: uninline progress engine

The latency number posted in that PR description didn't show any difference. However, the test was not bound to the HCA socket, so that may include additional latency due to memory movement.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [ ] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by hzhou** [comment]
Uninlining ch4 progress (1st commit) on Intel Xeon E7-8867 @ 2.50GHz UCX infiniband gains small message latency by `0.003 µs`

**Comment by hzhou** [comment]
The 2nd commit, uninlining `MPIDI_NM_progress` had no effect in the latency: `0.0426 ± 0.0044 µs`

**Comment by hzhou** [comment]
The 3rd commit, fast path for single vci config, saves `~0.001 µs`. The effect is very much in the noise.

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
Since there are concerns about compilation time -- I still haven't uninlined `MPIDI_OFI_dispatch_function` yet. Here are a quick check of compilation time (on a beefy skylake server):
```
make clean && time make -jx all
-j 48:
    this PR   (f48a157)    56.7"
    main      (ba43ff0)     56.6"
    pre3877(1546e7b)    2'27.9"
-j 8:
    this PR    54.3"
    main       52.4"
    pre3877  3'30.3"
```
It is interesting that `-j8` wasn't slower than `-j48`, probably being bottle-necked by the slow network file system on the cluster. But the bottom line is we didn't bring the the drastic slowdown from pre #3877 back.

**Comment by hzhou** [comment]
The GPU buffer check costs the latency `~ 0.01 us`

**Comment by hzhou** [comment]
Measuring short message (8-byte) inter-node latency on EPYC using `verbs;ofi_rxm`, with `--enable-thread-cs=global --without-ch4-shmmods`:
```
pre-3877:  1.7374 ± 0.0016 μs
post-3877: 1.7671 ± 0.0084 μs
pre-this:     1.7796 ± 0.0032 μs
after-this:   1.7564 ± 0.0044 μs
```
Improving but still not fully recovered.

**Comment by hzhou** [comment]
After further optimization (make `MPIDI_OFI_handle_deferred_ops` in unlikely branch):
```
after-this:     1.7480 ± 0.0037 µs
```

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Review by yfguo — APPROVED** [review]
Looks good to me.

I think the takeaway is the inlining improves the polling part of the progress since it happens way more frequently than the actual dispatching part.

**Comment by hzhou** [comment]
> 
> 
> Looks good to me.
> 
> I think the takeaway is the inlining improves the polling part of the progress since it happens way more frequently than the actual dispatching part.

Yeah, I think that assessment is accurate. The latency improvement here is very small, but some applications that is extreme latency driven may care.

**Pull request merged**
