### PR TITLE
test/mpi with MPI 3.0 implementations

### PR DESCRIPTION
**Pull request by shintaro-iwasaki**
## Pull Request Description

This PR enable strictly MPI-3.0 compatible compilers to run tests in `test/mpi`. This PR consists of two pieces:
- Replace removed-since-MPI-3.0 features in core test utilities.
- Mark all individual tests that use removed-since-MPI-3.0 features as `strict=FALSE` (130+ tests are marked)

Note that removed-since-MPI-3.0 features include `MPI_Errhandler_set()`, `MPI_Type_extent()`, `MPI_Type_struct()`, `MPI_Type_hvector()`, and `MPI_UB/LB`. Their replacements are as follows:
1. Function names are changed: `MPI_Errhandler_set()`, `MPI_Type_struct()`, `MPI_Type_hvector()`, ...
2. Rename + an extra argument: `MPI_Type_extent()`
3. Quite different: `MPI_UB/LB`

Actually around 60% of `strict=FALSE` tests are incompatible because of `MPI_Errhandler_set()`, while 30% of tests the second category and 10% the third category.
<details>
<summary>List of incompatible test</summary>

Category 1: MPI_Errhandler_set() only

attr/attrerr *
attr/attrerrcomm *
attr/attrerrtype *
attr/baseattr2 *
coll/allred *
coll/allred 4 10*
coll/icallreduce *
coll/icallgather *
coll/icallgatherv *
coll/opland *
coll/oplor *
coll/oplxor *
coll/opband *
coll/opbor *
coll/opbxor *
coll/nbicallreduce *
coll/nbicallgather *
coll/nbicallgatherv *
coll/bcast *
coll/bcast_comm_world_only *
comm/ctxalloc *
group/groupcreate *
pt2pt/bsendfrag *
rma/allocmem *
rma/adlb_mimic1 *
rma/rget_testall *
errors/attr/keyvalmis *
errors/coll/noalias *
errors/coll/nb_noalias *
errors/coll/rerr *
errors/coll/nb_rerr *
errors/coll/reduce_local *
errors/coll/bcastlength *
errors/coll/ibcastlength *
errors/coll/reducelength *
errors/coll/ireducelength *
errors/coll/allreducelength *
errors/coll/iallreducelength *
errors/coll/reduceop *
errors/coll/ireduceop *
errors/coll/gatherlength *
errors/coll/igatherlength *
errors/coll/scatterlength *
errors/coll/iscatterlength *
errors/coll/allgatherlength *
errors/coll/iallgatherlength *
errors/coll/alltoalllength *
errors/comm/cfree *
errors/comm/manysplit *
errors/comm/comm_create_nullarg *
errors/comm/comm_create_group_nullarg *
errors/comm/comm_get_info_nullarg *
errors/comm/comm_group_nullarg *
errors/comm/comm_size_nullarg *
errors/comm/comm_split_nullarg *
errors/comm/comm_split_type_nullarg *
errors/comm/intercomm_create_nullarg *
errors/datatype/getcnterr *
errors/datatype/type_contiguous_nullarg *
errors/datatype/type_get_extent_nullarg *
errors/datatype/type_get_true_extent_nullarg *
errors/datatype/type_get_true_extent_x_nullarg *
errors/datatype/type_size_x_nullarg *
errors/datatype/type_vector_nullarg *
errors/group/group_difference_nullarg *
errors/group/group_intersection_nullarg *
errors/group/group_range_excl_nullarg *
errors/group/group_range_incl_nullarg *
errors/group/group_rank_nullarg *
errors/group/group_size_nullarg *
errors/group/group_translate_ranks_nullarg *
errors/group/group_union_nullarg *
errors/pt2pt/proberank *
errors/pt2pt/truncmsg1 *
errors/pt2pt/errinstatts *
errors/pt2pt/errinstatta *
errors/pt2pt/errinstatws *
errors/pt2pt/errinstatwa *
errors/connect_timeout_no_accept *
errors/connect_timeout_mismatch *

Category 2: MPI_Type_extent()/MPI_Type_struct()/MPI_Type_hvector()/...

coll/scatter2 *
coll/scatter3 *
datatype/simple_pack_external *
datatype/simple_pack_external2 *
datatype/transpose_pack *
datatype/slice_pack *
datatype/struct_pack2 *
datatype/zeroparms *
datatype/getpartelm *
datatype/sendrecvt4 *
datatype/typelb *
datatype/struct_zero_count *
datatype/blockindexed_zero_count *
datatype/blockindexed_misc *
datatype/simple_size_extent *
datatype/struct_empty_el *
datatype/contig_zero_count *
datatype/hindexed_zeros *
datatype/simple_resized *
datatype/unpack *
datatype/struct_derived_zeros *
datatype/hvecblklen *
io/getextent *
io/bigtype *
io/i_types_with_zeros *
perf/transp_datatype *
perf/twovec *
pt2pt/eagerdt *
rma/putfidx *
rma/transpose1 *
rma/transpose3 *
rma/transpose3_shm *
rma/transpose4 *
rma/transpose5 *
rma/transpose6 *
rma/transpose7 *
errors/datatype/type_extent_nullarg *
errors/pt2pt/truncmsg2 *

Category 3: MPI_UB/MPI_LB

coll/scatterv *
datatype/lbub *
datatype/struct_pack *
datatype/typename *
datatype/struct_no_real_types *
datatype/unusual_noncontigs *
datatype/struct_ezhov *
datatype/struct_verydeep *
io/i_noncontig *
io/i_noncontig_coll *
io/i_noncontig_coll2 *
rma/transpose2 *
errors/datatype/type_lb_nullarg *
errors/datatype/type_ub_nullarg *

</details>

If marking 130 tests is too much, we may change tests of the first two categories. The new interface for `MPI_UB` and `MPI_LB` is quite different, so we should keep these tests.

This needs #4521 to really make the testsuite strictly MPI-3.0 compatible.

Future TODO: check Fortran tests.

## Expected Impact

The test coverage is slightly changed since this PR changes functions used in core test utilities.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [ ] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/ofi

**Comment by pavanbalaji** [comment]
We should move all tests to the new interface and add one or two "duplicate" tests with the old interface.  It makes more sense to have most testing for the new interface.

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch3/ofi

**Comment by pavanbalaji** [comment]
@shintaro-iwasaki Can you also remove the "mpi3.0" flags in the test suite?  We assume MPI-3.0 support at this point for the MPI implementations.  Implementations that do not have that can easily create an xfail file for their specific implementations (or we can provide a script to do that for them, if they really care about it).

**Comment by shintaro-iwasaki** [comment]
@pavanbalaji There are `mpiversion=2.2` and `mpiversion=3.1` as well. I think we can remove `mpiversion=2.2` and `mpiversion=3.0`, but can we also remove the `mpiversion=3.1` tag?

**Comment by pavanbalaji** [comment]
> @pavanbalaji There are `mpiversion=2.2` and `mpiversion=3.1` as well. I think we can remove `mpiversion=2.2` and `mpiversion=3.0`, but can we also remove the `mpiversion=3.1` tag?

Yeah, I think so.  We added those we had the xfail infrastructure.  They are now irrelevant given that anyone can xfail tests based on the MPI version.

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch3/ofi

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch3/ofi
test:mpich/ch4/ofi

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch3/ofi

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/ofi

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/ofi

**Comment by pavanbalaji** [comment]
@shintaro-iwasaki does this PR subsume the changes in https://github.com/pmodels/mpich/pull/4303?  If so, can that PR be closed?

**Comment by pavanbalaji** [comment]
Sorry, I meant https://github.com/pmodels/mpich/pull/2382

**Comment by shintaro-iwasaki** [comment]
#2382 is based on an old MPICH testing infrastructure, but basically yes (although I have not really take a look at the Fortran/C++ part, which I will fix in the future).

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch3/most

**Comment by shintaro-iwasaki** [comment]
test:mpich/warnings
test:mpich/ch3/most

**Comment by shintaro-iwasaki** [comment]
test:mpich/ch4/most

**Pull request merged**
