### PR TITLE
ch4/generic: Remove weird request copy logic

### PR DESCRIPTION
**Pull request by raffenet**
Testing may prove me wrong, but I don't see why this logic is needed in the AM code.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by hajimefu** [comment]
@raffenet This is needed for the trylock/handoff models, which aren't running in your Jenkins I believe. I know this particular part has an issue, so I'm preparing a patch to clean it up (+some better documentation), but I would like to keep it for now.

**Comment by hajimefu** [comment]
CC: @halimamer

**Comment by raffenet** [comment]
Oh, OK. That use-case rings a bell and now I see the code that does this in `ch4_recv.h`. Closing.

**Comment by hajimefu** [comment]
👍

**Pull request closed without merging**
