### PR TITLE
coll: revert alltoall ring

### PR DESCRIPTION
**Pull request by hzhou**
The PR #3415 was committed prematurely. This PR reverts the commit. The alltoall ring algorithm seems to be flawed and does not pass the tests.

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by wesbland** [comment]
Is this warning the problem?

```
  CC       src/mpi/coll/ialltoallv/lib_libpmpi_la-ialltoallv.lo
src/mpi/coll/ialltoall/ialltoall.c: In function 'MPIR_Ialltoall_impl':
src/mpi/coll/ialltoall/ialltoall.c:289:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
                     MPIR_Ialltoall_intra_gentran_ring(sendbuf, sendcount, sendtype, recvbuf,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                       recvcount, recvtype, comm_ptr, request);
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/mpi/coll/ialltoall/ialltoall.c:291:13: note: here
             case MPIR_IALLTOALL_INTRA_ALGO_GENTRAN_BRUCKS:
             ^~~~
```

We just need to add the error checking and `break` call.

**Comment by hzhou** [comment]
@wesbland It is not just warning. It fails to pass the tests. As I reading the code, I do not understand how the algorithm would work in the first place, and I couldn't fix it. Get some one open a new PR so we can discuss and review it again.

**Comment by hzhou** [comment]
ref: https://jenkins.mpich.org/job/mpich-master-ch3-ubuntu/compiler=gnu,jenkins_configure=default,label=ib64/1073/testReport/junit/(root)/summary_junit_xml/469_____coll_alltoall1_8__MPIR_CVAR_ALLTOALL_DEVICE_COLLECTIVE_0_MPIR_CVAR_ALLTOALL_INTRA_ALGORITHM_nb_MPIR_CVAR_IALLTOALL_DEVICE_COLLECTIVE_0_MPIR_CVAR_IALLTOALL_INTRA_ALGORITHM_gentran_ring/

**Comment by wesbland** [comment]
Right, but what I'm saying is that the reason all of those tests are failing is because each alltoall is actually running twice. Give me a few minutes to create a new PR to try and fix this before you merge the revert. We can save a roundtrip.

**Comment by hzhou** [comment]
> Give me a few minutes to create a new PR to try and fix this before you merge the revert. We can save a roundtrip.

We'll wait until the other PR #3606 get merged first. So you have more than a few minutes :)

**Comment by hzhou** [comment]
The mistake was a missing `break` in the switch cases.

**Pull request closed without merging**
