### PR TITLE
combined tag cleanup

### PR DESCRIPTION
**Pull request by raffenet**
This PR is a combination of @wesbland and my tag fixes that we started independently.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by wesbland** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
this time don't leave debugging printfs in the code...
test:jenkins/ch4/most

**Comment by raffenet** [comment]
@wesbland I squashed my matching fixes into the "Sepatate out match bits" patch. Going to test this again on ch3 and ch4 this time. Is there anything else we want to add to this PR?

test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by wesbland** [comment]
test:jenkins/ch4/most
test:jenkins/ch3/most

**Comment by wesbland** [comment]
test:ch4/ofi/all/all/all/shm-exclusive,shm-no/debug,default

**Comment by wesbland** [comment]
test:intel:ch4/ofi/all/all/all/shm-exclusive,shm-no/debug,default

**Comment by wesbland** [comment]
test:intel:ch4/ofi/all/all/all/shm-exclusive,shm-no/debug,default

**Comment by wesbland** [comment]
test:intel:ch4/ofi/all/all/all/shm-exclusive,shm-no/debug,default

**Comment by wesbland** [comment]
test:intel:ch4/ofi/all/all/all/shm-exclusive,shm-no/debug,default

**Comment by wesbland** [comment]
The tests are looking good here. I'll wait for them to finish and merge this in the morning.

**Comment by wesbland** [comment]
The Intel tests should be all green. All of those failures are xfails that I'm still working on getting the new job set up properly.

**Pull request merged**
