### PR TITLE
build: update libtool patch for oracle-fortran

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

The default `-shared` flag:
    `sunf77 -shared -olibxxx.so [objs]`
does not work. It need use `-G`
    `sunf77 -G -olibxxx.so [objs]`

## Expected Impact

This PR fixes the build issues for Oracle Developer Studio 12.5.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
test:jenkins/custom
compiler=solstudio

**Comment by hzhou** [comment]
test:more/warnings

**Comment by hzhou** [comment]
test:more/warnings

**Comment by hzhou** [comment]
test:more/warnings

**Comment by hzhou** [comment]
Fixed a pgi compiler 19.4 regression. Try again:

test:more/warnings

**Comment by hzhou** [comment]
test:jenkins/custom
compiler=solstudio

**Comment by raffenet** [comment]
> The default `-shared` flag:
> `sunf77 -shared -olibxxx.so [objs]`
> does not work. It need use `-G`
> `sunf77 -G -olibxxx.so [objs]`
> 

Wow. Looks like 12.4 supported `-shared` as an alias for `-G`, but removed in 12.5. 😠 

> -shared                       Same as -G

**Comment by raffenet** [comment]
@hzhou I think the last piece of the puzzle is here: https://github.com/pmodels/mpich/blob/master/confdb/config.rpath#L100-L102

**Comment by raffenet** [comment]
FWIW, `-Wl,` seems to work, but `-Qoption ld ` is actually documented. I suppose we should use that. I'm going to push a couple of patches here and see how it goes.

**Comment by raffenet** [comment]
test:more/warnings

**Comment by hzhou** [comment]
Ignore the more-warnings tests, its script still has some issues. 

The results looks good!

**Pull request merged**
