### PR TITLE
confdb: fix checking for Fortran compiler

### PR DESCRIPTION
**Pull request by yfguo**
fix pmodels/mpich#2929

### CODE REVIEW

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
@yfguo could you explain the fix more in the commit message? Otherwise I have to start from scratch to understand and review this.

**Comment by yfguo** [comment]
I have rebased it on the latest master and added the following description in the commit message.

The original test for assumed rank is correct but the linking of the
test fails because `TEST_ASSUMED_RANK_ASYNC_IMPL` is not implemented.
This fix adds the implementation as a C function
`test_assumed_rank_async_impl_c` and bind it to the Fortran interface to
correctly mimic the use case in MPICH.

**Comment by yfguo** [comment]
Intel has updated their Fortran compiler and fixed the problem (since version 2018.3.222 and 2019.0.070). The test is still useful for any future Fortran compiler that runs into the same problem.

**Pull request merged**
