### PR TITLE
ch4/ucx: Only set window base pointer when allocating

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Fix a bug in ch4/ucx window creation. A number of RMA tests were failing with UCX 1.13.0 and newer releases.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
test:mpich/submodules

**Comment by raffenet** [comment]
test:mpich/submodules

**Review by hzhou — APPROVED** [review]

**Comment by jeffhammond** [comment]
https://github.com/nwchemgit/nwchem/issues/633#issuecomment-1231890316 looks favorable

**Pull request merged**
