### PR TITLE
test: fix MPIX_Query_cuda_support etc

### LINKED ISSUE #5716: MPIX_Query_cuda_support triggers assertion error
Calling `MPIX_Query_cuda_support()`  on a Mac triggers an assertion error:
```
Assertion failed: (mpi_errno), function MPIX_Query_cuda_support, file src/mpi/misc/gpu.c, line 90.
```
Seen in both the homebrew version, and the Julia BinaryBuilder-built one

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
The manual tests are not regularly tested. Modify the gpu_query to be
able to run by default and move into impls/mpich so it can be tested
regularly.

## TODO
* [x] verify the bug
* [x] Fixes #5716

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp
test:mpich/ch4/ofi
test:mpich/ch4/gpu/ofi

**Review by raffenet — APPROVED** [review]

**Pull request merged**
