### PR TITLE
coll: TSP Iallreduce using recursive exchange reduce scatter and allgatherv

### PR DESCRIPTION
**Pull request by tarudoodi**
## Pull Request Description
Rebased and creating a new branch to replace https://github.com/pmodels/mpich/pull/3344

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [ ] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by tarudoodi** [comment]
test:jenkins/ch4/most

**Comment by tarudoodi** [comment]
I am working on checking the whitespace check failure.

**Comment by tarudoodi** [comment]
test:jenkins/ch4/most

**Comment by tarudoodi** [comment]
@hzhou The tests passed.

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
@tarudoodi There is warning of unused variable. Could you squash it?

**Comment by tarudoodi** [comment]
test:mpich/warnings

**Comment by tarudoodi** [comment]
test:mpich/warnings

**Pull request merged**
