### PR TITLE
Prereq commits for topology-aware comm_split_type

### PR DESCRIPTION
**Pull request by pavanbalaji**

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/all
test:jenkins/ch4/all

**Comment by raffenet** [comment]
this doesn't appear to compile https://jenkins.mpich.org/job/mpich-review-ch3-armci-mpi/961/console

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/all
test:jenkins/ch4/all

**Comment by pavanbalaji** [comment]
No unexpected failures.  Rebased on to `mpich/master` and pushed again.

@raffenet ?

**Pull request merged**
