### PR TITLE
hydra: handle SIGCHLD

### LINKED ISSUE #1620: hydra: automatically handle bad ssh setup
**Originally by _balaji_ on 2012-04-26 07:43:36 -0500**

---

Hydra doesn't automatically handle the case where there is something wrong with your ssh setup.  The user has to explicitly kill the job (either Ctrl-C or timeout).

It will be convenient if Hydra can automatically detected failed ssh attempts and exit.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Handle SIGCHLD to catch the case when we launch proxy with ssh and ssh
fails.

Fixes #1620

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
After this PR:
```
$ mpirun -host localhost,something -n 2 ./cpi
ssh: Could not resolve hostname something: Name or service not known
[mpiexec@pmrs-gpu-240-02.cels.anl.gov] ui_cmd_cb (mpiexec/pmiserv_pmci.c:53): Launch proxy failed.
[mpiexec@pmrs-gpu-240-02.cels.anl.gov] HYDT_dmxu_poll_wait_for_event (lib/tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@pmrs-gpu-240-02.cels.anl.gov] HYD_pmci_wait_for_completion (mpiexec/pmiserv_pmci.c:182): error waiting for event
[mpiexec@pmrs-gpu-240-02.cels.anl.gov] main (mpiexec/mpiexec.c:330): process manager error waiting for completion
```

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Review by raffenet — APPROVED** [review]

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Pull request merged**
