### PR TITLE
test/mpi: Free arg list to avoid leak

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Fixup #4608.

## Expected Impact

Fix leak found with AddressSanitizer.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/custom
config: asan
testlist: threads/comm/dup_leak_test -iter=1234

**Comment by hzhou** [comment]
test:mpich/custom
config: asan
testlist: threads/comm/dup_leak_test 2 arg=-iter=1234

**Comment by hzhou** [comment]
Oh, we switched to `gcc` for `asan` tests now?

**Comment by raffenet** [comment]
It's just not dictated by the script. The nightly job sets `clang-8` in the `compiler` variable.

**Comment by hzhou** [comment]
> 
> 
> It's just not dictated by the script. The nightly job sets `clang-8` in the `compiler` variable.

Does that mean `gcc` `asan` also works or did I miss something?

**Comment by raffenet** [comment]
It does work, but it's missing some newer features. I think LeakSanitizer might even be off by default. I vaguely remember some other problems in particular configurations, but do not have any specifics.

**Pull request merged**
