### PR TITLE
Improvements in release_gather framework

### PR DESCRIPTION
**Pull request by jain-surabhi-23**
- Make release_gather algorithms default for posix Bcast, Allreduce and Barrier
- Allocate shared memory buffers in release_gather only when collective calls are made on a communicator certain number of times
- Fixes cxx/errhan/commcallx 2, when odd_even_cliques is disabled and
MPIR_CVAR_ALLREDUCE_POSIX_INTRA_ALGORITHM is set to release_gather.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by jain-surabhi-23** [comment]
test:jenkins/ch4/ofi

**Comment by jain-surabhi-23** [comment]
@pavanbalaji Please review the PR. (I cannot assign a reviewer by myself)

**Comment by jain-surabhi-23** [comment]
It has patches from #4370 as well

**Comment by jain-surabhi-23** [comment]
test:jenkins/warnings
test:mpich/ch4/most

**Comment by jain-surabhi-23** [comment]
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
@jain-surabhi-23 Most of these patches look good.

In one of the patches, you are falling back to the MPIR-level algorithm when `MPIDI_POSIX_mpi_release_gather_comm_init` returns an error.  Why are you doing that instead of raising an error in that case?

**Comment by jain-surabhi-23** [comment]
> @jain-surabhi-23 Most of these patches look good.
> 
> In one of the patches, you are falling back to the MPIR-level algorithm when `MPIDI_POSIX_mpi_release_gather_comm_init` returns an error. Why are you doing that instead of raising an error in that case?

`MPIDI_POSIX_mpi_release_gather_comm_init` returns error when it cannot create shared memory. So we either fallback or throw error depending on what `MPIR_CVAR_COLLECTIVE_FALLBACK` is.

**Comment by pavanbalaji** [comment]
> `MPIDI_POSIX_mpi_release_gather_comm_init` returns error when it cannot create shared memory. So we either fallback or throw error depending on what `MPIR_CVAR_COLLECTIVE_FALLBACK` is.

Doesn't it depend on what the error is?

**Comment by jain-surabhi-23** [comment]
test:jenkins/ch4/most

**Comment by hzhou** [comment]
> @hzhou Can we add some testing in our jenkins without `ODD_EVEN_CLIQUES`?

We already do it as one of the weekly tests -- `shmem`: 
https://pmrs-jenkins.cels.anl.gov/view/mpich-weekly/job/mpich-master-ch4-special-tests/compiler=gnu,jenkins_configure=shmem,label=centos64,netmod=ofi/15/testReport/junit/(root)/summary_junit_xml/_____spawn_disconnect3_3__/history/

test:jenkins/custom
netmod: ch4:ofi
config: shmem

**Comment by jain-surabhi-23** [comment]
> Alright, thanks. Can you create an issue for it?
Looks like you already have an issue for it - https://github.com/pmodels/mpich/issues/4090

**Comment by jain-surabhi-23** [comment]
@pavanbalaji The only test failure was `disconnect3`, which is a known issue. Are we ready to merge this?

**Comment by pavanbalaji** [comment]
> @pavanbalaji The only test failure was `disconnect3`, which is a known issue. Are we ready to merge this?

Looks good to me.  Go ahead and merge it.

**Comment by jain-surabhi-23** [comment]
@pavanbalaji Thank you for your patches and quick review!

**Pull request merged**
