### PR TITLE
coll: Add ring algorithm for Allgather

### PR DESCRIPTION
**Pull request by akhillanger**

### CODE REVIEW

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
This has failures that need to be investigated.

**Comment by raffenet** [comment]
Oops, sorry, I meant #3157, which this is based on.

**Comment by akhillanger** [comment]
@raffenet this PR is independent of #3157.

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Pull request closed without merging**
