### PR TITLE
ofi: Fix bcastlength/ibcastlength test failures

### PR DESCRIPTION
**Pull request by jain-surabhi-23**
## Pull Request Description
This PR fixes the failures introduced by #3655 and removes it from the xfail list.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Passes tests (included warning check)
* [x] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [x] Commits are self-contained and do not do two things at once
* [x] Remove xfail from the test suite when fixing a test
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by jain-surabhi-23** [comment]
test:jenkins/ch4/ofi

**Comment by jain-surabhi-23** [comment]
test:jenkins/ch3/most

**Comment by jain-surabhi-23** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/ofi

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi

**Pull request merged**
