### PR TITLE
Fix .sln line endings

### PR DESCRIPTION
**Pull request by wesbland**
The line endings in the Windows solutions files don't appear to even be regular Windows line endings. Convert them to the standard CRLF format.

I'd like to get feedback from @ddurnov on whether this is ok or not as I thought this problem had been fixed previously (#2819), but apparently fresh clones still have this problem. I don't have a good way to check that this doesn't mess things up for Windows people.

### CODE REVIEW

**Comment by wesbland** [comment]
@ddurnov - Can you comment on this PR?

**Comment by wesbland** [comment]
This is still a confusing problem for some folks that are doing fresh clones on non-Windows systems. Can we move this forward?

**Comment by raffenet** [comment]
As far as I'm concerned, this is fine. Are we skipping input from Intel MPI folks?

**Comment by wesbland** [comment]
I believe @ddurnov is taking a look right now. Can you give him another hour before you merge it?

**Pull request merged**
