### PR TITLE
Collectives Algorithms Prerequisite

### PR DESCRIPTION
**Pull request by akhillanger**
The PR contains collective algorithms cleanup commits and prereq commits for adding new algorithms.

### CODE REVIEW

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
@raffenet the test results are good!

**Comment by raffenet** [comment]
Agreed. I have signed off on everything and resolved the minor conflict that arose from your other branch. Let me run at least one test configuration for sanity.
test:jenkins/ch3/tcp

**Pull request merged**
