### PR TITLE
ch4/ofi: Provide count attribute when creating address vector

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Address vector size is known ahead of creation, so provide it as an
attribute to libfabric. Some providers may be able to use the
information for efficiency or correctness.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
cc: @yutaka0298 
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
cc @yutaka-ishikawa

**Comment by minsii** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
@wesbland do you know if there is any reason not to do this? We had a request from a provider developer working on "instant-on" to have this information at named AV open time. I don't see why we shouldn't always provide it, though.

**Comment by wesbland** [comment]
I don’t know any reason why not, but I can think of reasons why the size of the job might not be the correct number (e.g. multi-nic).

**Comment by raffenet** [comment]
> I don’t know any reason why not, but I can think of reasons why the size of the job might not be the correct number (e.g. multi-nic).

Jotting down a few notes and questions after our discussion the phone:
1. providers do not seem to treat this value as a hard limit, so inserting more addresses than specified may be OK.
2. could ep_per_node attribute cover multi-NIC case? https://ofiwg.github.io/libfabric/master/man/fi_av.3.html
3. if each is NIC isolated in a domain object, then it should not matter since we will need multiple AVs.

Ultimately it sounds like we can merge this, and re-work it later if we come across an incompatible scenario.

**Comment by wesbland** [comment]
> 2. could ep_per_node attribute cover multi-NIC case? https://ofiwg.github.io/libfabric/master/man/fi_av.3.html

You might be right that as a hint, it serves the same purpose and the combination of the number of nodes and `ep_per_node` gives an adequate hint.

> 3. if each is NIC isolated in a domain object, then it should not matter since we will need multiple AVs.

I'm not sure that's entirely true. My expectation was that we could use a shared AV between the different domains to avoid having to create more than on CH4-level AV table. The alternative is to either:

1) Create one CH4-level table per ep or
2) Create one big CH4-level table and map it to multiple OFI tables, though since we probably want to be able to send and receive to every endpoint, it seems silly to have to duplicate this.

**Comment by raffenet** [comment]
> > 1. could ep_per_node attribute cover multi-NIC case? https://ofiwg.github.io/libfabric/master/man/fi_av.3.html
> 
> You might be right that as a hint, it serves the same purpose and the combination of the number of nodes and `ep_per_node` gives an adequate hint.
> 
> > 1. if each is NIC isolated in a domain object, then it should not matter since we will need multiple AVs.
> 
> I'm not sure that's entirely true. My expectation was that we could use a shared AV between the different domains to avoid having to create more than on CH4-level AV table. The alternative is to either:
> 
> 1. Create one CH4-level table per ep or
> 2. Create one big CH4-level table and map it to multiple OFI tables, though since we probably want to be able to send and receive to every endpoint, it seems silly to have to duplicate this.

We should clarify, because my reading is that an AV is specific to a single domain (input to fi_av_open).

**Comment by wesbland** [comment]
> > 2. Create one big CH4-level table and map it to multiple OFI tables, though since we probably want to be able to send and receive to every endpoint, it seems silly to have to duplicate this.
> 
> We should clarify, because my reading is that an AV is specific to a single domain (input to fi_av_open).

My assumption was that that we could use a shared AV (either created by the PMIx server or locally if necessary) to share between processes on the same nodes and domains within the same process. The documentation page only specifically lists the first case though.

**Comment by raffenet** [comment]
> > > 1. Create one big CH4-level table and map it to multiple OFI tables, though since we probably want to be able to send and receive to every endpoint, it seems silly to have to duplicate this.
> > 
> > 
> > We should clarify, because my reading is that an AV is specific to a single domain (input to fi_av_open).
> 
> My assumption was that that we could use a shared AV (either created by the PMIx server or locally if necessary) to share between processes on the same nodes and domains within the same process. The documentation page only specifically lists the first case though.

Yeah, that's what I read. You can create domain objects from different providers in the same app, so that would obviously not work. But if some provider can share we should take advantage of that.

**Comment by pavanbalaji** [comment]
@raffenet and @wesbland   What did we decide to do with this PR?

**Comment by raffenet** [comment]
> Ultimately it sounds like we can merge this, and re-work it later if we come across an incompatible scenario.

I still feel this way. I will rebase and get it ready for merge.

**Comment by raffenet** [comment]
test:mpich/ch4/ofi

**Comment by wesbland** [comment]
Yeah, my hope about having a shared AV for each domain didn't pan out, but in the end, it just gets duplicated across all of the domains. So the AV ends up being `num_procs * nics_per_proc`. Of course, we can modify this value, so that's fine.

**Comment by raffenet** [comment]
Ignoring th_taskmaster failures. This is good to go.

**Pull request merged**
