### PR TITLE
CH4/OFI: Added CVAR for libfabric auto progress

### PR DESCRIPTION
**Pull request by nusislam**
Added a CVAR to enable/disable auto progress based on the
OFI provider and runtime configuration.

Fixes csr/mpich-ofi#172

Fixes pmodels/mpich#2523

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by pkcoff** [comment]
Looks ok but when I tried to apply the patch to latest master I get this:

[pkcoff@vestalac2 mpich]$ git apply --check ~/tmp/cvarautoprog.patch
error: patch failed: src/mpid/ch4/netmod/ofi/ofi_init.h:464
error: src/mpid/ch4/netmod/ofi/ofi_init.h: patch does not apply

**Comment by wesbland** [comment]
Sorry @pkcoff, I'm not sure I understand what the problem is. Is it that this snippet isn't getting patched correctly?

    +        MPIDI_Global.settings.enable_auto_progress      = MPIDI_Global.settings.enable_auto_progress == 0 ? 0 :
    +                                                            ((hints->domain_attr->data_progress & hints->domain_attr->control_progress) & (FI_PROGRESS_AUTO)) > 0ULL ? 1 : 0;

The patch seems to be fine here on GitHub, which is essentially doing the same thing. Can you provide any more information?

**Comment by pkcoff** [comment]
I added nuislam's github repo to my remotes and just cherry-picked the commit and it applied.  I am noticing now there really needs to be a separation between control_progress and data_progress, in the case of the bgq provider we only support manual control_progress but have both auto and manual for data_progress, the problem is if I set MPIDI_OFI_ENABLE_AUTO_PROGRESS then it will set both the control and data progress to auto and BGQ doesn't support the auto control progress.  I think there really needs to be MPIDI_OFI_ENABLE_CONTROL_AUTO_PROGRESS and MPIDI_OFI_ENABLE_DATA_AUTO_PROGRESS  since they are separate entities.

**Comment by pkcoff** [comment]
Anyhow if I turn MPIDI_OFI_ENABLE_AUTO_PROGRESS off it should work but then I'm getting this compiler error:

/home/pkcoff/development/github/OFI-BGQ-BuildEnv/mpi/mpich/src/mpid/ch4/netmod/include/../ofi/ofi_init.h: In function 'MPIDI_NM_mpi_init_hook':
/home/pkcoff/development/github/OFI-BGQ-BuildEnv/mpi/mpich/src/mpid/ch4/netmod/include/../ofi/ofi_init.h:264:55: error: 'MPIR_CVAR_CH4_OFI_ENABLE_AUTO_PROGRESS' undeclared (first use in this function)
/home/pkcoff/development/github/OFI-BGQ-BuildEnv/mpi/mpich/src/mpid/ch4/netmod/include/../ofi/ofi_init.h:264:55: note: each undeclared identifier is reported only once for each function it appears in

**Comment by wesbland** [comment]
The compile error is because you need to re-run `./autogen.sh` to regenerate the CVARs.

**Comment by wesbland** [comment]
As for the separation between control and data auto progress, we can do that if that's what we need. I don't love the idea of having to have two since it will be very confusing for users. I guess we don't really get a choice though. Maybe we should do that instead of merging this PR?

Thoughts from others?

**Comment by raffenet** [comment]
@wesbland @pkcoff ugh, I suppose we need both, confusing as it is.

**Comment by wesbland** [comment]
Ok. We'll work on a new version then.

**Comment by raffenet** [comment]
Alternative in #2560 was merged.

**Pull request closed without merging**
