### PR TITLE
cherry-picked fixes for 3.4.x

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

1. FreeBSD xfails
2. typerep fix
3. upgrade yaksa
4. macOS xfail typo fix

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Review by hzhou — APPROVED** [review]

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
@hzhou I added a couple more commits from `main`. Do you still approve? I actually haven't been waiting for explicit approval  for `3.4.x` for commits that were already approved for `main`, but since the process already started here, no harm in completing it.

**Comment by hzhou** [comment]
> @hzhou I added a couple more commits from `main`. Do you still approve? I actually haven't been waiting for explicit approval for `3.4.x` for commits that were already approved for `main`, but since the process already started here, no harm in completing it.

Yes. Looks good.

**Pull request merged**
