### PR TITLE
debug: consolidate USE_MEMORY_TRACING macros

### PR DESCRIPTION
**Pull request by hzhou**
If MPICH honors that option for memory tracing, then `mpl` has to honor it
too, or we are forcing errors for all memory calls (`malloc` et.el.)

Fixing issue #3731

### CODE REVIEW

**Comment by hzhou** [comment]
Manually test this PR with `--enable-g=most`

**Comment by hzhou** [comment]
The way we configure memory tracing in two parts -- `mpl` and `mpir` -- is terrible. It is very difficult to understand and very easy to mess up.

**Comment by hzhou** [comment]
While reading the code, `hydra` and `hydra2` calls `MPL_trinit/config` but there is no `MPL_trdump`. 
`mpir_handlemem.h` defines a set of similar macros specific for MPI handle objects; it'll be nice to consolidate with MPL. It'll be much easier to read and maintain when the semantically related code is in one place.

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
This is unfortunately not safe for ROMIO, which still retains it's own set of memory allocation wrappers...

> In file included from /sandbox/raffenet/mpich/src/mpl/include/mpl.h:16:0,
>                  from ./adio/include/adioi.h:996,
>                  from ./adio/include/adio.h:432,
>                  from adio/common/malloc.c:17:
> /sandbox/raffenet/mpich/src/mpl/include/mpl_trmem.h:231:27: error: expected identifier or ‘(’ before '\x6c6c6f63'
>  #define malloc(a)         'Error use MPL_malloc' :::
>                            ^
> /sandbox/raffenet/mpich/src/mpl/include/mpl_trmem.h:232:27: error: expected identifier or ‘(’ before '\x6c6c6f63'
>  #define calloc(a,b)       'Error use MPL_calloc' :::
>                            ^
> In file included from adio/common/malloc.c:24:0:
> /usr/include/malloc.h:49:49: error: macro "realloc" passed 2 arguments, but takes just 1
>  extern void *realloc (void *__ptr, size_t __size)
>                                                  ^
> /usr/include/malloc.h:49:14: error: ‘realloc’ redeclared as different kind of symbol
>  extern void *realloc (void *__ptr, size_t __size)
>               ^
> In file included from ./adio/include/adio.h:77:0,
>                  from adio/common/malloc.c:17:
> /usr/include/stdlib.h:480:14: note: previous declaration of ‘realloc’ was here
>  extern void *realloc (void *__ptr, size_t __size)
>               ^
> In file included from /sandbox/raffenet/mpich/src/mpl/include/mpl.h:16:0,
>                  from ./adio/include/adioi.h:996,
>                  from ./adio/include/adio.h:432,
>                  from adio/common/malloc.c:17:
> /sandbox/raffenet/mpich/src/mpl/include/mpl_trmem.h:233:27: error: expected identifier or ‘(’ before '\x66726565'
>  #define free(a)           'Error use MPL_free'   :::
>                            ^
> Makefile:3058: recipe for target 'adio/common/malloc.lo' failed

**Comment by hzhou** [comment]
test: mpich/custom --enable-g=most

**Comment by hzhou** [comment]
test:mpich/custom
--enable-g=most

**Comment by raffenet** [comment]
The above error was reproducible with both `--enable-g=most` and `--enable-g=all` in manual tests.

**Comment by hzhou** [comment]
test:mpich/custom
--enable-g=most

**Comment by hzhou** [comment]
test: mpich/custom --enable-g=most

**Comment by hzhou** [comment]
test: mpich/custom --enable-g=most

**Comment by hzhou** [comment]
test:mpich/warnings/more

**Comment by hzhou** [comment]
test: mpich/custom --enable-g=all
test: mpich/warnings
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
test:jenkins/ch4/ofi

**Comment by hzhou** [comment]
The warnings are fixed in #3792.
Two tests failed in `ch4:ofi`:
```

summary_junit_xml.355 - ./pt2pt/cancelanysrc 2          Error Details            Stack Trace           not ok 355 - ./pt2pt/cancelanysrc 2   ---   Directory: ./pt2pt   File: cancelanysrc   Num-procs: 2   Timeout: 180   Date: "Thu May 16 17:01:58 2019"   ... ## Test output (expected 'No Errors'): ##  No Errors ## In direct memory block for handle type REQUEST, 1 handles are still allocated | 0.49 sec | 2
-- | -- | --
summary_junit_xml.1110 - ./threads/comm/idup_nb 4          Error Details            Stack Trace           not ok 1110 - ./threads/comm/idup_nb 4   ---   Directory: ./threads/comm   File: idup_nb   Num-procs: 4   Timeout: 180   Date: "Thu May 16 17:32:58 2019"   ... ## Test output (expected 'No Errors'): ## [mpiexec@pmrs-centos64-240-06.cels.anl.gov] APPLICATION TIMED OUT, TIMEOUT = 180s

```

**Comment by hzhou** [comment]
test: mpich/custom --enable-g=most

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by hzhou** [comment]
@raffenet This PR is ready. There are a few tests revealed on the new Jenkins server that I believe not related to this PR. I have opened separate issues for them. Could you give it a review?

**Pull request merged**
