### PR TITLE
submodule: Update libfabric to v1.10.1

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Plus some MPICH patches for warning and embedded build fixes.

## Expected Impact

Fix ch4:ofi embedded build on FreeBSD.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ofi

**Comment by raffenet** [comment]
@hzhou I cherry-picked your commits onto 1.10.1, which should include fixes for the FreeBSD build, as well.

**Comment by hzhou** [comment]
> @hzhou I cherry-picked your commits onto 1.10.1, which should include fixes for the FreeBSD build, as well.

Good. I don't remember the fixes for FreeBSD, let's try that (with a new custom script):

test:mpich/custom/pipeline
netmod: ch4:ofi
label: freebsd64

**Comment by hzhou** [comment]
Expanded the review tests to include `asan` and `ubsan`:

test:mpich/ch4/ofi

**Comment by raffenet** [comment]
> Expanded the review tests to include `asan` and `ubsan`:
> 
> test:mpich/ch4/ofi
> 
> EDIT: `asan` didn't work:
> 
> ```
> ==263709==ERROR: LeakSanitizer: detected memory leaks
> 
> Direct leak of 40 byte(s) in 1 object(s) allocated from:
>     #0 0x7fa39f77bae8 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:144
>     #1 0x7fa39b679df7 in vasprintf (/lib64/libc.so.6+0x77df7)
> ```
> 
> Which I believe is triggered by a driver library. `FI_PROVIDER=sockets` bypassed the error, but seems didn't work here.

I used to see this in the old asan Jenkins tests before this update. So I think it is OK to ignore?

**Comment by hzhou** [comment]
> I used to see this in the old asan Jenkins tests before this update. So I think it is OK to ignore?

I believe this is triggered during ofi init time so it will fail every `asan` tests. Give me a day or so to look deeper.

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/custom/pipeline
netmod: ch4:ofi
label: freebsd64

**Comment by hzhou** [comment]
test:mpich/custom/pipeline --with-ch4-ofi-direct-provider=sockets
netmod: ch4:ofi
label: freebsd64

**Pull request merged**
