### PR TITLE
ch4: Check valid window shared table

### PR DESCRIPTION
**Pull request by shawnccx**
After allocating a shared table for RMA, check that the allocation was
successful.

### CODE REVIEW

**Comment by shawnccx** [comment]
@minsii Can you take a look at this PR?

**Comment by shawnccx** [comment]
test:jenkins/ch4/most

**Comment by minsii** [comment]
The commit looks good to me. I will approve and merge it once the tests are done.

**Comment by minsii** [comment]
@shawnccx looks like I do not have permission to update your fork. Can you please add my signature within this commit ?

There are some jenkins failures in ch4/ofi, but I believe none of them is related to this PR.

**Comment by shawnccx** [comment]
@minsii I added your signature into commit msg, also sent a collaborator invitation to you.

**Pull request merged**
