### PR TITLE
ch4/ofi: add MPIDI_OFI_ENABLE_DATA back

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
In PR #2985 we merged MPIDI_OFI_ENABLE_DATA and MPIDI_OFI_ENABLE_TAG, thus making support of cq_data a requirement. This unnecessarily restricts our support to some legacy providers, `gni` being one of the important ones.

This PR tries to revert that change.

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Review by raffenet — COMMENTED** [review]
I'm OK with adding this back in. Looks like we missed something in the status path, though.

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

test:mpich/custom
netmod: ch4:ofi
env: MPIR_CVAR_CH4_OFI_ENABLE_DATA=0

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

test:mpich/custom
netmod: ch4:ofi
env: MPIR_CVAR_CH4_OFI_ENABLE_DATA=0

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

test:mpich/custom
netmod: ch4:ofi
env: MPIR_CVAR_CH4_OFI_ENABLE_DATA=0

**Review by raffenet — APPROVED** [review]

**Comment by hzhou** [comment]
test:mpich/spellcheck

**Pull request merged**
