### PR TITLE
hydra: add singleton init

### LINKED ISSUE #4853: Singleton feature request
Hi all.
I would like to request the singleton functionality in MPICH (i.e. runs without _mpirun_). I have an interactive application which uses ncurses library and it doesn't work with _mpirun_. Currently I'm using OpenMPI which supports this feature but I would like to make it work with this implementation too. I have understood that it's not a prioritary feature now, so I add this issue like as a way for you to keep it present for the future.
Thanks.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Add singleton init to hydra PMI 1.

Fixes #4853 #1074 #4533 #2175 #1541

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most
test:mpich/ch4/pmi

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most
test:mpich/ch4/pmi

**Review by raffenet — APPROVED** [review]
LGTM

**Comment by raffenet** [comment]
Is there a companion PR to add support in Simple PMI in MPICH or is that still in the works?

**Comment by hzhou** [comment]
> Is there a companion PR to add support in Simple PMI in MPICH or is that still in the works?

It's already in Simple PMI. All the protocols and schemes are set in Simple PMI already. I guess it used to work until we moved on to hydra, which never finished the singleton part.

**Pull request merged**
