### PR TITLE
ch4/ofi: Turn off striping optimization by default 

### PR DESCRIPTION
**Pull request by nusislam**
## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by nusislam** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
What we experienced is, the multinic striping does work, but the threshold need be set much higher to account for the (big) overhead of MR registration.

**Comment by nusislam** [comment]
> What we experienced is, the multinic striping does work, but the threshold need be set much higher to account for the (big) overhead of MR registration.

Striping works. In this PR, I am just turning it off by default. The users can use the CVAR to enable striping. If you already have enough ranks per node such that each rank gets a separate NIC, you need not use striping.

**Review by hzhou — APPROVED** [review]
LGTM
Did it pass the tests?

**Comment by nusislam** [comment]
> LGTM Did it pass the tests?

Yes, the tests passed.

**Pull request merged**
