### PR TITLE
ch4/ofi: Changes to get MPICH RMA working with CXI 2.0

### PR DESCRIPTION
**Pull request by nitbhat**
## Pull Request Description
In conversation with CXI engineers, I confirmed that CXI 2.0 will have FI_MR_ENDPOINT set. These changes ensure that MPICH continues to work with that change. I have verified that these changes will continue to work with the current CXI versions as well. This is because of the additional capability set variable (MR_REGISTER_NULL) added to MPICH in https://github.com/pmodels/mpich/pull/6067/files. 

Once CXI 2.0 is available everywhere, we can revert https://github.com/pmodels/mpich/pull/6067/files since the MR_ALLOCATED capability set change along with provider supplied FI_MR_ALLOCATED should handle skipping registration for null addresses. 

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Review by hzhou — APPROVED** [review]
LGTM

**Comment by hzhou** [comment]
@nitbhat Approved. Could you rebase and clear the ch4/ofi tests?

**Comment by nitbhat** [comment]
test:mpich/ch4/ofi

**Comment by nitbhat** [comment]
> @nitbhat Approved. Could you rebase and clear the ch4/ofi tests?

Sorry for the delay in getting back on this. I've rebased it and launched the tests. It should be good to be merged if the tests pass.

**Pull request merged**
