### PR TITLE
Enable ROMIO to be built stand alone

### PR DESCRIPTION
**Pull request by wkliao**
One advantage of being able to build ROMIO separately from MPICH is to
allow users to run a customized ROMIO while keep using the MPI 
communication and other non-I/O parts of the MPI library on the target
systems, for instance Cray XC40 or IBM BlueGene, which is well tuned for
the hardware and software of the systems

This PR has been tested using MPICH, OpenMPI, and Intel MPI libraries
for stand-alone build. It has also been tested when building within
MPICH and OpenMPI. Here is a sample configure command to build a 
stand-alone library (VPATH build).
```
   cd build_dir
   /path/to/romio/configure --prefix=$HOME/ROMIO \
                            --with-mpi=$HOME/MPICH/3.3.1
or
   /path/to/romio/configure --prefix=$HOME/ROMIO \
                            --with-mpi=$HOME/OpenMPI/4.0.1
```
One remaining issue is that thread-safety is not supported for the
stand-alone build. A better integration to the external MPI libraries to
make use of their thread-safety mechanism is a future work.

CC: @roblatham00 @paralepsis

### CODE REVIEW

**Comment by brianjmurrell** [comment]
Does this enable building of the ROMIO tests (i.e. in-tree) when MPICH is built, avoiding the need to first do "make install" and then `cd src/mpi/romio/tests; make`?

**Comment by hzhou** [comment]
@wkliao With this PR, does ROMIO still need `mpir_ext.h`? When ROMIO is built within MPICH, what minimal set of configure variable does ROMIO need?

**Comment by hzhou** [comment]
I guess the question I am curious about is, should we always build ROMIO standalone even within MPICH?

**Comment by wkliao** [comment]
Hi, @brianjmurrell 
This patch still requires `make install` first before `make check` when building ROMIO
within MPICH. As @hzhou explained earlier, the test programs need an already built
MPI library to compile and run correctly. ROMIO is not the last component during
MPICH building process, so when you run `make check` without first run `make install`,
the libraries and header files may not be ready yet and compilation of the test programs
can fail.

The best I can do is when building ROMIO stand alone, one can run 'make check'
without 'make install' first. In this case, the full package of MPI library is available.
When ROMIO is built stand alone, this patch now lets you run `make distcheck`
and `make dist` under src/mpi/romio.

**Comment by wkliao** [comment]
Hi, @hzhou 
I try to minimize the change to the building process when built within MPICH.
So it still uses `mpir_ext.h`. I wrap around codes with preprocessor if condition
of `ROMIO_INSIDE_MPICH`.

I suggest not to build ROMIO stand alone when building within MPICH.
As mentioned in my PR message, the stand alone version does not support
thread safety. When built within MPICH, ROMIO can rely on the thread-safety
mechanism to achieve this. However, due to this mechanism is not available to
external libraries, I cannot directly use it for stand-alone version.

**Comment by hzhou** [comment]
> I suggest not to build ROMIO stand alone when building within MPICH.
> As mentioned in my PR message, the stand alone version does not support
> thread safety. When built within MPICH, ROMIO can rely on the thread-safety
> mechanism to achieve this. However, due to this mechanism is not available to
> external libraries, I cannot directly use it for stand-alone version.

The thread safety is ultimately achieved with `MPL`, e.g. `MPL_thread_mutex_lock`, so I assume if we ensure passing down the same configure options, `--with-thread-package`, to `MPL`, then ROMIO can have its own thread-safety that is consistent with the rest of MPICH. `ROMIO` does not share critical section with `MPICH` internal anyway, right?

**Comment by wkliao** [comment]
I am not aware the thread-safety is implemented in MPL.
From the ROMIO source codes, I am seeing
`ROMIO_THREAD_CS_ENTER()` and `ROMIO_THREAD_CS_EXIT()`
wrapping all MPI-IO functions in folder romio/mpi-io. They are macros pointing to
`MPIR_Ext_cs_enter()` and `MPIR_Ext_cs_exit()` in file mpi-io/mpioimpl.h,
which in turn pointing to `MPID_THREAD_CS_ENTER()` and
`MPID_THREAD_CS_EXIT()` in file src/glue/romio/glue_romio.c.
The names suggest they are device dependent.
I did not dig deeper from there.

ROMIO configure.ac does have an option of `--with-mpl-prefix`.
we can make use of that. Can you give me more pointers? We can work
together to add thread safe support.

**Comment by brianjmurrell** [comment]
> This patch still requires make install first before make check when building ROMIO
within MPICH.

I am certainly misunderstanding then what this patch is doing.  So what is this patch allowing one to do that is different than the status quo?

> the test programs need an already built
MPI library to compile and run correctly.

Which does (or could) exist in the tree being built.

> ROMIO is not the last component during
MPICH building process,

Can it not simply be re-ordered so that it is built later in the building process such that when it is built (during the same top-level `configure && make` that is building all of MPICH) and as such all of the required components are built and in the tree?

> so when you run make check without first run make install,
the libraries and header files may not be ready yet and compilation of the test programs
can fail.

Understood, but again, is this not a simple matter of reordering what gets built first?

**Comment by wkliao** [comment]
This patch allows one to run 'make check' after 'make install'. All test programs under romio/test can be built and tested in this patch. The current master branch does not run ROMIO tests during 'make check'.

In theory, reordering and what you suggested could work with a build-time mpicc script mentioned @hzhou.

**Comment by hzhou** [comment]
> I am not aware the thread-safety is implemented in MPL.
> From the ROMIO source codes, I am seeing
> `ROMIO_THREAD_CS_ENTER()` and `ROMIO_THREAD_CS_EXIT()`
> wrapping all MPI-IO functions in folder romio/mpi-io. They are macros pointing to
> `MPIR_Ext_cs_enter()` and `MPIR_Ext_cs_exit()` in file mpi-io/mpioimpl.h,
> which in turn pointing to `MPID_THREAD_CS_ENTER()` and
> `MPID_THREAD_CS_EXIT()` in file src/glue/romio/glue_romio.c.
> The names suggest they are device dependent.
> I did not dig deeper from there.
> 

There are multiple thread model inside MPICH, regarding granularity of critical sections, as well as 
some details on how to take the lock, such as whether or not allow recursive locking. Since many of the research model is first developed inside a device, that is why the macro is in the `MPID_` namespace. However, these granularity model does not need to apply to ROMIO since the code don't really interleave. Therefore, I believe ROMIO can simply implement (or duplicate) its own `ROMIO_THREAD_CS_ENTER/EXIT` macros based on MPL. You may reference `src/mpid/common/thread/mpidu_thread_fallback.h` and look for the definition of `MPIDUI_THREAD_CS_ENTER_NREC(mutex)`. It calls `MPIDU_Thread_mutex_lock` which tracks the owner and lock count in addition to the MPL mutex lock. But if ROMIO does not do recursive locking and does not check lock owner, then a simple MPL_mutex lock will do. If needed, ROMIO can also copy the `MPIDU_Thread_mutex_t` struct (into sth like `ROMIO_Thread_mutex_t`).

> ROMIO configure.ac does have an option of `--with-mpl-prefix`.
> we can make use of that. Can you give me more pointers? We can work
> together to add thread safe support.

What MPICH does is accept the configure options on behalf of MPL, then simply passing all configure options down to MPL (or ROMIO)'s `configure`. So MPICH just use `--with-thread-package=xxx`. If ROMIO do the same (passing options down to MPL), then it should work.

**Comment by brianjmurrell** [comment]
As an aside, if ROMIO is meant to be MPI stack independent, why is it buried in the MPICH stack instead of being it's own stand-alone project?

**Comment by hzhou** [comment]
> As an aside, if ROMIO is meant to be MPI stack independent, why is it buried in the MPICH stack instead of being it's own stand-alone project?

I wouldn't say ROMIO was "meant" to be MPI stack independent. MPI-IO is part of the MPI standard. The result of ROMIO code become more or less independent is more of a implementation or engineering choice. And I believe it was not the first intention either but later made into a desirable goal.

**Comment by brianjmurrell** [comment]
Fair enough.  But would it be reasonable to extract it from MPICH now?

**Comment by wkliao** [comment]
I suggest you to file a feature request to make ROMIO a separate submodule of MPICH by creating a new github issue. It will be up to the MPICH team to evaluate and decide. If you have time to develop a patch, you can also contribute a PR.

**Comment by brianjmurrell** [comment]
Beyond adding the ROMIO tests to `make check` is there any other functionality this patch adds?  Specifically, should I be able to 
1. Extract the ROMIO source tree (i.e. `cp -a src/mpi/romio ../ && cd ../romio && ...`) from the MPICH source tree and `configure && make && cd tests && ./runtests`?  Or does it still depend on being inside the MPICH source tree?  Or alternatively,
2. Extract the MPICH source and then immediately `cd src/mpi/romio && configure && make && cd tests && ./runtests`?

**Comment by wkliao** [comment]
Once you ran `configure` under mpich folder, cd to src/mpi/romio, run `make dist` which generates a tarball named `romio-3.3.tar.gz`.

**Comment by wkliao** [comment]
Hi @hzhou 
I checked OpenMPI implementation and am seeing its MPI_File object contains
a member of MPI_Comm, which in turn contains a mutex lock member. To  support
thread-safety, OpenMPI wraps around  every MPI-IO subroutine  with lock and unlock
of this mutex.

I wonder if MPICH's communicators contain such mutex member, so I
can simply reuse it in ROMIO.

**Comment by brianjmurrell** [comment]
When I do this is what I get:

```
$ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for x86_64-redhat-linux-gnu-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... none
checking for gcc option to accept ISO C99... -std=gnu99
checking for grep that handles long lines and -e... /bin/grep
checking if gcc -std=gnu99 supports -fvisibility=hidden... yes
checking whether to enable symbol visibility... yes (via -fvisibility=hidden)
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for x86_64-redhat-linux-gnu-ar... no
checking for x86_64-redhat-linux-gnu-lib... no
checking for x86_64-redhat-linux-gnu-link... no
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-redhat-linux-gnu
checking host system type... x86_64-redhat-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc -std=gnu99... /bin/ld
checking if the linker (/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
checking the name lister (/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-redhat-linux-gnu file names to x86_64-redhat-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-redhat-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /bin/ld option to reload object files... -r
checking for x86_64-redhat-linux-gnu-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-redhat-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-redhat-linux-gnu-ar... ar
checking for archiver @FILE support... @
checking for x86_64-redhat-linux-gnu-strip... no
checking for strip... strip
checking for x86_64-redhat-linux-gnu-ranlib... no
checking for ranlib... ranlib
checking command to parse /bin/nm -B output from gcc -std=gnu99 object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for x86_64-redhat-linux-gnu-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... no
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether make supports nested variables... (cached) yes
configure: Configuring with args dummy mt
configure: ===== configuring mpl =====
configure: WARNING: no configuration information is in mpl
configure: ===== done with mpl configure =====
checking whether clock skew breaks make... no
checking whether make supports include... no
checking whether make allows comments in actions... no
configure: WARNING: Your make does not allow comments in target code.
Using this make may cause problems when building programs.
You should consider using gnumake instead.
checking for virtual path format... VPATH
checking whether make sets CFLAGS... yes
configure: WARNING: Unknown architecture ... proceeding anyway
ROMIO home directory is .
configure: error: MPI library /usr/lib64/mpich/lib not found
```

[config.log](https://github.com/pmodels/mpich/files/3575899/config.log)

**Comment by wkliao** [comment]
@brianjmurrell 
To build this ROMIO stand alone, you need to specify the MPI C compiler.
This can be done by setting either CC environment variable of through --with-mpi option.

**Comment by wkliao** [comment]
@brianjmurrell 
It seems you are using an out-dated version. I made a force push 3 days ago.
Please run `git fetch` and `git reset origin/romio_stand_alone --hard`

**Comment by brianjmurrell** [comment]
@wkliao Ahhh.  I think I know what the problem is:

```
$ echo $MPI_LIB
/usr/lib64/mpich/lib
```

This is because I am using [modules](http://modules.sourceforge.net/) to _activate_ mpich as the MPI stack in my environment and that _activation_ does an:
```
setenv        MPI_LIB       /usr/lib64/mpich/lib
```

But ROMIO's configure also uses `$MPI_LIB`.

**Comment by hzhou** [comment]
> Hi @hzhou
> I checked OpenMPI implementation and am seeing its MPI_File object contains
> a member of MPI_Comm, which in turn contains a mutex lock member. To support
> thread-safety, OpenMPI wraps around every MPI-IO subroutine with lock and unlock
> of this mutex.
> 
> I wonder if MPICH's communicators contain such mutex member, so I
> can simply reuse it in ROMIO.

Currently ROMIO calls `MPIR_Ext_cs_enter()`, which is defined in `src/glue/romio/glue_romio.c`, and it simply uses the global mutex `MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX`. Ideally, ROMIO should create its own mutex, potentially in `MPIR_Ext_init`, and use that instead. That mutex can be a global inside ROMIO. All it can use per-FILE mutex as OpenMPI did. Either way, ROMIO should maintain its own mutex system. Using `MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX` may suffer unexpected performance hit as it creates thread contentions between ROMIO and other MPICH functions that may not be necessary. I am not familiar with MPI-IO enough to say whether such contention is necessary. If it is, then it need further investigation.

**Comment by wkliao** [comment]
Hi @hzhou 
Per-file mutex alone may not be sufficient, as ROMIO maintains a few global variables
(see file src/mpi/romio/adio/include/adio_extern.h) that keep track of files created and derived datatypes flattened so far (and some others) which need to be updated atomically.

I assume mutex MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX is created at MPI_Init_thread()
and visible to all threads. Is this correct? However, MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX
appears to be a local symbol. A stand-alone ROMIO is not able to link it.

**Comment by hzhou** [comment]
You are correct that `MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX` is a global mutex variable created in `MPI_Init_thread()`.  However, it is not exposed to external code due to the "visibility" linker flag.

However, what I was saying is you don't really need `MPIR_THREAD_GLOBAL_ALLFUNC_MUTEX` in ROMIO since it does not access MPICH's internal global states anyway (unless I am wrong). So ROMIO could simply create its own global mutex or per file mutexes or both, and use that instead. The mutex in MPICH is created with `MPID_thread_mutex_create`. But if you trace the macro definitions in `src/mpid/common/thread/mpidu_thread_fallback.h`, it is ultimately just `MPL_thread_mutex_create`, which ROMIO can directly call.

**Comment by wkliao** [comment]
Here is a scenario. Let me know if it makes sense.
Let's assume the approach you suggested: a global ROMIO mutex is created, instead of
using MPICH global mutex. An I/O thread grabs the ROMIO mutex and calls an MPI collective
I/O. The collective I/O calls MPI collective communication functions that may call
thread yield to let other threads to progress while waiting for the collective communication
to complete. Note because the communication uses MPICH global mutex, other I/O threads waiting to lock ROMIO mutex will never be granted the lock. I guess this is why the current
design of MPICH uses the same global mutex in ROMIO.

**Comment by hzhou** [comment]
@wkliao In the collective I/O (can you give a example? I am not quite familiar with MPI-IO), who takes the lock? ROMIO code or MPICH code?

**Comment by hzhou** [comment]
@wkliao I am trying to understand your scenario. When you doing one collective IO, is it allowed to have another collective IO simultaneously? I guess they have to be in different communicator. Then ideally they should not be locked with the same ROMIO lock anyway, right? I guess I am saying that for better performance, ROMIO may need more granular locks which shouldn't have these recursive locking issues. Even with a single ROMIO global lock, since the lock is only protecting ROMIO's global state, shouldn't ROMIO release the lock before calling MPI collectives and retake the lock afterwards?

**Comment by wkliao** [comment]
I discussed a thread-safety issue on OpenMPI https://github.com/open-mpi/ompi/issues/6951
A test example provided by @ggouaillardet clearly shows the hanging problem due to
different mutex-es were used by I/O and communication.

When building ROMIO within MPICH, the same mutex is used by both ROMIO and MPICH communication, and thus the test program does not hang.

I believe you that ROMIO can have a better performance if finer granular locks were used,
but I don't think I have time to invest this. If I can obtain a pointer to the global mutex
through an MPL function call (or something similar), that will be the easiest way for
the stand-alone ROMIO to support thread safety.

Let me know. I can explain more.

**Comment by hzhou** [comment]
@wkliao Thanks for the link to examples. Relying on MPICH's global lock to protect ROMIO's state ties the code (MPICH's and ROMIO's) together and it'll require refactor sooner or later. We are actively researching on more granular locks inside MPICH, and the global lock may become unreliable at some point. The refactor that ROMIO needed is: 1. create and use its own global lock; 2. unlock before calling MPI functions that are expected to yield (that involves waiting for progress) and re-take the lock afterwards (if necessary). That way the yield should work (as the ROMIO lock was unlocked). 

The refactor should make openmpi work too (even without uncommenting the locks around `MPI_File_open`). But I am a bit confused there, doesn't `MPI_File_open` take any lock inside?

**Comment by wkliao** [comment]
I am glad to hear that new design of thread safety is actively under research.

ROMIO internally uses file locks, but no mutex lock, as the MPICH global mutex
lock is already in place to protect the shared objects, like global variables.
For shared file pointers, the implementation does not reply on a mutex
either.  Locks used inside ROMIO is to protect resources that are accessible
by MPI processes concurrently, but not threads. At least, this is my understanding.
@roblatham00 would know better than I.

**Comment by pavanbalaji** [comment]
Is this PR still being pursued?  It's been inactive for a while.

**Comment by brianjmurrell** [comment]
> Is this PR still being pursued? It's been inactive for a while.

I certainly would like to see it accomplished.

**Comment by pavanbalaji** [comment]
Alright, in that case, it's harder to get such a large PR merged in.  I'd recommend splitting into a few separate PRs:

1. There are several patches that are bug or warning fixes and are unrelated to running ROMIO standalone.  Those should be separated out and are easier to merge in.

2. There are some general code improvements, such as avoiding using global variables and protecting MPI extensions with corresponding macros.  Those should be a separate PR.

3. White space changes should be, at the very least, a separate PR.  But I think that'll probably get dropped at this point (at least till we start working on the next major release).  So, perhaps that can be simply dropped.

4. The actual changes that this PR refers to (i.e., enabling ROMIO to be built standalone) should be the only ones in this PR.

Can you make those changes, so we can start merging those in?

**Comment by pavanbalaji** [comment]
I haven't heard back from @wkliao, who is the original PR, so I rebased it on to the latest master.  I'll run a set of tests to make sure it doesn't break anything.  After that, @roblatham00 can take a look to see if this is acceptable.  But if there are any additional changes needed, and we don't hear back from @wkliao, we'll need to drop this PR.

test:mpich/ch3/most
test:mpich/ch4/most

**Comment by pavanbalaji** [comment]
> @roblatham00 can take a look to see if this is acceptable.

Actually, I take that back.  This PR has a bunch of unrelated changes, which need to be split out first before it can be merged.  Given that Open MPI has its own MPI-IO implementation now, I'm not inclined to spending time to work on this PR.  This is really a very low priority for us.  So I'll wait for the tests and close this PR.

**Comment by wkliao** [comment]
This patch was developed a while ago.
Breaking it down to smaller patches may break the codes and
take a while for testing. I prefer not  to do so and currently do
not have time.

**Comment by paralepsis** [comment]
Thing is, this allows us to selectively replace vendor MPI-IO implementations, which is useful. -- Rob

**Comment by ggouaillardet** [comment]
FWIW, the `io/romio` component of Open MPI is not the latest version.
The difference between Open MPI and MPICH w.r.t ROMIO used to be quite small (read manageable), but we had to make many changes to replace stuff that has been removed from the standard a while ago such as `MPI_Address()`, `MPI_UB`, `MPI_LB`, `MPI_Type_struct()`.

This is addressed here in https://github.com/pmodels/mpich/pull/4008/commits/3ccef8bf9087444fcbf0b931b1044cb4bcb59c14

I think addressing this would be a very good first step.
Unfortunately, I do not have much bandwidth to do it myself.

**Comment by pavanbalaji** [comment]
Yes, most certainly it'll be good to have ROMIO that can be built standalone.  I'm not denying that. 
 But, unless someone can invest the time to make that happen, I don't know what the solution here is.  I don't have the bandwidth to break this PR into smaller pieces, and I'd prefer not to bundle everything into a single "standalone ROMIO" PR.  That makes it difficult if we run into problems later and need to revert parts of the PR.

But if someone can put in the time to do that, we can surely merge those PRs in.

**Comment by pavanbalaji** [comment]
This PR seems to be failing a lot of tests.  Closing this till someone has time to fix these up as well as make the other above mentioned changes.

**Comment by wkliao** [comment]
When submitted, this PR passed all tests.
After your rebase, some failures appear, but none of them is related to ROMIO.

**Comment by pavanbalaji** [comment]
@wkliao I've reverted my update and pushed your original version to this PR.  Now it's back to the same state as before I tried to help, i.e., several conflicts.  I'll let you make whatever changes you prefer before you submit a version for consideration.

**Pull request closed without merging**
