### PR TITLE
confdb: Add check for aligned variable attribute

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
@hajimefu @wesbland how about something like this?

**Comment by wesbland** [comment]
That's a good start for those that support the GCC attributes (GCC, Clang, Intel). We'll have to add some other kind of magic for the rest. We were hoping to avoid manual alignment whenever possible.

**Comment by hajimefu** [comment]
👍

**Comment by raffenet** [comment]
A better version would probably be to check for this in `mpl`, and create some sort of `MPL_VAR_ALIGNED` macro to decorate variables.

**Comment by raffenet** [comment]
do you guys want to take this as a start and run with it? I.e., can I assign this to one of you and forget about it? :smile:

**Comment by wesbland** [comment]
Go for it.

**Comment by hajimefu** [comment]
Just FYI, I started to take a crack on this.

**Comment by hajimefu** [comment]
So by simply moving `AX_GCC_VAR_ATTRIBUTE(aligned)` to `mpl/configure.ac`, I got `MPL_HAVE_VAR_ATTRIBUTE_ALIGNED` in `mplconfig.h`. Is this what you wanted @raffenet?

**Comment by raffenet** [comment]
Yes. Then what I was thinking is something like this in `mpl_base.h`.
```
#if MPL_HAVE_VAR_ATTRIBUTE_ALIGNED
#define MPL_ATTR_ALIGNED __attribute((aligned))__
#else
#define MPL_ATTR_ALIGNED
#endif
```

**Comment by hajimefu** [comment]
Oh okay. `MPL_ATTR_ALIGNED` would be useful when alignment is optional, for instance performance optimizations. In cases where alignment is a must, for example a hardware or instruction require a particular alignment, we would have to switch implementations using `#ifdef MPL_HAVE_VAR_ATTRIBUTE_ALIGNED`.

**Comment by raffenet** [comment]
OK, I'm not sure I know a portable way to do that. For heap memory would test for and use new aligned allocation functions. But for stack variables we are probably stuck with compiler hints and assertions at runtime, no?

**Comment by hajimefu** [comment]
Right. What I can think of so far is to do some dirty trick like:
```
char buff[REAL_SIZE + ALIGNMENT - 1];
type *aligned_ptr = buff + pad; // where pad is calculated so that (buff+pad) meets alignment requirement
```

**Comment by hajimefu** [comment]
Anyway, I'll add `MPL_ATTR_ALIGNED` to my commit. We may find some use case for it.

**Comment by hajimefu** [comment]
FYI: merged as acc8cbf8

**Pull request closed without merging**
