### PR TITLE
stream: implement stream communicator

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Implement stream communicator.

Reference https://github.com/pmodels/mpich/discussions/5908

Depend on: 
* https://github.com/pmodels/mpich/pull/5948
* https://github.com/pmodels/mpich/pull/5904
* https://github.com/pmodels/mpich/pull/5949

TODO:
* [x] RMA to use explicit vcis
       Currently, RMA assumes all processes with the same window uses the same vci. We need add a vci_table to the window structure to allow each process to use their own vci before we can enable explicit vcis.
       EDIT: ref #5967
* [ ] am-only fallback paths to use multiple vci
       Currently, it is hard-wired to use vci 0.

[skip warnings]
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
Retest to confirm:
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Review by raffenet — APPROVED** [review]

**Pull request merged**
