### PR TITLE
coll: fix allgatherv early return case

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

The localcopy omitted considering displs.

Thanks @mathstuf for discovering the bug. ref: https://github.com/pmodels/mpich/pull/5034#issuecomment-1399271498

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
@mathstuf Could you verify the fix?

**Comment by mathstuf** [comment]
Thanks, will test. Here's a test case I adapted (but haven't run because I built MPICH out-of-source and `test/mpi` doesn't seem to be set up for that…): https://github.com/mathstuf/mpich/commit/1935ffef61c362a232b097d77c575a1dd97391f9

**Comment by mathstuf** [comment]
That works!

**Comment by mathstuf** [comment]
Backport for Fedora requested: https://bugzilla.redhat.com/show_bug.cgi?id=2162892

**Review by raffenet — APPROVED** [review]

**Pull request merged**
