### PR TITLE
[4.2.x] Backport fixes in prep for 4.2.1

### PR DESCRIPTION
**Pull request by raffenet**
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most
test:mpich/ch4/gpu

**Comment by prj-** [comment]
Do you have a rough estimate for the 4.2.1 release by any chance?

**Comment by raffenet** [comment]
I was aiming for end of this month. I believe there are some large count fixes on the way, but otherwise this set of patches is mostly complete.

**Comment by abrooks98** [comment]
@raffenet Could you please also include the changes from #6962? They fix a bug for Intel GPUs introduced in one of the included commits

**Comment by raffenet** [comment]
> @raffenet Could you please also include the changes from #6962? They fix a bug for Intel GPUs introduced in one of the included commits

Yes, will do. Thanks!

**Pull request merged**
