### PR TITLE
CH4: Fix warnings with `--enable-strict`

### PR DESCRIPTION
**Pull request by hajimefu**
This PR fixes a few warnings from `--enable-strict` + GCC 7.2.1. This fixes the warning pointed out in #2874 after it getting merged, plus few other warnings.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
Still a build issue with `--enable-strict` and FreeBSD. Has to do with the function symbol being found, but no declaration in `stdlib.h`. Ugh, this is what I get for trying to follow standards. I throw together a patch that adds a decl when missing, but these types of things seem like fragile workarounds. We really should figure out a better way.

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
@hajimefu My patch appears to fix the build errors. I'll let the tests complete over lunch and then merge.

**Comment by hajimefu** [comment]
Hmm, another possible solution might be until the day we migrate to C11 standard, completely forget about `aligned_alloc` and search only for `posix_memalign`.

**Comment by hajimefu** [comment]
@raffenet oh okay, nevermind. Since our time is limited right now, I think your solution is fine. We can revisit this later if needed.

**Comment by raffenet** [comment]
The `PAC_CHECK_NEEDS_DECL` method is accepted practice in MPICH at this point, so I'm OK with the workaround for now, i.e. 3.3b1.

**Comment by zhenggb72** [comment]
As you may already find out, the real problem is that autoconf for example for aligned_alloc always passes the test because autoconf automatically generates a dummy function prototype, and since the function exist in library, it always compile and link fine even with "strict". However, with "strict" later on, and no dummy prototype, it will fail during the compilation.

**Comment by raffenet** [comment]
:( new failure in the sock review job. Looking into it.

**Comment by raffenet** [comment]
Can't reproduce the sock failure even with same machine, same configuration. I'm willing to ignore it in this case, especially because this code should not affect the sock configuration at all.

**Pull request merged**
