### PR TITLE
SHM active message with some fixes

### PR DESCRIPTION
**Pull request by minsii**
This PR should be compared against #3199 , but compare with master for jenkins test.

### CODE REVIEW

**Comment by minsii** [comment]
test:jenkins/ch4/most

**Comment by minsii** [comment]
test:jenkins/ch4/ofi

**Comment by minsii** [comment]
test:jenkins/ch4/most

**Comment by minsii** [comment]
test:jenkins/ch4/most

**Comment by minsii** [comment]
test:jenkins/ch4/most

**Comment by minsii** [comment]
test:jenkins/ch4/most

**Comment by wesbland** [comment]
So I had gone back to fbox being the default since we decided to wait for the updated LMT protocol. Should I leave it as iqueue. We might need to have more discussion about this as I assume that fbox will perform better than iqueue.

**Comment by minsii** [comment]
I am not sure if we really want to set `fbox` as default for all messages. It simply blocks program on the producer side in message rate test.

**Comment by wesbland** [comment]
Let's move this conversation back over to #3199 and close this PR (you can just push patches directly to the other PR since you're a repository writer).

**Comment by minsii** [comment]
Closed this PR to work together on #3199

**Pull request closed without merging**
