### PR TITLE
coll: TSP allreduce ring

### PR DESCRIPTION
**Pull request by tarudoodi**
Implements allreduce ring algorithm
Updates tag use in allgatherv ring algorithm which gets used in allreduce ring algorithm

### CODE REVIEW

**Comment by tarudoodi** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by tarudoodi** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by tarudoodi** [comment]
test:jenkins/ch3/most

**Comment by hzhou** [comment]
Since this is Allreduce, compared to recursive-doubling algorithm, the ring algorithm has no benefit at all. Both transport one data size at a time, but the ring algorithm simply do more transports. Suggest drop this PR.

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
Mis-read the code, re-opening it.

The algorithm spread the message into N pieces and reduce each pieces followed by `allgather`. 

reference: baidu allreduce ring

**Comment by hzhou** [comment]
... need click the `Reopen` button ...

**Comment by hzhou** [comment]
Reference: Issue #2637, PR #2916

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Pull request merged**
