### PR TITLE
CH4/OFI: Add capability for fetch_atomic iovec limit

### PR DESCRIPTION
**Pull request by wesbland**
CH4/OFI: Add capability for fetch_atomic iovec limit

For some providers, the limit for fetch_atomic operations might be
different than for other RMA operations. Add a capability to allow the
user/provider developer to set this value at runtime/compile-time,
respectively.

This PR is sitting on top of #2475. It should be merged after that one.

### CODE REVIEW

**Comment by wesbland** [comment]
Also updated this PR to remove "Capability Sets" tag mentioned in #2475.

**Comment by wesbland** [comment]
Yep. I'll rebase this again.

**Comment by wesbland** [comment]
Done.

**Comment by raffenet** [comment]
Looks like I should have build tested this one...

**Comment by raffenet** [comment]
@wesbland https://jenkins.mpich.org/view/nightly-master-ch4/job/mpich-master-ch4-ofi/compiler=gnu,fabric_prov=sockets,jenkins_configure=default,label=ib64/68/console

**Comment by wesbland** [comment]
Hmm. This must be from compiling the capability sets a different way. Let me take a look. If you want to roll back in the meantime, you can do that.

**Comment by raffenet** [comment]
FWIW, I don't supply any capability set information to the current Jenkins builds. Just a default `--with-device=ch4:ofi`.

**Pull request merged**
