### PR TITLE
CH4 ADI namespace

### PR DESCRIPTION
**Pull request by raffenet**
Removes the namespace shift from ADI functions defined in CH4. A build issue cropped up when I first implemented this, which is the reason for the handlemem patch that precedes the CH4 changes. Need to verify that this PR will not affect device layer inlining/instruction counts.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/all

**Comment by wesbland** [comment]
We can take a look at instruction counts when the build issues are fixed.

**Comment by raffenet** [comment]
Got bit by not building ROMIO on my local machine :). Added another commit to address that failure. test:jenkins/ch4/all

**Comment by raffenet** [comment]
@wesbland I think the build issues are resolved now.

**Comment by wesbland** [comment]
Ok. We'll take a look.

**Comment by wesbland** [comment]
👍 

Rubasri took a look at the IC and everything looks fine.

**Pull request merged**
