### PR TITLE
CH4/OFI: Added CVAR for libfabric auto progress

### PR DESCRIPTION
**Pull request by wesbland**
Added CVARs to enable/disable auto progress based on the
OFI provider and runtime configuration.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by pkcoff** [comment]
I tested and looks good, only request is can you turn off data auto for bgq as well for the default - ie:

#define MPIDI_OFI_ENABLE_DATA_AUTO_PROGRESS_BGQ MPIDI_OFI_OFF

Thanks.

**Comment by wesbland** [comment]
Done.

**Comment by pkcoff** [comment]
Thanks looks good - Ken if you can approve/ merge my bgq rel 0.2 will be ready

**Pull request merged**
