### PR TITLE
Additional fixes for 3.4.x

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Accumulated fixes from main that apply to the 3.4.x branch.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
I had to re-implement 2 commits by hand because of `main` branch refactoring. Could use review of https://github.com/pmodels/mpich/pull/5143/commits/c0f6863456acee6dff739d4abab6053479dd6899 and https://github.com/pmodels/mpich/pull/5143/commits/bb587a337bf40cf17a231c046a5e3a8e88185c65 @hzhou.

@minsii is there an additional fix for GNI provider support still in the works? No rush. I just want to plan to include it when ready.

**Comment by minsii** [comment]
@raffenet I plan to fix some rma/atomics issues for gni. But I don't have a "near-to-ready" PR yet. I am on summit now so maybe the fix has to be delayed till the next time I visit cray machine.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
> op: refactor to use straight builtin op index 
> ch4: add assertion for MPI_OP_NULL in parse_info_accu_ops_str 

These two commits are more of refactoring/enhancement nature, so you may consider omit them. I believe omitting them will not break the build (and you will find out with tests).

**Comment by raffenet** [comment]
> > op: refactor to use straight builtin op index
> > ch4: add assertion for MPI_OP_NULL in parse_info_accu_ops_str
> 
> These two commits are more of refactoring/enhancement nature, so you may consider omit them. I believe omitting them will not break the build (and you will find out with tests).

OK, I was a bit curious about those. I reworked the commit making NO_OP and REPLACE non-commutative after understanding it better. Now it basically matches what is in main.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
Added a bunch more fixes.
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most
test:mpich/warnings

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Pull request merged**
