### PR TITLE
pmi usage optimizations

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/most
test:jenkins/ch4/pmix

**Comment by raffenet** [comment]
test:jenkins/ch4/most
test:jenkins/ch4/pmix

**Comment by raffenet** [comment]
test:jenkins/ch4/most
test:jenkins/ch4/pmix

**Comment by raffenet** [comment]
test:jenkins/ch4/most
test:jenkins/ch4/pmix

**Comment by raffenet** [comment]
test:jenkins/ch4/most
test:jenkins/ch4/pmi

**Comment by raffenet** [comment]
test:jenkins/ch4/pmi

**Comment by raffenet** [comment]
test:jenkins/ch4/pmi

**Comment by raffenet** [comment]
test:jenkins/ch4/pmi

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch4/pmi

**Comment by raffenet** [comment]
@yfguo I'm still working out some testing setup kinks with the pmix and pmi2 configurations, but I think this is ready for review. You're best informed to look at it, given the nodemap and address vector experience. Let me know if you have questions!

**Comment by raffenet** [comment]
@janjust if you could run this through your tests and confirm things are working, that would be great.

**Comment by raffenet** [comment]
@yfguo reminder to take a look at this.

**Comment by yfguo** [comment]
Sorry for the delay. I will review this right away after finishing the work on my hand right now.

**Comment by janjust** [comment]
@raffenet Something is off, 
```
tomislavj@hpchead /hpc/mtr_scrap/users/tomislavj/workspace/tests/imb/src$  cat hosts 
vegas17:1
vegas31:1
#vegas32:16
#vegas33:16
#vegas34:16
#vegas35:16
#vegas36:16
tomislavj@hpchead /hpc/mtr_scrap/users/tomislavj/workspace/tests/imb/src$  mpirun -np 2 -f hosts -bind-to core -env UCX_NET_DEVICES=mlx5_0:1 -env MPIR_CVAR_ENABLE_HCOLL=0 -env HCOLL_ENABLE_MCAST_ALL=1 -env HCOLL_MAIN_IB=mlx5_0:1 ./IMB-MPI1 alltoall -npmin 128
Assertion failed in file src/mpid/common/bc/mpidu_bc.c at line 375: out_len == bc_len
0x7f95aa781958 MPL_backtrace_show() + 0x18
0x7f95aa730e9c MPIR_Assert_fail() + 0x11e
0x7f95aa776d85 MPIDU_bc_table_create() + 0x65c
0x7f95aa40efac MPIR_Init_thread() + 0x204d
0x7f95aa407a97 PMPI_Init() + 0x1f0
0x401a29 main() + 0x29
0x7f95a9f00c05 __libc_start_main() + 0xf5
0x4023bb _start() + 0x29
Abort(1) on node 0: Internal error
[vegas31:4585 :0] Caught signal 11 (Segmentation fault)
==== backtrace ====
 2 0x000000000006858c mxm_handle_error()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/util/debug/debug.c:641
 3 0x0000000000068adc mxm_error_signal_handler()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/util/debug/debug.c:616
 4 0x0000000000035270 killpg()  ??:0
 5 0x000000000002ae30 ucp_address_unpack()  ??:0
 6 0x0000000000010612 ucp_ep_create_to_worker_addr()  ??:0
 7 0x0000000000010e2f ucp_ep_create()  ??:0
 8 0x000000000016d21f MPIDI_NM_mpi_init_hook()  /hpc/mtr_scrap/users/tomislavj/workspace/mpich/./src/mpid/ch4/netmod/include/../ucx/ucx_init.h:100
 9 0x0000000000165a97 PMPI_Init()  /hpc/mtr_scrap/users/tomislavj/workspace/mpich/src/mpi/init/init.c:180
10 0x0000000000401a29 main()  /hpc/mtr_scrap/users/tomislavj/workspace/tests/imb/src/IMB.c:136
11 0x0000000000021c05 __libc_start_main()  ??:0
12 0x00000000004023bb _start()  ??:0
===================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 4585 RUNNING AT vegas31
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

**Comment by janjust** [comment]
If I run it on a single node it works fine.

**Comment by janjust** [comment]
`./configure --prefix=/hpc/mtr_scrap/users/tomislavj/workspace/mpich/install --with-device=ch4:ucx --with-ucx=/usr/lib64 --with-hcoll=/opt/mellanox/hcoll --enable-g --disable-fast`

**Comment by raffenet** [comment]
@janjust hmm, OK. Will investigate

**Comment by raffenet** [comment]
Oh, I didn't allow for variable sized business cards in this implementation. Duh. I have an idea and will update asap.

**Comment by janjust** [comment]
@raffenet works now, tested up to 13 nodes 208ranks, ran alltoall IMb tests.

**Comment by janjust** [comment]
+1

**Comment by raffenet** [comment]
test:jenkins/ch4/most
test:jenkins/ch4/pmi

**Comment by raffenet** [comment]
test:jenkins/ch4/most
test:jenkins/ch4/pmi

**Comment by raffenet** [comment]
@janjust this is ready to test again

**Comment by raffenet** [comment]
I had to make a few tweaks when rebasing, so getting confirmation would be good.

**Comment by raffenet** [comment]
@yfguo ready for another review

**Comment by raffenet** [comment]
@yfguo the ch4 tests results from Jenkins look good. I'm going to push another commit to fix the PMI2 breakage and just retest that configuration. Your review can still go forward.

**Comment by raffenet** [comment]
test:jenkins/ch4/pmi

**Comment by raffenet** [comment]
@janjust please test again when you have a chance. this looks good to go on our side.

**Comment by janjust** [comment]
@raffenet tested on 32 nodes - alltoall, works
👍

**Comment by raffenet** [comment]
Awesome, thanks.

**Pull request merged**
