### PR TITLE
submodule: Update UCX to v1.10.1

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Update UCX submodule.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ucx
test:mpich/ch4/gpu/ucx

**Comment by raffenet** [comment]
test:mpich/ch4/ucx
test:mpich/ch4/gpu/ucx

**Comment by raffenet** [comment]
This one should be OK to merge. As a note, v1.10.1 fixes a bug introduced in v1.10.0 that broke the UCP active message API behavior.

**Review by hzhou — APPROVED** [review]
LGTM

**Pull request merged**
