### PR TITLE
testing of MPIR_CVAR_CH4_ROOTS_ONLY_PMI

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
This is a testing PR. Same as PR #4036, but I added a few debugging code and customized `test/mpi/coll/nonblocking.c`.

### CODE REVIEW

**Comment by hzhou** [comment]
The ofi:socket provider hangs every once a while, more often with more processes. With 20 processes, it hangs nearly 1 out of 3-5. Seems some of the address inserted at second stage often fails to get through.

With ofi:psm provider, it hangs much less, but it still hangs sometime.

This is tested on single node with `MPIR_CVAR_CH4_ROOTS_ONLY_PMI` and `MPIR_CVAR_ODD_EVEN_CLIQUES`.

With multiple nodes, it does not hang (or at least I haven't observed it yet).

**Comment by hzhou** [comment]
Update: do the initial root exchange on a temporary `fi_domain`, create new `fi_domain` and use the temporary `fi_domain` to exchange addresses of the new one, then replace the old ones with the new one. Since the run-time is working on a brand new context, it does not exhibit any glitches.

We need disable `fi_inject` (by setting the inject-size thresh to zero) for the exchange to complete cleanly.

**Comment by pavanbalaji** [comment]
Testing PRs should be created in personal GitHub repos, instead of on the main mpich github.

**Comment by hzhou** [comment]
> 
> 
> Testing PRs should be created in personal GitHub repos, instead of on the main mpich github.

How do we run jenkins tests with personal repos?

**Comment by pavanbalaji** [comment]
> > Testing PRs should be created in personal GitHub repos, instead of on the main mpich github.
> 
> How do we run jenkins tests with personal repos?

By copying jenkins tests for your repos.  Please don't clutter the mpich repo.

**Pull request closed without merging**
