### PR TITLE
ch4/ucx: added hugetbl error handling fix in 1.5.0

### PR DESCRIPTION
**Pull request by minsii**
Cherry picked the hugetbl error handling fix from UCX master.

### CODE REVIEW

**Comment by minsii** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
Looks good to me. Let's just wait for Jenkins to finish, otherwise 👍 .

**Comment by minsii** [comment]
Locally confirmed that the `UCX error` disappears on `yuzu`.

**Comment by minsii** [comment]
The Jenkins result looks good.

**Comment by minsii** [comment]
Testing again after rebased with master
test:jenkins/ch4/ucx

**Comment by minsii** [comment]
test:jenkins/ch4/ucx

**Comment by minsii** [comment]
test:jenkins/ch4/ucx

**Comment by minsii** [comment]
The only failure seems unrelated. It was reported in nightly test as well.

**Pull request merged**
