### PR TITLE
romio/daos: conditionally compile out svcl setting

### PR DESCRIPTION
**Pull request by mchaarawi**
## Pull Request Description

The SVCL argument is being removed from the DAOS API, so conditionally compile out while maintaining backwards compatibility to versions where it's still required.
 

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by hzhou** [comment]
The changes look okay to me. Why is it a draft (are you still working on it)?

**Comment by mchaarawi** [comment]
> The changes look okay to me. Why is it a draft (are you still working on it)?

yes, I wanted someone else from our team to double check it. i'll flip it to ready once that is done.

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Review by hzhou — APPROVED** [review]
Looks good to me. @mchaarawi Please do a rebase and I'll merge it.

**Comment by mchaarawi** [comment]
> Looks good to me. @mchaarawi Please do a rebase and I'll merge it.

done. thanks

**Pull request merged**
