### PR TITLE
ch4/ofi: Upgrade to libfabric 1.7.0

### PR DESCRIPTION
**Pull request by hajimefu**
As libfabric 1.7.0 is out, this PR upgrades the embedded libfabric.

During the testing we found a few issues in the runtime capability set logic, which had been there for a long time but exposed by 1.7. This PR also contains a fix for that.

### CODE REVIEW

**Comment by hajimefu** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
`large_acc_flush_local` is not any slower in our testing, as far as I can tell. I would prefer to drop that patch. Then this should be good to merge.

**Comment by wesbland** [comment]
Fine with me. 👍

**Pull request merged**
