### PR TITLE
CH4 Netmod Small Fixes

### PR DESCRIPTION
**Pull request by wesbland**
* Add missing `FCNAME` macros to allow `--enable-ch4-netmod-direct=yes` (Fixes pmodels/mpich#3105)
* Stash internal flags when configuring OFI
* Remove non-existent shm netmod

### CODE REVIEW

**Comment by wesbland** [comment]
test:jenkins/ch4/most

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
I added a couple more patches here. One is trivial (removing `shm` netmod) and the other I think we've looked at before (stashing internal environment variables before configuring embedded libfabric).

The embedding patch fixes builds with this configure line:

```
./configure --with-device=ch4:ofi --prefix=$PWD/_inst --enable-ch4-netmod-direct=no --enable-ch4-shm-direct=yes --enable-debug=all --enable-fast=no --enable-ch4-shm=exclusive:posix
```

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
Tests look good here.

@raffenet - I seem to remember us (me) attempting a similar patch a while back and we decided not to do it. This is causing trouble again. Can you remember what the problem was from last time? I though the concern was that we were losing user flags, but with what I have here, that shouldn't be a problem again.

**Comment by raffenet** [comment]
This looks like it should work similar to how Hydra clears out flags. I'm OK with it. Going to run the `ch4/ucx` tests, as well, since the last patch could affect it.
test:jenkins/ch4/ucx

**Pull request merged**
