### PR TITLE
ch4/part: Add framework for nm/shm optimizations

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Add request private areas and hooks to enable lower-level optimizations for partitioned communication. This PR only adds the framework for RFC purposes. Actual optimization will come later.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
One thing this PR doesn't do, but I considered, is move `MPIDIG_mpi_psend|precv_init` functions to MPIDI namespace. Doing so would imply that they not optional, i.e. nm/shm do not have to opt-in to them. The actual optimization happens once the requests are matched (in `MPIDI_NM|SHM_precv_matched_hook`).

This is similar to how RMA window creation always first calls the "generic" version, then a follow-up hook for nm/shm optimization. The difference being that window creation is collective, so we are OK to call hooks at that time, as opposed to psend/precv matching which happens sometime later. Moving namespace would be a lot of churn, for partitioned or window creation, which is why I'm adding the RFC label.

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
Dropped the communicator reference commit because the ch4/ofi RDMA read path depends on it 😦.
test:mpich/ch4/most

**Review by hzhou — APPROVED** [review]
LGTM.

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Pull request merged**
