### PR TITLE
Fix fortran binding for f08 subarray

### PR DESCRIPTION
**Pull request by yfguo**

### CODE REVIEW

**Comment by yfguo** [comment]
test:jenkins/ch3/osx

**Comment by yfguo** [comment]
test:jenkins/ch3/tcp

**Comment by yfguo** [comment]
working, but I don't think this is the right fix. Please ignore.

**Comment by SteveO-Cray** [comment]
What problem are you trying to fix?  I might be able to find you some help (I'm pretty f08 ignorant myself) if I know what the problem is.

**Comment by yfguo** [comment]
@SteveO-Cray On the latest Intel Fortran Compiler (ifort 18), the `test/mpi/f08/subarray/test12.f90` failed to build with the following error
```
../../../../../mpich/test/mpi/f08/subarray/test12.f90(38): error #7505: If an actual argument is an array section with vector subscript and corresponding dummy argument does not have VALUE attribute, it must not have ASYNCHRONOUS / VOLATILE attribute.   [BUF]
            call mpi_isend(iar(2:7), 6, MPI_INTEGER, 1, 678, MPI_COMM_WORLD, request, ierr);
```
Haven't tried Cray Fortran Compiler yet, but will do.

**Comment by raffenet** [comment]
@yfguo can this be closed?

**Comment by yfguo** [comment]
Problem is solved by updating confdb, closing.

**Pull request closed without merging**
