### PR TITLE
mpl: automatic debug logging for function entering/leaving

### LINKED ISSUE #4111: general: remove MPIR_FUNC_ENTER/EXIT
We have these `MPIR_FUNC_VERBOSE_STATE_DECL`, `MPIR_FUNC_VERBOSE_ENTER`, `MPIR_FUNC_VERBOSE_EXIT` boilerplate code in nearly every functions -- nearly, but not all of them, which raises the question when to add them or delete them. Ultimately, this depends on its purpose and utility, and I would like to argue that their utility is diminishing and hardly account for the cluttering it brings. 

Previously we had some discussion in issue #3535. I think it is worthwhile to keep the discussion open.

First, I would like to acknowledge that these logging are potentially useful. I personally never use them so I would like to gather comment from other developers that do use them -- please add your comment if you do use them. 

Second, let's list some options:

1. Keep the way as is, having explicit `DECL/ENTER/EXIT` macros in every functions.

2. Remove all explicit macros. Provide script in `maint/` to automatically insert these boilerplate based on our function naming conventions and potential comment annotations. 
    This is proposed in #3535. It has been tried and works. The concern is the massive script insertion may mess-up local git diffs -- which matters to some developers.

3. Remove all explicit macros. Provide script in `maint/` to selectively add logging calls. 
    This is a modification of option 2.  Instead of adding logs to every function blindly, we only add logs to those functions that we are interested. The script need be more extensive to provide useful options. Example options include: function-list, file-list, sub-tree list, etc.
    This will have similar concern of messing up local git diffs, but in a smaller controlled scope.

4. Remove all explicit macros. Add support to gcc `-finstrument-functions`. 
    Since they are boiler-plates, ideally we'd like compiler do this for us without messing up the source code. Turns out, `gcc` already have something like this. `-finstrument-functions` automatically adds function call to `__cyg_profile_func_enter/exit` to every function. We can provide a custom code to these functions and therefore able to do exactly what our current debug/logging facility do.
    The catch is gcc only supply the function address instead of human readable function names -- which, makes sense as string handling is expensive and messy. To make it useable, we can easily provide a script in `maint/` to filter the log and translate the address to actual function names and line numbers in the source code. The translations are supported in "binutils" by `addr2line`.

In my opinion, the sacrifice to readability by the boiler-plate clutter is too big to tolerate, so any of the alternative 2-4 (or combination of them) are better than the current status.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

GCC and its suit provides `-finstrument-functions` option to automatically insert function tracing calls. This PR utilizes this option to replace current manual `MPIR_FUNC_ENTER/LEAVE` macros.

TODO list:
* [x] add MPL facility
* [x] add log parsing script
* [x] add/enable configure options
* [x] remove all `MPIR_FUNC_VERBOSE_ENTER/LEAVE` macros
* [x] add script to automatically insert logging macros (as a fall-back)

## Expected Impact

Cleaner code.

## Controversial
It works on Linux. 

However, I couldn't get it to work on mac (Mojave). On Mac, it appears that each function pointer parameters for the `cyg_profile_func_enter/exit`  calls are randomly shifted. Figuring out the base loading address is insufficient to resolve the function names. 

The more I fiddling around, the more disgust I accumulate. Instead of `void *fn, void *call_site` parameters, the compiler could simply generate `const char *fn_name, const char *call_site_name`. C99 has `__func__` standardized, so those `const char *` names are right there. It is really silly jumping through all these hoops using binary addresses. 

At this point, I am much preferring having a script automatically inserting tracing macros.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
       Fixes #4111
* [ ] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
* `./configure --enable-g=log`
* `mpirun -n 4 ./cpi -mpich-dbg=file -mpich-dbg-level=verbose -mpich-dbg-filename="dbg-%d.log"`
* `perl ../maint/util/mpich_parse_log.pl dbg-0.log > t.log`

Raw log:
```
0       -1      ...     2       0.000079        [ADDR:0x7ff413bbf481] Leaving [FUNCTION:0x7ff413bbc790]
0       -1      ...     1       0.000140        [ADDR:0x7ff413bbf486] Entering [FUNCTION:0x7ff413c2b110]
0       -1      ...     1       0.000149        [ADDR:0x7ff413bbf486] Entering [FUNCTION:0x7ff413c2af40]
0       -1      ...     2       0.000157        [ADDR:0x7ff413bbf486] Leaving [FUNCTION:0x7ff413c2af40]
0       -1      ...     1       0.000163        [ADDR:0x7ff413bbf486] Entering [FUNCTION:0x7ff413c2afa0]
0       -1      ...     2       0.000169        [ADDR:0x7ff413bbf486] Leaving [FUNCTION:0x7ff413c2afa0]
...```
Parsed log:
```
140686278217728 - 140686282833920 - /home/hzhou/work/pull_requests/mpich-dbglog/_inst/lib/libmpi.so.0.0.0
0       -1      ...     1       0.000140        -> MPIR_T_env_init 
0       -1      ...     1       0.000149        . -> MPIR_T_cat_env_init
0       -1      ...     2       0.000157        . <- MPIR_T_cat_env_init
0       -1      ...     1       0.000163        . -> MPIR_T_cat_env_init
0       -1      ...     2       0.000169        . <- MPIR_T_cat_env_init
0       -1      ...     1       0.000175        . -> MPIR_T_cvar_env_init
...
```

**Comment by hzhou** [comment]
The automatic logging logs way more functions than before. Here is an example with both types logging:
```
0       -1      ...    1       0.012351        . . . . -> MPIDI_CH3_VC_Init
0       -1      ...     1       0.012355        src/mpid/ch3/channels/nemesis/src/ch3_init.c    159     Entering MPID_STATE_MPIDI_CH3_VC_INIT
0       -1      ...    2       0.012360        src/mpid/ch3/channels/nemesis/src/ch3_init.c    192     Leaving MPID_STATE_MPIDI_CH3_VC_INIT
0       -1      ...     2       0.012364        . . . . <- MPIDI_CH3_VC_Init
```

**Comment by hzhou** [comment]
@wesbland Do you think this solution is okay?

**Comment by wesbland** [comment]
This seems reasonable to me.

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
Line summary is pretty enticing 😄! `+391 −10,473`. I want to send this out to the devel list for feedback before going any further, but I definitely like the direction. One note: there is a program `addr2line` in `binutils` that should take care of some of the work in your script, if I am not mistaken.

**Comment by hzhou** [comment]
> One note: there is a program `addr2line` in `binutils` that should take care of some of the work in your script, if I am not mistaken.

True. However, it is undesirable to call `addr2line` for each address translation, as each time it need reload symbol table. It does have a batch mode, but then we need add code to manage the batching. For just turn the address into function names, I find loading all the symbols at once using `nm` simple enough. If there is demand to also translate call-site addr into `__FILE__:__LINE`, then probably calling `addr2line` is more economic.

**Comment by yfguo** [comment]
In the meantime, I will make this work for OSX which does not have a proc fs

**Comment by pavanbalaji** [comment]
It'll be good to start with a survey on what compilers/platforms can we do this without any additional scripts, i.e., purely using compiler-provided functionality.  At that point, we can decide whether that's set is large enough for us to remove the FUNC_ENTER/EXIT macros fully.  Supporting all platforms might not be critical, but it depends on how many/which platforms we are missing.

**Comment by hzhou** [comment]
> 
> 
> It'll be good to start with a survey on what compilers/platforms can we do this without any additional scripts, i.e., purely using compiler-provided functionality. At that point, we can decide whether that's set is large enough for us to remove the FUNC_ENTER/EXIT macros fully. Supporting all platforms might not be critical, but it depends on how many/which platforms we are missing.

`gcc`, `clang`, `icc` on Linux.

If you don't care about symbol names (only hexadecimal function addresses) then it pretty much works on all platforms. However, I don't think anyone would find that useful.

You should try it to see whether you like this solution. ref https://github.com/pmodels/mpich/pull/4139#issuecomment-549418623, it still need you to run a script to translate the log file into readable symbol names. And personally, I don't really like it since it logs *everything*. We can annotate functions to skip logging, but that simply adds the maintenance back, so no go.

**Comment by hzhou** [comment]
@pavanbalaji If you give #4276 a try, you'll see that is way more cleaner. There is no code added to the code base so no maintenance or mess there. The scripts added in `maint/` folder is just helper scripts that are not essential. To the worst case, one run with `--enable-g=log` and by default, only explicit debug logs are showing, no function logs -- that is not a disaster. Most of the time we don't really need function logs. To get function logs, just run the script:
`perl maint/util/add_func_log.pl`
and re-`make`, clean and simple.

The script takes care of multiple exit path as long as follow basic coding style, which we already do. The only requirement is always protect 
```
if (...) {
    return ...;
}
```
with braces. I can make script to add braces automatically, but that makes clean removal (for clean commits) impossible.

**Comment by pavanbalaji** [comment]
It's not cleaner.  I already pointed out on that PR that anything to do with adhoc scripts is problematic.  I'm going to close both PRs till we have a better solution.

**Pull request closed without merging**
