### PR TITLE
abi: add mpix op and errhandler delcarations in mpi_abi.h

### LINKED ISSUE #6997: ABI build broken
https://github.com/mpi4py/mpi4py-testing/actions/runs/8856151905/job/24322077944

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
These new extensions are meant for the new mpi abi prototypes.

Fixes #6997
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/custom
config: mpi-abi

**Comment by hzhou** [comment]
test:mpich/custom
config: mpi-abi

**Comment by hzhou** [comment]
test:mpich/custom
config: mpi-abi

**Comment by hzhou** [comment]
test:mpich/custom
config: mpi-abi

**Comment by hzhou** [comment]
test:mpich/custom
config: mpi-abi

**Review by raffenet — APPROVED** [review]
This looks good to me. There are some compilation failures in the nightly builds related to the op proxy changes that probably need attention.
```sh
src/binding/fortran/mpif_h/user_proxy.c:29:5: error: conflicting types for ‘MPII_op_create’; have ‘int(void (*)(void *, void *, MPI_Fint *, MPI_Fint *), MPI_Fint,  MPI_Fint *)’ {aka ‘int(void (*)(void *, void *, long int *, long int *), long int,  long int *)’}
   29 | int MPII_op_create(F77_OpFunction * opfn, MPI_Fint commute, MPI_Fint * op)
      |     ^~~~~~~~~~~~~~
In file included from src/binding/fortran/mpif_h/user_proxy.c:6:
src/binding/fortran/mpif_h/mpi_fortimpl.h:404:5: note: previous declaration of ‘MPII_op_create’ with type ‘int(void (*)(void *, void *, int *, MPI_Datatype *), MPI_Fint,  MPI_Fint *)’ {aka ‘int(void (*)(void *, void *, int *, int *), long int,  long int *)’}
  404 | int MPII_op_create(MPI_User_function * opfn, MPI_Fint commute, MPI_Fint * op);
      |     ^~~~~~~~~~~~~~
make[2]: *** [Makefile:39536: src/binding/fortran/mpif_h/lib_libf77_mpi_la-user_proxy.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
copying selected object files to avoid basename conflicts...
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/scratch/jenkins-slave/workspace/mpich-main-fortran/compiler/gnu/config/integer-8/label/ubuntu22.04/netmod/ch3-tcp/mpich-main'
make[1]: *** [Makefile:40012: install-recursive] Error 1
make[1]: Leaving directory '/scratch/jenkins-slave/workspace/mpich-main-fortran/compiler/gnu/config/integer-8/label/ubuntu22.04/netmod/ch3-tcp/mpich-main'
make: *** [Makefile:40123: install] Error 2
```

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by raffenet** [comment]
To make clear my view on this and #6965, I'm approving these extensions in hopes of furthering the ABI discussion. As this point the MPICH ABI implementation is malleable and IMO, can and should be a place for settling open questions before standardization.

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Pull request merged**
