### PR TITLE
ch4/posix: shortcut eager send to use lightweight request

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Avoid creation (and later free) of normal request object in the posix eager send path. This should improve the small message intranode latency.

## Discuss
We save two critical sections, one in `MPIR_Request_create` and one in `MPIR_Request_free`.
We also save one atomic operation in `MPIR_Request_complete`.

I guess this is more significant in `MPI_THREAD_MULTIPLE`. Otherwise, we are just saving a few instruction counts.

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
Benchmark on Jenkins node (Intel Xeon Silver 4216 @ 2.10GHz, `mpirun -n 2 -bind-to core`):
```
# size              before                          after
     0  0.814 +/- 0.124         0.765 +/- 0.047
     1  0.821 +/- 0.004         0.783 +/- 0.087
     2  0.817 +/- 0.015         0.678 +/- 0.002
     4  0.661 +/- 0.017         0.607 +/- 0.023
     8  0.683 +/- 0.016         0.599 +/- 0.002
    16  0.660 +/- 0.017         0.605 +/- 0.011
    32  0.666 +/- 0.014         0.607 +/- 0.004
    64  0.692 +/- 0.002         0.619 +/- 0.002
   128  0.715 +/- 0.001         0.641 +/- 0.002
   256  0.787 +/- 0.009         0.717 +/- 0.002
   512  0.868 +/- 0.003         0.795 +/- 0.002
  1024  0.965 +/- 0.011         0.890 +/- 0.003
  2048  1.124 +/- 0.023         1.061 +/- 0.003
  4096  1.477 +/- 0.036         1.397 +/- 0.003
  8192  2.240 +/- 0.003         2.084 +/- 0.010
 16384  4.884 +/- 0.095         4.775 +/- 0.010
 32768  6.459 +/- 0.082         6.193 +/- 0.051
```

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
MPI_THREAD_MULTIPLE latency (albeit uncontended):
```
     0  0.912 +/- 0.144         0.795 +/- 0.108
     1  0.925 +/- 0.001         0.843 +/- 0.001
     2  0.846 +/- 0.097         0.819 +/- 0.058
     4  0.706 +/- 0.002         0.658 +/- 0.003
     8  0.715 +/- 0.008         0.658 +/- 0.009
    16  0.708 +/- 0.002         0.660 +/- 0.002
    32  0.715 +/- 0.002         0.662 +/- 0.002
    64  0.736 +/- 0.002         0.684 +/- 0.002
   128  0.758 +/- 0.002         0.711 +/- 0.002
   256  0.828 +/- 0.002         0.792 +/- 0.002
   512  0.896 +/- 0.002         0.871 +/- 0.002
  1024  0.994 +/- 0.003         0.961 +/- 0.002
  2048  1.170 +/- 0.004         1.134 +/- 0.004
  4096  1.499 +/- 0.004         1.467 +/- 0.003
  8192  2.174 +/- 0.026         2.139 +/- 0.015
 16384  4.949 +/- 0.020         4.895 +/- 0.015
 32768  6.312 +/- 0.020         6.333 +/- 0.014
```
The gain is consistent, but only slight better.

**Review by raffenet — APPROVED** [review]
This looks OK to me. I was thinking while looking at the code that we might want to add explicit `am_isend_eager` and `am_isend_rndv` APIs rather than have a single `am_isend`. We did finally expose an eager limit to the generic layer after a lot of debate.

But this is a good change in the meantime.

**Pull request merged**
