### PR TITLE
test/rma: add tests with atomics hints in testlist

### PR DESCRIPTION
**Pull request by minsii**
The tests have been extended to cover atomics hints TEST_HWACC_INFO
and TEST_ACCOPS_INFO, but they were not added into testlist.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by minsii** [comment]
test:mpich/ch4/most

**Comment by minsii** [comment]
test:mpich/ch4/most

**Comment by minsii** [comment]
@hzhou I found this old PR which was never reviewed. Can you please help review? It is a very simple testlist change.

**Review by hzhou — APPROVED** [review]
LGTM. Probably it will be a better idea to combine all the datatypes into a single test.

**Comment by minsii** [comment]
We can address the datatype refactoring in a separate PR.

**Comment by minsii** [comment]
skip retest for rebase push as the new commits are irrelevant to this PR

**Pull request merged**
