### PR TITLE
pmi+hydra: refactor PMI message layer

### LINKED ISSUE #6191: hydra: pmi wire buffer not large enough
I tried running an MPI program fully subscribed on two nodes of JLSE skylake.
```
mpiexec -bind-to core -n 112 -ppn 56 ./examples/cpi
mpiexec: src/pmi_wire.c:580: PMIU_cmd_output_v1: Assertion `buflen + 1 < MAX_TMP_BUF_SIZE' failed.
[1]    21311 abort (core dumped)  mpiexec -bind-to core -n 112 -ppn 56 ./examples/cpi
```

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Abstract the message protocol handling into `PMIU_msg_...` utilities.

* Generated `pmi_msg.h` and `pmi_msg.c`
    * https://github.com/hzhou/Temp/blob/master/pmi_msg.h
    * https://github.com/hzhou/Temp/blob/master/pmi_msg.c

Fixes #6191  (ref: https://github.com/pmodels/mpich/pull/6168/commits/a21bae95b60bb49b2085175748c77dba66747c04)
[skip warnings]

## Reference
* [Flux RFC document on PMI-1](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_13.html)
## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/pmi
test:mpich/ch3/most
test:mpich/ch4/most

**Review by raffenet — COMMENTED** [review]
Looks good. Just one comment about reserving key prefixes to avoid collision with job attributes if we do merge the server side functionality.

**Comment by hzhou** [comment]
test:mpich/pmi

**Review by raffenet — APPROVED** [review]

**Pull request merged**
