### PR TITLE
Improvements to MPI_Alloc_mem

### PR DESCRIPTION
**Pull request by pavanbalaji**
## Pull Request Description

Several improvements to MPI_Alloc_mem, including support for the MPI-4 info hint `mpi_minimum_memory_alignment`.

Fixes https://github.com/pmodels/mpich/issues/4883.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:mpich/ch3/most
test:mpich/ch4/most
test:mpich/warnings/gpu

**Comment by pavanbalaji** [comment]
test:mpich/ch3/most
test:mpich/ch4/most
test:mpich/warnings/gpu

**Review by yfguo — APPROVED** [review]

**Comment by pavanbalaji** [comment]
test:mpich/ch3/most
test:mpich/ch4/most
test:mpich/warnings/gpu

**Comment by hzhou** [comment]
test:mpich/authorship

**Comment by hzhou** [comment]
test:mpich/authorship

**Comment by hzhou** [comment]
test:mpich/whitespace

**Comment by hzhou** [comment]
test:whitespace

**Comment by hzhou** [comment]
test:mpich/whitespace

**Comment by pavanbalaji** [comment]
test:mpich/ch3/most

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
test:mpich/ch4/sock

**Comment by hzhou** [comment]
test:mpich/ch3/sock

**Pull request merged**
