### PR TITLE
Remove FCNAME and FUNCNAME macros (Issue #2787)

### PR DESCRIPTION
**Pull request by akhillanger**
This PR removes FCNAME and FUNCNAME macros. FCNAME gets replaced by `__func__`, the compiler provided symbol. Issue #2787

### CODE REVIEW

**Comment by akhillanger** [comment]
test:ch3/jenkins/most
test:ch4/jenkins/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by akhillanger** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by wesbland** [comment]
This PR obviously needs a lot of work to be brought back up to speed. I'm going to close this and someone else can start a new PR.

**Pull request closed without merging**
