### PR TITLE
Comm parent commit

### PR DESCRIPTION
**Pull request by yfguo**
## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by yfguo** [comment]
@zhenggb72 Can you try this PR to see if it works with `fi_join_collective`.

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi

**Comment by yfguo** [comment]
test:mpich/ch4/ofi

**Comment by zhenggb72** [comment]
in ch4_init.c, needs to call the new hook function:
     mpi_errno = MPIR_Comm_commit(MPIR_Process.comm_world);
     MPIR_ERR_CHECK(mpi_errno);
+    mpi_errno = MPIR_Comm_parent_commit(MPIR_Process.comm_world, MPIR_Process.comm_world);
+    MPIR_ERR_CHECK(mpi_errno);

**Comment by zhenggb72** [comment]
also missing:
.mpi_comm_parent_commit_hook = MPIDI_OFI_mpi_comm_parent_commit_hook,
in the function table in: src/mpid/ch4/netmod/ofi/func_table.c

**Comment by raffenet** [comment]
Why this approach vs. #4426?

**Comment by zhenggb72** [comment]
> Why this approach vs. #4426?

I think this approach is conceptually cleaner, and less intrusive. 
 #4426 changes the meaning and signature of MPIR_Comm_commit, which impacts the implementation of MPIR_Comm_commit itself and all the hook functions called by it.

**Comment by raffenet** [comment]
Before we go much further, we should agree on the background. Off list, we discussed that the `fi_join_collective` call was collective over the parent communicator, which is why it needs to be accessible from the netmod hook functions.

I see this passage in the manpages:

> For provider managed memberships, the join collective call requires as input a coll_addr that refers to either an address associated with an AV set (see fi_av_set_addr) or an existing collective group (obtained through a previous call to fi_join_collective). The fi_join_collective call will create a new collective subgroup. If application managed memberships are used, coll_addr should be set to FI_ADDR_UNAVAIL.

What about constructing the collective AV set locally instead of relying on the parent comm? Is that a possibility? https://ofiwg.github.io/libfabric/master/man/fi_av_set.3.html

**Comment by yfguo** [comment]
@raffenet I think this PR is a slightly cleaner solution. I have just updated #4426 to show what these two solutions could be.

**Comment by raffenet** [comment]
@yfguo thanks for the additional info. My other question is posed to @zhenggb72 about whether we truly need to call a collective on the parent comm in order to setup libfabric collectives. If we can create an address set locally at each process for the purposes of setting up the new collective. The latter would only require a collective call on the new comm, so exposing the parent comm in this way would be unnecessary.

**Comment by zhenggb72** [comment]
@raffenet I have tried that scheme on libfabric, but it does not work. This is because in this case, only new group member calls fi_join_collective, and so I need to pass a multicast group address as the parameter to the function. The function to get multicast group address from an av_set seems broken. 
Let me look into libfabric to see how this can be done. If this bug is fixed, maybe we can do the join collective only on the new group members.

**Comment by pavanbalaji** [comment]
This change is getting a bit out of hand.  I think it's time we completely removed the comm_commit stage.  That's the root cause of most of the problems.  There's no commit phase in MPI.  That's an MPICH internal usage, and one that got introduced in MPICH-2.  We should instead go back to the mpich-1 design although, admittedly, it'll require some effort to redo the code:

1. Find a context ID (utility function using the parent comm)
2. Inherit attributes/info from the parent comm
3. call the downstream hook

**Comment by zhenggb72** [comment]
@raffenet In theory there is a flaw though if the MPI call is Comm_create(). If only the new group member join the collective, and let the other ranks go without participating, those ranks may call another Comm_create that potentially overlaps with the first one.

> This change is getting a bit out of hand. I think it's time we completely removed the comm_commit stage. That's the root cause of most of the problems. There's no commit phase in MPI. That's an MPICH internal usage, and one that got introduced in MPICH-2. We should instead go back to the mpich-1 design although, admittedly, it'll require some effort to redo the code:
> 
> 1. Find a context ID (utility function using the parent comm)
> 2. Inherit attributes/info from the parent comm
> 3. call the downstream hook


I guess this is fine. The concern in this PR is rather which ranks call the downstream hook, the parent_comm or new comm?

**Comment by raffenet** [comment]
> The function to get multicast group address from an av_set seems broken.
> Let me look into libfabric to see how this can be done. If this bug is fixed, maybe we can do the join collective only on the new group members.

**Much** prefer fixing libfabric. Then these changes can be tossed. Refactoring comm creation might still be a good idea, but would have less priority.

**Comment by zhenggb72** [comment]
> > The function to get multicast group address from an av_set seems broken.
> > Let me look into libfabric to see how this can be done. If this bug is fixed, maybe we can do the join collective only on the new group members.
> 
> **Much** prefer fixing libfabric. Then these changes can be tossed. Refactoring comm creation might still be a good idea, but would have less priority.

Working on that. I think I fixed it, going to submit a PR soon to ofiwg.
However, I want to make sure semantically this is ok, that is:
for MPI_comm_create,  in the comm_commit only those ranks in the new group calls join_collective (which internally calls allreduce), other ranks do not block. Is there any potential risk about this?

**Comment by raffenet** [comment]
> > > The function to get multicast group address from an av_set seems broken.
> > > Let me look into libfabric to see how this can be done. If this bug is fixed, maybe we can do the join collective only on the new group members.
> > 
> > 
> > **Much** prefer fixing libfabric. Then these changes can be tossed. Refactoring comm creation might still be a good idea, but would have less priority.
> 
> Working on that. I think I fixed it, going to submit a PR soon to ofiwg.
> However, I want to make sure semantically this is ok, that is:
> for MPI_comm_create, in the comm_commit only those ranks in the new group calls join_collective (which internally calls allreduce), other ranks do not block. Is there any potential risk about this?

I believe this will be safe.

**Comment by raffenet** [comment]
@zhenggb72 I see https://github.com/ofiwg/libfabric/pull/5826 was merged. Should we close this assuming you'll be able to construct the AV set independent of the parent comm?

**Comment by zhenggb72** [comment]
Yes, my libfabric PR fixed it. I can go back to the original plan to use Comm_commit hook function for construct av set now.

**Comment by raffenet** [comment]
Great, thanks for confirming.

**Pull request closed without merging**
