### PR TITLE
warnings: misc coverity defect fix

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Fixing some coverity reports.

Note: There are too many outstanding issues (184 currently), so this will be a continuous series.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by hzhou** [comment]
> Hooray for people checking Coverity! 😄

They send me email only showing a couple new defect, so I went in on a fine morning, and ... how I regret that 😒

**Comment by wesbland** [comment]
> > Hooray for people checking Coverity! 😄
> 
> They send me email only showing a couple new defect, so I went in on a fine morning, and ... how I regret that 😒 -- It's a can of worms.

Yep. We use Klocwork (which is horribly noisy and false positive prone). I'm trying to move us to Coverity and then we can sync on the same set of checkers enabled so we can at least help each other out a bit more here.

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Pull request merged**
