### PR TITLE
misc: fixes some issues with mpicc and friends

### LINKED ISSUE #1045: mpicc -compile-info/-link-info
**Originally by _balaji_ on 2010-05-09 23:18:36 -0500**

---

mpicc -compile-info and -link-info don't work correctly -- they just show all flags.

### LINKED ISSUE #4171: /bin/sh version of the mpicc mistreats quotes and attempts array expansion
```
$ mpicc -show -DT="'a'" -DT="'\""
cc  \"-DT='a'\" '-DT='"' -lmpi
```

there's also the erroneous array expansion, `"${allargs[@]}"`, at https://github.com/pmodels/mpich/blob/c99bb8d563ee374beb652bf0af812931bbe0773d/src/env/mpicc.sh.in#L264-L266

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
* Fixes spelling errors
* Fixes #4171 -- misquoting in posix version of scripts
* Fixes #1045 -- add `-show-compile-info` and `-show-link-info`

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/tcp

**Comment by hzhou** [comment]
We have 8 scripts that are largely repeated -- really tiresome! I would very much like to use a Perl or Python scripts generate them so we can properly use templates rather than repeating changes manually.

**Review by raffenet — APPROVED** [review]
Pavan once proposed removing the bash versions since (in theory) they worked identically to the POSIX versions. Maybe after this change that is true? Agree we could do better to avoid all the duplication.

**Comment by hzhou** [comment]
> 
> 
> Pavan once proposed removing the bash versions since (in theory) they worked identically to the POSIX versions. Maybe after this change that is true? Agree we could do better to avoid all the duplication.

yeah, where is that PR? I recall that there was a freebsd failure, that we have to keep the bash version because non-bash shells may not be 100% posix portable?

**Comment by raffenet** [comment]
https://github.com/pmodels/mpich/pull/3499

I think the bash array syntax have been the issue on FreeBSD, but don't remember for sure.

**Pull request merged**
