### PR TITLE
Clean trailing whitespace

### PR DESCRIPTION
**Pull request by yfguo**
The first commit cleans some example code and the template for header files which I think makes a lot of sense.

The second one cleans the build scripts, which is more of an OCD thing.

### CODE REVIEW

**Comment by yfguo** [comment]
whitespace-checker is false positive as it does not process Fortran code correctly.

**Comment by wesbland** [comment]
This doesn't seem to cause any problems with our internal patches so I guess I'm fine with it. 👍

**Comment by wesbland** [comment]
I guess the cleanup script missed these because they're all files that it's set up to ignore?

**Comment by raffenet** [comment]
Can you add a commit message prefix `whitespace: ` to these? I'm not convinced I want to include this for 3.3, though. Might merge just after the release is cut. Or do we really want to include this?

**Comment by hzhou** [comment]
@yfguo Close or update?

**Comment by pavanbalaji** [comment]
@yfguo is something happening with this PR?  These files are ones that we run the white space checker on anyway, so it'll be good to clean them up.

**Comment by yfguo** [comment]
@pavanbalaji I can bring this up to date. Although I am not sure if this is a good time to do white space cleaning and potentially conflicts with everyone. Some vendors has voiced the concern about it.

If we decide to delay it, I will create an issue for it and close the PR.

**Comment by pavanbalaji** [comment]
Yeah, let's close it for now.

**Pull request closed without merging**
