### PR TITLE
Remove MPIX_Mutex extentions

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
We explicitly say in version.m4 that MPIX functionality is not considered part of the ABI, so we are safe to remove these. I'll remove the ABI label from this PR.

**Comment by minsii** [comment]
@raffenet The PR looks good to me. But could you please provide more information why we want to delete it ?

**Comment by raffenet** [comment]
1. It does not seem there is a proposal to bring these features to the MPI Forum for standardization
2. This implementation is based on MPI-2 RMA. An MPI-3 version exists in `test/mpi/rma/mcs-mutex.c` which was said to be more efficient according to #1778

I can add this to the commit message for historical purposes.

**Comment by minsii** [comment]
Yes, adding comments in commit message will be useful.

**Comment by raffenet** [comment]
@minsii I have added more info to the commit messages. Let me know if they look OK. No rush.

**Comment by minsii** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by minsii** [comment]
I believe the failing tests should be irrelevant to this PR. Shall we go ahead and merge it ?

**Pull request merged**
