### PR TITLE
config: refactoring handling of configure subcomponents

### PR DESCRIPTION
**Pull request by hzhou**
When configure with sub-configured components such as mpl, openpa etc.there are many common semantics and logics in dealing with embedded, system, user supplied prefix. Currently these are individually coded, resulting in significant amount of code duplication and with multiple inconsistencies. It is also difficult to patch behaviors as each time it may involve some exhaustive search and understanding.
    
By creating confdb/aclocal_subdir.m4, these common code are factored out to unify behavior and improve code reuse. It also gathers all component specific handling into one central place.

Configure is too big and it Is the bottleneck of current build system. Refactoring it is the starting step.

### CODE REVIEW

**Comment by hzhou** [comment]
This PR is related to https://github.com/pmodels/mpich/issues/3427.

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp

**Comment by raffenet** [comment]
This will take some time to look through. At a glance, though, the Travis test failed because Hydra now seems to treat `libcr` as a requirement when it should be optional.

**Comment by hzhou** [comment]
test:jenkins/ch4/ucx

**Comment by hzhou** [comment]
test:jenkins/ch3/tcp
test:jenkins/ch3/sock

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
test:ch3/most
test:ch4/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:jenkins/custom

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
test:jenkins/ch3/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by hzhou** [comment]
test:ch3/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most

**Comment by hzhou** [comment]
test:jenkins/ch3/most

**Comment by hzhou** [comment]
test:jenkins/custom

**Comment by hzhou** [comment]
test:jenkins/custom

**Comment by hzhou** [comment]
test:jenkins/custom
netmod=ch4:ucx
testlist: attr

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by pavanbalaji** [comment]
Large refactoring change.  Should be delayed till the next major release.

**Pull request closed without merging**
