### PR TITLE
Fixes for 3.3.1

### PR DESCRIPTION
**Pull request by raffenet**
Initial draft set of changes for 3.3.1 bug-fix release. I filtered out ch4 fixes for this series, as I expect ch4 users to build from master to get the latest developments. I used the following command to produce a git log which I then picked commits from one-by-one:

> git log --oneline v3.3..master ":(exclude)src/mpid/ch4"

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by raffenet** [comment]
Failures here are for `gather_big` with ch4/ucx, which master also exhibits. ch3/tcp failures are from slurm communication issue, the actual tests passed successfully.

**Comment by yfguo** [comment]
test:jenkins/ch3/most

**Comment by raffenet** [comment]
This looks OK to merge based on testing. One series of fixes not included are the large dtype fixes from @minsii. Since there were reported internally and not by a user, I'm tempted to say leave them out of 3.3.x for now. Thoughts?

**Comment by pavanbalaji** [comment]
> This looks OK to merge based on testing. One series of fixes not included are the large dtype fixes from @minsii. Since there were reported internally and not by a user, I'm tempted to say leave them out of 3.3.x for now. Thoughts?

Yeah, those are OK to leave out.  We lived with those bugs for a decade.  Another few months won't change anything.

**Comment by yfguo** [comment]
I have looked through the commits. I think the PR is good to go without the dtype fixes.

**Comment by raffenet** [comment]
👍

**Pull request merged**
