### PR TITLE
thread: introduce light and heavy versions of thread yield

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

The way nemesis progress uses conditional variable to synchronize
between progress threads requires the progress to monoplize the lock to
certain extent.

Discussion:
`MPID_THREAD_CS_YIELD` is a tricky business  --
1. It is not as simple as `MPID_THREAD_CS_EXIT` followed by `MPID_THREAD_CS_ENTER` due to the use of recursive locking. It is possible to eliminate all recursive mutex usages in mpich, but that is a separate effort.
2. How effective to yield depends on several factors
    * How quick is the lock being held. In nemesis, each `progress_test` takes couple hundred cycles or less. A busy-style or noop between `EXIT/ENTER` does not cause lock-monopoly. If the lock is held for more than a thousand cycles a time, then other waiting threads will be put to sleep, causing severe lock-monopoly.
    * How big the window is for the lock to remain unlocked for other threads to grab.  A sleep is an effective yield, ensuring other threads will wake up and grab the lock before this thread re-grab the lock. But a sleep is also heavy. In between, try multiple `sched-yield` can significantly increase the fairness for grabbing lock.
    * Finally, what thread package we are using. If we are using argobots, then a `MPL_thread_yield` is mandatory.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by hzhou** [comment]
refer to discussion in #4424

**Comment by hzhou** [comment]
Looking at `./threads/pt2pt/threads 2`:
* ch3:tcp on shared memory: 2.27sec
* ch3:tcp on tcp: 44 sec
* ch3:tcp with mutliple `sched_yield`: 585 sec.  -- I guess we should rejoice that it is not deadlocking :smiley:

**Comment by hzhou** [comment]
test:mpich/warnings/quick

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most
test:mpich/async

**Comment by hzhou** [comment]
@raffenet I abandoned the previous hacky patch (that undefine/redefine `MPL_thread_yield` inside nemesis) and opted to have two explicit light/heavy versions.  I also pulled two other patches that are needed for the ch4 fixes. It's ready for your review.

**Comment by raffenet** [comment]
I think I understand the problem now, but the proposal still seems hacky. I know there's been various decisions in the past regarding how to yield. Maybe @pavanbalaji can share some thoughts?

**Comment by pavanbalaji** [comment]
> I think I understand the problem now, but the proposal still seems hacky. I know there's been various decisions in the past regarding how to yield. Maybe @pavanbalaji can share some thoughts?

Yeah, this is a total hack.  I'm not going to signoff on this.  😃

**Comment by hzhou** [comment]
> > I think I understand the problem now, but the proposal still seems hacky. I know there's been various decisions in the past regarding how to yield. Maybe @pavanbalaji can share some thoughts?
> 
> Yeah, this is a total hack. I'm not going to signoff on this. 😃

I need suggestions or discussions. This is a blocker.

**Comment by pavanbalaji** [comment]
> I need suggestions or discussions. This is a blocker.

The multiple yield path is a no-go as far as I'm concerned.  If you really want to force a yield, why don't you use `futex`?  It can be repurposed as a kernel queuing system.

**Comment by hzhou** [comment]
> > I need suggestions or discussions. This is a blocker.
> 
> The multiple yield path is a no-go as far as I'm concerned. If you really want to force a yield, why don't you use `futex`? It can be repurposed as a kernel queuing system.

Is the multiple yield part the only bit that you feel to be hacky (which I admit is)? How is the `MPL_thread_yield_light/heavy` wrapper? As long as ch3 and ch4 can have different yield solutions, I am less concerned with what actually goes into the heavy yield. A `sleep(0)` would also work. My test shows multiple yield has less overhead than the sleep, but it is not critical for ch4 performance. Ch4 is really emphasizing on not to block other threads and any threads can contribute equally on progress; while in ch3, we serialize one thread to make most of the progress , which I believe is the reason that a heavy yield become detrimental.

I have to investigate the futex, but that can be orthogonal to this PR. If futex does not put waiting threads to sleep, then we can simply switch back to use "light" yield.  A futex implementation will need swap out nearly the entire `mpidu_thread_fallback.h`. Depend on the pro and cons, we may still need two versions for ch3 and ch4.

**Comment by pavanbalaji** [comment]
> > > I need suggestions or discussions. This is a blocker.
> > 
> > 
> > The multiple yield path is a no-go as far as I'm concerned. If you really want to force a yield, why don't you use `futex`? It can be repurposed as a kernel queuing system.
> 
> Is the multiple yield part the only bit that you feel to be hacky (which I admit is)? How is the `MPL_thread_yield_light/heavy` wrapper? As long as ch3 and ch4 can have different yield solutions, I am less concerned with what actually goes into the heavy yield. A `sleep(0)` would also work. My test shows multiple yield has less overhead than the sleep, but it is not critical for ch4 performance. Ch4 is really emphasizing on not to block other threads and any threads can contribute equally on progress; while in ch3, we serialize one thread to make most of the progress , which I believe is the reason that a heavy yield become detrimental.
> 
> I have to investigate the futex, but that can be orthogonal to this PR. If futex does not put waiting threads to sleep, then we can simply switch back to use "light" yield. A futex implementation will need swap out nearly the entire `mpidu_thread_fallback.h`. Depend on the pro and cons, we may still need two versions for ch3 and ch4.

This is also a hack.  How heavy a sleep should be does not depend on `ch3` vs. `ch4`.  If you want to discuss design, this is not the right forum.  I'm looking at the PR as a whole and the solution doesn't make sense to me.

**Pull request closed without merging**
