### PR TITLE
threadcomm: support comm dup and thread-local attributes

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

A second split from #6326.

* Add support for MPI_Comm_dup of an active threadcomm. This addition results in two kinds of theadcomm. One created via `MPIX_Threadcomm_init` and is able to `MPIX_Threadcomm_start/finish` multiple times. This is very similar to persistent requests.
The other kind of threadcomm is created via duplicate -- and in future, `MPI_Comm_split` etc. -- from an active threadcomm. This results in an active threadcomm that has to be freed within the same parallel region.
* Add communicator attributes support. We need use thread local storage since each thread rank need to have their local attributes.
* Turn on `MPIR_ThreadInfo.isThreaded` inside `MPIX_Threadcomm_start/finish` region to ensure thread safety. Threadcomm is fully thread-aware so we are able to optimize and avoid thread contention to our best. But we need `isThreaded` on to enable the
 mutexes.
* Enhance the test to cover the new features.

## Test
```
$ MPITEST_VERBOSE=1 mpirun -l -n 2 ./threadcomm -nthreads=3 -commdup=1 -restart=2
[0] Test Threadcomm: nthreads=3, restart=2, commdup=1
[1] Test Threadcomm: nthreads=3, restart=2, commdup=1
[0] Rank 0 / 6
[0] Rank 1 / 6
[1] Rank 3 / 6
[1] Rank 5 / 6
[1] Rank 4 / 6
[0] Rank 2 / 6
[0] Rank 0 / 6
[0] Rank 2 / 6
[0] Rank 1 / 6
[1] Rank 3 / 6
[1] Rank 4 / 6
[1] Rank 5 / 6
[0] Rank 0 / 6
[0] Rank 2 / 6
[1] Rank 3 / 6
[1] Rank 4 / 6
[1] Rank 5 / 6
[0] Rank 1 / 6
[0]  No Errors[0]
```

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Review by raffenet — APPROVED** [review]

**Comment by raffenet** [comment]
Just noticed the test failures after approving.

**Comment by hzhou** [comment]
> Just noticed the test failures after approving.

The MPL trmem was not initialized properly resulting in NULL dereference. I'll fix it.

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/ch4/most

**Pull request merged**
