### PR TITLE
comm: Remove unsafe intercomm merge optimization

### PR DESCRIPTION
**Pull request by raffenet**
We cannot guarantee we are the only group within MPI_COMM_WORLD doing
MPIR_Get_contextid_sparse_group, so this optimization is unsafe. Use
the default method in all cases for now.

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Comment by raffenet** [comment]
@yfguo I pulled this patch out of my more comprehensive tag management branch. I think we should merge it now rather than wait for all that to be done. This removes the optimization you added for intercomm merge within the same `MPI_COMM_WORLD`. The operation may not be fully collective over `MPI_COMM_WORLD`, so there needs to be more care taken that messages will not conflict, i.e. with dynamically allocated tags or something that MPI can internally track. For now, I think I we should remove it. This should fix the AM-only configuration of `ch4/ofi`.

**Comment by raffenet** [comment]
Also an issue here that I intend to clean up in the other PR is that using `tag_ub` internally is incorrect. That's a user-accessible tag value. We either need to reserve a bit, or a range of tag values for these types of operations.

**Comment by raffenet** [comment]
Tests look good. Please go ahead and review.

**Comment by yfguo** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
@yfguo I have a fixup for the whitespace issue caught by the checker. Once the tests are done I can squash and merge.

**Comment by yfguo** [comment]
OK

**Comment by raffenet** [comment]
Made a change to the test configuration to avoid spawn tests when in am-only mode. Let's try it out...
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
No new failures in existing configs. Looks like there are some bugs in the `am-only` config, which we'll have to work on. Hopefully some of our tag fixes will help. In the meantime, I'll xfail them.

**Pull request merged**
