### PR TITLE
mpir_pmi: Use namespace returned in PMIx_Init as world_id

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

The pmix_proc_t returned by PMIx_Init contains the namespace information already. No need to get it separately.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/pmi

**Comment by raffenet** [comment]
test:mpich/pmi

**Comment by raffenet** [comment]
test:mpich/pmi
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/pmi
test:mpich/ch4/most

**Review by hzhou — APPROVED** [review]
LGTM

**Pull request merged**
