### PR TITLE
Minor autogen fixes

### PR DESCRIPTION
**Pull request by nmorey**
First commit fixes the behaviour of --without-json.
Even if used, json is built and used instead of the system one.
Also fix the same behaviour for yaksa

Second commit add --without-yaksa option to use a system version instead of the submodule.

### CODE REVIEW

**Comment by nmorey** [comment]
This is not enough as the embedded json is built and added to the flags anyway

**Comment by hzhou** [comment]
What was the issue?

**Comment by nmorey** [comment]
The original issue is that, as a packager for SUSE, I do not want applications/libraries to use their own embedded version if a system equivalent exists.
As we do package libjson-c, I would like to use it rather than the embedded one (specially as make check fails for the embedded version on Leap 15.3).
I did use `./autogen [...] --without-json ` but it does not change anything.
json is hardcoded into the external module list and using the without seems to just remove the submodule check but not the autogen part.

The issue with my patch is that I only fixed the autogen side of things but not the autoconf/configure one.
I whipped a quick fix for that but I doubt it would be accepted as it is right now:

```
diff --git a/configure.ac b/configure.ac
index dd7b4d7c6425..fa8c8b16c81a 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1189,14 +1189,23 @@ AC_SUBST([jsonsrcdir])
 jsonlib=""
 AC_SUBST([jsonlib])
 
-PAC_PUSH_ALL_FLAGS()
-PAC_RESET_ALL_FLAGS()
-PAC_CONFIG_SUBDIR_ARGS([modules/json-c],[--enable-embedded --disable-werror],[],[AC_MSG_ERROR(json-c configure failed)])
-PAC_POP_ALL_FLAGS()
-jsonsrcdir="${main_top_builddir}/modules/json-c"
-jsonlib="${main_top_builddir}/modules/json-c/libjson-c.la"
-PAC_APPEND_FLAG([-I${use_top_srcdir}/modules/json-c],[CPPFLAGS])
-PAC_APPEND_FLAG([-I${main_top_builddir}/modules/json-c],[CPPFLAGS])
+PAC_CHECK_HEADER_LIB([json-c/json.h], [json-c], [json_object_get], [have_json=yes], [have_json=no])
+
+if test "${have_json}" = "no" ; then
+   AC_MSG_NOTICE([Using an embedded libjson-c])
+   PAC_PUSH_ALL_FLAGS()
+   PAC_RESET_ALL_FLAGS()
+   PAC_CONFIG_SUBDIR_ARGS([modules/json-c],[--enable-embedded --disable-werror],[],[AC_MSG_ERROR(json-c configure failed)])
+   PAC_POP_ALL_FLAGS()
+   jsonsrcdir="${main_top_builddir}/modules/json-c"
+   jsonlib="${main_top_builddir}/modules/json-c/libjson-c.la"
+   PAC_APPEND_FLAG([-I${use_top_srcdir}/modules/json-c],[CPPFLAGS])
+   PAC_APPEND_FLAG([-I${main_top_builddir}/modules/json-c],[CPPFLAGS])
+else
+   AC_MSG_NOTICE([Using an external libjson-c])
+   PAC_APPEND_FLAG([-I/usr/include/json-c],[CPPFLAGS])
+   PAC_APPEND_FLAG([-ljson-c],[WRAPPER_LIBS])
+fi
 
 # ----------------------------------------------------------------------------
 # HWLOC

```

**Comment by hzhou** [comment]
Try this patch see if it works --
```
diff --git a/configure.ac b/configure.ac
index 415f807014..68f56a954c 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1098,14 +1098,19 @@ AC_SUBST([jsonsrcdir])
 jsonlib=""
 AC_SUBST([jsonlib])

-PAC_PUSH_ALL_FLAGS()
-PAC_RESET_ALL_FLAGS()
-PAC_CONFIG_SUBDIR_ARGS([modules/json-c],[--enable-embedded --disable-werror],[],[AC_MSG_ERROR(json-c configure failed)])
-PAC_POP_ALL_FLAGS()
-jsonsrcdir="${main_top_builddir}/modules/json-c"
-jsonlib="${main_top_builddir}/modules/json-c/libjson-c.la"
-PAC_APPEND_FLAG([-I${use_top_srcdir}/modules/json-c],[CPPFLAGS])
-PAC_APPEND_FLAG([-I${main_top_builddir}/modules/json-c],[CPPFLAGS])
+m4_define([json_embedded_dir],[modules/json-c])
+PAC_CHECK_HEADER_LIB_EXPLICIT([json],[json.h],[json-c],[json_tokener_parse])
+
+if test "$with_json" = "embedded" ; then
+    PAC_PUSH_ALL_FLAGS()
+    PAC_RESET_ALL_FLAGS()
+    PAC_CONFIG_SUBDIR_ARGS([modules/json-c],[--enable-embedded --disable-werror],[],[AC_MSG_ERROR(json-c configure failed)])
+    PAC_POP_ALL_FLAGS()
+    jsonsrcdir="${main_top_builddir}/modules/json-c"
+    jsonlib="${main_top_builddir}/modules/json-c/libjson-c.la"
+    PAC_APPEND_FLAG([-I${use_top_srcdir}/modules/json-c],[CPPFLAGS])
+    PAC_APPEND_FLAG([-I${main_top_builddir}/modules/json-c],[CPPFLAGS])
+fi

 # ----------------------------------------------------------------------------
 # HWLOC / NETLOC
```

We prefer to embed `json-c` because user applications may use a different json library (e.g. `jansson`) and they often collide in symbols.

**Comment by hzhou** [comment]
> The issue with my patch is that I only fixed the autogen side of things but not the autoconf/configure one.

If you build from distributed source package, you don't need worry about `autogen`. The flags for `autogen` doesn't affect how the library is configured or built. The autogen flags are simply to skip/expedite the process for developers.

**Pull request closed without merging**
