### PR TITLE
ch4/ofi: Added progress in MPIDI_OFI_do_handle_long_am

### PR DESCRIPTION
**Pull request by tarudoodi**
Added progress to during am read to clear cq entries to free memory

Fixes csr/mpich-ofi#247

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ofi

**Comment by raffenet** [comment]
Could this cause reentrancy issues?

**Comment by tarudoodi** [comment]
One thing I should've mentioned is that with the current implementation the time to complete the dt_large_vec test is really long time, about 45 minutes. So we've added an xfail for our jenkins testing. Previously this test would crash but now its just slow. I will ask @hajimefu about the reentrancy aspect.

**Comment by tarudoodi** [comment]
mpich-ofi/test/mpi/datatype/large_vec.c

**Comment by hajimefu** [comment]
@raffenet hmm, that's a good point.
@pavanbalaji this happens with AM-only mode. OFI native path is fine.

**Comment by pavanbalaji** [comment]
@hajimefu I'm very surprised by the comment above that it takes 45 minutes.  AFAICT, on ch3 it finishes within the regular timeout (i.e., 3 minutes).

**Comment by raffenet** [comment]
As with other "large" tests, it could be related to the amount of physical memory on the machine and whether or not it's causing swap to disk to occur. Our 64-bit Jenkins nodes have 24GB of physical memory, for reference.

**Comment by hajimefu** [comment]
@pavanbalaji it's due to the way OFI netmod implements AM data transfer right now. This test transfers a datatype with some millions of small contiguous chunks in it. OFI netmod issues RDMA read for each of these chunks, that's why it takes so long. I believe CH3 does pack/unpack for this.
OFI netmod should also implement pack/unpack, at least for this kind of data, although nobody from our team is currently working on this.

**Comment by pavanbalaji** [comment]
@hajimefu: @raffenet is working on a patch to not rely on RDMA read at all in the AM path.  I think that should fix this issue, isn't it?

**Comment by hajimefu** [comment]
@pavanbalaji oh yeah, that may help. I think not only avoiding RDMA but also pack/unpack is important.

**Comment by pavanbalaji** [comment]
I think mpich already packs/unpacks when the provider doesn't support IOVs.

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
test:ch4/ofi/sockets,psm2/all/all/shm-exclusive,shm-no/debug,default

**Comment by wesbland** [comment]
Closing this PR in favor of a more extensive solution to do pack/unpack in the OFI AM code path.

**Pull request closed without merging**
