### PR TITLE
ch4/ucx: add support for ucx dynamic processes

### LINKED ISSUE #6797: Feature request: Dynamic process management in CH4 with UCX
MPICH configured `--with-device=ch4:ucx` does not currently support any of the dynamic process management features (spawn and friends) of MPI-2. https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/netmod/ucx/ucx_spawn.c

@leofang and I were discussing about the feasibility of switching MPICH in conda-forge to use UCX. However, without proper spawn support, we cannot do it without harming a lot of users that rely on the `mpi4py.futures` subpackage, thus leaving them with no other option than migrate away of MPICH.

cc @jeffhammond

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Add implementations for ucx dynamic processes.

Fixes #6797 

[skip warnings]
## Discussion
* We need increase `MPI_MAX_PORT_NAME` to `1024` from `256` in order to fit the ucx business card.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
UCX's name string does not fit inside `MPI_MAX_PORT_NAME`, which is only `256`. What to do?

**Comment by raffenet** [comment]
> UCX's name string does not fit inside `MPI_MAX_PORT_NAME`, which is only `256`. What to do?

Add it to the ABI wishlist for one 😅.

**Comment by raffenet** [comment]
A new worker address format was recently added into UCX master. One of the state goals was to make addresses shorter. https://github.com/openucx/ucx/pull/7439

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
test:mpich/ch4/ucx

**Comment by hzhou** [comment]
test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
test:mpich/ch4/ucx

test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
test:mpich/ch4/ucx

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

test:mpich/custom
netmod: ch4:ucx
env: with_ucx_spawn=1

**Comment by hzhou** [comment]
test:mpich/ch3/most

**Review by raffenet — APPROVED** [review]

**Comment by hzhou** [comment]
@raffenet I enabled ucx spawn tests in jenkins-scripts. You may need to add the exceptions back for stable release tests.

**Comment by dalcinl** [comment]
@hzhou Is there any upper bound for "port_name_size" ? I see 1024 being used in some defines, but I'm not sure whether that's the upper bound.

**Comment by hzhou** [comment]
We are currently stuck with the MPICH ABI which defines `MPI_MAX_PORT_NAME` to `256`. A ucx address will not fit in `256`, thus `MPI_Open_port` will fail with ucx + the current MPICH ABI. To work around, this PR added an info hint to allow users to tell `MPI_Open_port` the size of its name buffer (ref. https://github.com/pmodels/mpich/pull/5467/commits/ab2be7740cad6c6b482bc41f28553db089059c3c). `1024` appears to be a safe value -- until we encounter a system that UCX return a huge address string.

**Comment by dalcinl** [comment]
@hzhou Would it be possible to add a new `#define MPIX_MAX_PORT_NAME <value>` in `mpi.h`? If using ch4:ucx, then` <value>` should be 1024, but otherwise you set it just to `MPI_MAX_PORT_NAME`. This way, with just the C preprocessor at compile time, users can easily add proper workarounds for the issue.

**Comment by hzhou** [comment]
How would `MPIX_MAX_PORT_NAME` help? By standard, we are required to assume the name buffer in `MPID_Open_port` is bound by `MPI_MAX_PORT_NAME` missing info hint.

**Comment by dalcinl** [comment]
Maybe a `MPIX_Open_port(MPI_Info info, char *port_name, int len)` would also be useful?

**Comment by hzhou** [comment]
For users, it is always safe to allocate a name buffer that is larger than `MPI_MAX_OPEN_PORT`, there is no upper bound. An implementation will never fill the buffer more than `MPI_MAX_OPEN_PORT` unless info hints are given. Without hints, the implementation can't tell the buffer size and only can assume it is `MPI_MAX_PORT_NAME`. The actual port name size is a runtime thing depend on the underlying network and system.

**Pull request merged**
