### PR TITLE
coll: optimized neighborhood collectives

### PR DESCRIPTION
**Pull request by SeyedMir**
This adds optimized neighborhood collective communication schedules based on message combining.

### CODE REVIEW

**Comment by pavanbalaji** [comment]
@SeyedMir Thanks for the PR.  Some comments:

1. Several of the commits are bug/compile fixes to previous commits that should be squashed, so each commit is independent.  (e.g., Using `MPIU_QUOTE` first and then changing to `MPL_QUOTE` is unnecessary and should be squashed into the location where `MPIU_QUOTE` is first used).

2. The persistent neighborhood collectives part should be a separate PR.  That's orthogonal to the regular neighborhood collectives themselves, and is not a part of the MPI standard yet.  Also, that part should not be called `MPI_`.  You can use `MPIX_` for now, if you like, since the MPI standard does not allow us to call non-MPI functions as `MPI_`.

3. Please use C89-style comments (i.e., `/* comment */`) instead of C99-style comments (i.e., `// comment`) to be consistent with the rest of the mpich code.

Can you make these changes and either create a new PR or force-push on this PR?

**Comment by SeyedMir** [comment]
Thanks for your comments Pavan. I will update things accordingly and proceed as you advised.

**Comment by pavanbalaji** [comment]
@SeyedMir is something happening with this PR?  Or should this be dropped?

**Comment by SeyedMir** [comment]
I Updated it recently but it still needs more work. I have to separate the implementation for the persistent neighborhood functions as you advised.

**Comment by pavanbalaji** [comment]
Thanks.  This needs to be rebased on to `mpich/master` first.  And all prereq changes that are not related to the direct implementation should also be separated out as different patches.

**Comment by SeyedMir** [comment]
All right, will work on that too.

**Comment by hzhou** [comment]
Superseded by PR #3892

**Pull request closed without merging**
