### PR TITLE
util/mpir_pmi: use PMIX byte object type for put_ex

### LINKED ISSUE #5241: pmi: Remove unnecessary encoding for PMIx put/get values
The PMIx put/get usage in MPICH converts values to string representation despite PMIx supporting binary blob data. It should be OK to remove this extra step without any loss of functionality.

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
PMIx can directly put/get binary data. Use it rather than the extra
steps of encoding/decoding.

Fixes #5241

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/pmi

**Comment by hzhou** [comment]
test:mpich/pmi

**Review by raffenet — APPROVED** [review]

**Pull request merged**
