### PR TITLE
threads: implement a scheduling point for ULTs

### PR DESCRIPTION
**Pull request by shintaro-iwasaki**
## Pull Request Description

This PR solves a deadlock issue when Argobots is used.

Unlike OS-level threads (e.g., Pthreads), most user-level threads (=ULTs e.g., Argobots) are non-preemptive, so without explicit yield, other ready threads are never scheduled.

For example, there are two non-preemptive threads (`send-and-recv` and `recv-and-send`) that send and receive messages with each other. If `recv-and-send` is first scheduled, it enters an infinite loop in the progress function of `MPI_Recv` and never schedules `send-and-recv`; as a result, deadlock.

To avoid this problem, MPICH inserts yield functions to such potential busy loops. However, the current implementation of `MPIDU_Thread_yield()` and `MPIDUI_THREAD_CS_YIELD_GLOBAL()` has paths that do not actually "yield" (if mutexes are not contended). They are optimizations for Pthreads I guess, but even in that case, ULTs require a real yield.

This PR adds a new function `MPL_thread_schedule()` --which yields if a ULT library is used, and otherwise does nothing--, and puts this function to these yield macros.

## Expected Performance Changes

This PR does not change the behavior if Argobots is not used. With Argobots, it is necessary for correctness.

## Known Issues

None

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [ ] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
Who should review this? @yfguo @pavanbalaji?

**Comment by pavanbalaji** [comment]
@shintaro-iwasaki can you give some background on why we need this extra yield?

**Comment by shintaro-iwasaki** [comment]
@pavanbalaji In general, non-preemptive threads (e.g., user-level threads, or ULTs) require an explicit yield at any possibly busy loop. Otherwise, other threads that must be scheduled for progress will never be executed and cause a dead lock.

Example: wIth `MPI_THREAD_MULTIPLE`, two threads (`recv` and `send`) have the following code.
```
// Consider this process is rank-0.
void recv() {
  int data[1]; 
  MPI_Recv(data, 1, MPI_INT, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
}
void send() {
  int data[1] = {123};
  MPI_Send(data, 1, MPI_INT, 0, 0, MPI_COMM_WORLD);
}
```
To complete `recv`, `send` must be executed. However, if `recv` is first executed, `MPI_Recv` will enter an internal "waiting" state, which is ultimately an infinite loop checking the queues etc.  If Pthreads is used, `send` will be scheduled sooner or later by preemption, but if ULTs are used (and only 1 worker (or "execution stream") is used), such preemption does not happen, so `recv` will be stuck in the "wait" function.

Such a busy wait can be harmful even if Pthreads is used, so MPICH inserts a yield function to "most" busy waits.  However, `MPIDU_Thread_yield` and `MPIDUI_THREAD_CS_YIELD_GLOBAL()` do not contain such a yield function for performance optimization (or any other reasons that I do not know in details).

This optimization is at least correct over Pthreads, but incorrect if ULTs are used. `MPL_thread_schedule` solves the problem in cases where 1. if Pthreads is used, yield is not required for performance reasons but 2. ULTs need an explicit yield for correctness.

**Comment by pavanbalaji** [comment]
Is that true?  I see that `MPIDU_Thread_yield` is calling `MPL_thread_yield`:

https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L559

**Comment by shintaro-iwasaki** [comment]
`MPIDU_Thread_yield ()` doesn't call `MPL_thread_yield()` if `OPA_load_int(&(mutex_ptr_)->num_queued_threads) == 0`: https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L564

**Comment by pavanbalaji** [comment]
I see.  If we remove the `num_queued_theads` branch, will we still need your patch?

The reason I'm asking is that we are discussing with @rzambre and @danghvu about whether that's needed at all.

**Comment by shintaro-iwasaki** [comment]
If https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L485 and https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L564 are removed, this PR is not necessary.

**Comment by pavanbalaji** [comment]
@rzambre Are we removing the `num_queued_threads` branch?

**Comment by rzambre** [comment]
Here are some message-rate numbers (million messages/s) with and without the `num_queued_threads` infrastructure on the global critical section with varying number of threads. In both contented and uncontended cases, the counter infrastructure adds overhead. The difference decreases with higher degrees of contention.

|            Type\Threads    	|             1            	|             2            	| 4                        	| 16                       	|
|:---------------:	|:------------------------:	|:------------------------:	|:------------------------:	|:------------------------:	|
| Without counter 	| 3.4751818 +/- 0.17376206 	|  1.2519798 +/- 0.0731206 	| 0.7207548 +/- 0.00436602 	| 0.5623326 +/- 0.0023393  	|
| With counter    	| 3.0989848 +/- 0.19410791 	| 1.1821644 +/- 0.04451139 	| 0.7154916 +/- 0.00801219 	| 0.5522925 +/- 0.0072086  	|
 

In the per-VCI critical section, we could have the following cases in master:

Case 1: Yielding for the global lock (or any other lock). Currently, in master there are some communication operations that take the global lock in the per-VCI critical section. If the thread is indeed holding the global lock and yields it, we would see a performance behavior similar to the one above. If the thread is not holding the global lock (which would most likely be the case in the future as we increase per-VCI support in the rest of the critical-path communication operations), then no yield occurs because of the branch [1] in which case we just accumulate the overhead of maintaining the counter.

Case 2: Thread yielding its own VCI lock. This case does not occur anywhere in master currently but may occur in the future, if the design requires it. The performance behavior would be similar to the numbers we see in the table above.

Case 3: Thread does not yield inside a per-VCI critical section. In this case we are just accumulating the overhead of maintaining the state of the counter.

It seems to me that we should get rid of the `num_queued_threads` counter. However, getting rid of the `num_queued_threads` alone would not invalidate this PR since we still need this branch [1] to prevent undefined behavior if we unlock a mutex held by some other thread during the yield.

[1] https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L485

**Comment by pavanbalaji** [comment]
> It seems to me that we should get rid of the `num_queued_threads` counter. However, getting rid of the `num_queued_threads` alone would not invalidate this PR since we still need this branch [1] to prevent undefined behavior if we unlock a mutex held by some other thread during the yield.

Thanks for the detailed analysis.  I don't understand this comment.  If we remove the number of queued threads, why would we still need a separate scheduling point?

**Comment by rzambre** [comment]
According to this PR, the new scheduling point is needed even if the current thread is not the owner of the lock, which is separate from the removal of `num_queued_threads`. https://github.com/pmodels/mpich/pull/3861/files#diff-41b9705d677872839a07486d91d3f4a9R492

`MPIDU_Thread_yield` is called only if the current thread is the owner of the lock. So, if we get rid of `num_queued_threads`, this PR should get rid of the new scheduling point inside `MPIDU_Thread_yield`. Should I go ahead an open a new PR to remove the counter so that this PR can rebase on top of it?

**Comment by pavanbalaji** [comment]
If a thread is not the owner of the lock, it'd simply wait for the lock, so it doesn't need to yield.  So I'm still unsure why you think this PR is still needed.

Anyway, let's start with a separate PR to to remove `num_queued_threads` first.

**Comment by shintaro-iwasaki** [comment]
@rzambre Thanks for performance data!
@pavanbalaji I will wait for a separate PR which removes `num_queued_threads`, but I believe this PR is still necesary.

`MPIDU_Thread_yield()`(https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L564): If `num_queued_threads` is removed, this yield function always runs `MPL_thread_yield()`, so the scheduling point is unnecessary.

`MPIDUI_THREAD_CS_YIELD_GLOBAL()` (https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L485): Even if `num_queued_threads` is removed, `MPIDUI_THREAD_CS_YIELD_GLOBAL()` does not always perform `MPL_thread_yield()` when `equal_` is `false`.  If it is the case, programs with nonpreemptive threads (e.g., Argobots) will hung because one ULT possibly enters a busy loop and thus other ULTs are never scheduled.
```
thread1():
  while (1) { // In an MPI blocking function, thread1 waits for the execution of thread2.
              // However, thread2 won't be scheduled since thread1 does not actually
              // yield in YIELD(), causing a deadlock.
    [check completion of something related to thread2()]
    MPIDUI_THREAD_CS_YIELD_GLOBAL();
  }
thread2():
  ...
```
To avoid this, we need a scheduling point so that `MPIDUI_THREAD_CS_YIELD_GLOBAL()` performs `yield()` with nonpreemptive threads in any cases (
https://github.com/shintaro-iwasaki/mpich/blob/MPLThreadSchedPoint/src/mpid/common/thread/mpidu_thread_fallback.h#L492)

**Comment by rzambre** [comment]
@shintaro-iwasaki Thanks for addressing Pavan's comment.
@pavanbalaji I have opened up #3917 to remove `num_queued_threads`.

**Comment by danghvu** [comment]
> MPIDUI_THREAD_CS_YIELD_GLOBAL() does not always perform MPL_thread_yield() when equal_ is false

I wonder why would ever `CS_YIELD_GLOBAL` have a case when `equal_ == false` ? This means the thread which is executing the yielding is not the thread that owns the lock, which is weird! Do we have a case when one can yield a GLOBAL lock without acquiring it at first ?

If the answer is YES, looks like a bug/design flaw we need to fix somewhere else; if NO, how about just remove the branch ?

**Comment by rzambre** [comment]
@danghvu Yes, in the `per-vci` critical section of master we call `CS_YIELD_GLOBAL` in the progress code: https://github.com/pmodels/mpich/blob/master/src/mpid/ch4/src/ch4_progress.h#L141
I think this exists because we haven't completed the support of `per-vci` for all communication operations (collectives, for example). For example, two threads could perform `MPI_Barrier(per_thread_comm)` -- without the `CS_YIELD_GLOBAL`, we could have a deadlock.

The ideal fix would be to extend the `per-vci` critcal section for all communication operations so that we don't need to call `CS_YIELD_GLOBAL` anywhere in the `per-vci` build. But of course, that would require some careful work.

**Comment by shintaro-iwasaki** [comment]
https://github.com/pmodels/mpich/pull/3917 removes the branch in `MPIDU_Thread_yield`, but a scheduling point in `MPIDUI_THREAD_CS_YIELD_GLOBAL` still seems necessary. I updated this PR.

**Comment by hzhou** [comment]
@shintaro-iwasaki What is the status of this PR? Do we still need it?

**Comment by shintaro-iwasaki** [comment]
The issue is irrelevant to recursive mutex. In the current code, I still believe a scheduling point is needed.
https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L156

Perhaps we should call `MPL_thread_yield()` anyway when requested. Right now `MPIDUI_THREAD_CS_YIELD()` does the following (https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L149-L163):
```c
void MPIDUI_THREAD_CS_YIELD(mutex) {
  if (mutex->owner_tid == get_self_tid() && mutex->locked) {
    // In MPIDU_Thread_yield
    unlock(&mutex);
    yield();
    lock(&mutex);
  } else {
    ; // Shouldn't we yield as well?
  }
}
```
The intention of the condition is that, a program crashes if it tries to unlock a given mutex though the mutex is not actually locked or the thread does not own its mutex. In any case, however, I think we should yield (without operating the mutex) as the name of `MPIDUI_THREAD_CS_YIELD()` implies.

What I do not really understand is whether this condition can be satisfied or not. If this condition never becomes false, we do not need a scheduling point (nor yield).

**Comment by hzhou** [comment]
Once the recursive mutex usage is eliminated, the above condition check will become an assertion and the `MPL_thread_yield` will always be called.

**Comment by shintaro-iwasaki** [comment]
If it is the case, this PR will be unnecessary if #4425 is merged.

**Comment by hzhou** [comment]
> If it is the case, this PR will be unnecessary if #4425 is merged.
Sounds good. I'll leave it open and assign to myself, and I'll close this PR once aforementioned commits get merged.

**Comment by shintaro-iwasaki** [comment]
I still believe the problem remains: yield is conditional.
https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L149-L163

**Comment by hzhou** [comment]
> I still believe the problem remains: yield is conditional.
> https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L149-L163

Yeah, I need make another PR to turn that into an assertion.

**Comment by pavanbalaji** [comment]
@shintaro-iwasaki What's the status of this PR?

**Comment by shintaro-iwasaki** [comment]
I am waiting for @hzhou 's mutex refactoring PR; if that PR is created and merged, this PR gets unnecessary, but the current implementation still requires this fix.

**Comment by hzhou** [comment]
> I am waiting for @hzhou 's mutex refactoring PR; if that PR is created and merged, this PR gets unnecessary, but the current implementation still requires this fix.

Does the current master https://github.com/pmodels/mpich/blob/8e124512b3ad551ec4dfc75dccd75be6f7a3aac9/src/mpid/common/thread/mpidu_thread_fallback.h#L215-L229 address your concerns?

**Comment by shintaro-iwasaki** [comment]
Yes, thank you very much @hzhou! It solves the problem.

**Comment by shintaro-iwasaki** [comment]
I will close this PR since this change is no longer needed.

**Comment by shintaro-iwasaki** [comment]
Oops, sorry, I didn't really check the code.
There is still a conditional yield, which hasn't been solved yet.
https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L149-L163

But it passes all the tests now with Argobots. I will reopen this PR (or create another) if I can confirm this causes an issue.

**Comment by hzhou** [comment]
> Oops, sorry, I didn't really check the code.
> There is still a conditional yield, which hasn't been solved yet.
> https://github.com/pmodels/mpich/blob/master/src/mpid/common/thread/mpidu_thread_fallback.h#L149-L163
> 
> But it passes all the tests now with Argobots. I will reopen this PR (or create another) if I can confirm this causes an issue.

Ahh, I hated it that we put in so many layer of indirections. That conditional can be replaced with an assertion.

**Pull request closed without merging**
