### PR TITLE
test: convert testsuite to be function based

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
This a split/renew from #5725.

The current testsuite consists of thousands of individual mpi test programs. Running the entire testsuite involves invoking process manager to spawn mpi processes and each process goes through MPI_INIT again and again. Both the process spawning and MPI initialization are very slow compared to the tested MPI operation itself. The current testsuite runs for a couple of hours and we run hundreds of them every day.

This PR attempts to convert individual tests into functions, so multiple tests can be tested within a single MPI_Init/Finalize window. I believe this can significantly reduce the CI testing time.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/spellcheck
test:mpich/whitespace

**Comment by hzhou** [comment]
test:mpich/spellcheck
test:mpich/whitespace

**Comment by hzhou** [comment]
test:mpich/custom

**Comment by hzhou** [comment]
test:mpich/custom

**Comment by hzhou** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by hzhou** [comment]
test:mpich/whitespace

**Comment by hzhou** [comment]
test:mpich/whitespace

**Comment by raffenet** [comment]
I think my only question is how much does this differ in timing than if we configured MPICH `--without-hwloc` and skipped all the topology discovery stuff? If there's still substantial savings for most CI jobs, then this is probably worth it in the long run.

**Comment by hzhou** [comment]
> I think my only question is how much does this differ in timing than if we configured MPICH `--without-hwloc` and skipped all the topology discovery stuff? If there's still substantial savings for most CI jobs, then this is probably worth it in the long run.

https://jenkins-pmrs.cels.anl.gov/job/mpich-review-custom/1182/console
```
Running tests in ./attr [00:00:00]
Running tests in ./coll [00:00:09]
Running tests in ./comm [00:31:54]
```
So ~32min without hwloc.

**Review by raffenet — APPROVED** [review]
OK, I think the increased throughput is going to be a big enough benefit to warrant the changes. Let's do it.

**Pull request merged**
