### PR TITLE
mpl: unit test framework

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Some of our code, especially utility functions and wrapper functions, can be better tested with a unit-test framework. 

This PR adds a script, `unit_test.pl`, to make such unit tests easier.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [ ] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by shintaro-iwasaki** [comment]
The idea of unit test should be very promising.

One main concern about adding a new testing mechanism is that `unit_test.pl` does not consider the dependency of libraries etc. For example,
- `test/strsep.c` requires `mplconfig.h`, so configure must be run beforehand.
- `unit_test.txt` says `LDFLAGS: libmpl.la` but the script does not automatically detect what must be compiled before.

Is it possible to integrate this unit testing framework into the current make system (like, `make unittest` runs all)?
 
Minor comments:
1. Is `/src/mpl` a good place to place `unit_test.pl`? For example, not `/maint`?
2. Is it okay to add a perl dependency to MPICH (even if it is only for testing)?
3. `unit_test.pl` says it can create multiple tests in a single source file, though it is hard to get how to use it. For example, if I define multiple `TESTS:`, can I change `CFLAGS`?
4. A timeout feature should be useful.

In any case, I would like to use this framework for MPL/atomic tests (#3923). It should be a good use case..

**Comment by hzhou** [comment]
> The idea of unit test should be very promising.
> 
> One main concern about adding a new testing mechanism is that `unit_test.pl` does not consider the dependency of libraries etc. For example,
> 
>     * `test/strsep.c` requires `mplconfig.h`, so configure must be run beforehand.
>
Correct. Not always though. To precise, the dependency is in `include/mpl_str.h`. Not all features have this dependency (but most do). If we write some code with unit tests in mind, ie more isolated units with fine-grained dependency, some of the tests may be able to run without configure, which could be desirable during development.
> 
>     * `unit_test.txt` says `LDFLAGS: libmpl.la` but the script does not automatically detect what must be compiled before.
> 
It's mixed bag. Some units may be able to run without configure, some may require configure, and some may require the convenience library. The script is kind of general enough that it doesn't really care. The individual tests need be written with a target testing stage in mind.
> 
> Is it possible to integrate this unit testing framework into the current make system (like, `make unittest` runs all)?
> 
+1. Actually that was the plan, but I neglected a commit. I'll add it. 

The idea was to run `make test` for unit testing, at which point, configure is already run. We can add multiple targets, e.g. make test-atomics etc. and add appropriate dependency such as libmpi.la if necessary.

However, I see unit tests mostly a tool during development, when the developer needs test individual functionalities; therefore I mostly documented the manual interface.

> Minor comments:
> 
>     1. Is `/src/mpl` a good place to place `unit_test.pl`? For example, not `/maint`?
> 
Good question. `maint` or `confdb`. `confdb` is being duplicated for each sub package, so it makes more practical sense. But we need start somewhere and mpl is the most needed place for now. We can make another PR to change the location later, but first, let's get the framework in.

>     2. Is it okay to add a perl dependency to MPICH (even if it is only for testing)?
> 
It always have been a dependency (for building from git source). It is not a dependency for just build from distributed tar ball and just to install -- I think that is the reason we didn't list it explicitly as a dependency. Same with autotools. It is probably a good idea to list the build-from-repo dependency and make-testing-dependency in the README.

>     3. `unit_test.pl` says it can create multiple tests in a single source file, though it is hard to get how to use it. For example, if I define multiple `TESTS:`, can I change `CFLAGS`?
> 
Yes, you can. However, the options get inherited down -- ie. will not reset inside the same source file.

>     4. A timeout feature should be useful.
> 
If you need timeout, then it is probably not a good unit tests. Unit tests need be small and quick to be effective. A default timeout to prevent deadloop might be helpful, but it complicates the test script. Let's keep it simple for now.
> 
> In any case, I would like to use this framework for MPL/atomic tests (#3923). It should be a good use case..

Great. Looking forward for your feedbacks.

**Comment by hzhou** [comment]
> What if we need to test features that may or may not be available in the system and that we usually detect at configuration time in the testsuite? For example, slurm nodelist parsing test requires posix regular expressions. Assuming these are always available will cause test compilation to fail or test fail launching in some cases.

* We can add specific make targets for groups of unit tests that have different dependencies -- refer to my last commit (that I just added). So only put tests that we are expected to run in the default `make test` target. Other tests can be configured to run only at developer's discretion.

* The integral tests are responsible for testing configuration issues. Unit tests only test for functionality. I.e. it tests whether you written posix regular expressions work as intended assuming the config options are met. 

* Let's get this started and keep it simple at the beginning, and we'll improve on the feedback what works and what does not.

**Comment by shintaro-iwasaki** [comment]
I still believe timeout is useful. At least it is very necessary for MPL/atomic (bad atomic operations can cause a deadlock). In general, any algorithms (even a simple string parser) might have an infinite loop.

I understand the others you mentioned. `make test` also looks good.

**Comment by hzhou** [comment]
configure is simply a set of macros. So may be the unit test file can forge some of these macros to test some specific feature that is not in the default config?

**Comment by hzhou** [comment]
> I still believe timeout is useful. At least it is very necessary for MPL/atomic (bad atomic operations can cause a deadlock). In general, any algorithms (even a simple string parser) might have an infinite loop.

For some timing, maybe the unittest itself can put in the benchmark and fail the test if the timing exeeds?

**Comment by shintaro-iwasaki** [comment]
I believe the unit tests should be used in the normal test process in the future. Otherwise, there is no point to make a standard interface (i.e., `unit_test.py`) for unit tests; everyone can make his own.

**Comment by shintaro-iwasaki** [comment]
I tried your framework.

1. Don't you give 775 permission to `unit_test.pl`? If it is uncommon as a perl script, please ignore it.

2. Should the following work or is my argument wrong?
```
mpich$ perl src/mpl/unit_test.pl src/mpl
Removing old .test folder...
Ran 0 tests, 0 OK, 0 FAIL, 0 XFAIL, 0 SKIP
```

3. Shouldn't the following read `src/mpl`?
```
mpich$ perl src/mpl/unit_test.pl src/mpl
Removing old .test folder...
Ran 0 tests, 0 OK, 0 FAIL, 0 XFAIL, 0 SKIP
```

4. I cannot correctlyrun the strsep test. How can I run this script?
```
mpich/src/mpl$ perl unit_test.pl
Removing old .test folder...
Test 1: MPL_strsep.h ... gcc: error: -E or -x required when input is from standard input
FAIL (1) - failing command: gcc -I include -o .test/test-1 .test/test-1.c  $test_opts->{SOURCE} && .test/test-1
Ran 1 tests, 0 OK, 1 FAIL, 0 XFAIL, 0 SKIP
```

5. Can you print the expanded string for an error message so that I can `read {SOURCE}` and `$test_opts`? It is too hard to manually debug later: `FAIL (1) - failing command: gcc -I include -o .test/test-1 .test/test-1.c  $test_opts->{SOURCE} && .test/test-1`)

6. I think this script does not remove `.test` after the test because the developer can use the created code later. If so, can it use more readable name for test codes (e.g., `MPL_strsep_h_1.c`)?

I'd like to try to integrate this to MPL/atomic tests (#3973) after I can understand how I should run this script.

**Comment by hzhou** [comment]
> I tried your framework.
> 
>     1. Don't you give 775 permission to `unit_test.pl`? If it is uncommon as a perl script, please ignore it.
> 
We could. I am used to run scripts explicitly, e.g. Perl xxx.pl, sh xxx.sh, python xxx.py, ... so I usually just leave the execution bit off.

>     2. Should the following work or is my argument wrong?
> 
> 
> ```
> mpich$ perl src/mpl/unit_test.pl src/mpl
> Removing old .test folder...
> Ran 0 tests, 0 OK, 0 FAIL, 0 XFAIL, 0 SKIP
> ```
> 
The default looks for tests inside `test` folder in your current working directory. You could try overwrite that with `perl unit_test.pl srcdir=src/mpl/atomic` if your tests are in `src/mpl/atomic`.

>     1. I cannot correctly run the `strsep` test. How should I run this script?
> 
> 
> ```
> mpich/src/mpl$ perl unit_test.pl
> Removing old .test folder...
> Test 1: MPL_strsep.h ... gcc: error: -E or -x required when input is from standard input
> FAIL (1) - failing command: gcc -I include -o .test/test-1 .test/test-1.c  $test_opts->{SOURCE} && .test/test-1
> Ran 1 tests, 0 OK, 1 FAIL, 0 XFAIL, 0 SKIP
> ```
> 
>     1. Can you print the expanded string for an error message so that I can `read {SOURCE}` and `$test_opts`? It is too hard to manually debug later: `FAIL (1) - failing command: gcc -I include -o .test/test-1 .test/test-1.c  $test_opts->{SOURCE} && .test/test-1`)
> 

A bug. I somehow used a single quote where I should use double quote. I'll fix it.

>     2. I think this script does not remove `.test` after the test because the developer can use the created code later. If so, can it use more readable name for test codes (e.g., `MPL_strsep_h_1.c`)?
> 

You won't want all the test files pollute your top folder, right? Do you mean change `.test` folder into something like `test_tmp`, ie not hidden? 
>

**Comment by hzhou** [comment]
@shintaro-iwasaki Updated the PR to fix the single quote. `$test_opts->{SOURCE}` was literally what you may specify in the source code with comment e.g. `/* SOURCE: extra_unit.c */`. It is supposed to be expanded into the command line but the mistaken single quote prevented that.

**Comment by shintaro-iwasaki** [comment]
Thanks for updates! I will try.

To me, it is fine whether `.test` is a hidden file or not. My point is whether you *remove* the temporary directory or not; I believe it is beneficial to keep it (and maybe the folder should not be hidden for this purpose). Anyway if bugs are found, the developer needs to debug each program with a debugger.

**Comment by hzhou** [comment]
Updated the script to add some features. Example results:
```
~/work/pull_requests/mpich3973/src/mpl$ make test
perl unit_test.pl
Removing old .test folder...
Test 1: MPL_strsep - NULL ... OK
Test 2: MPL_strsep - empty ... OK
Test 3: MPL_strsep - a|b|c ... OK
Test 4: MPL_strsep - a|b:c ... OK
Test 5: MPL_strsep - a|:b:c ... OK
Test 6: test/atomic/example - [-O0 ] ... OK
Test 7: test/atomic/example - [-O1 ] ... OK
Test 8: test/atomic/example - [-O2 ] ... OK
Ran 8 tests, 8 OK, 0 FAIL, 0 XFAIL, 0 SKIP
  --> [unit_test.xml]
```

**Comment by pavanbalaji** [comment]
This PR has been sitting for almost 9 months.  I'm going to assume that this is not being pursued anymore.

**Pull request closed without merging**
