### PR TITLE
Capability Set Fixes

### PR DESCRIPTION
**Pull request by wesbland**
Fix some missing capability set global definitions.

### CODE REVIEW

**Comment by wesbland** [comment]
test:jenkins/ch4/ofi

**Comment by wesbland** [comment]
Looks like there's a few more failures here. Many of them can be explained:

* Anything related to any source is fixed by https://github.com/pmodels/mpich/pull/2442
* The multisend* tests are all fixed by https://github.com/pmodels/mpich/pull/2614
* disconnect_reconnect3 should be xfailed
* spawnintra/spawnintrax should be xfailed
* idup_comm_gen should be xfailed
* multifence should be xfailed
* large-acc-flush_local should be xfailed

That leaves window_creation. Still working on that one.

**Comment by wesbland** [comment]
Oops. I'm wrong. The multisend tests don't get fixed by #2614. The problem is that they're going over tag_ub. Why tag_ub is so low is a mystery though. If I run the tests with `MPIR_CVAR_OFI_USE_PROVIDER=sockets` (or probably anything), it has a reasonable value for `tag_ub`.

**Comment by hajimefu** [comment]
`window_creation` might be from several environmental limitations (`ulimit` etc.) I will check what we are doing in our internal testbed.

**Comment by raffenet** [comment]
FWIW, `window_creation` fails in our nightly tests with the current master: https://jenkins.mpich.org/view/nightly-master-ch4/job/mpich-master-ch4-ofi/compiler=gnu,fabric_prov=sockets,jenkins_configure=default,label=ib64/lastCompletedBuild/testReport/

**Comment by wesbland** [comment]
Ok, then why don't we go ahead and get all these little patches merged and then we can see what's left to be fixed. I just pushed the fix for the multisend* tests in #2649.

**Comment by hajimefu** [comment]
FYI this is what I have in my .bashrc for `window_creation`.
```
export FI_SOCKETS_DEF_CONN_MAP_SZ=4096
```

**Pull request merged**
