### PR TITLE
mpl/thread: Fix warning for mpl_thread_priv.h

### PR DESCRIPTION
**Pull request by wesbland**

### CODE REVIEW

**Comment by raffenet** [comment]
Should all these thread private macros be converted to static inlines instead so we have better type safety?

**Comment by wesbland** [comment]
The information is probably lost now, but it would be nice to know how this warning can be reproduced.

**Comment by raffenet** [comment]
FWIW, it should be legal to assign a `void *` to another pointer type without a warning in C. This PR might have come about because @charlesarcher was trying to compile with C++? Anyway, I haven't been able to reproduce this, so I'm closing.

**Comment by charlesarcher** [comment]
Correct.  It was a c++ warning.

**Pull request closed without merging**
