### PR TITLE
Replace OpenPA with MPL/atomic [mpl/atomic part 3]

### PR DESCRIPTION
**Pull request by shintaro-iwasaki**
## Pull Request Description

This PR replaces all the OpenPA calls with MPL/atomic, which will be introduced by #3906.
This PR enables us to see the required change by this replacement and the sufficiency (i.e., the coverage) of the new MPL/atomic interface.

This commit is not based on the very latest master and needs some whitespace cleanup. 
One can also test the new MPL/atomic with the real MPICH, not small units tests (#3923).

This PR must be rebased in the future.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [ ] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by raffenet** [comment]
What is the difference between this and #3906?

**Comment by shintaro-iwasaki** [comment]
#3906: Implement MPL/atomic
#3926 (this PR): (on top of #3906) replace OpenPA with MPL/atomic and drop OpenPA.
I tried to avoid making a large PR, but if we should make a huge one, I will.

**Comment by raffenet** [comment]
I have no strong preference, was just trying to get it straight in my head. Maybe we could add a part number in the title to indicate the ordering (part 1, part 2, etc.).

**Comment by shintaro-iwasaki** [comment]
That's a good idea! I will put numbers. Thank you!

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch4/ucx

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch3/tcp

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch4/tcp

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch3/tcp

**Comment by shintaro-iwasaki** [comment]
test:jenkins/ch3/tcp

**Comment by shintaro-iwasaki** [comment]
This PR is stale; this replacement work has been split and done by several PRs. The last piece will be #4391 (after that we just need to remove OpenPA from MPICH).

**Pull request closed without merging**
