### PR TITLE
romio: one sided aggregation fixes

### PR DESCRIPTION
**Pull request by pkcoff**
I have uncovered and fixed several bugs within or using the one-sided aggregation algorithm for ROMIO collective writing to lustre.

### CODE REVIEW

**Comment by roblatham00** [comment]
Whitespace checker is failing.   See https://wiki.mpich.org/mpich/index.php/Coding_Standards#Code_Cleanup_Script

**Comment by raffenet** [comment]
@roblatham00 these changes look fine to me, and should be isolated to the onesided aggregation configuration. OK if I merge them?

**Comment by pavanbalaji** [comment]
@pkcoff  or @roblatham00   Looks like this PR never got merged in.  Is there still a plan to merge this in?

**Comment by pavanbalaji** [comment]
test:mpich/warnings
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by pavanbalaji** [comment]
The `contribution-checker` failure can be ignored for Argonne employees.

**Comment by pavanbalaji** [comment]
The tests seem to be fine.  @roblatham00 waiting for your review at this point.

**Comment by roblatham00** [comment]
These should all go in.

**Comment by pavanbalaji** [comment]
Not sure why the warnings didn't get triggered.  Trying to manually force it.

test:mpich/warnings

**Pull request merged**
