### PR TITLE
build: build shared libfabric if --disable-static

### LINKED ISSUE #6905: build: Build embedded libfabric as a shared library
Would it be possible to add a configure option to build the embedded libfabric as a shared library (just like what is done with UCX as default)?

PS: I'm working on producing binary distributions of MPICH as Python wheels, such that users can `pip install mpich` in both Linux and macOS. I'm considering a `ch4:ofi` option where librabric is built as a shared library and installed alongside the MPI library, allowing users to override libfabric via `LD_LIBRARY_PATH` (at least on Linux).

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
Build the embedded libfabric as shared library if configured with option --disable-static.

Fixes #6905
[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by dalcinl** [comment]
Sorry, I'm not really an autotools expert, but are you sure this covers all possible use cases? 

What If you want to build a shared `libmpi.so` but with the libfabric code still embedded in it, but you do not need `libmpi.a` so you pass `--disable-static` at the top level configure invocation? What would happen in this case?

**Comment by raffenet** [comment]
> Sorry, I'm not really an autotools expert, but are you sure this covers all possible use cases?
> 
> What If you want to build a shared `libmpi.so` but with the libfabric code still embedded in it, but you do not need `libmpi.a` so you pass `--disable-static` at the top level configure invocation? What would happen in this case?

You are right. This case would not be handled by this PR. Also, by removing the embedded mode flag, libfabric headers will be installed in the MPICH install directory, which might not be desirable.

I was playing around with a new option:
```
+AC_ARG_ENABLE([libfabric-static],
+        [AS_HELP_STRING([--enable-libfabric-static],
+                [Enable static linking of the embedded libfabric module (default)])])
```
but it needs additional modifications in `modules/libfabric` to be compatible with "embedded" mode since we have some assumptions there that shared libraries are never built. @hzhou what do you think?

**Comment by hzhou** [comment]
> Also, by removing the embedded mode flag, libfabric headers will be installed in the MPICH install directory, which might not be desirable.

I assume the purpose of building the embedded libfabric as a shared library is to be able to swap with a system libfabric or independently built libfabric at some point, thus the blifabric should be build as if it is independently built. Thus, without the embedded mode flag.

> What If you want to build a shared libmpi.so but with the libfabric code still embedded in it, but you do not need libmpi.a so you pass --disable-static at the top level configure invocation? What would happen in this case?

We only cater to those *legitimate* "what-if"s :) If you want the embedded dependency libraries, build both static and dynamic ones. It takes a bit more build time and you may need to manually delete the static ones if necessary, but I think that is a tolerable compromise.  We have several dependency libraries in addition to libfabric, we will need an exponential number of options to turn individual static/shared on or off. I think that is more undesirable.

**Comment by dalcinl** [comment]
> I assume the purpose of building the embedded libfabric as a shared library is to be able to swap with a system libfabric or independently built libfabric at some point

Yes, that my primary motivation and use case. BTW, this is how Intel uses and distributes librafric in some of their binary packages.

> We only cater to those legitimate "what-if"

When compiling on an emulated emulated architecture via docker on public CI infrastructure takes a long time. 
As long building both the shared and static libraries does not imply building twice PIC/non-PIC code, then I guess the extra `*.a` libs will not be a big deal and they can be easily removed. Again, as long as PIC/non-PIC is a non issue and the static lib is built with the same PIC objects as the shared lib.

**Comment by hzhou** [comment]
> When compiling on an emulated emulated architecture via docker on public CI infrastructure takes a long time.
> As long building both the shared and static libraries does not imply building twice PIC/non-PIC code, then I guess the extra `*.a` libs will not be a big deal and they can be easily removed. Again, as long as PIC/non-PIC is a non issue and the static lib is built with the same PIC objects as the shared lib.

Building both shared and static libraries will compile code twice for PIC/non-PIC code.

Maybe instead of piggy-back on the `--disable-static` option, we can add a `--disable-embedded` option?

**Comment by raffenet** [comment]
> > Also, by removing the embedded mode flag, libfabric headers will be installed in the MPICH install directory, which might not be desirable.
> 
> I assume the purpose of building the embedded libfabric as a shared library is to be able to swap with a system libfabric or independently built libfabric at some point, thus the blifabric should be build as if it is independently built. Thus, without the embedded mode flag.

That makes sense, but what I would prefer to avoid is the scenario where the libfabric installed in the MPICH directory is treated like a standalone library with headers etc. That's actually one of the things that bugs me about Intel's packaging. We have to add workarounds in our build scripts to make sure a rogue libfabric doesn't get picked up.

**Comment by hzhou** [comment]
@dalcinl I am currently leaning toward leaving this issue as `wontfix`.  For your purpose, may I suggest first building libfabric separately (`cd modules/libfabric && ./configure ... && make install`) and then configure mpich with `--with-libfabric=[path]`?

**Comment by dalcinl** [comment]
> I would prefer to avoid is the scenario where the libfabric installed in the MPICH directory is treated like a standalone library with headers etc.

@raffenet Slightly of topic, but wouldn't the same concerns apply to  UCX? In the embedded UCX case with the 4.1.2 tarball, right now there are a few files that get installed and maybe they should not.

```
$prefix/bin/io_demo
$prefix/bin/ucx_read_profile
$prefix/lib/cmake/ucx/ucx*.cmake
```
> @dalcinl I am currently leaning toward leaving this issue as `wontfix`.

@hzhou Fair enough. I thought it was going to be a relateive easy fix. I need to figure out if I can still get things working on scenarios where `make install` with `DESTDIR` is used.

**Comment by hzhou** [comment]
UCX is always installed the same way as an external dynamic library because we haven't figured out a robust hack to embed it yet.

**Comment by dalcinl** [comment]
> may I suggest first building libfabric separately (`cd modules/libfabric && ./configure ... && make install`)

I believe this usage is broken in the release tarball, probably because the embedded option is already set by `autogen.sh` at the time the tarball was generated. Or am I missing something?

**Comment by dalcinl** [comment]
In other words, libfabric's embedded mode is slightly broken, as it tries to build some tools like `fi_pinpong` that fail to link.

**Comment by hzhou** [comment]
> In other words, libfabric's embedded mode is slightly broken, as it tries to build some tools like `fi_pinpong` that fail to link.

Ah I see. We hard patched libfabric header so that all its API functions are not visible internally.  We need patch it properly so the symbols are only hidden if we build in embedded mode.

**Comment by dalcinl** [comment]
@hzhou I would open a separate issue myself, but you definitely know better how to describe the problem.

**Comment by hzhou** [comment]
@dalcinl The PR should fix it - https://github.com/pmodels/mpich/pull/6915

**Pull request closed without merging**
