### PR TITLE
mpl: fix configure for HIP detection

### PR DESCRIPTION
**Pull request by yfguo**
## Pull Request Description

The pop on CPPFLAGS will cleanup the HIP related flags. Creating a new macro for supporting extra CPPFLAGS when checking.

Accidentally deleted the old branch, recreate it here. This is the same thing with #6187 

## Author Checklist
* [ ] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [ ] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [ ] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by yfguo** [comment]
Passed on Crusher

**Comment by yfguo** [comment]
test:mpich/ch4/gpu

Just to make sure it does not break other things.

**Comment by yfguo** [comment]
Tests are clean.

**Review by hzhou — APPROVED** [review]
LGTM

**Pull request merged**
