### PR TITLE
UCX send refactor

### PR DESCRIPTION
**Pull request by raffenet**
test:jenkins/ch4/ucx

### CODE REVIEW

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
Fixed more stuff. Figure out commit order and messages later. test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
Add proper datatype refcounting. test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
Hopefully final version. test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
Fixed bug in refactor patch. test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
Fixed one more minor bug in send refactor patch. Hopefully last time! test:jenkins/ch4/ucx

**Comment by raffenet** [comment]
@LenaO I think I finally got it right. Please review.

**Comment by LenaO** [comment]
Looks good to me.

**Pull request merged**
