### PR TITLE
submodule: Update UCX to v1.11.0

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Testing PR for UCX release candidate.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/ucx
test:mpich/ch4/gpu/ucx

**Comment by hzhou** [comment]
Is this version with the GPU am support?

**Comment by raffenet** [comment]
> Is this version with the GPU am support?

I believe so. The included AM example is updated to support CUDA memory buffers. I'll try it out to confirm.

**Comment by hzhou** [comment]
> 
> 
> > Is this version with the GPU am support?
> 
> I believe so. The included AM example is updated to support CUDA memory buffers. I'll try it out to confirm.

By the way, PR #5390 is ready for your review.

**Comment by raffenet** [comment]
> > Is this version with the GPU am support?
> 
> I believe so. The included AM example is updated to support CUDA memory buffers. I'll try it out to confirm.

Confirmed in experiments. CUDA memory type is supported with AMs in the v1.11.x branch.

**Comment by raffenet** [comment]
Reverting and re-testing to get a baseline for GPU failures.
test:mpich/ch4/gpu/ucx

**Comment by raffenet** [comment]
Updated to `v1.11.0-rc4` tag from upstream.
test:mpich/ch4/ucx

**Comment by raffenet** [comment]
test:mpich/ch4/ucx

**Review by hzhou — APPROVED** [review]

**Pull request merged**
