### PR TITLE
OpenPA: Support C11 atomics and GCC's __atomic

### PR DESCRIPTION
**Pull request by shintaro-iwasaki**
This PR supports C11 atomics and GCC's `__atomic` and drops all the other architecture-specific atomic wrappers.

Currently C11 atomics and GCC's `__atomic` are most portable ways to express acquire-release semantics provided by OpenPA, which thus perform best; the previous GCC's `__sync` follows sequential consistency, which imposes additional overheads.

The previous approaches based on inline assembly or architecture-specific intrinsics essentially perform as good as C11 atomics and GCC's `__atomic`, but they are very error-prone and hard to maintain, and actually have some potential bugs (e.g.,  inline assembly-based atomic operations (e.g., `cmpxchg`) without clobbering memory). Since most compilers support either C11 (many compilers) or GCC's `__atomic` (i.e., >GCC 4.1), now the architecture-dependent implementations can be removed.

This commit drastically changes the atomic wrappers in OpenPA. I welcome any comments and feedback.

### CODE REVIEW

**Comment by pavanbalaji** [comment]
This PR seems to be using relaxed memory ordering in the GCC and C11 implementations.  I'm not sure if we strictly follow that in MPICH.  For example, to be correct in relaxed ordering, shared memory queueing will need to do something like this:

1. Add data to cell
2. Write barrier
3. Atomic enqueue of the cell into the receiver's queue

I don't think we do step 2, and simply assume that step 3 will give the necessary memory consistency.  Of course, we'd get that consistency if we use sequential (`seq_cst`) ordering, but that would add a cost.

**Comment by pavanbalaji** [comment]
As a side note, don't we need to add an autoconf macro to let configure find any necessary flags for C11 support (such as `-std=c11`), in case it's not available by default on a compiler?

**Comment by pavanbalaji** [comment]
I'd also recommend removing `_opa_inline`, `_opa_restrict` and `_opa_const` from all of OPA.  We require C99 support from the compiler now.

**Comment by wzssyqa** [comment]
In fact I also just figure out a version of this patch.
Do you have any idea about how to test the performance?

**Comment by wzssyqa** [comment]
@shintaro-iwasaki I don't think that we need to support __atomic_* at all, since all of the gcc version have __atomic_*, have C11 atomic support at the same time.

Anyway, I think that we should keep __sync, and other asm imp, since some people may use older compilers.
For example, redhat/centos 6 is 4.4, and redhat/centos7 is 4.8.
If I am correct, gcc support __atomic/C11atomic from 4.9

**Comment by wzssyqa** [comment]
sorry.  __atomic/C11atomic is from 4.7

**Comment by pavanbalaji** [comment]
I think that covers all current systems, except for RHEL 5 (which is still under extended support, but hardly "current").  We do have the backup lock-based atomics path, so we are not losing correctness here.  Just performance for really old systems.  Does that even matter at this point?

**Comment by shintaro-iwasaki** [comment]
Thank you for all of your comments and suggestions
If GCC started to support both ``__atomic` and c11 atomics at the same time, GCC's `__atomic` seems useless. Instead, as @wzssyqa suggested, we can keep `__sync` instead of `__atomic`
So c11 atomics => `__sync` => lock-based synchronization.

But maybe some users might want to use GCC without C11 support. I don't know the usage of OpenPA. I am happy to hear any feedback.

**Comment by pavanbalaji** [comment]
Is there a real system where C11 atomics + GCC `__atomic` is not sufficient, or is this just a theoretical debate?

**Comment by shintaro-iwasaki** [comment]
As far as I read https://www.gnu.org/software/gcc/gcc-4.7/changes.html, GCC started to support C11 atomic and GCC's `__atomic` from the same version (GCC 4.7); in that sense, if OpenPA uses GCC 4.7 or higher with C11 enabled, we don't need to support GCC's `__atomic` because the coverage of `__atomic` is the same as C11 atomics. C11 atomics => lock-based system should be enough.

I don't know there is a real system which requires `__sync`. If not, C11 atomics => lock-based system might be sufficient.

**Comment by wzssyqa** [comment]
Sorry, my mistake: __atomic is from 4.7 and C11Atomic is from 4.9:
https://gcc.gnu.org/wiki/C11Status
https://gcc.gnu.org/onlinedocs/gcc-4.7.4/gcc/_005f_005fatomic-Builtins.html#_005f_005fatomic-Builtins

The last major release lack of C11 or __atomic is CentOS 6.

**Comment by shintaro-iwasaki** [comment]
Oh, then my understanding seems wrong :(
Then it seems meaningful to support GCC's `__atomic` as well as C11 atomics.

**Comment by wzssyqa** [comment]
CentOS 7 doesn't have __atomic support.

**Comment by pavanbalaji** [comment]
> CentOS 7 doesn't have __atomic support.

That's very surprising.  What version of GCC does it have?

**Comment by wzssyqa** [comment]
yep. I was confused: CentOS 7 and Ubuntu 14.04 both uses 4.8, which support __atomic while doen't support C11 atomic.

So, we need to support GCC's __atomic as well as C11 atomics.

**Comment by wzssyqa** [comment]
> 
> 
> > CentOS 7 doesn't have __atomic support.
> 
> That's very surprising. What version of GCC does it have?

Sorry. My mistake, CentOS 6 doesn't have __atomic support.
CentOS 7 uses gcc4.8, which support __atomic

**Comment by pavanbalaji** [comment]
> > > CentOS 7 doesn't have __atomic support.
> > 
> > 
> > That's very surprising. What version of GCC does it have?
> 
> Sorry. My mistake, CentOS 6 doesn't have __atomic support.
> CentOS 7 uses gcc4.8, which support __atomic

Does CentOS 6 (i.e., GCC 4.4) have `__sync`?

**Comment by wzssyqa** [comment]
CentOS6/gcc4.4 has __sync.

__sync is supported from gcc4.1

**Comment by pavanbalaji** [comment]
So, I guess we need to support four models then?

1. C11 atomics
2. GCC `__atomic`
3. GCC `__sync`
4. Lock-based atomics

Hopefully we can delete the second and third options in a few years.

**Comment by pavanbalaji** [comment]
It's somewhat weird that we are supporting these extra models for users who are not willing to upgrade their GCC from 4.4, but want to use the latest version of MPICH.  I can't imagine such users even existing, but we already have `__sync` support, so it doesn't hurt to leave it in there.  The ASM code is really what I want to completely get rid of.

**Comment by wzssyqa** [comment]
> 
> 
> So, I guess we need to support four models then?
> 
>     1. C11 atomics
> 
>     2. GCC `__atomic`
> 
>     3. GCC `__sync`
> 
>     4. Lock-based atomics
> 
> 
> Hopefully we can delete the second and third options in a few years.

In fact I don't think that we need GCC `__atomic` at all.
For users with gcc 4.7/4.8, they can continue to use  GCC `__sync`.

**Comment by shintaro-iwasaki** [comment]
The latest commit follows  C11 atomics => GCC `__atomic` => GCC `__sync` => Lock-based atomics.

**Comment by wzssyqa** [comment]
With experience, some code maybe works well on fast machines, while not on slow machines.

I will test your code on qemu for mips64r6el.
If you have any interesting, you can download it from:
http://mips64el.bfsu.edu.cn/debian-new/tarball/

qemu system is really slow.

**Comment by raffenet** [comment]
Just want to point out https://github.com/pmodels/openpa. It has gotten slightly out of sync with MPICH over the years. If we are doing these dramatic changes, it is probably a good time to update opa to submodule and use the canonical repo.

**Comment by wesbland** [comment]
If you remember from our last attempt to use submodules with high-churn repos, it was a pain to keep in sync.

**Comment by jeffhammond** [comment]
FWIW I did the C11 and GCC `__atomic` ports of OpenPA years ago (2014 and 2016), but nobody on the MPICH team cared to review the patches.

https://github.com/jeffhammond/openpa

**Comment by jeffhammond** [comment]
The reason you want to keep `__sync` and/or `__atomic` around is to allow somebody to build OpenPA with a C++ compiler.  I don't know why one would want to break this usage.

**Comment by hzhou** [comment]
It's about timing:smile:

**Comment by wzssyqa** [comment]
I test your patch with qemu system for mips64r6el on Debian buster.
It works well. Thank you very much. I think that it is suitable to merge.

**Comment by wzssyqa** [comment]
How about this PR?

**Comment by jeffhammond** [comment]
@wesbland I think the justification for keeping OpenPA separate from MPICH is mostly gone now that C11 and C++11 atomics are widely available.  Instead of using a submodule, just move OpenPA into MPICH.  Are there any downstream projects that would notice?

**Comment by wesbland** [comment]
> @wesbland I think the justification for keeping OpenPA separate from MPICH is mostly gone now that C11 and C++11 atomics are widely available. Instead of using a submodule, just move OpenPA into MPICH. Are there any downstream projects that would notice?

That's the argument I was going for too. I was just pointing out that for the brief time that we had OPA/MPL/etc. as submodules, it was a huge pain to keep them in sync. I know that OPA is relatively low churn, but if there aren't external users, I'd rather see it stay in MPICH too.

**Comment by hzhou** [comment]
I haven't really looked at OpenPA yet, but for wrappers, it sounds like they really belong in MPL. The configure can decide to pull in OpenPA fallback if necessary.

**Comment by hzhou** [comment]
> I'd also recommend removing `_opa_inline`, `_opa_restrict` and `_opa_const` from all of OPA. We require C99 support from the compiler now.

These are all the side-effects of `AX_PREFIX_CONFIG_H`. It adds package prefix to isolate config macros from other packages, forcing the use of `_opa_inline` even when the keyword works. PR #3856 (hopefully gets merged soon) replaces `AX_PREFIX_CONFIG_H` and stops adding prefix to intrinsic to `inline`, `const`, `restrict`, so we can directly use them in OPA.

**Comment by hzhou** [comment]
> Just want to point out https://github.com/pmodels/openpa. It has gotten slightly out of sync with MPICH over the years. If we are doing these dramatic changes, it is probably a good time to update opa to submodule and use the canonical repo.

Here is my latest thought (FWIW): create mpl_atomics.h and create MPL atomics wrappers to replace all OPA interfaces. mpl_atomics.h should wrap around C11 atomics if available, or wrap around OPA as fall back. The benefit: openpa become a secondary dependency of MPICH. For most modern system that support C11 atomics, things are simple and remain simple. OpenPA has its legacy and has its value, keeping it as a separate submodule ensures legacy support and detach it from mpich maintenance. At some future points, we can just leave openpa as a legacy project, and with the MPL layer, that will be trivial.

**Comment by hzhou** [comment]
> This PR seems to be using relaxed memory ordering in the GCC and C11 implementations. I'm not sure if we strictly follow that in MPICH. For example, to be correct in relaxed ordering, shared memory queueing will need to do something like this:
> 
>     1. Add data to cell
> 
>     2. Write barrier
> 
>     3. Atomic enqueue of the cell into the receiver's queue
> 
> 
> I don't think we do step 2, and simply assume that step 3 will give the necessary memory consistency. Of course, we'd get that consistency if we use sequential (`seq_cst`) ordering, but that would add a cost.

I don't see any follow-ups on this -- quote it again as a reminder.

**Comment by hzhou** [comment]
test:jenkins/ch3/most
test:jenkins/ch4/most

**Comment by shintaro-iwasaki** [comment]
> > This PR seems to be using relaxed memory ordering in the GCC and C11 implementations. I'm not sure if we strictly follow that in MPICH. For example, to be correct in relaxed ordering, shared memory queueing will need to do something like this:
> ```
> 1. Add data to cell
> 
> 2. Write barrier
> 
> 3. Atomic enqueue of the cell into the receiver's queue
> ```
> 
Just a clarification: 2 is not necessary if 3 uses an acquire-release atomic operation (e.g., `OPA_cas_int`) since the atomic operation in 3 guarantees that 1 is (virtually) flushed, in my understanding. If you use a relaxed atomic operation (e.g., `OPA_store_int`), 2 is "usually" necessary (for some types of algorithms), but I guess the developers are aware of it; without using compare-and-swap (`OPA_cas_int`, or a so-called spin lock) or fetch-and-add (`OPA_fetch_and_add_int`), algorithms usually look incorrect (again, depending on types of algorithms).

**Comment by shintaro-iwasaki** [comment]
Note that OPA lacks the following compared to izem:
- "consume" memory model
- weak compare-and-swap (the default compare-and-swap in OPA is "strong" while izem has both)
- test_and_set and clear (generally better for a spin lock)
- more types (potentially `int32_t`, `uint32_t`, `int64_t`, `uint64_t`, and more, while OPA only supports `int` and `void *`)

If necessary, we can extend the API to support them.

**Comment by raffenet** [comment]
I see these memord values in use in `src/mpid/ch4/shm`:
```
zm_memord_relaxed
zm_memord_seq_cst
zm_memord_acquire
zm_memord_release
```

No use of consume.

**Comment by wzssyqa** [comment]
any progress on it?

**Comment by shintaro-iwasaki** [comment]
@wzssyqa This change will be moved to #3906; we will not update OpenPA but apply this improvement to the MPL layer (mpl/atomic).

**Comment by raffenet** [comment]
@shintaro-iwasaki shall we close this PR then?

**Comment by shintaro-iwasaki** [comment]
Yes. Let's close this PR.

**Pull request closed without merging**
