### PR TITLE
Remove code for per-object critical sections in CH4

### PR DESCRIPTION
**Pull request by rzambre**
Only the `global` and `per-vci` critical sections are maintained in CH4. The `per-object` critical section hasn't been maintained in CH4 for multiple years. This PR removes any `POBJ` related code in CH4. When `global` or `per-vci` are selected through the `--enable-thread-cs` config option, all the `POBJ` macros expand to nothing.

@raffenet could you verify these changes will not break anything that is currently supported? This PR removes `POBJ` code in the OFI netmod as well.

### CODE REVIEW

**Comment by rzambre** [comment]
test:jenkins/ch4/most

**Comment by rzambre** [comment]
Rebased on top of the namespace cleanup.

test:jenkins/ch4/most

**Comment by rzambre** [comment]
I added the configure error message if the user selects `per-object` with CH4.
All tests have passed (refer to links in the previous comment).

Ready to be reviewed.

**Comment by raffenet** [comment]
test:jenkins/ch4/most

**Pull request merged**
