### PR TITLE
coll: Consolidate trivial cases

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Move trivial cases out of individual algorithms and into the C binding layer as "early return" blocks.

## Expected Impact

Simplify trivial case handling.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
I had this commit stashed away and forgot about it until now. There's probably more of this sort of cleanup that could be done, but this one is a no-brainer, IMO.

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
Oh, I think this was preparation for allocating the request before nonblocking collective invocation. That could be useful for things like buffer swap in the future.

**Review by hzhou — COMMENTED** [review]
How about we do this in `src/binding/c/coll_api.txt` with a `early_return` code block?

**Comment by raffenet** [comment]
> How about we do this in `src/binding/c/coll_api.txt` with a `early_return` code block?

Makes sense. I will update it.

**Comment by raffenet** [comment]
test:mpich/ch4/most

**Comment by raffenet** [comment]
> > How about we do this in `src/binding/c/coll_api.txt` with a `early_return` code block?
> 
> Makes sense. I will update it.

An issue with this approach is that trivial cases do not apply equally to intra and intercomms...

**Comment by raffenet** [comment]
> > > How about we do this in `src/binding/c/coll_api.txt` with a `early_return` code block?
> > 
> > 
> > Makes sense. I will update it.
> 
> An issue with this approach is that trivial cases do not apply equally to intra and intercomms...

Not specific to my original version or earlyreturn. Both suffer from the same problem.

**Comment by raffenet** [comment]
> > > > How about we do this in `src/binding/c/coll_api.txt` with a `early_return` code block?
> > > 
> > > 
> > > Makes sense. I will update it.
> > 
> > 
> > An issue with this approach is that trivial cases do not apply equally to intra and intercomms...
> 
> Not specific to my original version or earlyreturn. Both suffer from the same problem.

Added comm kind check to trivial cases to solve this.

test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Review by hzhou — APPROVED** [review]
LGTM

**Comment by raffenet** [comment]
Removed a couple of unused labels. Will merge after warnings pass.

**Pull request merged**
