### PR TITLE
White space cleanup

### PR DESCRIPTION
**Pull request by pavanbalaji**
Allow nemesis/netmods and ch3/sock to be white space clean.

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:jenkins/ch3/most

**Comment by pavanbalaji** [comment]
This patch will need to be redone because of the conflicts.  I'll do that once we make a decision on whether we want to do this.

**Comment by raffenet** [comment]
No objections to this on the call today. Re-testing after rebase.
test:jenkins/ch3/most

**Comment by raffenet** [comment]
test:jenkins/ch3/portals4

**Comment by raffenet** [comment]
ch3/portals broke in master on 2/18. I'm ignoring that Jenkins job and merging these changes.

**Pull request merged**
