### PR TITLE
test/mpi: Move comm_info_hint tests to standard directory

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

These behaviors will be part of MPI-4.0, and so are no longer
implementation specific. Move them alongside other standard tests.

See pmodels/mpich#4882.

## Expected Impact

These tests will run more regularly in manual and Jenkins testing.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Passes whitespace checkers
* [ ] Passes warning tests
* [ ] Passes all tests
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] You or your company has a signed contributor's agreement on file with Argonne
* [ ] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by raffenet** [comment]
Hmm, looks like `mpiversion` option was removed by @shintaro-iwasaki in https://github.com/pmodels/mpich/commit/9a5704cdb38d2e17fb09bc573c9289e298bcb101. How do we want to handle tests for MPI-4.0 features? Just assume support?

**Comment by raffenet** [comment]
Note that some tests use `MTEST_HAVE_MIN_MPI_VERSION` preprocessor guards for some functionality.

**Comment by shintaro-iwasaki** [comment]
Reverting `test/mpi/runtests.in` is okay.

**Comment by hzhou** [comment]
> 
> 
> Hmm, looks like `mpiversion` option was removed by @shintaro-iwasaki in [9a5704c](https://github.com/pmodels/mpich/commit/9a5704cdb38d2e17fb09bc573c9289e298bcb101). How do we want to handle tests for MPI-4.0 features? Just assume support?

If there are tests that only works with particular old versions, we should move those tests to a separate folder -- e.g. `mpi-2`, `mpi-3` -- and add configure mechanism to enable them on-demand.

Mpich-specific tests are protected by `!defined(USE_STRICT_MPI)` or `defined(MPICH)` -- I think we only need the latter.

By default, I think "Just assume support" will be fine, makes the maintenance cleaner.

What do you think?

**Comment by hzhou** [comment]
> 
> 
> > Hmm, looks like `mpiversion` option was removed by @shintaro-iwasaki in [9a5704c](https://github.com/pmodels/mpich/commit/9a5704cdb38d2e17fb09bc573c9289e298bcb101). How do we want to handle tests for MPI-4.0 features? Just assume support?

We have xfail.conf, so for particular down-stream/third-party mpi implementation, they should maintain their custom xfail.conf to manage.

**Comment by raffenet** [comment]
> Mpich-specific tests are protected by `!defined(USE_STRICT_MPI)` or `defined(MPICH)` -- I think we only need the latter.

Also with `strict=FALSE` in `testlist`. `--enable-strictmpi` controls whether those are built/executed.

**Comment by raffenet** [comment]
OK, my assumption about query support for these keys in MPI-4.0 was wrong. Implementations are not required to support them, even if they are defined in the standard. I.e., they don't need to report `false` if the user queries for them. So this can either go back to the `impls` directory, or we can put it here and add `strict=FALSE` to the testlist.

It does appear that we should be defaulting these keys to `false` in the case where the user supplies no info object or otherwise does not set info on the communicator. That is strongly suggested in advice to implementors.

**Comment by raffenet** [comment]
> It does appear that we should be defaulting these keys to `false` in the case where the user supplies no info object or otherwise does not set info on the communicator. That is strongly suggested in advice to implementors.

Well turns out we already do this, so the only thing to do is to decide how to protect these tests from running when they shouldn't.

**Comment by hzhou** [comment]
> 
> 
> > It does appear that we should be defaulting these keys to `false` in the case where the user supplies no info object or otherwise does not set info on the communicator. That is strongly suggested in advice to implementors.
> 
> Well turns out we already do this, so the only thing to do is to decide how to protect these tests from running when they shouldn't.

My suggestion is to have them run by default (since they are now standard hints), and any specific implementations can xfail them if they don't support it.

**Comment by raffenet** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by raffenet** [comment]
> > > It does appear that we should be defaulting these keys to `false` in the case where the user supplies no info object or otherwise does not set info on the communicator. That is strongly suggested in advice to implementors.
> > 
> > 
> > Well turns out we already do this, so the only thing to do is to decide how to protect these tests from running when they shouldn't.
> 
> My suggestion is to have them run by default (since they are now standard hints), and any specific implementations can xfail them if they don't support it.

Hm, I suppose that works. In fact, that looks to be inline with how RMA window hints are treated in the testsuite today.

**Comment by raffenet** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by raffenet** [comment]
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by raffenet** [comment]
Closing this PR. The behaviors in this test are indeed implementation specific, since info hints are always allowed to be ignored.

**Pull request closed without merging**
