### PR TITLE
Code clean up for RMA operations' AM callbacks.

### PR DESCRIPTION
**Pull request by monicasee**
This patch includes following changes:
- renamed all internal used functions as do_{op};
- always set sreq's ref_counter to 2 in do_{op}, one for progress
  engine, the other for caller function (e.g., put|rput). Thus ensure
  the request cannot be freed for request-based ops before return to
  user. Then in normal op functions, simply release the second ref.
- separate internal routine for accumulate and get_accumulate.

### CODE REVIEW

**Comment by monicasee** [comment]
test:jenkins/ch4/ofi

**Comment by monicasee** [comment]
test:jenkins/ch4/ucx

**Comment by monicasee** [comment]
test:jenkins/ch4/ofi

**Comment by monicasee** [comment]
test:jenkins/ch4/all

**Comment by monicasee** [comment]
test:jenkins/ch4/ofi

**Comment by monicasee** [comment]
test:jenkins/ch4/ucx

**Comment by monicasee** [comment]
test:jenkins/ch4/all

**Comment by raffenet** [comment]
Is this superseded by #2412? Can it be closed?

**Pull request closed without merging**
