### PR TITLE
misc: Fix warnings reported by pgi/nvidia compilers

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Fix various issues reported by the PGI warning builds in Jenkins. This only addresses low-hanging fruit. There are some more tricky ones that need a little more time to address. I tried to isolate modules to some degree, but ended up grouping together similar fixes for mpi/mpir/ch4-level stuff.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Comment by raffenet** [comment]
test:mpich/ch4/most
test:mpich/ch3/most

**Review by wesbland — APPROVED** [review]

**Review by hzhou — APPROVED** [review]
I am ok with the fix.

Personally, I wish the compiler do not enable some of these warnings by default.

**Comment by raffenet** [comment]
> I am ok with the fix.
> 
> Personally, I wish the compiler do not enable some of these warnings by default.

The one that is really annoying "transfer of control bypasses initialization" that flags lots of our C99 style variable declarations that get skipped over by error handling gotos. I wonder if that can either be disabled, or put in a mode that understands decl after statement better.

**Comment by hzhou** [comment]
> > I am ok with the fix.
> > Personally, I wish the compiler do not enable some of these warnings by default.
> 
> The one that is really annoying "transfer of control bypasses initialization" that flags lots of our C99 style variable declarations that get skipped over by error handling gotos. I wonder if that can either be disabled, or put in a mode that understands decl after statement better.

Yeah, that one is really annoying. One of the fix is to split 
```
int tmp = xxx;
```
into 
```
int tmp;
tmp = xxx;
```

**Pull request merged**
